### ISSUE TITLE
Update to Jython 2.7

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#1005]
Jython 2.7 was just released.  We are currently on 2.5.1.  There are also 2.5.3 and 2.5.4-rc1 releases available as options.

**Comment by kennedyoliveira** [comment]
any news on this one?

**Comment by thadguidry** [comment]
@kennedyoliveira To get this now... you can drop in the Jythono 2.7 jar file yourself and it should work.  The path is something like this: "\openrefine-win-2.6-rc.2\openrefine-2.6-rc.2\webapp\extensions\jython\module\MOD-INF\lib"

Just make sure to move the original jython-standalone-2.5.3.jar file to another folder and not have both Jython jars in that folder path.

**Comment by kennedyoliveira** [comment]
@thadguidry i had done it already and looks like it's working fine up to now, but would be good to be on the project it self because some things work on 2.7 but not on 2.5, like json.

How would i parse json on Jython 2.5.x? Using the 2.7 i can simple do like in python, import json, and use it.

Thanks in advance.

**Comment by thadguidry** [comment]
@kennedyoliveira ask that json parsing question again on our mailing list, or on StackExchange where the community can help and provide support. (our issues on Github are not a support queue)

**Comment by kennedyoliveira** [comment]
@thadguidry ok, thank you

**Comment by wetneb** [comment]
This was solved!

**Comment by tfmorris** [comment]
Jython was updated from 2.5.3 to 2.7.0 in f9323d29c621c719c1eab82fcda8032f0bcd51ab before 2.7-rc.2 (sic).
