### ISSUE TITLE
Ampersands not escaped when exporting to HTML

### ISSUE THREAD

**Issue by joewiz** [OpenRefine/OpenRefine#1049]
Using v2.6-RC1, when a cell value contains an ampersand (i.e., `&`), this ampersand is not escaped (i.e., to `&amp;`) when exporting. As a result, the exported HTML is not compatible with applications that expect well-formed XHTML. 

Would it be possible to escape ampersands in HTML output?

**Comment by joewiz** [comment]
Thanks, @jackyq2015! I'm not a java developer, but looking at the source of some of your recent commits on the table exporter, would the fix be on https://github.com/RefinePro/OpenRefine/blob/issue-1015/main/src/com/google/refine/exporters/HtmlTableExporter.java#L108, to the effect of:

    writer.write(StringEscapeUtils.escapeXml(cellData.text));

Here I'm using https://commons.apache.org/proper/commons-lang/javadocs/api-3.1/org/apache/commons/lang3/StringEscapeUtils.html#ESCAPE_XML.

I suggest the XML escaping to limit escaping to just a few characters (as opposed to escaping the full range of HTML entities, which just make these characters more human editable).

My only worry is whether the HTML import would similarly need to unescape `&amp;`?

**Comment by jackyq2015** [comment]
That fix is for encoding issue. but StringEscapeUtils on the same method will fix the escape issue. That's why I self-assigned this issue to me. But we are actively working on the 2.6 milestone. The actual fix / merge will be postponed a little bit.

For the import, I am not quite sure whether we have the similar issue. If someone can help out to verify it that will be great!

**Comment by joewiz** [comment]
Okay, great! In the meantime I've switched to TSV export/import, so I'm handling the escaping/unescaping outside the application. Thanks for your help!
