### ISSUE TITLE
Reconciliation results are not sorted by score

### ISSUE THREAD

**Issue by joewiz** [OpenRefine/OpenRefine#1063]
In building my own reconciliation service, I noticed that OpenRefine displays the results in the order returned by the remote API, rather than sorting them by the score object. For example, a query for "McCarthy, Joseph M." returns 3 results, which are displayed in the following order, even though the 3rd match has the highest score:

```json
{"q0": {"result": [
    {
        "name": "McCarthy, Joseph R.",
        "score": 6.4928436,
        "type": ["person"],
        "id": "6603"
    },
    {
        "name": "McCarthy, Senator Joseph R.",
        "score": 6.4928436,
        "type": ["person"],
        "id": "3558"
    },
    {
        "name": "McCarthy, Joseph M.",
        "score": 11.757351,
        "type": ["person"],
        "id": "6536"
    }
]}}
```

OpenRefine should use the score value rather than the order of objects sent by the API (in particular since JSON lacks a notion of document ordering that either server or client can depend on).

(I'm using 2.6RC1 with current versions of Mac OS X and Google Chrome.)

**Comment by tfmorris** [comment]
Your assertion that JSON arrays aren't ordered is incorrect. 

http://stackoverflow.com/questions/7214293/is-the-order-of-elements-in-a-json-list-maintained

The reconciliation service is already filtering and ranking the results.   It makes far more sense, at least to me, to order them correctly at that point, particularly since the reconciliation service presumably has the most information available as to what the correct order is.

**Comment by joewiz** [comment]
Thanks for correcting my misunderstanding about JSON arrays being ordered.  That insight also helped me track down the cause of the misordering in my reconciliation service.

**Comment by tfmorris** [comment]
Cool.  Always happy to hear about new reconciliation services!
