### ISSUE TITLE
Firefox display issues

### ISSUE THREAD

**Issue by danpaulsmith** [OpenRefine/OpenRefine#1078]
Not sure if Firefox is supported, but the UI is lacking text (isn't present in the DOM) in lots of areas. Here's a screenshot from the import page:

![screen shot 2015-10-01 at 16 18 11](https://cloud.githubusercontent.com/assets/582589/10224906/211c98be-6858-11e5-849a-5647070f50dc.png)

**Comment by thadguidry** [comment]
Use the Line-based text file selection instead of the
CSV/TSV/separator-based.

Play around with the importing options, until you can better understand
your data.

Optionally, look at your file in a regular Text Editor such as Notepad++ on
Windows, etc, to determine the file type or patterns that you can see.
Then adjust the importing options to your needs or liking.

However, the Line-based importer can work for anything, even without
determining a patter, it just depends on Line Feeds and Carriage Returns as
its separator.

Let us know how far you get, and if not far, then try to attach a sample of
your file if you can (privacy concerns and all that).

**Comment by danpaulsmith** [comment]
Hi Thad,

I think the issue is more wide-spread that the parsing screen. The Open project page is blank, and buttons and dropdowns on the main page are missing text:

![screen shot 2015-10-02 at 10 19 57](https://cloud.githubusercontent.com/assets/582589/10243251/42869472-68ef-11e5-8255-678c34eed7cb.png)
![screen shot 2015-10-02 at 10 19 44](https://cloud.githubusercontent.com/assets/582589/10243250/42864c1a-68ef-11e5-9efb-031c44ce3d39.png)
![screen shot 2015-10-02 at 10 19 22](https://cloud.githubusercontent.com/assets/582589/10243252/42897e76-68ef-11e5-9732-a3d54801c0f6.png)

Firefox 41, OSX 10.10.5

**Comment by magdmartin** [comment]
Which version of OpenRefine are you using the 2.6beta or RC1?
This seems related to #871

**Comment by tfmorris** [comment]
@danpaulsmith What version of OpenRefine was your testing done with?

**Comment by danpaulsmith** [comment]
I have Version 2.6-rc1 installed on my personal laptop, and it's fine, so it might be my work laptop. I'll check tomorrow.

**Comment by kafran** [comment]
Same problem here on 2.6-rc2, the openproject page returns "No existing project. Select 'Create Project' on the left to create a new project." but there are projects. Running on Firefox 43.0.4; not tried others.

**Comment by tfmorris** [comment]
@kafran That doesn't sound like the same problem.  How do you know there are projects?  Do they appear when you use a different browser? What operating system are you running on?

If you're still having the problem, please post to the OpenRefine mailing list with details of your configuration and we'll see if we can get you sorted out.

**Comment by kafran** [comment]
@tfmorris https://github.com/OpenRefine/OpenRefine/issues/1120
