### ISSUE TITLE
Cannot cluster a column with 2 million rows

### ISSUE THREAD

**Issue by charlie7691** [OpenRefine/OpenRefine#1083]
A single CSV file with a column of messy data for clustering.
Edit cells -> Cluster and Edit -> leave default settings
Browser hangs while memory usage goes up to a couple of gigs.
Returns huge amounts of data.
Try to select all (bottom left) and press "merge selected and recluster"
Error message says the form submission has too many items.

Any chance it might be possible to see the clustering preview output with a limited sample, rather than showing / ticking all results in the view? The current situation makes my internet connection speed and the browser performance a limiting factor!

Thanks, Charlie

PS: This is an awesome piece of software, for which I am incredibly grateful!!

**Comment by thadguidry** [comment]
@charlie7691 Try to use a Facet on some column to limit the rows however you wish. THEN perform your Clustering.  OpenRefine is designed for operations near 1 million rows or less.  So you might have to batch up your operations into phases or slices at a time with Facets or Limit Rows during the import and project creation. (make 2 projects at 1 million rows each, then do clustering, etc)

I am closing this and marking as a non-issue since this goes against our original design, but we understand that you want to do more work with Refine.  However, we have hit up against limits with the current design, which hopefully one day we will rework that and allow ~ 10 million rows  Feel free to have open discussion with us on our mailing list and not this issue.

**Comment by charlie7691** [comment]
Thank you so much for this prompt and useful reply. I used facets, as you suggested, and have achieved exactly the results I was hoping for! Awesome stuff - thanks!

**Comment by thadguidry** [comment]
@charlie7691 Glad you got some work done Charlie ! :)  Yes, Facets are very powerful in OpenRefine, so use them judiciously. And there are so many kinds to choose from, or you can build your own custom facet with GREL, Clojure, or even Python language.

**Comment by charlie7691** [comment]
Thanks! At the moment I am trying to clean massive columns of employer names and job titles, but am limited by the cluster sizes. Looks like 7500 is about the most I can merge at once.
I did try using Levenshtein distance to normalise them but even with 32 cores and 60GB ram it ran too slow!!
Would you happen to be able to offer any hints on good approaches to this sort of problem?!
Many thanks, Charlie

**Comment by thadguidry** [comment]
@charlie7691 For large data you might try Pentaho ETL which has a Fuzzy Match that has the same algorithms and has highly parallelized code. http://infocenter.pentaho.com/help/index.jsp?topic=%2Fpdi_user_guide%2Freference_step_fuzzy_match.html

Download PDI latest here: http://sourceforge.net/projects/pentaho/files/Data%20Integration/
create a new transformation with 1st step being a CSV Input step with a hop to the Fuzzy Match step.
Then right click preview on the Fuzzy Match step. :)
