### ISSUE TITLE
problem reading csv can not tolerate nulls

### ISSUE THREAD

**Issue by daviddou82** [OpenRefine/OpenRefine#1084]
Open refine can not read CSV file with nulls in the first column.   automatically drops all the records with nulls.

**Comment by thadguidry** [comment]
Uncheck the option for removing blank rows ?

**Comment by daviddou82** [comment]
I have tried all the options.  only the first column is null.  There is no way of reading rows with nulls in the first column

**Comment by thadguidry** [comment]
Try line-based importer, then find the separator pattern for fields and split.

OpenRefine has no problem with nulls in the first column, such as if your CSV file opened in Notepad looked like this:

fieldA,fieldB,fieldC
1,2,3
1,2,3
,2,3
1,,3

**Comment by daviddou82** [comment]
IT looks like open refine does read the row.  But open refine does not assign a row index.  The row index is blank.  The behavior of these rows are strange.  Total record count at the top is incorrect as well.

**Comment by thadguidry** [comment]
You'll have to attach the CSV for me to find out...or if it is private then email to me and I can take a look.

**Comment by daviddou82** [comment]
sure. what is your email?

**Comment by thadguidry** [comment]
thadguidry@gmail.com  - I thought it was publically available to see in my Github profile ? hmm.

**Comment by thadguidry** [comment]
@daviddou82 

Looks like OpenRefine is handling your file just fine as a CSV import with default values.

You can verify this, by being in "rows" mode in the upper left once your looking at the data grid, and in the upper right corner clicking on "last" to see the last few rows, which might take a few seconds to actually display since you have a large amount of rows. (took 12 seconds on mine with default RAM allocation given to OpenRefine -Xmx 1024m)

Please replay and confirm if you see the same, and then we can close this issue out.

**Comment by daviddou82** [comment]
I would really like to see a fix where open refine assigns a index/ID for every row.  This problem have messed me up quite a few times.  I would like to row count number at the top be fixed.

**Comment by thadguidry** [comment]
@daviddou82 if your in "rows" mode, then the count should be accurate.

**Comment by daviddou82** [comment]
okay I never saw that option before.. thanks for you help.
