### ISSUE TITLE
Fetch from URL gives 403

### ISSUE THREAD

**Issue by sphirelabs** [OpenRefine/OpenRefine#1099]
I tried to call an REST API using the fetch from URL option. I tried multiple APIs, But all giving a 403. I manually tested the URL in browser,my IP is not blocked. Is there any other reason for 403?
Note: Am using HTTPS

**Comment by tfmorris** [comment]
Please use the mailing list / Google Group for questions.  https://groups.google.com/forum/#!forum/openrefine

Browsers aren't a very good testing mechanism because they can have all kinds of cached cookies, authentication tokens, etc.  A utility like curl will give you a better indication of what's going on.  My first guess, since you say it's HTTPS, is that the API requires authentication, but if you ask on the mailing list with more details about what API it is, exactly what URL you're hitting, etc, we can get it figured out.
