### ISSUE TITLE
RegEx on Match Function

### ISSUE THREAD

**Issue by LibrarPotter** [OpenRefine/OpenRefine#1100]
The "match" function does not appear to be compatible with regular expressions at this time.  I was able to use the "replace" function with regex, but "match" would not display anything correctly for me.

**Comment by joewiz** [comment]
Can you provide a specific example?

**Comment by thadguidry** [comment]
@LibrarPotter Match does work, but your probably just missing some knowledge on how it works.

Match can output a boolean or an array.  So it depends on how you wired it up.
Use our documentation below to get a bit more familiar on how flexible it can be for your needs.
https://github.com/OpenRefine/OpenRefine/wiki/GREL-String-Functions#matchstring-s-regexp-p

https://github.com/OpenRefine/OpenRefine/wiki/Understanding-Regular-Expressions

Close this issue if you find that those are helpful and get your further, otherwise, @joewiz is correct in asking you for more information for an example string that your trying to match, and what your GREL recipe looks like.  Let us know.

**Comment by LibrarPotter** [comment]
Thank you for your assistance. I did use that documentation before reaching out, but through further experimentation I have realized that it does not cover some of the characters (e.g. * ), which has resolved my issue. 
replace() does not require the use of * to search within a continuous string whereas match() does.
