### ISSUE TITLE
Clickable fields

### ISSUE THREAD

**Issue by Opennat** [OpenRefine/OpenRefine#1115]
Make `case sensitive` and `regular expression` text in Text filter and all headers of columns
 as link (or better - make all cell in layout table clickable) to control their state, to avoid clicking to pixels (checkboxes/down arrow, respectively).

**Comment by ostephens** [comment]
Making `case sensitive` and `regular expression` text clickable in the Text filter was fixed by af1cc19c6db0f55a7226bfaa527eb0cdb244cd76

I'm against making the cells in the layout table clickable with the current editing mechanism - I often need to copy cell values, and I want to be able to do this without opening up an Edit pop-up.

I'm not sure about the column headings. Being able to copy these is sometimes useful, but I don't do it so often as copying cell values.

Any other views? @ettorerizza ?

**Comment by ostephens** [comment]
@ettorerizza any views on making the column headings more generally clickable? I'm against for the reasons I state above, but if you disagree then it would be good to have a discussion. Otherwise I'll close this

**Comment by ettorerizza** [comment]
Oops, sorry, I did not see the previous mention. No, it's clearly not something that I think is useful, personally. I very often select the name of a column to copy it. A completely clickable column name seems to have many disadvantages for very little advantages.

**Comment by ostephens** [comment]
Agreed

* Make case sensitive and regular expression text in Text filter **DONE**
* Make all headers of columns or all cell in layout table clickable **WON'T DO**
  * This would cause problems in the UI where people want to simply copy text rather than interact with controls.
  * If an alternative approach to making clicking on column/cell controls easier can be suggested it will definitely be considered - please do this in a new issue if you have any suggestions

**Comment by thadguidry** [comment]
@ostephens well, with current human-computer interaction via mouse, there are 3+ buttons now, and some folks COULD use the middle mouse in various ways, but that that's like 1000 support issues waiting to be written for us to triage :)  We'll keep our plans to simple 1 button processing for now and the future UI work.
