### ISSUE TITLE
New action for Transform window

### ISSUE THREAD

**Issue by Opennat** [OpenRefine/OpenRefine#1118]
As we have no ability to apply more than one transform on the column in a row, add new "action button" - `Apply and stay here` in `Transform` window, to not close this window (like in `Cluster and edit` window: "Merge / Merge and close / Close"). Now you spend time to open Transform window again manually.

**Comment by wetneb** [comment]
It's not clear to me why this would be useful, since you can easily chain functions in your expression language.
For instance `value.trim().toLowercase()` instead of doing first `value.trim()` and then `value.toLowercase()`.
In some rare cases you might want to use different expression languages - but I don't feel like it warrants an additional button. Plus we might get support for using different expression languages in the same expression if we go down the Graal route (#2250).

Closing, feel free to reopen if I misunderstood.
