### ISSUE TITLE
Potentially harmful cookie usage

### ISSUE THREAD

**Issue by rcaa** [OpenRefine/OpenRefine#1129]
After this [commit](https://github.com/OpenRefine/OpenRefine/commit/aef95e7c30317d2e2ad11f16a844d9a0044c81a6), there is no more verification whether a cookie is public in com/google/refine/extension/gdata/GDataImportingController.java, line 198. 

This would allow someone with access to user browser to access user spreadsheets without proper authorization.

**Comment by thadguidry** [comment]
@wetneb Do you have thoughts on this ?  or do we close this as a "won't fix" citing "such and such reasoning" ?

**Comment by wetneb** [comment]
This issue is not clear to me. Yes, if someone can access a user's cookies, then they will be able to steal the authentication and access user spreadsheets. This is true for most services which use cookie-based authentication (which is the default).

The issue mentions a `verification whether a cookie is public`, but I am not sure what they mean, since there is no notion of visibility on cookies as far as I am aware (all cookies are private to the website that issued them). The commit linked to deals with changes of visibility for spreadsheets, which is a different thing.

So as far as I am aware this issue does not make sense.
