### ISSUE TITLE
Help for building an extraction

### ISSUE THREAD

**Issue by BernardBoureee** [OpenRefine/OpenRefine#1171]
Hello
I have in one web page (https://fr.wikipedia.org/wiki/Meaulne-Vitray) the following items
```
<div class="bandeau-cell">
	<strong class="bandeau-titre">
		Cet article est une 
		<a href="/wiki/Aide:%C3%89bauche" title="Aide:Ébauche">ébauche </a>
                  concernant une 
		<a href="/wiki/Commune_(France)" title="Commune (France)"> Commune </a>
			de l’
		<a href="/wiki/Allier_(d%C3%A9partement)" title="Allier (département)">
			**Allier**
		</a>
```

I need to extract Allier 
I have tried with the following code
value.parseHtml().select('#div>strong>a[2]').htmlText()

But I get an error that the first item is not an html item.
I'm a newbe in html.
I hope some can help me
Thanks
Bernard

**Comment by thadguidry** [comment]
With Chrome and Firefox you can right click on an element on a webpage and
get lots of details on elements through an Inspector window.  The inspector
window highlights elements and you can move your mouse around in the
inspector window of the HTML code.

In Chrome or Firefox -
1. Right click on the element you are interested in in the page itself and
choose Inspect Element.
2. The inspector window appears with HTML code.
3. In the inspector window move your mouse around and hover over elements
to highlight them.
4. Right click on the <div> or whatever element that you are really
interested in extracting then choose Copy -> Copy Selector (or Css Selector)
5. You can then use that which is copied to the clipboard and paste into
the GREL select() itself, since that just uses Jsoup under the covers.

#mw-content-text > div.bandeau-article.bandeau-niveau-ebauche.plainlinks

becomes

value.parseHtml().select("
div.bandeau-article.bandeau-niveau-ebauche.plainlinks ")

More details here in these links and read the important tip about refering
to Jsoup's specific Selector command (which is what the GREL select()
actually exposes:

https://github.com/OpenRefine/OpenRefine/wiki/StrippingHTML

https://jsoup.org/apidocs/org/jsoup/select/Selector.html

-Thad
+ThadGuidry <https://www.google.com/+ThadGuidry>

**Comment by BernardBoureee** [comment]
Hello Thad


Thank you so much!

Regards

Bernard


_________________

Bernard Bourée

________________________________
De : Thad Guidry <notifications@github.com>
Envoyé : mercredi 15 février 2017 15:59:57
À : OpenRefine/OpenRefine
Cc : BernardBoureee; Author
Objet : Re: [OpenRefine/OpenRefine] Help for building an extraction (#1171)

With Chrome and Firefox you can right click on an element on a webpage and
get lots of details on elements through an Inspector window. The inspector
window highlights elements and you can move your mouse around in the
inspector window of the HTML code.

In Chrome or Firefox -
1. Right click on the element you are interested in in the page itself and
choose Inspect Element.
2. The inspector window appears with HTML code.
3. In the inspector window move your mouse around and hover over elements
to highlight them.
4. Right click on the <div> or whatever element that you are really
interested in extracting then choose Copy -> Copy Selector (or Css Selector)
5. You can then use that which is copied to the clipboard and paste into
the GREL select() itself, since that just uses Jsoup under the covers.

#mw-content-text > div.bandeau-article.bandeau-niveau-ebauche.plainlinks

becomes

value.parseHtml().select("
div.bandeau-article.bandeau-niveau-ebauche.plainlinks ")

More details here in these links and read the important tip about refering
to Jsoup's specific Selector command (which is what the GREL select()
actually exposes:

https://github.com/OpenRefine/OpenRefine/wiki/StrippingHTML

https://jsoup.org/apidocs/org/jsoup/select/Selector.html

-Thad
+ThadGuidry <https://www.google.com/+ThadGuidry>

**Comment by magdmartin** [comment]
Please use the [mailing list](https://groups.google.com/forum/#!forum/openrefine) for support request regarding the usage of OpenRefine. Github ticket are to report bugs and request new feature.

**Comment by BernardBoureee** [comment]
OK thanks
