### ISSUE TITLE
Change to higher performance CSV parser

### ISSUE THREAD

**Issue by xseris** [OpenRefine/OpenRefine#1372]
Why not adopt a more powerful CSV parser? I noticed we still use Bytecode OpeCSV parser for SeparatorBasedImporter and CsvExporter, that is old (last version 2.4: 13 Aug 2014 ) and slow. According to this [benchmark](https://github.com/uniVocity/csv-parsers-comparison) there are a lot of better alternatives. I also made some [tests](https://github.com/xseris/Benchmarking/tree/master/csv) with the latest versions of common CSV parsers, founding that bytecode csv parser is about 50-70% slower. I think that [Jackson](https://github.com/FasterXML/jackson-dataformats-text/tree/master/csv), [SFM](http://simpleflatmapper.org/0101-getting-started-csv.html) or [Univocity](https://github.com/uniVocity/univocity-parsers) could be great alternatives to increase a bit the importing performances.

**Comment by thadguidry** [comment]
@xseris We had issues with earlier versions of Jackson, but that was nearly 7 years ago.  Jackson's CSV parser is considered production ready now since 2.3 and latest is now 2.9.2  Jackson also gives us the flexibility with CSVMapper or Factory...which will be useful to setSchema prior to reading/writing (via previous metadata inspection once we decide on approach in #1096 )

**Comment by jackyq2015** [comment]
I think there are two factors should be considered. One is how fast it can load and another is how much it can load. Current OpenRefine come across issue with big data set which will be failed to load into the system. I am not blaming the CSV parser. There are several reason and one reason is the OpenRefine itself. 

If the library you mentioned above can handle this that will be great! But normally the faster it can load, the more memory it requires.

**Comment by wetneb** [comment]
See also #2268.

**Comment by tfmorris** [comment]
A unique requirement that OpenRefine has for its CSV parser is support for multi-character field delimiters, which greatly limits the field of potential replacement candidates, although it would potentially be possible to have a fast path which uses a higher performance parser for the common single character delimiter case (ie vanilla CSV/TSV) and a more general, but slower, parser when exotic features like multi-character string delimiters are needed.

**Comment by thadguidry** [comment]
What if we gave the user (UI) a choice and let them select if/when needed? They could see issues in the preview and then try the other strict importer.  We could label it "CSV multisepartor" and it would have the separator input box and the strict importer would not.  Or better maybe just have Strict options isolated away in the UI and greyed out until a Strict? checkbox is unchecked.  Or is that a crazy idea?

I feel to blame on this situation since I asked for the support but not too bad since multi character support was needed to clean some of my "messy" CSVs.

**Comment by tfmorris** [comment]
I wasn't thinking of anything nearly as complex. Just simply using the faster parser for single character field delimiters and the slower parser for multi-character delimiters. An explicit override might be useful if the faster parser turns out to be unreliable in some way, but we can probably save designing that until we have some experience with whatever parser gets chosen (if/when someone picks up this task).
