### ISSUE TITLE
Fetch URLs should follow redirections

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1410]
Apparently, HTTP redirections are not followed by the URL fetcher: they probably should.

**Comment by ostephens** [comment]
I'm already looking at the URL fetching as part of #1217 so I can look at this as well

**Comment by ettorerizza** [comment]
[Related question on the mailing list.](https://groups.google.com/forum/#!topic/openrefine/TKdZPToV3hY)

**Comment by ostephens** [comment]
OK - the issue seems to be that the URLConnection library does not follow redirects when they use different protocols to the original request. In particular this means that if you request an http URI, and there is a redirect to an https URI, this will not be followed. Redirects which are to the same protocol (http->http or https->https) work as expected in OpenRefine.

This behaviour is deliberate, as it stops redirects taking the user from a secure protocol to an unsecured one (https->http). The second answer in this StackOverflow post gives a good explanation of why this is a bad idea https://stackoverflow.com/questions/1884230/urlconnection-doesnt-follow-redirect

What is less clear to me is whether there are any issues in supporting http->https redirects (which will be the far more common scenario) - this feels like it is increasingly common and we could support it without any security concerns. 

Any other views?

**Comment by wetneb** [comment]
I agree there should not be any security concern with HTTPS -> HTTP. By the way, if URLConnection does this sort of nonsense, it might be worth migrating to a more modern library (https://stackoverflow.com/questions/1322335/what-is-the-best-java-library-to-use-for-http-post-get-etc). Ideally one that we already have in our dependencies, and in a dream world something that can be easily mocked for tests.

**Comment by ostephens** [comment]
#748 looks like already implements a work around for data import
