### ISSUE TITLE
Installer on package for Linux

### ISSUE THREAD

**Issue by pabloab** [OpenRefine/OpenRefine#1445]
Would be great to offer/build Linux installer on a package form: Classic DEB, RPM or new AppImage/Snap/Flatpak. Either way also would be great to have it available on official repos of main Linux distros.

**Comment by wetneb** [comment]
@pabloab That's very true! This mostly requires familiarity with these packaging systems rather than OpenRefine itself, so it's a good task for anyone who wants to help without diving in the internals too much.

**Comment by magdmartin** [comment]
@pachamaltese can you send a PR so our core team can review and provide feedback and merge it?

**Comment by thadguidry** [comment]
@pachamaltese Hi!  We would like to see this issue get some love.  Do you think you could volunteer as a maintainer for our Linux packaging?  What do you need from us to help, let us know.

**Comment by pachamaltese** [comment]
@thadguidry HI! Of course, let me retake this. A lot of things have changed since my last commit to this, so now I can dedicate time to this.

**Comment by pachamaltese** [comment]
@thadguidry I shall follow package creation in a very similar way to RStudio, I; ll start with DEB files

**Comment by pachamaltese** [comment]
@thadguidry here is an updated deb package https://github.com/pachamaltese/openrefine-deb/releases/download/3.2/openrefine-3.2.deb
now I shall find a way to create an rpm package for fedora/fedora-based

**Comment by thadguidry** [comment]
@pachamaltese How's the progress going on this?  By the way, we are about to push out Github Actions to create nightly releases (and later general releases, packages) so this might be an opportunity to coordinate.

@wetneb @magdmartin any other thoughts on this issue and Github Actions?

**Comment by pachamaltese** [comment]
hi!!

debian/ubuntu: ok and ready

fedora/centos: I need to ask a friend, it's a different world

—————

*Mauricio Vargas Sepúlveda 帕夏*
Do you like Data Science? visit pacha.hk
你爱科学数据专吗？你走pacha.hk

**Comment by pachamaltese** [comment]
@thadguidry Hi. I shall need help to translate the Ubuntu/Debian work (ready) to Fedora/CentOS/RedHat. It's a totally different world. The unified solution would be to create a snap package, but I'd avoid it as much as I can.

**Comment by wetneb** [comment]
Feel free to submit your DEB packaging on its own - it's already something that would be very welcome even without an accompanying RPM.

**Comment by pabloab** [comment]
Have you tried with [alien](https://sourceforge.net/projects/alien-pkg-convert/)? [`alien --to-rpm /path/to/file.deb`](https://wiki.debian.org/Alien)

**Comment by pachamaltese** [comment]
@pabloab the problem with that is that creates a static conversion, and dependencies are not solved

**Comment by pachamaltese** [comment]
@wetneb I've just uploaded what I had in a external drive https://github.com/pachamaltese/openrefine-deb, it's updated to openrefine 3.3.

**Comment by wetneb** [comment]
Ok, so the remaining work to get this integrated in this repository would be to wrap this process inside the Maven packaging process, configured in `packaging/pom.xml`.

**Comment by pachamaltese** [comment]
@wetneb hi, I've looked the xml file and I have no idea of how to integrate deb scripts with that

**Comment by mrjohnc** [comment]
Can I +1 for Flatpak (and appearing on Flathub), very easy for people less experienced with Linux to use, also works well on Intel Chromebooks which expands the range of devices OpenRefine works on

Thanks

**Comment by kristbaum** [comment]
Hi there!

I've tried to create and test a snap package [here](https://github.com/kristbaum/OpenRefine/blob/master/snap/snapcraft.yaml). It woks good so far, but more testing is always good. I've also created an unlisted snapcraft.io storepage [here](https://snapcraft.io/openrefine). 

A pull request with the snapcraft.yaml file could be created (it needs to be in a top-level folder called snap, doesn't work under your packaging folder, sorry), if there is any interest on your side. The control of the store listing could also be handed over to a project member, or shared, depending on your preferred setup. (The person needs to have an [Ubuntu SSO](https://login.ubuntu.com/) account for this to work).

Differences between the snap and the normal installation:

-  the command to start is available from PATH and is called "openrefine" not "refine". We could request an alias for that in the future
- The browser doesn't automatically launch, because of the missing java-desktop integration. (This seems to be solvable but complicated)
- The location of $HOME/.local/share/openrefine is $HOME/snap/openrefine/versionnr/.local/share/openrefine

Apart from this, I think it is mostly the same. But more testing is always good, as of now you can install it via:
`sudo snap install openrefine` on most distros after enabling snap support (see the unlisted store page for instructions if you aren't using Ubuntu).

**Comment by wetneb** [comment]
That is absolutely amazing, thank you so much for doing this!

I would be up for turning that into an official image. Either by including the `snap` directory in this repository, or another one in our organization to avoid cluttering our root directory further (or is the snap name taken from the repository name?).

**Comment by thadguidry** [comment]
@kristbaum I've reviewed it and tested.  I agree with @wetneb that we should make this an official snap.

There's a few things that come to my mind:
1. such as our defaults for the openrefine workspace.  It might not work on **all** distributions that's for sure.  But that's something we can resolve much later as/if we get reports.
    >A snap is a bundle of an app and its dependencies that works without modification across Linux distributions.
2. the snap categories - Select up to two store Categories where your application will be featured.  Only Science right now seems rather limiting for us.  So I'd likely add "Productivity" as well... since "Utilities" is tangential for us.  We're more like [LibreOffice Calc](https://snapcraft.io/libreoffice) I think, yeah?
3. the metadata https://snapcraft.io/docs/adding-global-metadata
4. what releases to support.  I would likely only add our stable latest release and use publish to their [snap "stable" channel](https://snapcraft.io/docs/channels) only (for now).

**Comment by kristbaum** [comment]
> I would be up for turning that into an official image. Either by including the `snap` directory in this repository, or another one in our organization to avoid cluttering our root directory further (or is the snap name taken from the repository name?).

Adding the snapcraft.yaml in another repository would be no problem, as of now it is integrated with my fork and builds every time a new commit happens. 
So if the file were to be used in another repo upon a new release a build should be manually triggered, or some webhooks could be set up to automate this. Also the Version number needs to be changed manually, which could also be automated afaik.
Do you have a recommendation on another repo, or should I pull request the main one?

**Comment by kristbaum** [comment]
>     1. such as our defaults for the openrefine workspace. It might not work on all distributions that's for sure. But that's something we can resolve much later as/if we get reports. 
As of now every automatic build of the release is added as edge automatically and can be promoted to stable manually.
>     2. the snap categories - Select up to two store Categories where your application will be featured.  Only Science right now seems rather limiting for us.  So I'd likely add "Productivity" as well... since "Utilities" is tangential for us.  We're more like [LibreOffice Calc](https://snapcraft.io/libreoffice) I think, yeah?
done.
>     3. the metadata https://snapcraft.io/docs/adding-global-metadata
Do you have any specific values that should be added? The icon is only added to the store listing as of now, but it shouldn't make much of a difference if it were added to the metadata in the folder. Unless you would want to create a real launcher icon, then it needs to be there.
>     4. what releases to support.  I would likely only add our stable latest release and publish to their [snap "stable" channel](https://snapcraft.io/docs/channels) only (for now).
I agree.

**Comment by wetneb** [comment]
Then it sounds like it would be easier with this repository, we could try that first.

**Comment by thadguidry** [comment]
Agree, let's use this repo.

**Comment by pabloab** [comment]
> I would be up for turning that into an official image.

It's an excellent news to have a snap build! But considering [its great controversies](https://hackaday.com/2020/06/24/whats-the-deal-with-snap-packages/)  I wouldn't choose it as an ̣_official image_. I would go for hopefully future  Flatpak build instead, which is the preferred choice for almost everyone except Canonical.

**Comment by kristbaum** [comment]
Couldn't there be more than one official image? The downloadable zip file, a snap package and if somebody creates it a flathub package? Official can just describe coming from the official repository, not packaged by a third party.

Am 30. Januar 2022 21:27:11 MEZ schrieb Pablo ***@***.***>:

**Comment by wetneb** [comment]
Absolutely, we could totally add an official flatpak image too (we already have four different official builds across 3 platforms).

**Comment by wetneb** [comment]
This issue is a mixture of multiple feature requests, so I would like to close it and encourage people to open one issue per package repository they want OpenRefine to appear in.

Also, we now have an `openrefine` Debian package, which landed in Debian testing a few months ago:
https://packages.debian.org/bookworm/openrefine

Packaging OpenRefine for other repositories is still very welcome!

**Comment by pabloab** [comment]
@wetneb [That link](https://packages.debian.org/bookworm/openrefine) is broken, it seems [was moved](https://packages.debian.org/search?suite=all&searchon=names&keywords=openrefine) to `bullseye-backports` and `sid` (unstable).

Also, I believe this issue shouldn't be closed, since currently OpenRefine still doesn't offer on the [release assets](https://github.com/OpenRefine/OpenRefine/releases) **any** Linux package (like a .deb a .flatpakref or an .appimage), the essence of this issue, add the linux package build to the CI.

**Comment by wetneb** [comment]
I would say that at least the `.deb` package is not meant to be built by the CI, since Debian's own build process for it must adhere to certain rules (such as no dependency to online services at build time). So even if we were to build the `.deb` in the CI, it would not be usable as such by Debian, and I would not recommend users to install our `.deb` file manually, but rather use the one from the repositories.

Offering a Flatpak, snap or Appimage build on our own might be more doable, I am not familiar with those formats. I would still prefer having one specific issue for each of those formats if you do not mind, since they can be worked on independently. Would that work for you?

**Comment by wetneb** [comment]
I just created a repository to host the configuration files for containerized builds of OpenRefine: https://github.com/OpenRefine/containers. Feel free to open PRs there to add Flatpak, AppImage, Snap…
