### ISSUE TITLE
Extract view/link URL for reconciled cells

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1457]
In a reconciled cell, the content of the cell is enhanced with a link to the reconciled item in the relevant service/site which has been used for the reconciliation.

From what I can see, the URL for the link is built on the fly by using the cell.recon.service to identify the service being used, to look up the 'view' URL from the service definition, and then building the link by combining the view URL template with the cell.recon.match.id

This makes it impossible (I think?) to extract the URL directly - but this is a feature I've seen asked for more than once.

Is there any reason that the view.url isn't stored directly in the reconciled cell? (either storing the template in cell.recon, or the view/link url in cell.recon.match?

If there is not a strong reason to not store it, I'm inclined to look at adding it in to make it more convenient to extract the information in GREL etc.

@wetneb ?

**Comment by wetneb** [comment]
That would make a lot of sense! I am not sure whether this should be stored directly in the recon objects, or if it should be recomputed on the fly with the id and the URL template. (So, in the unlikely case where the template would change later on, the URLs would be transparently updated.)

**Comment by ostephens** [comment]
At the moment there is some information stored in the recon object that feels like it would cause problems if there is a change to the service:

- cell.recon.service
- cell.recon.identifierSpace
- cell.recon.schemaSpace

Given these are already there, and because my instinct is it will be simpler option, I'm inclined to store the link directly in the recon object

**Comment by thadguidry** [comment]
After a year of thought and recon service reworkings... have the 2 of you come to some final conclusion on the link URL handling ?  on the recon object or recomputed ?  Have folks within Wikidata expressed some preference during workshops, conferences, meetups, etc ?

**Comment by wetneb** [comment]
Storing explicitly is simple to implement, but it is going to make recon objects even heavier (they already take up a lot of memory, I think). Potentially we could take up this opportunity to refactor the Recon objects to keep the `service` and remove `identifierSpace` and `schemaSpace` which would be retrieved from the service at runtime. But that is more involved: reconciliation services are currently stored in the preferences, not in the project data at all… so it is much more involved (and harder to get right).

**Comment by thadguidry** [comment]
Agree, it is also an opportunity to update our code and reduce object counts for ReconEntries ... like using map more, for instance on https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/operations/recon/ReconOperation.java#L307  we could use map.replaceAll() 
It also seems like **all** the old cell recon entries are held in memory until have the run() is complete, or am I misreading the code flow ?

**Comment by wetneb** [comment]
To avoid having to make heavy changes (add a field in the `Recon` Java class), I propose the following approach.

We add a menu entry in the "Reconcile" > "Actions" menu, labeled "Add column with URLs of matched entities". Under the hood, this menu item creates a new column based on the reconciled column, using a GREL expression which inserts the matched id inside the view template found in the service manifest.

For instance, for the Wikidata service, we would be using a GREL expression such as:
`"https://www.wikidata.org/wiki/{{id}}".replace("{{id}}", cell.recon.match.id)`.

@ostephens @thadguidry are you onboard with this approach?

**Comment by thadguidry** [comment]
I like the menu option.  Does the GREL actually work directly in the expression editor also?  That's what @ostephens wanted originally above.

**Comment by wetneb** [comment]
The GREL expressions generated (like the sample above) already work in OpenRefine of course, and I am sure people come up with similar things on their own.

But this solution would *not* give users an easy GREL access like `cell.recon.match.url` which could be used independently of the service. I see the value in that for sure, but I think it could be implemented as a second step. I think providing the menu option would already help a lot of people as such (and this feature request is already 5 years old so I feel like it's better to deliver something soon rather than block it for more years because we set a too high bar for ourselves).

**Comment by thadguidry** [comment]
Gotcha. Agree.

**Comment by ostephens** [comment]
I'm happy this approach improves things and is probably sufficient in most cases.

**Comment by ayushrai206** [comment]
Hello everyone,
I just made a pull request that works for reconciliation services like Wikidata(service url-https://wikidata.reconci.link/en/api) as it has a view url but not for reconciliation service like -https://fornpunkt.se/apis/reconciliation/geonames which has the view url under the name of preview. I need suggestions upon how to tackle this one. Thank you so much in advance!

**Comment by wetneb** [comment]
Amazing, congrats for this great progress!

It's interesting that https://fornpunkt.se/apis/reconciliation/geonames does not provide a `view` field. This field is optional according to [the specifications](https://www.w3.org/community/reports/reconciliation/CG-FINAL-specs-0.2-20230410/#service-manifest) so it's something we need to plan for indeed.

Intuitively I would say that the feature should be disabled if the reconciliation service does not have a `view` field. For instance with an `alert()` with a message such as "The reconciliation service does not associate URLs to the entities it contains."

I'll add more comments regarding to your implementation in the PR itself.

**Comment by ayushrai206** [comment]
Hey everyone,
 In my recent commit I have modified the GREL function so that it displays an empty cell for the unmatched cells  of the reconciled column, can anyone think of some better way to handle this situation or we should go ahead with this?
Thank you

**Comment by ostephens** [comment]
That sounds reasonable to me @ayushrai206

**Comment by ayushrai206** [comment]
Hi everyone,
 I noticed that even if we are only displaying url of matched entities for reconciled cells the message after creating the new column says it '...filled <the total no. of rows in the column> rows with...'(i.e. even if some rows are empty because their corresponding cells are unreconciled), what should we do about this?
Thank you!

**Comment by ostephens** [comment]
That's because you are populating the cells with an empty string - so the function runs GREL like:
`if(cell.recon.match!=null,<service view url>.replace("{{id}}",escape(cell.recon.match.id,"url")),"")`

If you use null instead then it will only report the ones that have been filled with a value
`if(cell.recon.match!=null,<service view url>.replace("{{id}}",escape(cell.recon.match.id,"url")),null)`

To be honest I'd never noticed this difference in reporting before, but if you want to keep the report to only be the cells where they were populated with a value you can switch to the second version. I don't have strong feelings on which the 'correct' behaviour is though

**Comment by wetneb** [comment]
While reviewing #5960, I realized that we likely need to prompt the user for the new column name, like the existing action which adds a column of entity identifiers. We cannot use a fixed name for the generated column, because a column is already using this name, we are not going to be able to add another column with the same name.
I see various options for that:
* either we imitate the UI of the "Add entity identifiers column" action (just prompt the user for a column name) - in which case it's worth being aware of the current issues with it: https://github.com/OpenRefine/OpenRefine/issues/5998
* or use an automatically generated column name (which does not conflict with any existing column name)
* or even merge the two menu entries and let the user choose between identifiers and URLs in the dialog itself? Maybe it helps with keeping the menus more compact? But maybe the menu entry would become less clear because of that?

@ostephens how would you go about this?
