### ISSUE TITLE
Support streaming file import for project creation

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#147]
_Original author: iainsproat (September 30, 2010 11:59:20)_

At the moment, as I understand it, an imported file is uploaded to Refine with the entire importing process loading everything into memory.  Only once the entire import process has finished is the Refine data file saved and the memory released.  This causes the memory limits to be exceeded when dealing with large files.

I'd like to propose refactoring the import process to stream files, and deal with the data import on a record-by-record basis.  i.e. the Refine project file is appended to after every few records and the memory cleared for the next batch.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=147_

**Comment by junwei-wang** [comment]
what going on with streaming inputs?

**Comment by tfmorris** [comment]
@junwei-wang The conversation here pretty much summarizes things.  Is there a specific aspect that you don't understand?

**Comment by junwei-wang** [comment]
@tfmorris I am wondering whether Refine support stream processing. I mean the input is a stream and the output is a stream. I don't have to load and process the data all at once. I process the data with all operations one by one.

**Comment by wetneb** [comment]
Update on this: the architecture in 4.0 implements some of the ideas mentioned here. Many importers, operations and exporters are able to work on the data in a streaming fashion. This makes it possible to work on datasets which do not fit in RAM (see [this video](https://vimeo.com/568913971)) for a demo).

While some importers work in a streaming fashion, some of them do need to do multiple passes on the data. For instance, the CSV/TSV importer needs to do one pass on the entire dataset to determine how many columns it has (because the number of columns of the project is the maximum number of columns on any given row). There are also importers and operations which still load the entire data set in memory (for instance, XLS or ODS importers, or transpose operations), because the underlying libraries or the operation definition make it difficult or impossible to avoid.

For workflows which consist only of stream-based workflow elements (importers, operations, facets, expressions, exporters), it would be nice to be able to execute those in a genuine streaming fashion. I would like to try implementing this in a command-line interface, which could then be used as part of a wider pipeline (even reading the input dataset from the standard input and printing the exported dataset to standard output). This would be based on the modularization of our code in various Maven artifacts which could be used directly by an external project to implement this. See this thread on the forum for more details: https://forum.openrefine.org/t/a-new-start-for-the-4-0-architecture/51

**Comment by wetneb** [comment]
I think this issue is really about the project creation stage so the 4.0 architecture solves this: closing.
