### ISSUE TITLE
Document backend commands/operations to help separate frontend/backend

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#1483]
@thadguidry is currently using Structure101 to begin documenting what will be the backend API.

However mostly this is already documented from a high-level in /main/webapp/modules/core/MOD-INF/controller.js

**Comment by magdmartin** [comment]
A first mapping is available on the page 5 of[ OpenRefine Batch Processing with Apache Beam document.](https://docs.google.com/document/d/1WT8nCYdNUU14y39IJJlB9fqnxhO0XZnjgHZljEdw-60/view#heading=h.vu5af3jav0u)

**Comment by wetneb** [comment]
Just noting that the backend and frontend are separated - there is no particular coupling to be undone as far as I am aware. Unless someone has a clear example of what they find problematic?

That being said we can always document the existing API commands, that definitely cannot hurt.

**Comment by thadguidry** [comment]
I think @tcbuzor found some coupling... will ask him to comment here.
@jackyq2015 was the one who originally was speaking about this.  Is he still around to comment?

**Comment by wetneb** [comment]
I propose we close this in a few weeks unless anyone can come up with a concrete coupling issue.

**Comment by fpompermaier** [comment]
The problem is that you can't deploy backend services and frontend separately, they are tightly coupled

**Comment by wetneb** [comment]
That is not what I would call backend/frontend coupling… That would be the case if the backend was rendering HTML there directly, which is not the case: it just serves a single-page app which then does API calls to interact with the frontend. So I don't see any big architectural issue here.

The fact that the frontend is served on the same web server as the backend is desired (you want them to be served on the same port). The concrete separation between the two parts will change when we migrate out of Butterfly.

If we agree that Butterfly is the issue here, can we stop calling that "coupling" and use "migrate out of Butterfly" instead?

**Comment by thadguidry** [comment]
yes, "migrate out of butterfly" is the issue that i see also

**Comment by thadguidry** [comment]
closing this issue... we have a better roadmap now
