### ISSUE TITLE
Ensure consistent behaviour on populating a cell with an empty string

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1491]
From #820 

If you try to populate a cell in OpenRefine with an empty string, there is different behaviour in different circumstances. Specifically if the cell already contains null, then doing either of:

* Edit cells -> Transform and put ""
* Edit cells -> Transform and " ".trim()

Results in the cell still containing null.

However, if the cell contains a non-null value, then the two operations above result in the cell being populated with an empty string.

Both transformations should always result in the cell containing an empty string and this behaviour should be consistent whether the cell initially contains a null or non-null value **<-- THAD HAS ISSUE WITH THIS STATEMENT...User knows best, we should let user decide, avoid saying "always" which usually implies MAGIC for us behind the scenes and we traditionally try to avoid that.**

**Comment by ostephens** [comment]
It looks like it is 'sameValue' in main/src/com/google/refine/expr/ExpressionUtils.java that leads to the current behaviour. This treats a null value and a zero length string value as being the same.

It's easy to change this, but before doing this, I'm trying to think of any implications of ceasing treating these as equivalent here.

@thadguidry do you have any background info on why these are currently treated as equivalent when comparing values?

**Comment by thadguidry** [comment]
@ostephens Yeap, the background for treating them the same was to make simplifying the GREL handling characteristics.  We assumed that most users of OpenRefine did not care about NULL and just wanted Blanks or ZERO LENGTH STRING.  However, we now know, 8 years later, that these should actually be handled distinctly, since that has risen to be the expectation from most journalist, data scientists, etc.  Basically, we assumed too early that the world didn't care much about NULL as much as we did.  We were wrong.  They care :)  So we can now go back and change this assumption so that NULL and ZERO LENGTH STRING will be treated distinctly in OpenRefine.  Its a minor change to how OpenRefine treats the semantic meaning of NOTHING.  For purists and data scientists, its NULL.  For journalists and the vast majority of our users its ZERO LENGTH STRING.  This will take care of Export value issues automatically, since users can now explicitly convert NULL references to BLANK or whatever String value they want (like what I do sometimes <NULL>.
