### ISSUE TITLE
Duplicating a reconciled column

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1548]
We can duplicate a column by "add column based on this column" and the default `value` expression, but that will only copy the values, not the reconciliation data. There is a "Copy reconciliation data" operation but it does not seem to work for me. (I haven't looked into the code to see what is happening there)

When working with wikidata, we can create a new column with `cell.recon.match.id` and then reconcile that again, but it is a bit sad that this reconciliation step is required.

Did I miss anything?

**Comment by thadguidry** [comment]
@wetneb It still works just fine for me in OpenRefine 2.8 ... just tested with

Abraham Lincoln
George Washington
Barack Obama

Where all 3 were Recon'd and matched.
I made a new column based on "copy value from original column"
Then selected Copy Recon and the dialog came up and I clicked Copy...
![capture](https://user-images.githubusercontent.com/986438/37780655-2a441e3a-2dbd-11e8-9f15-776c5453871d.PNG)

**Comment by ettorerizza** [comment]
Oh gosh, God, never paid attention to this very useful function... The reconciliation menu is too crowded with obsolete features related to Freebase. As all this stuff is not documented, when something does not work, we tend to give up too quickly. 

I am just discovering the "best candidate type" facet that looks super-interesting. It allows to classify candidates by their classes (the QID of the classes in the case of Wikidata) !

**Comment by wetneb** [comment]
@thadguidry okay, it seems that it checks that the cell values are equal before transferring the reconciliation results (which was not the case for me).

**Comment by msaby** [comment]
While writing about #2114 I tried to understand the behavior of "Edit cells > copy reconciliation data".

It is the only menu in OR that copy values in an other column, instead of creating new column. I suppose the only way to use this feature is a manual workflow with 2 steps : 

- step 1 : create a new column with the values of the source column (column -> create new colum...)
- step 2 : copy recon data to that new column.

That would explains why the underlying values of source and destination columns have to be the same.

So would you agree to see this menu creating a new column instead of copying recon data to a new column? The user will be asked the name of the column to create, then this column will be created with a copy of "ordinary" values of source column, then the recon data will be copied to that new column.
