### ISSUE TITLE
Frustrating UI for the selection of reconciliation services.

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1658]
#### Steps followed to create the issue:

Select a reconciliation service - the service panel sometimes comes back
https://twitter.com/ruthbrarian/status/1008786606495584257
The UI should be more intuitive there.

#### Version of OpenRefine used:
3.0

**Comment by tfmorris** [comment]
That tweet no longer exists. Is there any more information available on when this happens (a particular reconciliation service?) or why?

**Comment by thadguidry** [comment]
@tfmorris I sent her an email just now:
>Hi Ruth,
>
>We are curious if you still have problems with the Reconciliation Service panel in OpenRefine.We saw that you opened the issue here:https://github.com/OpenRefine/OpenRefine/issues/1658and would like for you to give us a bit more information if you recall if it was Wikidata Recon service or some other custom Recon service that caused the panel to "come back".
>
>Please add the steps into the issue if you recall them (2 years ago!) and we can take a look more deeply.  If the issue has been resolved, then just type in an issue comment that you no longer have this problem or that you are using a newer OpenRefine version that has fixed the issue for you.
>
>Thanks so much!

**Comment by wetneb** [comment]
There you go:
![recon_dialog_ui_bug](https://user-images.githubusercontent.com/309908/84932443-95bd7c00-b0d4-11ea-817f-6af732576e4c.gif)

**Comment by ruthtillman** [comment]
Checking my twitter archive, I found the tweet was "This box will. not. stay. shut. It's like an over-sugared toddler. Any tips? #openrefine ??????????????????? Whyyyy. (I click either services or the bookmark-type icon and it closes and then hey it's back again)"

the above demonstrates it. And I think in the interim I've switched versions and that might've solved it? But maybe not. However if you can still do the above... yeah, that's it. :-/

**Comment by thadguidry** [comment]
@wetneb Is that still a problem in 3.4 version?

**Comment by wetneb** [comment]
Yes it is still current.

**Comment by tfmorris** [comment]
A related issue, which might actually be triggering this, is that the panel doesn't close after adding a new service, obscuring the rest of the panel. I didn't recognize the little tab as a "close" affordance, so ended up dismissing the entire dialog and then starting the reconciliation over again.

**Comment by thadguidry** [comment]
@tfmorris It looks like an old product price tag to me, so not the best choice for a slider icon.  It should be an close X icon and also we should simplify the handling by introducing a visibility toggle icon as well or another button called "Services..." next to the existing button "Add Standard Service...".  Instead of keeping the slide effect that retains the price tag icon and sliver of the Services panel.

Something like this behavior: https://material.io/components/sheets-side#standard-side-sheet

**Comment by wetneb** [comment]
@pyrog is the problem still present on the master branch? This issue should have been closed by #2915. (It has not been closed because it was not properly linked to the pull request)

**Comment by pyrog** [comment]
> @pyrog is the problem still present on the master branch?

Yes with [**Firefox**](https://www.mozilla.org/en-US/firefox/79.0/releasenotes/?utm_campaign=whatsnew&utm_medium=firefox-browser&utm_source=firefox-browser) 😞 
Also, there is the same issue when you delete a service.

But it worked fine with **Chrome**  😃
Version 84.0.4147.125 (Build officiel) (64 bits)

And with **Safari**, issue #2990 is still there  😢

**Comment by allanaaa** [comment]
This problem persists in Firefox with 3.4 - I've never seen it before today, when I added the GND service. I wonder if it's happening (at this state) because certain services don't go into "Working" and thus trigger a retraction.

![service-tab](https://user-images.githubusercontent.com/28012148/92639249-856b0680-f2a9-11ea-8ea2-42a3fdcf992f.gif)

It both stays shut when you want it open, and stays open when you want it shut. 

![service-tab2](https://user-images.githubusercontent.com/28012148/92639259-87cd6080-f2a9-11ea-92bd-499fb1afebc9.gif)

**Comment by wetneb** [comment]
Yes we have not released this in 3.4, it will only be there in 3.5.

**Comment by wetneb** [comment]
This was closed by #2915, it is a duplicate of #2913.
