### ISSUE TITLE
Reconciled cells showing as (unreconciled) in facet

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1667]
**Describe the bug**
After reconciling cells, a "best candidate's types match" facet shows them as (unreconciled)

**To Reproduce**
I'm not completely sure what behaviour led to these particular cells showing as "unreconciled" - it doesn't happen to all cells. 

I think, but not 100%, that this has occurred where after the initial reconciliation step there are no matches at all, and then I've used the "Search for match" option to find the correct match

**Current Results**
![screen shot 2018-06-29 at 11 09 46](https://user-images.githubusercontent.com/576174/42087262-8a4787d6-7b8d-11e8-942f-9f093da20c2b.png)

**Expected behavior**
I would expect all the cells shown here as '(unreconciled)' in the facet to be showing as either 'true' or 'false'

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser: Safari

**OpenRefine (please complete the following information):**
 - Version: OpenRefine 3.0 Beta

**Comment by wetneb** [comment]
This is partly an issue of OpenRefine, partly of the reconciliation service.

This happens because the reconciliation interface does not return types in the suggest service. It should, but I still haven't got round to doing it yet, because it raises some performance issues.

Because it returns an empty list of types, the expression `forNonBlank(cell.recon.features.typeMatch, v, v, if(isNonBlank(value), "(unreconciled)", "(blank)"))` treats the entire cell as blank. So maybe we should just return a default uninformative type in the reconciliation service.
