### ISSUE TITLE
Implement "Prepend rows" command from gokbutils

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#1855]
The gokbutils extension includes a command which adds blank rows to the start of a project. This is a request to implement that command into the core product using the same implementation as currently in the gokbutils

 https://github.com/ostephens/refine-gokbutils

**Comment by ToVie** [comment]
Hi
is there a reason, why this enhancement is not pursued?
Best regards
Tobias

**Comment by wetneb** [comment]
Hi @ToVie, probably simply because nobody found the motivation or time to work on it. Personally my priority is to release a stable 3.5 release at the moment.

**Comment by ToVie** [comment]
Hi @wetneb , ok - I thought it might had technical reasons. But I get your priority. Using 3.5beta1 I find it stable and reliable. Though it chokes on URLs with uncoded blanks - should I write an issue?

**Comment by wetneb** [comment]
Yes please, that would be great!

**Comment by Ishankoradia** [comment]
Hey @wetneb  , I had like to work on this. I have gone through the contribution guidelines and have also set up the dev environment on my local pc & have open refine up & running. Could you assign this to me ? 

From what i have understood is the command class `AddRowsCommand`  in the extension needs to be migrated to `src/com/google/refine/commands` . Right ?
I am a little confused with the UI/UX. where would this command option go in the UI ? Is it under `All` ?

**Comment by wetneb** [comment]
Hi @Ishankoradia, thanks a lot for the interest!
This is a task that I have proposed as an [internship subject for GSoC](https://github.com/OpenRefine/OpenRefine/wiki/GSoC-Outreachy-2024-Ideas). So intuitively I would rather reserve it for that.
Is your interest in this issue related to GSoC at all?

That being said, I think my estimate of 175h for this project is on the very generous side, especially if the design is already specified ahead of time in the issue. It vastly depends on the proficiency of the person tackling the task, of course, but I think there is also a case to be made that this issue should be available for the initial contribution period rather than as an internship subject. Even then, that wouldn't make it a good first issue either: I would encourage you to start with something smaller.

**Comment by Ishankoradia** [comment]
Hey @wetneb , yes I was lead here from the GSoc project ideas page. I am planning to apply this year and would like to undertake this as my project idea. This looks challenging enough for me.  

I will take a closer look at the code based to understand the idea behind this task. Do you recommend any smaller issues for me to start with ? Just to get my hands dirty and as a warm up.

**Comment by wetneb** [comment]
Yes, we specifically maintain a list of [good first issues](https://github.com/OpenRefine/OpenRefine/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22).

**Comment by tfmorris** [comment]
> This is a request to implement that command into the core product using the same implementation as currently in the gokbutils

That implementation uses [MassRowChange](https://github.com/OpenRefine/OpenRefine/tree/6ba044c4e39d49b0dd4221f4b9a9328e5c71117c/main/src/com/google/refine/model/changes) which is a pretty resource hungry approach, basically copying the entire project.. I would suggest creating a RowInsertChange along the lines of [RowRemovalChange](https://github.com/OpenRefine/OpenRefine/blob/6ba044c4e39d49b0dd4221f4b9a9328e5c71117c/main/src/com/google/refine/model/changes/RowRemovalChange.java).

Extending the implementation to allow the specification of an insertion point (ie insert new rows before/after row N) would allow more flexibility for users who want their new rows at the end or somewhere else.

**Comment by zyadtaha** [comment]
Hi @wetneb, I am interested in "New operation to add blank rows" Project and want to start contributing and solving this issue.
Is the project still available or someone already took?

**Comment by wetneb** [comment]
Hi @zyadtaha, this issue will only be assigned after someone successfully applies to do a GSoC internship on it (via the GSoC portal). Looking forward to reading your application there!

**Comment by Ahmed-Elgamel** [comment]
Hi @wetneb ,I have read openRefine's GSoC projects but this one particularly interests me.Is the feature requireed to add only one row or given a number it appends this many rows?

**Comment by lokendra-singh-rao** [comment]
Hey @wetneb, I am coming from gsoc. It's my first time to gsoc but my skills help me believe that I can do it for sure. But I have some doubts, as I can see from the above discussion that many people are interested in this, will it be given to one only or more than one ?

**Comment by wetneb** [comment]
@Ahmed-Elgamel as you can see in the discussion above and the title of the issue, the goal is to be able to add multiple rows at once.

@lokendra-singh-rao at most one applicant will be selected to work on any given topic

**Comment by steve-kasica** [comment]
I just stumbled upon this issue during the community meeting today, and I actually wrote some backend code a month ago that provides a proof of concept or starting point for this feature request. I just pushed it in a [branch of my OpenRefine fork](https://github.com/steve-kasica/OpenRefine/tree/prepend-rows). I wrote it as part of an extension I'm making. I wasn't aware of the gokbutils extension until today. Coincidentally, I followed [RowRemovalChange](https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/model/changes/RowRemovalChange.java) as a guide, as @ostephens suggested. 

I'm not sure if GSoC makes sense for me, but happy to be involved with whoever gets assigned this topic/issue. It fits into my multi-table data wrangling focus because in the last paper I pushed we found users who wrangle data with Python or R often have to use a UNION-like operation to insert just a few rows, which is kind of overkill. So I'm a fan of seeing this feature implemented in OpenRefine core.

**Comment by tfmorris** [comment]
That looks great. I didn't review in detail, but it looks like it is basically done except for the addition of unit tests which doesn't seem like enough work to be the basis for a GSoC project. Would you be willing to add a test and submit it as a PR?

A couple of things caught my eye. This [comment](https://github.com/OpenRefine/OpenRefine/compare/master...steve-kasica:OpenRefine:prepend-rows#diff-24637376e30d138ceb1f9b4f5b95235ba7dfab3fa5f6021b139cb023ce6c81feR18-R19)

```
// It's not technically an engine dependent command, but it is easier to write
// by extending EngineDependentCommand than Command
```
suggests that perhaps we should refactor this class hierarchy. Can you expand on your comment? (Perhaps in the form of an issue requesting one or more refactorings, like hoisting useful methods into the superclass)

>  because in the last paper I pushed we found ...

Is this paper available someplace?

**Comment by steve-kasica** [comment]
Thanks @tfmorris! I'd be happy to test it and submit it as a PR. The only testing I've done is a smoke test on my machine with [Postman](https://www.postman.com/roundup/workspace/openrefine-commands/request/1484391-85249422-9a26-4e04-8a98-48f4b6c60ca0?action=share&creator=1484391&ctx=documentation). A little code review from someone with more experience with OpenRefine's source code would be beneficial for me too. I'm working on more commands that follow this pattern, e.g. aggregating rows, interpolating rows, copying projects, splitting projects, joining projects.

With regards to that comment, I just started diving into the OpenRefine codebase over the last month or two. So maybe I'm doing things completely wrong, and please don't hesitate to tell me if I am. But, now that I think about it a little more, I'm leaning towards refactoring that command to extend `Command` for consistency. But I still posted it as an issue for discussion, #6443.

I've published two papers on users' patterns and tasks when wrangling data. I can't remember which one that observation came from or if its a synthesis of both. But those papers, with recordings of video talks, are:

- [Table Scraps: An Actionable Framework for Multi-Table Data Wrangling From An Artifact Study of Computational Journalism
](https://www.cs.ubc.ca/group/infovis/pubs/2020/table-scraps/)
- [Dirty Data in the Newsroom: Comparing Data Preparation in Journalism and Data Science
](https://www.cs.ubc.ca/group/infovis/pubs/2023/dirty-data-in-the-newsroom/)

**Comment by tfmorris** [comment]
Thanks for the papers! I'll add them to the reading list. Thanks for creating the issue for the refactoring discussion as well. I've added a draft PR there for discussion

On closer examination of your code, it looks like it doesn't just create empty rows, but has provisions for adding new rows based on data from the front end. What does the UI look like for this?
