### ISSUE TITLE
Support BibTex import into records

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#195]
_Original author: thadguidry (November 11, 2010 19:38:44)_

Ed Laurent (Freebase expert) would like to be able to use Google Refine to import BibTex files to then load data into Freebase regarding citations &amp; scholarly works.  He currently uses EndNote which he can use to export into XML, BibTex, and EndNote format among others. His other tools only have BibTex support unfortunately hence the need for this use case. (Note: Some academics also use Mendeley.com and Zotero Firefox plugin which also support BibTex and EndNote formats) (SubNote: Mendeley.com has a public api ! - darn, it's no longer truly public, but requires free registration.)

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=195_

**Comment by jrovegno** [comment]
(Zotero,Mendeley,EndNote,etc) Bibtex ->  (Jabref) csv -> OpenRefine

**Comment by DFoltzMorrison** [comment]
A problem with exporting from Mendeley to Bibtex is that non-ascii characters are converted into a LaTeX format, for example É becomes {'{E}}.

My solution was to export citations from Mendeley as an Endnote XML and import that into openrefine. I had to Join a few multi-valued cells after the import, but I avoided character encoding errors along the way.

**Comment by ettorerizza** [comment]
@DFoltzMorrison The workflow "Bibtex -> JabRef : export to CSV -> Open Refine" explained above seems to work quite well.

**Comment by DFoltzMorrison** [comment]
In most cases, yes. But Mendeley -> Bibtex can cause character encoding issues. É becomes {'{E}}, ö becomes {"{o}}, etc. That's obviously an issue with Mendeley that hasn't been addressed ([example 1 ](https://github.com/apcshields/zotero-bibtex-parse/issues/3), [example 2](https://github.com/Docear/Desktop/issues/426))

That's why I've suggested Mendeley -> export to Endnote XML -> openrefine in those cases.

**Comment by ettorerizza** [comment]
Ouch, the [Python bibtex parser](https://pypi.python.org/pypi/bibtexparser) mentioned in your first link is anything but simple. I hope there is something similar in Java, otherwise we will not see this importer anytime soon...

**Comment by thadguidry** [comment]
@ettorerizza There's is now a robust Java Bibtex parser https://github.com/jbibtex/jbibtex

**Comment by thadguidry** [comment]
Supports BibTex and RIS for Endnote importing https://michel-kraemer.github.io/citeproc-java/

**Comment by shelomi99** [comment]
Hi, I'm currently looking into this issue. Can I know the expected outcome of this feature? Should this be only focused on supporting the import of BibTex files?

**Comment by antoine2711** [comment]
@shelomi99 : yes. Importing BibText is enough.

Regards, Antoine

**Comment by shelomi99** [comment]
Thanks, @antoine2711 can you assign this issue to me, I can start working on it.

**Comment by shelomi99** [comment]
Hi, @antoine2711 I could use a little help with identifying the files that need to be modified to achieve this. Am I correct to assume that the entry point should be the `controller.js` where I can create a java file just like the `JsonImporter.java`. But I see 2 parser interfaces like `json-parser-ui.html` and `json-parser-ui.js`. Should I create such parser UI files for the BibTex importer as well? Overall, how many files should be created/modified  to implement this importer

I could use your guidance on how to complete this. Also, the parser that I'm planning to use is [1], and please mention if there are any objections to this.

Appreciate your input on these concerns.

[1] https://github.com/jbibtex/jbibtex

Kind regards,
Shelomi

**Comment by wetneb** [comment]
> Should I create such parser UI files for the BibTex importer as well?

yes!

> Overall, how many files should be created/modified to implement this importer

I am not used to giving this sort of quote, but on top of my mind:
* editing `controller.js`
* adding `bibtex-parser-ui.html`
* adding `bibtex-parser-ui.js`
* adding `BibtexImporter.java`
* adding `BibtexImporterTests.java`
* editing `pom.xml` to add a dependency to your Java Bibtex parsing library

There might be some I have forgotten about.

**Comment by shelomi99** [comment]
Thank you @wetneb

**Comment by wetneb** [comment]
As it has been noted above, BibTeX is actually a pretty complicated format, suffering from a lot of oddities imported from LaTeX.
Since it is rather domain-specific (academics, libraries) I would say that this is a good candidate for an extension. The good thing about making this an extension is that one would be free to use GPL-licensed libraries (or even closed source tools if you are into those sorts of things!), so it would give a broader choice of parsers - although superficially jbibtex could do the job.

Feel free to reopen if you feel strongly about it being in the core tool.
