### ISSUE TITLE
Problem reading CSV with initial null values

### ISSUE THREAD

**Issue by TeraBlitz** [OpenRefine/OpenRefine#1971]
The program when reading csv with initial null values previews them correctly but when the proyect is created it mistakeingly groups them in a wierd way with the previous column 
example:
this csv file:

a,b,c,d,e
,b,c,d,e
a,b,c,d,e
,,c,d,e
a,b,c,d,e
,b,c,d,e

it previews it like this:
![image](https://user-images.githubusercontent.com/18179402/53357023-75bbe500-38f2-11e9-8e52-7244fc2ae3dd.png)

but once the proyect is created it results on this:
![image](https://user-images.githubusercontent.com/18179402/53357066-92f0b380-38f2-11e9-9b59-2f3d93918026.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Chrome and Edge
 - JRE or JDK Version:
![image](https://user-images.githubusercontent.com/18179402/53357146-ce8b7d80-38f2-11e9-9d74-2a60c95af2b4.png)

**OpenRefine (please complete the following information):**
 - Version: Version 3.1 [b90e413]

**Comment by wetneb** [comment]
@TeraBlitz this is because OpenRefine uses its **records mode** by default. This records mode is a way to represent a hierarchical structure between rows and columns. This only makes sense for some data sources though, so if that does not apply to yours, just switch to the **rows mode** and you will obtain the desired result.

See https://librarycarpentry.org/lc-open-refine/03-working-with-data/index.html for some explanations about these two modes.

**Comment by TeraBlitz** [comment]
Thanks for the help/explanation!
