### ISSUE TITLE
Migrate out of Codacy

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#1972]
Codacy has multiple issues:
- their assessment of pull requests is not reliable as their detection of new and closed issues tends to issues that are unrelated to the changes
- the assessment takes quite a long time: codacy-bot generally comments on pull requests a long time after the PR is opened, which generates unwelcome notifications. 
- I haven't managed to turn off the spurious issues that are not useful to us
- code coverage is not taken into account in the PR assessment, and is poorly displayed in the codacy UI (if at all)
- they tend to have a fairly aggressive marketing and send out a lot of emails, the last one signalling me that they would stop OpenRefine's analysis if I don't log in to Codacy in a few days.

I propose that we migrate to a different service, focused on test coverage, such as Coveralls (which I know works well from other projects) or Codecov (which has an interesting diff coverage view).

**Comment by thadguidry** [comment]
Super big +1 and for the same reasons you gave.

There is also Sonarqube itself, which we use at Ericsson. And its available FREE for Open Source Projects in a hosted cloud platform that already integrates with Github with 1 click setup ... https://sonarcloud.io/about

You could try all 3 and then pick the one you most prefer... I am fine with any (since they all use the same backend plugins and db for Java/Javascript projects - cve, findsecbugs, etc.) So the only difference is in features and preferences.

**Comment by thadguidry** [comment]
I've deleted the Codacy account...as well as deleted the Webhook from our Github org settings.
