### ISSUE TITLE
discrepancy in number of rows expected

### ISSUE THREAD

**Issue by only1chunts** [OpenRefine/OpenRefine#1978]
**Describe the bug**
I have a txt file (table using | delimiter) with only 7 columns, but 755846 rows (including 1 header row).
When I import it into OR it tells me there are only 755797 rows (or records, no difference in number)
I have checked the input file and there 0 duplicate rows and there are 0 blank rows
Whats even more weird is that when I export that same data from OR as a tsv file and open it a text editor (or use wc -l) it tells me it contains 755846 rows! 
So why does the OR view of it tell me there are 50 less rows than it actually has?

**To Reproduce**
unfortunately the input file contains some unpublished data so I cannot openly share it here.

**Screenshots**
The input file has this summary:
![input-file-summary](https://user-images.githubusercontent.com/6037145/54025821-9c500a80-4193-11e9-9793-afe425cc5d7f.png)
When imported into OR it shows this:
![or-screenshot](https://user-images.githubusercontent.com/6037145/54025822-9c500a80-4193-11e9-9349-eb4566ca3191.png)
when exported from OR and opened in a text editor again, it shows this:
![or-output-file-summary](https://user-images.githubusercontent.com/6037145/54026312-51cf8d80-4195-11e9-819a-907302f7a2e8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10,
 - Browser Version: Chrome Version 72.0.3626.121 (Official Build) (64-bit)
 - java version "1.8.0_201"

**OpenRefine (please complete the following information):**
 - Version 3.1 [b90e413]

Any suggestions?

**Comment by ostephens** [comment]
It is possible for the number of rows in a tsv to be greater than the number of records (in a general sense, not the OpenRefine 'record') in the file. This is because it is valid for a tsv 'cell' to contain new line characters.

I have also occasionally seen other issues that have cause OpenRefine to not parse the file as expected when imported - I've never really understood the underlying cause, but I've seen it in situations where there are hebrew characters in the original data, which leads to what should be separate columns being lumped into a single cell

Some things to check:
* Are you sure there are really 755846 in the file, or is it possible that some of the rows counted by `wc -l` are actually multi-row records?
* Can you identify any rows in the OpenRefine project that have unusually large amounts of text in a single cell, or any cells which are empty which you would expect to be populated - in this case look for multiple bits of data being incorrectly merged into a single cell
* Do you unexplained empty columns in your OpenRefine project that might be populated on specific lines where (for e.g.) two lines in the original file have been interpreted as one line in OpenRefine? - in this case, look at what character has been used to indicate a new line in the original text file.

Hope that makes some kind of sense and helps you to identify the issue

**Comment by thadguidry** [comment]
Hi @only1chunts , In addition to what Owen says to check, I wanted to make sure you understood the concepts happening there...we call them Record Rows... rows within a record, which sometimes folks don't understand depending on their background of working in various tools with data.  This is all detailed on our Wiki here: https://github.com/OpenRefine/OpenRefine/wiki/Variables#record

**Comment by only1chunts** [comment]
Many thanks for the advice. I've finally found the issue, 4 instances of spurious quotation marks! they made some of the rows get treated as single values within 1.
Please go ahead and close this ticket, you can mark it up as user-error! sorry to have bothered you.

**Comment by ostephens** [comment]
@only1chunts don't apologise - all issues welcome (here or on the forum http://groups.google.com/forum/#!forum/openrefine). Glad you sorted
