### ISSUE TITLE
innerXml() not working in some cases

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#1980]
**Describe the bug**
In some cases innerXml() does not return the content of an xml element

**To Reproduce**
In a cell, enter this content : 
<?xml version="1.0" encoding="UTF-8"?>
<record>
  <datafield tag="035" ind1=" " ind2=" ">
    <subfield code="a">TEST</subfield>
</record>

Try to apply those GREL transformations : 
value.parseXml().select("datafield[tag=035] subfield[code='a']")[0].innerXml()
-> blank
value.parseXml().select("datafield[tag=035] subfield[code='a']")[0].innerHtml()
-> TEST

**Current Results**
What results occured or were shown.

**Expected behavior**
value.parseXml().select("datafield[tag=035] subfield[code='a']")[0].innerXml()
-> TEST

**Screenshots**
![image](https://user-images.githubusercontent.com/932804/54153813-c2e69d80-4440-11e9-8784-92c5ac6e17bf.png)

![image](https://user-images.githubusercontent.com/932804/54153835-cb3ed880-4440-11e9-9073-ab0b7d7c0378.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Version: Chrome
 - JRE or JDK Version:[output of "java -version" e.g. JRE 1.8.0_181]

**OpenRefine (please complete the following information):**
 - Version : OR 3.1

**Datasets**
If you are allowed and are OK with making your data public, it would be awesome if you can include or attach the data causing the issue or a URL pointing to where the data is.
If you are concerned about keeping your data private, ping us on our [mailing list](https://groups.google.com/forum/#!forum/openrefine)

**Additional context**

**Comment by msaby** [comment]
Addition : 
value.parseXml().select("datafield[tag=035]")[0].innerXml() is working well and gives the same result as value.parseXml().select("datafield[tag=035]")[0].innerHtml()

**Comment by ostephens** [comment]
I think this is deliberate, because the element selected in this case has no innerXml only text - so I think the right expression (as it currently works) would be:

`value.parseXml().select("datafield[tag=035] subfield[code='a']")[0].ownText()`

I think this reflects usage in other languages (e.g. see https://stackoverflow.com/questions/7877609/xmlnode-value-vs-innertext). It also means you can differentiate in situations where an XML node has both text and further child elements:
```
<?xml version="1.0" encoding="UTF-8"?>
<record>RECORD VALUE
   <datafield tag="035" ind1=" " ind2=" ">
      <subfield code="a">TEST</subfield>
   </datafield>
</record>
```
* `value.parseXml().select("record")[0].innerXml()` selects only the xml elements inside <record>
* `value.parseXml().select("record")[0].ownTextl()` selects only the string "RECORD VALUE" inside <record>

This gives finer grained control than `innerHtml` which selects both.

I can see arguments both ways for how this ought to work. I tend towards the current behaviour, although open to changing it

**Comment by msaby** [comment]
Ok. So it is more precise than innerHtml().
Could someone add an entry describing the behavior of this new function innerXml() in the wiki, I see no reference in https://github.com/OpenRefine/OpenRefine/wiki/GREL-Other-Functions  ?

**Comment by ostephens** [comment]
@msaby I've added some basic documentation on the various XML parsing functions, although I suspect it could be improved if anyone is inclined to add further information and examples.
