### ISSUE TITLE
YAML importer

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#210]
_Original author: iainsproat (November 15, 2010 10:22:51)_

It seems that Refine is being used to export YAML data, http://code.google.com/p/google-refine/wiki/ExportAsYAML , so a YAML importer seems like a good idea.

I reckon this would be fairly similar to the Json importer, so a lot of the code could be re-used there.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=210_

**Comment by wetneb** [comment]
I think the use case that prompted this issue is somewhat imaginary: iansproat only saw users exporting data to YAML, not having the need to import data in this format.

I have the impression that YAML ismostly used as a format to write configuration files or other declarative, relatively small documents. I am not saying you cannot use YAML to represent a tabular dataset, but it seems to be rare enough that it is probably not worth investing a lot of effort to support this natively in OpenRefine. So I would agree with @dfhuynh here and close this issue. An extension could implement that instead.

If anyone would need a YAML importer in OpenRefine, please do leave a comment here and it can be reconsidered. As a workaround, many YAML documents can be converted losslessly into JSON, which we do support.
