### ISSUE TITLE
Translate history in R and/or Python

### ISSUE THREAD

**Issue by msaby** [OpenRefine/OpenRefine#2118]
It would be great to have the ability to "translate" the history of a project in a R or Python script. It would improve interoperability and reproducibility of process, even if the resulting code is not optimized. I suppose it would require a huge work, to find an equivalent of each OR function in other languages. But is it theoretically realisable ?

### Describe the solution you'd like
[A clear and concise description of what you want to happen.]

### Describe alternatives you've considered
[A clear and concise description of any alternative solutions or features you've considered.]

**Comment by wetneb** [comment]
Yes it is doable, but indeed it requires quite some work especially if the feature is meant to be useful in practice, rather than a theoretical proof of concept.

**Comment by wetneb** [comment]
See more discussion in #6109: closing as duplicate.

**Comment by tfmorris** [comment]
The Stanford Data Wrangler project (which became the basis of Trifacta's Wrangler) had a Python library which implemented the various cleaning functions which could be used as a parallel back end to achieve this type of thing, but, as you surmised it can be "huge work." It's also the kind of thing that really needs to be designed in from the ground up, rather than tacked on as an after thought. A JSON Undo History to Python/R translator would probably fall short of being truly useful.

There were some related discussions in the context of exploratory.io on the mailing list back in 2017/2018:
https://groups.google.com/g/openrefine/search?q=exploratory.io
