### ISSUE TITLE
Filter bug on v.3.2

### ISSUE THREAD

**Issue by robroc** [OpenRefine/OpenRefine#2131]
**Describe the bug**
Adding a text filter on a column is including cells that don't have that string.

**To Reproduce**
1. On text column click on "Text filter"
2. Add a search string. In the case it was "19-"
3. Add a text facet or clustering to see unique values. 

**Current Results**
Things like "O", "ONE AND ONLY" and "GARDASIL" were included in results.

**Expected behavior**
Only cells with values like "19-2", "19-TWO", "POLICE ---- 19-2" to be returned

**Screenshots**
![openrefine](https://user-images.githubusercontent.com/1219001/63547898-1afaf300-c4fb-11e9-829a-42de0db31e1c.PNG)

![openrefine2](https://user-images.githubusercontent.com/1219001/63548208-c4da7f80-c4fb-11e9-9aac-12dbfeff1154.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Version: Chrome 76
 - JRE Version 1.8.0_151 

**OpenRefine version 3.2

**Datasets**
[Montreal film permits](http://donnees.ville.montreal.qc.ca/dataset/permis-et-autorisations-de-tournage/resource/a7b589d2-67bd-4892-9f4e-bcdd91e898ac)

**Comment by wetneb** [comment]
@robroc that is likely due to the fact that you are using the records mode and not the rows mode. In the records mode, only one cell within the record is required to match the filter, so if the records contains any other non-matching cells, these will also be visible in the results (and therefore included in the TITLE facet).

https://librarycarpentry.org/lc-open-refine/03-working-with-data/index.html

**Comment by robroc** [comment]
@wetneb Yes, that solved the issue. It also solved the issue of single items appearing in the clustering interface (instead of multiple items to be clustered). I don't remember seeing this in past versions, even in records mode.
