### ISSUE TITLE
Add conflict of interest policy

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2293]
Members of the steering committee are requested to take note of a conflict of interest policy when joining. We should write one, perhaps in this repository (alongside with GOVERNANCE.md)?

**Comment by thadguidry** [comment]
Types of conflicts that I can think of:

**USER level**
Our interest on the OpenRefine Project is to make OpenRefine a great data cleaning tool for **everyone** to use.  I guess a conflict would occur when someone begins to NOT align with our **everyone** inclusion, for instance, "I only work with big data, so let's not waste dollars on in-memory processing, because I have tons of servers I can use for clustering".  "Sorry, but that conflicts with our mission to include all types of users, big or small, grade school student or NASA researcher."

**IP intellectual property**
An other would be stealing the OpenRefine brand for their own business purpose. An IP conflict. Legally, this is called a violation of IP rights.

What other types of "conflicts" do others see that could potentially occur besides the above?
Maybe the Steering Committee could chime in on this one as well.

**Comment by magdmartin** [comment]
PR open here #2294

**Comment by wetneb** [comment]
No longer relevant since the steering committee is being disbanded.
