### ISSUE TITLE
Make maxlag configurable in Wikidata extension

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2304]
Maxlag is a parameter that controls how aggressive a mass-editing tool should be when uploading edits to Wikidata.

With the current issues around Wikidata's stability it is often impossible to edit with maxlag set to 5 seconds, the default value recommended by the guidelines (and the one set in OpenRefine by default).

As part of  #1640 we want to make the configuration of the Wikibase instance user-configurable (instead of being hard-coded to Wikidata) and part of that includes letting users set the maxlag value as they wish.

**Comment by james-cui** [comment]
Hey @wetneb, I want to take a look at this as the potential GSoC applicant. May I know where the variable was set to 5 sec by default?


Thanks!

**Comment by wetneb** [comment]
Sure!
Maxlag is set by default to 5 in Wikidata-Toolkit itself and can be changed here:
http://wikidata.github.io/Wikidata-Toolkit/org/wikidata/wdtk/wikibaseapi/WikibaseDataEditor.html#setMaxLag(int)

User preferences can be stored in the `PreferenceStore` (which can be accessed from the start page, in the "Preferences" section).

**Comment by james-cui** [comment]
@wetneb Here is the request to merge 
https://github.com/OpenRefine/OpenRefine/pull/2469/commits/af09b05d502157d9b4314ec71adec79e1d7e550a

**Comment by tfmorris** [comment]
> With the current issues around Wikidata's stability it is often impossible to edit with maxlag set to 5 seconds

That's the whole point, as I understand it. Allowing users to defeat this opens OpenRefine to being used as a tool for abuse.

Should this be added to the set of Wikibase configuration parameters so that a sysadmin can advertise the maximum value allowed and then users can set it to a lower, but not higher, value? That way if Wikidata advertises 5, users won't be able to change it to 10.

**Comment by wetneb** [comment]
In my opinion there is no reason for OpenRefine to forbid its users to do something that the API allows. Other bot editing frameworks (pywikibot) also let the user configure this parameter.

If Wikibase admins want to enforce a specific throttling, they can do that on their side. Editing requests made from OpenRefine are all marked with `bot=true` and tagged appropriately.

WMDE is indeed looking into changing this throttling mechanism: https://phabricator.wikimedia.org/T240442

**Comment by tfmorris** [comment]
That graph is frightening. 
![preview-maxlag](https://user-images.githubusercontent.com/82178/86519693-42a13400-be0b-11ea-8e8e-2932c0639229.png)
They really don't have a clue.

The fact that other clients enable cheating doesn't seem like a good reason to encourage our users to cheat and abuse the naïveté of the Wikidata admins when the current system depends on cooperative behavior.

This is clearly going to end up nowhere good, so we should make sure that we're ready to handle 429/Retry-After, if we don't already, so that we don't get shut out when they slam the gates.

**Comment by thadguidry** [comment]
@tfmorris Who doesn't have a clue...oh you mean users having more information provided to their clients so they can react better and slowdown?

**Comment by wetneb** [comment]
Yes it is a pretty sorry state of affairs - they are aware of the severity of the issue but it will clearly take a while before they can fix the underlying issue (scaling the SPARQL endpoint).

I agree it would be worth investing time in making sure WDTK handles 429/Retry-After correctly.
