### ISSUE TITLE
gSheet export thru « Custom tabular exporter… » doesn't work with empty values

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2306]
**Describe the bug**
I'm trying to export with « Custom tabular exporter… » and choosing « Upload to -> A new Google spreadsheet », and in some rows, if a value is missing, then the cell value disapear and the cell on the right shift left.

**To Reproduce**
1. « Custom tabular exporter… » 
2. choose « Upload to -> A new Google spreadsheet »
3. See the resulting document with mess up data.

**Current Results**
Some cell are shifted left when there is no data in the cell on the left.

**Expected behavior**
A clear and concise description of what you expected to happen or to show.

**Screenshots**
![Export-gSheet_decal_col_VueGA](https://user-images.githubusercontent.com/12217525/74112812-974ac680-4b6d-11ea-93b1-0b26463fc695.png)
![Export-gSheet_decal_col_VueOR](https://user-images.githubusercontent.com/12217525/74112813-987bf380-4b6d-11ea-86f2-f5669f7874d5.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser Version: Chrome latest
 - JRE 13.0.1

**OpenRefine (please complete the following information):**
 - Version 3.3

Relates to Google Groups « OpenRefine » discussion : [This seams to be a bug in exporting to gSheet](https://groups.google.com/forum/#!topic/openrefine/8BjfWdLwUhs)

**Comment by linderbarbara** [comment]
Hi everyone. I would like to solve this bug. Can I work on this issue?

**Comment by wetneb** [comment]
Sure! Let us know if you get stuck.

**Comment by Nishtha3512** [comment]
Hey,where i get the code related to this issue? please share link with me if any
Thanks :)

**Comment by wetneb** [comment]
Are you still working on this @linderbarbara?

The relevant code is in `extensions/gdata/src/org/openrefine/extension/gdata/SpreadsheetSerializer.java`.

**Comment by SubhamPramanik** [comment]
Hi! I would like to try this issue.
I'm getting this error during the OAuth call to Google while trying to recreate the issue.

Google
400. That’s an error.
Error: invalid_request
Missing required parameter: client_id

I've built the project locally on Eclipse. I use a Windows system.

**Comment by wetneb** [comment]
You will need to set up Google OAuth credentials as described here:
https://github.com/OpenRefine/OpenRefine/wiki/Google-Extension

**Comment by SubhamPramanik** [comment]
Created a PR. #2476

**Comment by linderbarbara** [comment]
Yes, I'm working on it. I've found a different solution, currently I'm writing the test cases related to the affected class.

**Comment by antoine2711** [comment]
> Created a PR. #2476

Hi Subham, you must be careful, as @linderbarbara has already started this case and is assigned to this issue. You are heading for a collision that will require merging. 

I understand that you are now well advance, and as such, you have something to offer, but I would strongly suggest that you choose issues that no one is assigned to.

Now, considering the current situation, you should talk with @linderbarbara as to make sure you don't do the same work twice. That being said, thank you for your help for make OpenRefine a better tool. It is much appreciated.

@Nishtha3512, I think there is already enough cook for this soup! ;-) If you want help to choose a issue, I'd be glad to help you.

Regards, Antoine

**Comment by tfmorris** [comment]
My apologies to @linderbarbara, but I don't think this is actually was a "good first issue". It looks like the code that is the focus of #2572 was introduced with 0eb7b4082f018c9bc6e22f1e6008667dcd067aef which was part of #1552 by @tcbuzor 

https://github.com/OpenRefine/OpenRefine/blob/1694400fea28ecc454c4b927c106d2cba3bf2d63/main/src/com/google/refine/exporters/CustomizableTabularExporterUtilities.java#L392-L398

That arguably should go in a SQL-specific table serializer, not the common exporter utilities, but it doesn't seem like it's likely the root cause of the problem.

A more likely avenue to explore is the massive refactoring of the GData extension in c758a6b6356e7ada6ec7531f5d184b4d32c7455f by @jackyq2015 (including removing all the copyright notices WTF?!?!). Unfortunately it's got a commit message of "exclude test-out" (???) and no related issue or documentation that I can find.
