### ISSUE TITLE
improve UX of "search for match" label display

### ISSUE THREAD

**Issue by VladimirAlexiev** [OpenRefine/OpenRefine#2334]
Neither "Исторически музей етрополе" nor "Исторически музей (Етрополе)"  finds this museum.
"Q26212305" finds it, and then it is displayed as the Q number and without a label.

Only after entering the exact WD label "Исторически музей, Етрополе" it finds the item and displays its label.

**Comment by wetneb** [comment]
Migrated to https://github.com/wetneb/openrefine-wikibase/issues/76

**Comment by thadguidry** [comment]
You have to hover on the Q label.  @wetneb had already fixed that from a previous request.
It should popout the label for you on the right side, like this:

![image](https://user-images.githubusercontent.com/986438/75353461-12e88b00-5871-11ea-9c5c-afbaf974ca49.png)

Although this seems to have a bug!  It does not always popout when hovering over the label, and took me 6 tries to show the label!

**Comment by VladimirAlexiev** [comment]
A popout over a dropdown over a modal dialog ?!?!
What UX horror is this?

Why can't you guys display the label below the Qid?
Given the migrated issue, I'll edit the title to reflect only the UI issue. Please reopen this one.

**Comment by VladimirAlexiev** [comment]
Furthermore, this popout doesn't seem to display useful info when autocompleting props:
![image](https://user-images.githubusercontent.com/536250/75438802-47d40b00-5961-11ea-82ce-dff4f1e2d342.png)

I have absolutely no clue what may P31 have to do with Friday, Shabat etc etc

**Comment by thadguidry** [comment]
Yes, I agree, let's reopen this to focus on the UX for the "search for match" feature.

@VladimirAlexiev We all agree the UX in many places needs to improve.  The team actually lost it's main frontend developer many years ago, and since then volunteers around the world have helped fix many things.  The UI technology that is used in places of OpenRefine is also not the most inviting to young new students and so it has been really hard to get volunteers to help fix many of those areas.  But we have a plan now to begin to improve different areas without completing rewriting the entire UI stack.

For now, let's also open **individual** issues for any problems that you see with our UI around any particular feature area of OpenRefine that you think needs to work better and in each issue try to describe the problem and pain it causes you and possible suggestions, or drawings on paper (or wireframe mockups if you can would be delightful!) of how you envision any area of OpenRefine working better.

**Comment by thadguidry** [comment]
@VladimirAlexiev regarding that P131 issue, I have no idea! Let's ask @wetneb !

@wetneb Do you know what might be going on here with the fbs component?

**Comment by wetneb** [comment]
This popout is called a "flyout" in Freebase's terminology. It was the way Freebase displayed descriptions (there were no descriptions in the auto-complete menu itself). Now that we have added support for descriptions, this is indeed redundant and I have been thinking of removing it from the Wikidata service.

So let's close this issue and turn it into: https://github.com/wetneb/openrefine-wikibase/issues/77
We can also decide to deprecate this feature in the reconciliation specs themselves: https://github.com/reconciliation-api/specs/issues/42

**Comment by tfmorris** [comment]
> You have to hover on the Q label.

Actually, the Q number is an ID, not a label. The reconciliation service shouldn't be returning an ID where the user expects/needs a name/label.

> Why can't you guys display the label below the Qid?

The label should be shown on the same line for the first copy of the ID is, on the left. The ID is already displayed to the right on the same line. Adding a second line needlessly doubles the amount of vertical space used.

**Comment by wetneb** [comment]
For this particular case, yes. Displaying a Qid twice is obviously not useful. The recon service should use a language fallback here.

But in general if you have namesakes, displaying the name and qid is not sufficient. In many cases, adding descriptions on a second line does help quite a lot. By the way, this was recently requested in a different context, for reconciliation candidates themselves: https://github.com/reconciliation-api/specs/issues/47

**Comment by wetneb** [comment]
By the way, the Wikidata recon service no longer returns a Qid in the label field in this case: https://wikidata.reconci.link/de/suggest/entity?prefix=Q26212305 (searching for an item which does not have a label in the target language falls back on another language)
