### ISSUE TITLE
AppVeyor configuration file still uses JDK1.8

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#2348]
AppVeyor configuration file still uses JDK1.8. Since we have recommended use of JDK8 the config must be updated too.

cc: @thadguidry @wetneb your views ?

**Comment by thadguidry** [comment]
You do know that JDK1.8 means "developer version 8", in essence an internal version number for Sun and Oracle.  And JDK8 means "product version 8"?  and since 2004 

If you were a bit older :) , some of this history would be known to you.  In version 5.0, Sun Microsystems changed the versioning system.  Read all about it: https://en.wikipedia.org/wiki/Java_version_history

But maybe your question was different or you intended to ask differently about our current AppVeyor config and how you specify the Java environment?  https://www.appveyor.com/docs/windows-images-software/#java

**Comment by kushthedude** [comment]
> You do know that JDK1.8 means "developer version 8",

I didn't know that. I am not a native JAVA developer that's why I got it wrong 😅 . Thanks for the detailed explanation 😄 .

**Comment by thadguidry** [comment]
@kushthedude You are welcome!  Anytime!  Don't be shy... "the most intelligent people in the world question everything"
