### ISSUE TITLE
inifite preparing if missing slash after Google Spreadsheet URL

### ISSUE THREAD

**Issue by afkbrb** [OpenRefine/OpenRefine#2380]
**Describe the bug**

When importing a Google spreadsheet, if we add a URL like `https://docs.google.com/spreadsheets/d/id_of_spreadsheet` (without "/" after it), then we will see an infinite "preparing" (you must login first).

![issue3-preparing](https://user-images.githubusercontent.com/29347603/76220120-e873d600-6251-11ea-936a-e4df75e0d6f0.png)

We can see the following error in the console.

![issue3-console](https://user-images.githubusercontent.com/29347603/76220335-430d3200-6252-11ea-9191-94432ddb71bd.png)

If we add "/" or "/any-path" after the URL above, it will works fine.

**To Reproduce**
1. Go to 'Create Project'
2. Click on 'Google Data'
3. Add spreadsheet URL like `https://docs.google.com/spreadsheets/d/id_of_spreadsheet`
4. Click 'Next'
5. Authorize OpenRefine with Google
6. See the error

**Expected behavior**

Even if we don''t have a "/" after URL like `https://docs.google.com/spreadsheets/d/id_of_spreadsheet`, the gdata extension should works fine. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Version: Chrome
 - JRE or JDK Version: openjdk version "1.8.0_232"

**OpenRefine (please complete the following information):**

I am using the dev version, because I have to manually add client_id / client_secret to `GoogleAPIExtension` java file and recompile it.

BTW, are there other options to add the id/secret pair?

**Datasets**

https://docs.google.com/spreadsheets/d/16L0JfpBWPfBJTqKtm-YU5-UBWLpkwXII-IRLMLnoKw0

**Comment by wetneb** [comment]
> I am using the dev version, because I have to manually add client_id / client_secret to GoogleAPIExtension java file and recompile it.
> 
> BTW, are there other options to add the id/secret pair?

Yes it would be more convenient to make this more easily configurable.

**Comment by afkbrb** [comment]
Is it possible to add the configuration into `refine.ini`?

**Comment by afkbrb** [comment]
> Is it possible to add the configuration into refine.ini?

Yes, we can! I've made it. Now I can put the client_id/client_secret in `refine.ini` for OAuth with Google!

@wetneb Should I open a new issue (feature) to introduce this new configuration?

**Comment by ostephens** [comment]
@afkbrb @wetneb if the client_id/client_secret are meant to be set by the user, I think they should be in a user configurable setting which can be edited in the Preferences (like refine.data_dir, ui.browsing.listFacet.limit etc.). If you are going to create a new issue around this I'd suggest including this as a requirement

**Comment by wetneb** [comment]
It's a bit complicated. At the moment, I introduce validated OAuth credentials in released versions. We don't want to expose these to users, since they should stay secret for as long as possible.
At the same time, it does make sense to make it easier for developers to set up their own credentials easily, without having to touch the source code. So I would say these settings should not go to the Preferences, since they are not meant to be changed by end users.

To be fully compliant with the TOS, we should in principle require all users to go through the process of getting OAuth credentials themselves - but given that this is a lengthy process, I don't think this is really helping users. But I am not opposed to that - I pointed out this exact problem when the Google extension was first revamped a few years ago. It's just how OAuth works, we cannot do much about it.

**Comment by ostephens** [comment]
Hmm - that seems problematic :(

To answer @afkbrb - that definitely feels like it deserves a separate issue for discussion :)

**Comment by afkbrb** [comment]
@wetneb @ostephens Thanks for you suggestions.

Didn't expect that this is so complicated. I'll open a seperate issue for it later.
