### ISSUE TITLE
datePart(value, "weeks"/"week"/"w") apparently returning week of month

### ISSUE THREAD

**Issue by japerron** [OpenRefine/OpenRefine#2406]
but it is documented to return week of the year as per https://github.com/OpenRefine/OpenRefine/wiki/GREL-Date-Functions

**Comment by thadguidry** [comment]
I'll update and fix our reference on the wiki.

Yes, it has historically returned week of month starting on a Sunday with minimum of 1 day for the week defined.  See https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/expr/functions/date/DatePart.java#L100

In this issue however, are you asking to have an additional function for week of year?  Would that be useful to you?

**Comment by thadguidry** [comment]
AH!  Capital `W` is not recognized!  That's a bug.
The syntax that we have has historically followed the SimpleDateFormat abbreviations.
But looks like we failed to have better testing for some of these.

**Comment by ostephens** [comment]
Is that a bug or a documentation error? Changing the code will mean any existing use of this function would be broken and lead to different results for re-running old edit histories

**Comment by thadguidry** [comment]
@ostephens Its both.
lowercase `w` should be week in year.
uppercase `W` should be week in month.

I understand changing this would lead to broken histories, but this is something we should have caught long ago and fixed.
I would hate to have it vice versa, since so many other programs are written and use this same convention, like https://momentjs.com/docs/#/parsing/string-format/

**Comment by ostephens** [comment]
My feeling is we need versioning on histories so we can ensure that older histories are not just run on 3.4+ without some warning to the user that this may not result in the same results as running on previous versions of OR

**Comment by thadguidry** [comment]
@ostephens yeah, that would help.  And further would could actually do some conversion of them to make them forward compatible, as I mentioned before.  An OpenRefine upgrade tool (Python, Javascript, whatever) that can be run and doesn't have to be fancy or we can make it fancy.  Our upgrade steps have alway been fairly rudimentary and not the easiest for our users.  We should put more work into making that easier for them.

**Comment by wetneb** [comment]
Until we have that, I'd be in favour of preserving the behaviour of the current values (it's fine to add support for other values though).

**Comment by ettorerizza** [comment]
[Related question on SO](https://stackoverflow.com/questions/62036538/extracting-week-in-the-year-with-openrefine)

**Comment by ettorerizza** [comment]
Wow, looks like a lot of SimpleDateFormat patterns do not work (L, M, W, G, F, y, Y...)

**Comment by ettorerizza** [comment]
Okaayy... It seems the issue comes from datePart(), since a construction like this (undocumented) works:

`"2020/05/11".toDate('y/m/d').toString('W')`

while this not:

`"2020/05/11".toDate('y/m/d').toString('W')`

--> Error: Date unit 'W' not recognized.

But in both cases, the pattern 'w' is not "week in year" as it should be.

(OR 3.3, Windows 10)

**Comment by arky** [comment]
Thanks @ettorerizza for doing the leg work to trace this problem. Kudos!

**Comment by thadguidry** [comment]
@ettorerizza datePart() uses it's own patterns for common usage (which is now based on java.time). They are mapped [in our code here](https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/expr/functions/date/DatePart.java#L114)) and documented here: https://github.com/OpenRefine/OpenRefine/wiki/GREL-Date-Functions#datepartdate-d-string-unit

Whenever there was a need for some datePart to extract, we would add to that... like when I added **milliseconds** a few years back in this commit https://github.com/OpenRefine/OpenRefine/commit/f2c4e3ab486207412ff9ac8678f0237e3828d2ca

**Comment by ettorerizza** [comment]
@thadguidry yep, but in this case I don't quite understand the usefulness of the datePart() function, since the undocumented trick @arky found makes it possible to use the whole range of SimpledateFormat patterns.

Example with G (era designator), which is not implemented in datePart():

![screenshot-localhost_3333-2020 05 27-13_59_20](https://user-images.githubusercontent.com/6286410/83016817-dcaed900-a022-11ea-9ed2-a2259eda79ce.png)

**Comment by thadguidry** [comment]
`toString()` will always output A STRING when supplying it with a Date object.

`datePart()` MIGHT output A STRING or it might output A NUMBER depending on which Date Part Unit you ask for... see the Returned data type column: https://github.com/OpenRefine/OpenRefine/wiki/GREL-Date-Functions#datepartdate-d-string-unit

**Comment by tfmorris** [comment]
All this discussion and no one fixed the bug? I've corrected the documentation so that it matches the code (and also fixed the examples which were returning two different values for different abbreviations of `weeks`).

@japerron Thanks for the bug report.

@ostephens versioning the operation history is a good idea. Please create a ticket for it if you haven't already done so.

@ettorerizza I would hardly characterize a simple documentation error as a "serious bug" as you did on StackOverflow.

**Comment by thadguidry** [comment]
@tfmorris To @ettorerizza and other's defense... that was the context here... to have just 1 of our senior developers jump in and characterize this as a bug or doc improvement.  Glad you or Antonin finally jumped in, made a decision, and closed it.  We can now rest peacefully.

**Comment by tfmorris** [comment]
@thadguidry I'm comfortable with you (or anyone else) making that call based on your research of the git history. If the code's been like that for 10 years, it's the documentation that's wrong, not the code. @wetneb already made the call that we're not going to make an incompatible change to `datePart()`, which I agree with, so we don't have a good way to extend it to do `week of the year` due to our initial choice. That's unfortunate, but not the end of the world. We can have a separate discussion about how to introduce that functionality, if it's needed.

**Comment by lonniev** [comment]
GREL could offer an alternative method like `simpleDatePart` which would extract variant-type property values from its GREL date/time object - using the format selectors of `SimpleDateFormat` [doc9](https://docs.oracle.com/javase/9/docs/api/java/text/SimpleDateFormat.html).

That would allow its users of the legacy `datePart` method to continue to use that method and continue to get the results they have come to expect and rely upon while allowing new users or themselves to have access to a convenience method to get the parts of dates that correspond to the `SimpleDateFormat` conventions.

Offer A _and_ B not A _or_ B.

**Comment by tfmorris** [comment]
Yup, that's what I meant by:

> We can have a separate discussion about how to introduce that functionality, if it's needed.

@lonniev Feel free to create an issue with a proposal if you feel it's important (although there are a bunch of problems with the date support that may cause it to get significantly reworked).

**Comment by lonniev** [comment]
Thank you for the offer to get really engaged but, for now, I have no pain
here.




On August 8, 2020 at 3:18:34 PM, Tom Morris (notifications@github.com)
wrote:

Yup, that's what I meant by:

We can have a separate discussion about how to introduce that
functionality, if it's needed.

@lonniev <https://github.com/lonniev> Feel free to create an issue with a
proposal if you feel it's important (although there are a bunch of problems
with the date support that may cause it to get significantly reworked).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OpenRefine/OpenRefine/issues/2406#issuecomment-670964186>,
or unsubscribe
