### ISSUE TITLE
Improve dependency management for the frontend

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2423]
**Problem**

We currently ship frontend javascript libraries in the repository itself. These libraries have not been updated for a while and they sometimes get patched in various ways. It would be cleaner to use a proper dependency management system for this, just like we have moved from Ant to Maven for the backend.

**Possibilities**

* npm is the standard javascript package manager. We could try to use this. This would mean that dependencies are configured in a `package.json` and are pulled in at compile time using npm. The PR #2418 demonstrates some of that. This means that in addition to requiring Maven for build, we would also need npm. We should look into downloading npm on the fly in the `refine(.bat)` wrappers, which currently do this for Maven itself.
* webjars offer a way to use Maven's existing dependency management system to fetch Javascript libraries. This would let us use a single dependency management system, but the selection and freshness of packages is a bit more restricted.
* anything else?

**Comment by thadguidry** [comment]
What is the scope here?
1. Users of OpenRefine
2. Developers of OpenRefine

**Comment by wetneb** [comment]
I am not sure what you mean?

**Comment by thadguidry** [comment]
Else's:
https://nodejs.org/en/download/package-manager  <-- Windows users rarely use Chocolatey, only corp's use it for automation.
https://github.com/nodejs/help/wiki/Installation  <-- Installing Node.js via binary archive

However's:
npm strongly suggests to [use a Node version manager rather than a Node installer](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm#using-a-node-version-manager-to-install-node-js-and-npm)
I personally like and use [nvm](https://github.com/coreybutler/nvm-windows) on Windows.

**Comment by thadguidry** [comment]
I mean "dependency"... for what?  Running OpenRefine or Building OpenRefine?  Your Problem statement doesn't really state a problem well enough...it assumes the reader of this issue knows.

Problem:
OpenRefine frontend development and testing is currently cumbersome and brittle with keeping up with Javascript library versions.

"I think" what you were trying to explain is that:
1. We would like to make testing OpenRefine easier for frontend development and ensure that it can be more easily tested with different versions of npm.
2. We would like to remove some Javascript dependencies from being stored in our repository?
3. We would like to use a package manager for Javascript for managing dependencies better for frontend development.
4. npm recognizes this and strongly suggests the use of a `Node version manager` instead of a `Node installer` when configuring for a development environment, rather than a regular user environment.

**Comment by fpompermaier** [comment]
Tell me if I am wrong but using npm affects only the developers part, not the user's one..am I wrong?
I am absolutely in favour of moving towards an npm-based UI but this probably would invalidate almost all current PRs..in this case I'll add the npm support in the next version, being aware that this would require an extra effort in order to try to close all affected PRs. Obviously @kushthedude should take care of carefully document the new build system and help in this transition..

**Comment by elebitzero** [comment]
I'm looking into this issue to see if we can put all the external dependencies into main/webapp/package.json.

These are the steps:
- PR1: Create a package.json with all the packages and current versions.
  - If a package is available in the npm registry, add it to package.json. Compare the files to the "externals" files to confirm it is the same version.
  - If the package is not in npm or the exact version is not available, leave it out for now.
 
- PR2: For packages where the exact version was not available, check to see if a higher version can be used. Then update the copy in externals and run manual and automated tests to make sure it is ok. Issue a PR for each library.

- PR3: Update the refine build scripts to run 'npm install' and update the build to include the 3rd party files into the OpenRefine installer.

- PR4 Modify the code to point to the node_modules/package/\*.js files rather than the externals/\*.js files.  Note: packages that were not available from npm would be left in externals.

**Comment by elebitzero** [comment]
I've looked at the UI dependencies under "externals", and found the following.

These packages are available on npm registry:

- jquery (1.12.4) - ✓
- jquery-ui (1.12.1) - ✓
- jquery-migrate (1.4.1) - ✓
- tablesorter (2.29.0) - ✓
- moment (2.19.2) - ✓
- underscore (1.5.1) - ✓
- js-cookie (2.2.1) - ✓
- select2 - (3.5.2) - ✓
- datejs-coolite (1.0 Alpha-1) - ✓

These packages might have to be left in externals:

- imgareaselect  - can't find 0.9.2 version in npm, found 0.9.11-rc.1 on GitHub (https://github.com/odyniec/imgareaselect)
- jquery.i18n (1.0.7) - not available in npm (Issue: https://github.com/wikimedia/jquery.i18n/issues/159)
- suggest (4.3a) - not available in npm, contains fixes from Google Code SVN

**Comment by wetneb** [comment]
Hi @elebitzero, thank you so much for having a look at this! As you found out this is indeed a significant piece of work. Your plan looks very good to me.

I would just make sure that the current file structure of the packaged software remains the same, so that we do not break compatibility with extensions for instance. So that would require copying dependencies at compile time into the corresponding folders (just like we do with Maven). Not having much experience with npm I do not know if that is easy to do.
If we stick to the current file structure for compiled modules, then extensions will still work as expected and they should be able to introduce a package management system for themselves in the same way (but do not have to).

I am super grateful you are thinking about this task and I think this means a lot in terms of your involvement in the project, so I would be interested to understand better what brings you to OpenRefine, what your plans are and so on. Happy to discuss that by email (for instance on the [openrefine-dev](https://groups.google.com/g/openrefine-dev) mailing list or privately, my email is first_name@last_name.eu). In general, if there is anything I can do to facilitate your onboarding, let me know :)

**Comment by elebitzero** [comment]
> I would just make sure that the current file structure of the packaged software remains the same, so that we do not break compatibility with extensions for instance.

Yes, I want to keep the file structure the same.  I don't think it should affect extensions at all.  But is there an example extension I can use to test? All of the ones I see just seem to have Java code in them.

I'm looking at how the UI files are packaged now, mainly the "externals" directory.  We need to include some of the files under node_modules so they can be loaded by the webapp.

> I would be interested to understand better what brings you to OpenRefine

I used OpenRefine to clean up some data for a project and noticed the UI needed some improvement.  It would be nice to be able to rewrite it in Angular or React, but that would be too tall a task.

**Comment by wetneb** [comment]
> We need to include some of the files under node_modules so they can be loaded by the webapp.

That is exactly what I was getting at: I wonder if it would instead be possible to copy files over from `node_modules` to `externals` as part of the build process.

On the Java side, this is what happens when you build OpenRefine for the first time:
* Maven downloads dependencies from the Maven Central repository into you local maven cache (typically located at `~/.m2` on Unix systems)
* We compile the Java source files of OpenRefine into `.class` files that land in the appropriate directory in the app
* We copy Java libraries (packaged as `.jar`) from the local repository (`~/.m2`) into the appropriate directory in the app

I am thinking it would be nice to follow a similar pattern on the UI side: let the package manager install the libraries where it sees fit, and then copy those over to the expected directory for the built app.

> I used OpenRefine to clean up some data for a project and noticed the UI needed some improvement. It would be nice to be able to rewrite it in Angular or React, but that would be too tall a task.

Thanks! There is definitely some interest in rewriting at least parts of the UI into a reactive framework, it is something people have been talking about for a while. I am especially interested in understanding how we could keep the UI extensible with this paradigm. If you have good examples of projects that got this right, I am all ears :)

**Comment by wetneb** [comment]
Closed by #4621, thank you again @elebitzero!
