### ISSUE TITLE
Data Type setted not remembered by application

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#2424]
**Describe the bug**

Change the data type of any cell, and see again the type of data is not remembered by the application.

**To Reproduce**

1. Go to 'Edit Cell'
2. Click on 'Boolean Datatype'
3. Set the data to `True/False`.
4. Again click on edit cell and see data type as text rather than boolean.

**Expected behavior**

Data-Type preference should be remembered

**Screenshots**

<img width="446" alt="Screenshot 2020-03-17 at 4 03 45 PM" src="https://user-images.githubusercontent.com/44091822/76847968-e967c180-6868-11ea-8d00-d29c2af5c002.png">

**Comment by kushthedude** [comment]
cc: @thadguidry @wetneb

**Comment by wetneb** [comment]
The data type in the edit dialog should indeed be set to the current datatype for that cell.
There is no need to use the preferences for this - the initial datatype in the dialog should only be determined by the current datatype for that cell, I think.

**Comment by thadguidry** [comment]
I understood what he meant.  Which was a "user preference".

@kushthedude our issues label "preferences" is to be used only for issues that involve using our global `preferences` structure which is currently using a Velocity template `preferences.vt`.  It is not for representing `static variables`.

@wetneb We should probably relabel that label to "global preferences" because that is what is really represents for OpenRefine project to avoid confusing new developers of OpenRefine on issues.
