### ISSUE TITLE
CI builds fail in forked repos

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#2537]
**Describe the bug**

In forked repos without the RELEASE_REPO_TOKEN secret defined, CI builds fail attempting to upload release artifacts.

**To Reproduce**
You can see a failed build here: https://github.com/tfmorris/OpenRefine/runs/579874494?check_suite_focus=true

**Current Results**
Fails with the error `##[error]request to https://api.github.comnull/ failed, reason: getaddrinfo ENOTFOUND api.github.comnull` during the Upload Release Asset Windows setp.

**Expected behavior**
It should gracefully skip the upload step and not fail the build.

p.s. As an aside, it appears that the "nightly" build is actually built and uploaded for every commit, which seems wasteful.

**Comment by wetneb** [comment]
I am not opposed to running the packaging daily instead of on every push, if GitHub Actions can be configured in this way. Perhaps it would be nice not to run the build if no push was made in the last 24h, in that case.

One thing I like about doing it after every push is that it lets us send a packaged version to the user who reported the bug whose fix was just merged. This is the main use for these builds, I would say. There are loads of people who are able to report bugs on mailing lists or GitHub, but do not have Maven or Git installed on their machine and are daunted by the process of building from source. If we have to wait for 24h before sending them that notification (instead of just a few minutes), it makes the maintaining process a bit harder.

**Comment by thadguidry** [comment]
@tfmorris what is it specifically that is "wasted" ?
