### ISSUE TITLE
Add Wikidata label or description from reconciled values

### ISSUE THREAD

**Issue by VojtechDostal** [OpenRefine/OpenRefine#2613]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**

Extending my data by loading statement values from reconciled items is very cool. I wish I could also "Add label/description" from reconciled values.

**Describe the solution you'd like**

Just a simple language selection + choosing if I want label/description/(alias) from Wikidata

**Additional context**

This feature would be great for certain kinds of data analysis but also certain workflows of reconciliation and preparation of some of my data for import into Wikidata.

**Comment by wetneb** [comment]
You can already do this by typing "Len" (for English label), "Dde" (for German description) or "Afi" (Finnish alias) in the property input in the data extension dialog. But it is true that this could be better documented.

**Comment by VojtechDostal** [comment]
Thanks. Just noticed that it's there in the documentation (https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation#labels-descriptions-aliases-and-sitelinks) but in the Wikidata-specific section which I missed when reading it.

**Comment by thadguidry** [comment]
@VojtechDostal I missed it also, then thought of why I missed reading it...and then realized we could probably add Table of Contents (TOC) at the top of the current wiki document... so I added that TOC last week.  Perhaps that's how you quickly spotted we have that new Wikidata section, and if so, glad its more readable now.

Anyways, regarding Docs improvements:  I think a lot of our Docs could use more TOC's (and less in some places and just split whole sections into entirely new pages) and with our new Documentation improvement plans that will happen automatically in Docusaurus since it's the default way to navigate it's allowed on the right side navigation: https://docusaurus.io/docs/en/site-config#onpagenav-string 

as well as having the ability of the Side Navigation (Collapsible) : https://docusaurus.io/docs/en/site-config#docssidenavcollapsible-boolean

We'll have to see what works best, but I think having both Navs (main on left side, secondary on right side for TOCs) available for users of our Docs will be useful.

Example of TOC on right side with main on left: https://docs.openrefine.org/operations/key_value_columnize.html

**Comment by VojtechDostal** [comment]
Thank you for that. I think we can safely close this issue now, but if you feel like there is still something actionable, reopen it please. Cheers,
