### ISSUE TITLE
Extending the "fluent interface" (or Dot Syntax) for controls

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2618]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
Currently, a function can be called by its normal syntax, like `datePart(now(), "year")` but it can also be called by its _Dot Syntax_, that is: `now().datePart("year")`.

On the other hand, `if(vMaybeTrue, eTrue, eFalse)` cannot be called `vMaybeTrue.if(eTrue, eFalse)`, because controls do not have the _Dot Syntax_.

It would enable a writing that could provide sometimes better readability.

It will also ease the process of transforming a function into a control if needed for some reasons.

**Describe the solution you'd like**
I'd like to be able to write in GREL: 
- `[0, 20, 2].forRange(vVar, eExpr)`
- `["string", "boolean", "number"].forEach(eExpr)`
- `vMaybeTrue.if(eTrue, eFalse)`
- `["a", 1, errorObject].filter(vVar, eExpr)`
- etc.

**Describe alternatives you've considered**
Not using the Dot Syntax.

**Comment by tfmorris** [comment]
A better name than "dot syntax" might be "fluent interface" since that's what the rest of the software engineering world [calls it](https://en.wikipedia.org/wiki/Fluent_interface).

From an implementation point of view for OpenRefine, a Control is fundamentally different from a Function. The differences are described in the documentation for the interfaces:

https://github.com/OpenRefine/OpenRefine/blob/d7d567439eb39957e149e1b67576fe67c7836a10/main/src/com/google/refine/grel/Control.java#L43-L48

https://github.com/OpenRefine/OpenRefine/blob/d7d567439eb39957e149e1b67576fe67c7836a10/main/src/com/google/refine/grel/Function.java#L43-L46

This is such a fundamental difference that there'd need to be a significant benefit to even consider pursuing the investigation as to whether or not it'd be possible to unify the two. I'm not seeing it for a little syntactic convenience.

**Comment by antoine2711** [comment]
> A better name than "dot syntax" might be "fluent interface" since that's what the rest of the software engineering world [calls it](https://en.wikipedia.org/wiki/Fluent_interface).
> 
> From an implementation point of view for OpenRefine, a Control is fundamentally different from a Function.
> 
> This is such a fundamental difference that there'd need to be a significant benefit to even consider pursuing the investigation as to whether or not it'd be possible to unify the two. I'm not seeing it for a little syntactic convenience.

Yes, I agree with you, changing function and/or control is opening a pandora box. Correct me if I'm wrong, but I understood that the « fluent interface » for functions is implemented by: HasField, HasFields, HasFieldsList and HasFieldsListImpl classes. I would rather try to stay at this higher level.

In any case, this issue is a mid-to-long term issue. I would think like you that it will involve quite some time to get to the bottom of it.

Regards,
   Antoine

**Comment by tfmorris** [comment]
Sounds like we're in agreement that this is too fundamental a change to pursue.
