### ISSUE TITLE
Feature to Goto a page directly

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#2638]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**
We can go to the first, the last, a next or previous page, but we can't jump to any page.

A simple link, with a prompt, telling you your current page, the max # of pages, and asking to what page you want to go would be a nice feature.
 
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/12217525/82745451-79872300-9d52-11ea-90dc-5c88fc17eb06.png)

**Describe alternatives you've considered**
Clicking many times the next button. I works.

**Comment by antoine2711** [comment]
Relates to #571

**Comment by antoine2711** [comment]
@wetneb & @thadguidry: this is the last feature I see that would be simple, not prone to breaking, and very useful for our user.

I coded it, it works well. I didn't do validation yet (range & number), but for the rest, you can try it.

Regards,
   Antoine

**Comment by antoine2711** [comment]
A background color could also be added to clarify a bit the interface and it's choices:
![image](https://user-images.githubusercontent.com/12217525/82746077-dcc88380-9d59-11ea-9110-245898d4f17d.png)

Regards, A.

**Comment by thadguidry** [comment]
@antoine2711 Appreciate you working on this! 
I think the popup display approach for our users is overly complex and I think we can make this easier and similar to other grids.  The numbers themselves currently display the Row range.  That's fine, but what we really want to improve and begin to integrate like other grids is the notion of Pages of Rows.

Therefore I think we should do a number of things here:
1. Keep the Row range (Rows per page) display (folks are used to that)
2. Show a new Page range display
3. Allow direct entry of the current page to view on the Page range display, rather than a popup

Look at this beautiful Example Demo that allows all 3 of those needs we have, but using simple control & display of them (Try it out!):
https://xaksis.github.io/vue-good-table/guide/configuration/pagination-options.html#mode

![image](https://user-images.githubusercontent.com/986438/82755281-38196680-9d98-11ea-954a-e4cb417d9f60.png)

I know you can make this look and work amazing if you iterate on this over a few days.  Looking forward to testing that out!

**Comment by antoine2711** [comment]
> I know you can make this look and work amazing if you iterate on this over a few days. Looking forward to testing that out!

Thanks for the carrying compliment! ;-)

> Therefore I think we should do a number of things here:
> 
> 1. Keep the Row range (Rows per page) display (folks are used to that)
> 2. Show a new Page range display
> 3. Allow direct entry of the current page to view on the Page range display, rather than a popup

So @thadguidry, do I go 
- « First
- < Previous
- Page [1] of 3
_or_
- Page [1] of 3 (Rows 1 to 10)
_and_
- Next >
- Last »

Regards,
   Antoine

**Comment by thadguidry** [comment]
* Page [1] of 3

Reasoning is that showing `1-10` or `1-50` etc. is redundant.
Folks already know the Rows per page via the existing selector:

![image](https://user-images.githubusercontent.com/986438/82761263-0bc51080-9dbf-11ea-8a30-95a9092eb416.png)

**Comment by thadguidry** [comment]
Is it easy enough to calculate the max pages however?  Do we already have integer value stored somewhere in our current architecture?  Or do you have to add functionality to calc that?  Is Java or JS the best place to calc that?  What does the future look like for calculating that with @lisa761 's upcoming work?

**Comment by antoine2711** [comment]
> Is it easy enough to calculate the max pages however?

It’s coded in the PR, I would say very easy since it’s done! ;-)

> How well would the update perform for the max pages count whenever users click and change the value Rows per page to `Show:` ?
> 
> Do we already have the max pages integer value stored somewhere in our current architecture?
> 
> Or do you have to add functionality to calc that?

In JS. It was semi-coded for the Goto LastPage.

> What does the future look like for calculating that with @lisa761 's upcoming work?

No use with infinite scrolling, and we would keep it as long as we keep Paging functionality.

Regards,
   Antoine

**Comment by antoine2711** [comment]
@thadguidry: you can try it, It's now coded with an <input> tag instead of the prompt. Much harder to code, less robust, but better user interface I would say.

Tell me if you like it.

Regards,
   Antoine

**Comment by antoine2711** [comment]
And I also did this little change… subtle, but stil, effective I would say.

![image](https://user-images.githubusercontent.com/12217525/82798269-47ef8400-9e46-11ea-9faa-795a4a68be14.png)

Regards, A.

**Comment by thadguidry** [comment]
On you last screenshot, I think we could reduce the padding around `rows` and `records`.  Unless that also increases the clickable area for them to make clicking on each easier, then I'd keep it as is.

**Comment by antoine2711** [comment]
@thadguidry: @wetneb made me change the weak mechanism, and now, it works flawlessly on FF as on Chrome! I just committed the code.

Try that when you're available.

Regards,
   Antoine
