### ISSUE TITLE
Stop testing for Oracle JDK in CI

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2861]
The differences between Oracle JDK and OpenJDK are minor starting from version 11. It is probably wasteful to be running both of them in Travis.

More background on the differences: https://www.baeldung.com/oracle-jdk-vs-openjdk

Over the past few years I do not recall encountering any bug in OpenRefine which would only be present with one of OracleJDK and OpenJDK. Running many builds at the same time increases the chances that we run into spurious build failures and can increase the build time if the builds are not run concurrently. So I propose we remove oraclejdk11 from Travis.

**Comment by tfmorris** [comment]
I agree it doesn't make sense to test multiple JDK 11s. We currently test oraclejdk11 and openjdk 8, 11, and 12. According to that article the Oracle JDK LTS releases are 8 and 11 and the openjdk policy is to drop support of the previous release when a new release comes out. Oracle JDK 8 LTS support officially ended in January, but commercial customers can buy support through at least December 2012.

Based on that, it seems like a better mix might be:
- oraclejdk8 (presuming that we can get it on Travis CI)
- openjdk 11
- openjdk 12

Certainly there doesn't seem to be any value in testing openjdk8 since it's many versions out of support -- and even the oraclejdk8 is on its last legs.

**Comment by wetneb** [comment]
I think setting up oraclejdk8 is harder than openjdk8 - but I would be happy to have the list you propose in principle.

**Comment by tfmorris** [comment]
I was able to find an oraclejd8 on trusty and got rid of the duplicate JDK 11 build, but then I realized that we didn't have JDK 13 or 14 and also didn't have an OS X build, so I ended up adding more builds than I removed. I think it'd be worth adding Early Access Program (ie JDK 16) builds, but jacoco doesn't support it.

You can see an example run here: https://travis-ci.org/github/OpenRefine/OpenRefine/builds/704530492

It currently has 6 jobs, which are, in order:
- openjdk14, bionic
- oraclejdk11, bionic
- bundled java, os x
- oraclejdk 8, trusty
- openjdk 13, bionic
- openjdk 12, xenial

If we can pare it to 5 jobs that will shave a couple of minutes off the build (6.5 min vs 9 min). Dropping the OS X build would get it under 5 minutes.

Having set all this up though, I'm wondering how necessary it is, particularly if we bundle a JRE on all platforms. Perhaps all we need is the Java version that we build our distributions on and future versions (so that we can spot coming compatibility issues).

**Comment by tfmorris** [comment]
Trimmed one more job to get it to 5 jobs which finish in 6-7 minutes with the first job finishing in 3-4 minutes.

**Comment by tfmorris** [comment]
I don't want to lose track of this question:

> Having set all this up though, I'm wondering how necessary it is, particularly if we bundle a JRE on all platforms. Perhaps all we need is the Java version that we build our distributions on and future versions (so that we can spot coming compatibility issues).

@wetneb What are your thoughts? Do we have any Linux distros building their own bundles which need support for older JREs? Is there any other reason to continue testing them or should we focus primarily on current and future JDKs?

**Comment by tfmorris** [comment]
Well, that doesn't seem to have improved things. The Mac failure can probably be fixed with a delay to wait for the database services to start up, but I'm not sure what to do about the Java installation failures. I wonder if using the bundled JDK for any given distro would help? I'll do some more investigation...

**Comment by wetneb** [comment]
I am sadly not aware of any linux distros packaging OR (and I feel bad about not having done that yet!). I think it makes sense to keep supporting relatively old JREs as long as this does not impede our work. So far, supporting Java 8 has never been a blocker for me, and there might be people out there who are stuck with it, so I would intuitively keep it in the CI by default.

I am really not an expert on these topics but perhaps we could just test with LTS versions, so Java 8 and 11? At the moment our main need is to reduce spurious build failures IMHO, I would reduce the number of combinations overall.

**Comment by tfmorris** [comment]
I've pushed a couple of tweaks. Let's see how they do on my PR CI builds.
- Added a sleep for Mac database startup
- Tried to use default JDKs for the build platforms
- Made some of the problematic builds optional

This will focus on three: Oracle JDK 8 on trusty, OpenJDK 11 on Bionic, Oracle JDK 14 on Mac

**Comment by wetneb** [comment]
Thanks a lot Tom!

**Comment by thadguidry** [comment]
@tfmorris I wonder if it might be worth moving all of CI/CD to Github Actions (Azure) instead of Travis which seems flaky at times?
