### ISSUE TITLE
Spurious test failures in ColumnAdditionByFetchingURLsOperationTests

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#2875]
**Describe the bug**
Sometimes the following test fails:
```
[ERROR] Tests run: 704, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 75.502 s <<< FAILURE! - in TestSuite
[ERROR] testHttpHeaders(com.google.refine.operations.column.ColumnAdditionByFetchingURLsOperationTests)  Time elapsed: 1.751 s  <<< FAILURE!
java.lang.AssertionError: expected [false] but found [true]
	at com.google.refine.operations.column.ColumnAdditionByFetchingURLsOperationTests.runAndWait(ColumnAdditionByFetchingURLsOperationTests.java:133)
	at com.google.refine.operations.column.ColumnAdditionByFetchingURLsOperationTests.testHttpHeaders(ColumnAdditionByFetchingURLsOperationTests.java:266)

```

**To Reproduce**
Run the tests many times? I find it curious that it does not happen on Travis more often, perhaps my machine is just slow.

**Desktop:**
 - OS: Linux
 - JRE or JDK Version: OpenJDK 11

**OpenRefine :**
 - master branch

**Comment by tfmorris** [comment]
I think I've seen it at least once on Travis. The current timeout is only 1 sec since I assumed that the MockWebServer would be very fast, but perhaps that's too aggressive.

Now that I've fixed the tests to check periodically (every 200msec) in a loop, rather than waiting the full timeout period, there's really no issue in increasing the timeout to 2, 3, or even 5 seconds. If it finishes in 1.2 sec, it won't slow down the tests excessively.
