### ISSUE TITLE
Simplify the Services dialog for reconciliation

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#2916]
The current slide handling for Services dialog for reconciliation is not ideal.
As mentioned in #1658 , this could probably be improved.

Currently the slider icon looks like an old product price tag to me, so not the best choice for a slider icon.  It should be an close X icon and also we should simplify the handling by introducing a visibility toggle icon as well or another button (to do the visibility toggle) called "Services..." next to the existing button "Add Standard Service...".  Instead of keeping the slide effect that retains the price tag icon and sliver of the Services panel shown on the left edge.

Something like this behavior: https://material.io/components/sheets-side#standard-side-sheet

_Originally posted by @thadguidry in https://github.com/OpenRefine/OpenRefine/issues/1658#issuecomment-656778345_

**Comment by Abbe98** [comment]
I wonder if we could get rid of the sidebar entirely? It's not really a pattern used elsewhere in OpenRefine. Is there a need to being able to switch endpoint after ones initial selection?

Maybe we could instead use something like the "separate-model" pattern used by the Wikibase extension to switch instances? It differs given that the extension has a clear default but we could maybe display the selection list prior to the reconciliation interface.

**Comment by Abbe98** [comment]
@wetneb awesome. That was also the pattern I was thinking of.

**Comment by wetneb** [comment]
So here is a rough proposal for the first dialog of the wizard workflow proposed above:

![image](https://github.com/OpenRefine/OpenRefine/assets/309908/d2eb63eb-793a-4b72-a1f8-e240a4a41733)

And the second dialog could look like this:

![image](https://github.com/OpenRefine/OpenRefine/assets/309908/70768c46-28c0-45ba-838c-ed430467dc01)

Note that in the second dialog there isn't any "price tag" in the top left corner anymore, and there aren't any buttons to add reconciliation services in the bottom left corner.

Let's refine this design here. @ayushrai206 I think I think you can start implementing this while we get the details right (things like button placement can be adapted later)

**Comment by Abbe98** [comment]
The above looks like an excellent start!

**Comment by ayushrai206** [comment]
Hello everyone, 
I just made a pull request regarding the issue, please check it out and give feedbacks. I also needed suggestions on what  happens if the user does not select any service and still clicks the next button, should we still move the next dialog that displays nothing except the back buttons etc. or should we display a message that 'select service first' which seems more intuitive to me.
I also just realised that I need to tackle the overflow of services in the service list in the first dialog, which I would do in the future commits.
Thank you and regards,
Ayushi

**Comment by Lydiaofficial** [comment]
Hi @ayushiand evryone, here is my proposed design changes for the service dialog and it does amswer your question about the next button when service hasn't been selected.

![image](https://github.com/OpenRefine/OpenRefine/assets/17748526/b9593f9b-2214-4b0b-a1d4-bd6c04998cba)
Here we get rid of the sidebar and the price icon because it serves little to no purpose as this first step is for users to select a service and collapsing or expanding of the sidebar does nothing for the jser, not to mention that the price icon is really out of place. So I got rid of the sidebar and displayed the services and their corresponding url in full view.

On buttons, like you I also replaced the "Start reconciling.." button with the default "**Next >>**" button on OpenRefine but until a service is selected, the button remains disabled and only enables on the selection of a service as seen here:
![image](https://github.com/OpenRefine/OpenRefine/assets/17748526/a0ba7f00-ad67-45a2-949b-1fad51fdc367)

I also replaced the grey hover effect with the Chrome primary variable as it's obtainable in the "manage extensions" selector of OpenRefine. 
![image](https://github.com/OpenRefine/OpenRefine/assets/17748526/99cd7f34-0bfd-4c7e-bf92-ead4b31d5bdb)

Since users cannot start reconciling without selecting a service,  I added a prompt for everytime they hover or take their cursor to the next button without selecting a service first. :
![image](https://github.com/OpenRefine/OpenRefine/assets/17748526/e5aa0379-a8de-4a2a-bf40-a8b454d3d92e)

Also, when cursor hovers on service url, it is highlighted as a hyperlink: 
![image](https://github.com/OpenRefine/OpenRefine/assets/17748526/7346dce3-0d6c-4b7c-b2c7-ab1e6275171d)
Same is obtainable even if a service has been selected: 
![image](https://github.com/OpenRefine/OpenRefine/assets/17748526/0447efca-7241-4416-9113-3f14adad1f72)

See in the screenshot that the "Next >>" button is enabled as a service has been selected. Users can then proceed to reconcile.

Also, the "Pick a service or extension to continue" message is now displayed in a more user friendly way above the services.

To delete a service, users are prompted like we have on most places on the software because accidental clicks can happen
![image](https://github.com/OpenRefine/OpenRefine/assets/17748526/82cdb185-b4a1-4e39-82e0-15015a8950ee)


Link to this part of the reconciliation dialog redesign: https://www.figma.com/file/QWESrOCcNY8gDcmtByY2UO/Reconciliation-Dialog-Redesign?type=design&node-id=625-1265&mode=design&t=CyWwBoVtDS7DWvOq-4

I'll like to know what everyone thinks.

**Comment by wetneb** [comment]
Thanks for the mock-ups Lydia!

I noticed you did not include radio buttons. Is that intentional? We have some in the dialog to select a Wikibase instance and intuitively it's a sensible (and standard) way to convey to the user the information that they need to pick one (and only one) item in the list, no?

I agree that marking the "Next" button as disabled is sensible as long as no service has been selected.

Also, I think it could be useful to pre-select the service last used by the user, so that they can spare one click. People often work with the same service during a data cleaning project.

Feel free to add comments on the corresponding PR (#6118), where I have added screenshots of the current state of the pull request.

**Comment by Lydiaofficial** [comment]
Yes, it was intentional for a simpler Ui but I do agree that since we have radio buttons in most lists on the softqare, retaining them helps with consistency and I've made appropriate modifications to the mockups and also with the pre-select suggestion

**Comment by thadguidry** [comment]
@ayushrai206 What does the "highlighting" look like?  What do you mean by that word?  If you mean, should we also show the light blue background on a selected item when someone clicks on the radio button...
I would vote 👍

**Comment by wetneb** [comment]
What would it look like for the "reconcile against no particular type" option, for instance? To me it would feel a bit weird.
Intuitively I'd leave the blue background out for consistency with the current state of the second screen.

**Comment by thadguidry** [comment]
I also think URLs should already be blue by default.  Why do we have to hover over the URL to make it blue and then appear like it's clickable?  Just show it as blue color to denote it's a clickable URL and not just text.

**Comment by wetneb** [comment]
> I also think URLs should already be blue by default? Why do we have to hover over the URL to make it blue and then appear like it's clickable? Just show it as blue color to denote it's a clickable URL and not just text.

That's another thing we were not sure about: should those actually be clickable? Personally I am not sure, because I can imagine that someone wanting to select a reconciliation service clicks on the link, which would not have the expected effect since it would just open another tab with a big JSON blob, which is not so useful as a user.

**Comment by thadguidry** [comment]
@wetneb Ah good point indeed.  The user might click on the URL first, rather than the row element to select via the radio button.  Agreed, quite confusing.  OK... no blue clickable link... so...
just make sure the URL text can be easily copy/pasted (i.e. grabbed by a user to paste into their browser on their own)

**Comment by ayushrai206** [comment]
@thadguidry yes, you got it right. Also I do agree that the URL links should not be clickable as that would be very confusing.
