### ISSUE TITLE
Python expression preview doesn't always report errors

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3012]
### To Reproduce
1. Select "Add Column based on this Column"
2. With the expression `cells.a.value.toNumber() - cells.b.value.toNumber()`, switch the expression language to Python

### Current Results

No error message is displayed, presumably because the response has an "ok" status:

```json
{"code":"ok","results":[{"message":"Traceback (most recent call last):\n  File \"<string>\", line 2, in __temp_594255022__\nAttributeError: 'unicode' object has no attribute 'toNumber'\n"}]}
```
### Expected Behavior

The error message should be displayed to the user

**Comment by tfmorris** [comment]
I don't think this is the correct fix. Errors are normally reported in red in the top pane of the dialog (where both screenshots says "No syntax error" in the related PR #4991). This change removes the line number (which is useful information for helping to figure out where in the Python program the error is), but the returned string is still being considered a value for the preview, not an error.

I haven't looked at it since, but when I wrote up the bug report, I clearly thought that the problem was with the `"code": "ok"` part of the response. That could be incorrect, but it's definitely worth looking at.

**Comment by thadguidry** [comment]
Could we also add a Cypress test for it?

**Comment by yeungven** [comment]
Hi! I'm a student and my partner @hniswand and I would love to be assigned to this! We are tasked with contributing to an open source project for a class of ours.

**Comment by Sudo-Aryan** [comment]
can I try with this?

**Comment by antoine2711** [comment]
@Sudo-Aryan : I think this issue is actually dealt with already. See the corresponding PR.

I will close this.

Regards, Antoine

**Comment by wetneb** [comment]
@antoine2711 see the discussion above: @tfmorris mentioned that the PR did something different and that this problem is still present.

**Comment by antoine2711** [comment]
> @antoine2711 see the discussion above: @tfmorris mentioned that the PR did something different and that this problem is still present.

Oh. Sorry. Didn't see that.

Regard, A.

**Comment by XxBrezxX** [comment]
Hey, I wanna work in this issue? Is it still available? Can you give me more details?

**Comment by wetneb** [comment]
Hi @DiamondMyK, you have already been assigned #5440. Let's focus on that one and then once you have solved that one, we can assign you other issues. If you are no longer working on #5440, please unassign yourself from it first.

**Comment by SymbolofMoon** [comment]
Hi @wetneb and @tfmorris. May I know if the issue is still there?
If yes can you clear me some points?
a) You want the error should be in red and by the name Internal Error?
b) A Line number of error should be there in the display of error?
c) It is not "code":"ok" but "code":"error" or something?

Please let me know if my above understanding is right?

**Comment by wetneb** [comment]
>  a) You want the error should be in red and by the name Internal Error?

The error should be displayed like other syntax errors in this dialog (you could try typing "foo(" as a GREL expression, for instance). The error message should be as informative as possible as to what is wrong in the expression. "Internal error" would not be a good error message, because it is very unspecific and doesn't convey the meaning that the expression is syntactically incorrect.

>  b) A Line number of error should be there in the display of error?

That would be convenient, but bear in mind that the expression that the user types in this box is then completed (to make a function declaration), so the line numbers and characters in the error would likely need adapting for them to make sense to the user.

> c) It is not "code":"ok" but "code":"error" or something?

Indeed. Including `"code":"error"` in the JSON response would make sure an error is correctly reported to the user (in red).

**Comment by wetneb** [comment]
Hmm, I didn't realize that the error mentioned in the issue statement is indeed not a syntax error, but a runtime one. Thanks for pointing that out! I would argue that we shouldn't expect runtime errors to be reported next to the expression editor: their reporting in the preview tab should be sufficient.

It is an unfortunate aspect of Python that so many programming errors only get discovered at runtime, but I don't think we can meaningfully work around that issue.

The approach of promoting a runtime error to a syntax one when the error is the same on all previewed rows could be tempting, but it is bound to be incorrect in some cases. For instance, it is quite common to use GREL expressions which will throw an error when run on a null cell. Because the default behaviour of transformations is to keep the resulting cell blank when an error is thrown, this often amounts to just ignoring null input cells. But now imagine you want to use such an expression and the first 10 rows of your project happen to have null input cells: your GREL expression would be rejected by the editor even though it might work correctly for some further non-empty rows.

**Comment by thadguidry** [comment]
TODO still on this issue to close it out would be adding @tfmorris suggestion here:
https://github.com/OpenRefine/OpenRefine/pull/7217#discussion_r2096613053

**Comment by ishankguptaaa** [comment]
> TODO still on this issue to close it out would be adding [@tfmorris](https://github.com/tfmorris) suggestion here: [#7217 (comment)](https://github.com/OpenRefine/OpenRefine/pull/7217#discussion_r2096613053)

Hi, I’ve opened this PR with a proposed fix. Please let me know if any changes are needed—happy to iterate.
