### ISSUE TITLE
Can't login to Google to access private Sheets / Drive

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3054]
It's impossible to login in when attempting to import from Google Sheets / Drive, because the spinner is shown instead of the "sign-in and authorize button"

### To Reproduce
1. When clicking on Google Data there is immediately a small spinner next to Authorized Documents.

### Current Results
I get a **Preparing**... spinner on the screen.

### Expected Behavior
No small spinner for Authorized Documents when first clicking on Google Drive options to Create Project.

### Screenshots
![image(3)](https://user-images.githubusercontent.com/986438/89843291-cc949900-db3d-11ea-906f-f636a215afab.png)

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox latest
 - JRE or JDK Version: JDK8
 - OpenRefine: OpenRefine 3.4 Beta SNAPSHOT

**Comment by tfmorris** [comment]
I've noticed this Javascript console message at startup recently, which could be related (or not):

```
index-bundle.js:37619 Uncaught TypeError: Cannot read property 'sort' of undefined
    at Refine.GDataSourceUI._renderDocuments (index-bundle.js:37619)
    at Object.success (index-bundle.js:37550)
    at fire (index-bundle.js:3234)
    at Object.fireWith [as resolveWith] (index-bundle.js:3364)
    at done (index-bundle.js:9842)
    at XMLHttpRequest.callback (index-bundle.js:10313)
```

**Comment by tfmorris** [comment]
Sorry this got ignored. There are actually two bugs here:

- can't access public Google Sheets (which is duplicated by #3604)
- can't log in to Google (because it shows the spinner by default instead of the "sign-in and authorize" button)

I'm going to repurpose this to focus on the second problem since we have another ticket for the first. The second problem is also mentioned in #3312.
