### ISSUE TITLE
Update Wikidata recon endpoint URL (again!)

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3080]
I used to maintain a Wikidata reconciliation service at https://wdreconcile.toolforge.org/.

The toolforge is an infrastructure provided by the Wikimedia Foundation for developers to host tools to support the Wikimedia community. It provides a managed ecosystem which enables shared maintenance of tools by multiple contributors, easy access to Wikimedia resources (SQL replicas of the MediaWiki dbs), and other useful things.

Being a managed environment comes with perks (no need to set up SSL yourself, free domain name, no hosting bills) but also downsides (being faced with devops bugs or downtime outside your control). Recently I faced a serious bug which I was unable to fix myself ([HTTP 502 errors being seemingly cached by some upstream component](https://phabricator.wikimedia.org/T257405)). I have therefore decided to host the tool outside this environment, on a server I rent myself and with a domain name I own:

https://wikidata.reconci.link/

Therefore I propose to use this as the default reconciliation service in OpenRefine. This is not benign, since this is a web service I totally control. I have access to all the reconciliation queries submitted to the service, I could decide to shut it down anytime, forget to renew the domain name, or other things like that. That being said, the previous service was not official either (since it was not run by Wikidata itself) and I could also access all the queries run on the service.

Beyond the absence of cached HTTP 502 errors, the new service is also significantly faster because I took the opportunity to rewrite it to use asynchronous parallelism.

I would very much prefer to run this service in the scope of the OpenRefine project but there has been limited appetite from the rest of the team about the idea of running our own server. I have also been trying to encourage the Wikidata team to run the service themselves, but that is an ongoing effort which is not likely to come to fruition immediately.

**Comment by tfmorris** [comment]
Wikidata should run their reconciliation service, not some third-party. The fact that they shirk the needs of their customers and refuse to do so isn't OpenRefine's problem. It's above and beyond the call of duty that you volunteer to do this for them on top of all your (many) other responsibilities.

Having said that, this feels like an area where an official policy on the criteria for inclusion as a bundled reconciliation service in OpenRefine's default distribution would be useful. That would provide a measure of transparency for the standard to be met and protect against accusations of arbitrariness. Obviously, other distributions/bundles can make their own rules as to what extensions and reconciliation services they bundle, as LODRefine and others have done in the past.

In advance of a formal policy, my initial reaction is that I'm uncomfortable bundling a personally controlled reconciliation service with the standard OpenRefine distribution. I'm not sure what measures are available to mitigate the risk. Find another institutional host besides Wikidata? Redirect through the openrefine.org domain so that we can at least turn off the redirect if necessary at some point in the future? Others?

I'd like to hear @thadguidry @magdmartin @ostephens and others weigh in on the idea of formal policy here (perhaps a mailing list discussion topic).

**Comment by thadguidry** [comment]
@tfmorris Yes please, let's discuss this on the dev mailing list for transparency.  I have many questions that I'd like Antonin to reply with, as he mentioned that he has had discussions with Wikidata and we probably need for him to mention some of the outcomes of those for the record (he mentioned one on recent CS&S call).

**Comment by magdmartin** [comment]
For reference the [discussion on the mailing list](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openrefine-dev/KK4frsSGhA4/yaCLan0nCQAJ)

**Comment by wetneb** [comment]
Closed by #4206
