### ISSUE TITLE
NullPointerException WikitextImporterTests.readTableWithLinks

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3128]
I'm not sure what's going on here since the tests pass locally for me, but on LGTM.com this test fails with a NPE on both master and the merge commit.

An example build is [here](https://lgtm.com/projects/g/OpenRefine/OpenRefine/logs/rev/pr-5dfbf8f70eb220a8d42e6816b04981b1d24253dd/lang:java/stage:Build%20master_3fe2281d9449d11eaeb1104addc71f3628e239c0)

java.lang.NullPointerException
 	at com.google.refine.importers.WikitextImporterTests.readTableWithLinks(WikitextImporterTests.java:204)
https://github.com/OpenRefine/OpenRefine/blob/5ca5f3cb7b6cc1be1813e9e196a3c0f669298a4c/main/tests/server/src/com/google/refine/importers/WikitextImporterTests.java#L200-L204

Presumably either the recon field is null or `getBestCAndidate()` is returning null.

**Comment by wetneb** [comment]
This is probably a test with an HTTP call that is not properly mocked.

**Comment by tfmorris** [comment]
This isn't restricted to LGTM builds. It's causing Travis CI failures as well: https://travis-ci.org/github/OpenRefine/OpenRefine/jobs/721243474

@wetneb Any chance you know what the fix is?

**Comment by wetneb** [comment]
I had a look and it is a bit unclear to me what is going on. I think the proper solution to this would be to avoid using PowerMockito for mocking. That requires architectural changes in the reconciliation code (which I am keen to do for other reasons - it is just a big mess at the moment). Perhaps we could also just get away with tweaking the importer so that the ReconConfig it uses can be set from outside, in which case we would be able to set it to a mock without resorting to PowerMockito.

**Comment by tfmorris** [comment]
Anything that keeps every build from showing up with a red X works for me.

**Comment by wetneb** [comment]
This is now solved by migrating out of PowerMock.
