### ISSUE TITLE
Retrieving Undo History for lost changes

### ISSUE THREAD

**Issue by sinairusinek** [OpenRefine/OpenRefine#3130]
Hi, I seem to have the same problem described in this closed issue: https://github.com/OpenRefine/OpenRefine/issues/1936
On August 20, 2020,  around 10:00 UTC, I still had a column of VIAF_ID fully reconciled with Wikidata (a large part of it was matched, but not all) and many more thousands of values in 2 columns (split 1 and split 2) reconciled with data. Also, the recent history in the "undo" was from the morning and the night and day before.

Something happened on Thursday afternoon and in the evening, the project suddenly lost the VIAF reconciled column and most of the reconciliation on the other columns. the "undo" panel now shows actions that I did back in June.
When I look at the workspace directory, I see files in the history folder of the project through Thursday, before and after this change, but after copying the project folder, removing history files from Thursday afternoon and reopening Open Refine, nothing changes and I still get the old state from June. The data files seem to be from that date.  Is there a way to re-update the project using the history files? 

### To Reproduce
I have no idea how this happened! power breaks, internet problems while reconciling, but nothing that didn't happen before.

### Versions:
 - Operating System: 
 - Browser Version: 
 - JRE or JDK Version: 
 - OpenRefine: 

### Datasets
I uploaded the project to here: https://drive.google.com/drive/folders/1FYgAIHV2ZDeJIZre4JLChn3_u5f6Zy1D?usp=sharing

### Additional context
I tried to use the mailing list but no luck yet.

many thanks,
Sinai

**Comment by tfmorris** [comment]
Thanks for opening a separate issue. Can you please provide a date for "last Thursday" and give times in UTC (or tell us what timezone you are in)? All of the internal timestamps are saved in UTC.

Also, if you haven't already done so, you should immediately backup your OpenRefine workspace directory before doing anything additional.

**Comment by sinairusinek** [comment]
thank you, Tom! I am backing the workspace directory now and edited the details above:August 20, 2020, around 10:00 UTC.

**Comment by tfmorris** [comment]
I had a look at the project and I don't think this is related to #1936, which was due to a malformed reconciliation service manifest.

There are two project data files:

```
  15800 Aug 21 05:49 data.temp.zip
1607174 Jun 17 08:31 data.zip
```

The first is a partial truncated file which has no data in it. The timestamp on the other one indicates that it from from June 17 (which is consistent with the internal dates). 

I'm not sure I understand the sequence of events. When you say:

> after copying the project folder, removing history files from Thursday afternoon and reopening Open Refine, nothing changes and I still get the old state from June

Do you have a copy of the project from before you started modifying it by hand? Do you have any backups of your workspace directory which are more recent than June 17? I would expect that the `data.zip` file would have a much more recent date given the sequence of events that you described.

You asked:

> Is there a way to re-update the project using the history files?

It is theoretically possible to rebuild the change history from the individual changes, but we don't have any ready-made tools to do this.

The number of changes for the two zip files and the history directory are:
```
 305 2020-06-17T14:52:14Z
 330 2020-06-17T15:23:26Z
1478 2020-08-20T15:14:32Z
```

The `data.temp.zip` file ends in midstream, indicating that the system failed to finish writing it:

`{"id":1592404705886,"description":"Reconcile cells in column tosplit 2 to type /geonames/name","time":"2020-06-17T14:52:14Z","operation":{"op":"core/recon","description":`

These are the timestamps for the changes on Aug 20:

```
2020-08-20T08:07:36Z
2020-08-20T08:18:33Z
2020-08-20T08:20:19Z
2020-08-20T09:13:16Z
2020-08-20T09:13:49Z
2020-08-20T09:16:42Z
2020-08-20T09:18:05Z
2020-08-20T09:18:17Z
2020-08-20T09:19:34Z
2020-08-20T09:20:56Z
2020-08-20T09:24:01Z
2020-08-20T09:24:58Z
2020-08-20T10:30:26Z
2020-08-20T11:11:37Z
2020-08-20T15:02:43Z
2020-08-20T15:04:17Z
2020-08-20T15:04:31Z
2020-08-20T15:04:31Z
2020-08-20T15:06:43Z
2020-08-20T15:08:06Z
2020-08-20T15:09:24Z
2020-08-20T15:10:28Z
2020-08-20T15:11:22Z
2020-08-20T15:11:40Z
2020-08-20T15:14:32Z
```

I'm having a hard time making the timeline match up, but I do see one theoretically possible failure scenario. On save we:
* write `data.temp.zip`
* rename `data.zip` to `data.old.zip`
* rename `data.temp.zip` to `data.zip`

At least, I believe that's the intent, but it looks like there's a bug that deletes the `data.old.zip` files, so that there's no backup.

On load we try to read the following, in sequence:
* `data.zip`
* `data.temp.zip`
* `data.old.zip`

My theory is that there was a partial `data.temp.zip` file from June 17 which got left around when the server crashed in the middle of writing (out of memory, power fail, etc). On Aug 20, the `data.zip` file couldn't be read for some reason, so the system tried the (corrupted) `data.temp.zip` file from June 17.

There are a few things that we should fix:
1. Don't delete `data.old.zip` so that there is a backup available
1. On successful load of `data.zip`, **do** delete any `data.temp.zip` to prevent this scenario
1. If we have to fall back to one of the backups, warn and/or ask the user

**Comment by sinairusinek** [comment]
Thanks a lot, Tom, this does seem to be a full explanation to what happened. Unfortunately, there is not uncorrupted data file anywhere from August: all the changes I did were on other copies of the project folder and what I uploaded was a copy of the original project. I did not touch the data files anyway.
So the solution sounds good to prevent this from happening again. But how do I now make use of the history files to complement the old data? even if it is a grudging manual work I'm up for it..

**Comment by tfmorris** [comment]
> But how do I now make use of the history files to complement the old data?

Unfortunately, using them would depend on starting with a data grid that matched their state, which you don't appear to have.

I wrote some code to recreate history entries from orphaned changes found in the history directory. It successfully created 1126 history entries which can be reapplied by clicking on them, but things go off the rails almost immediately with a reconciliation operation on a column which doesn't exist, "HebWDRecon". Other operations are trying to operate on more rows than exist, more columns than exist, etc. Even the operations which don't error are likely not doing what they are intended to do. Without a starting point that matches the undo history, this doesn't have any chance of working.

**Comment by thadguidry** [comment]
@tfmorris Do we close this issue now?  I think that issue #732 captures most of the solution you think might be needed long term?  Perhaps you could put those thoughts added in #732 given some of your research and new knowledge from this issue.

**Comment by sinairusinek** [comment]
Fine with me - I redid everything now. Hope the fix to prevent this from happening will be implemented soon. Good luck!

**Comment by tfmorris** [comment]
I have some tooling which could help in future cases, but only if, as I mentioned above, the data grid matching the starting point of the recovered undo history is available.
