### ISSUE TITLE
Sandbox reconciliation candidate preview iframes

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3140]
We display the entity previews returned by reconciliation services using an `<iframe>`, which lets services return arbitrary HTML pages for their entities.

These pages could potentially contain scripts, which could do all sorts of things, including talking to the backend, which can be considered a security vulnerability.

Reconciliation services are already able to execute arbitrary javascript in the user's browser when they add the service with its URL, because of the JSONP-based fetching method.

### Solution proposed

Use the `<iframe sandbox="">` attribute to disable scripts and other APIs:
https://developer.mozilla.org/fr/docs/Web/HTML/Element/iframe#attr-sandbox

Perhaps `sandbox=""` is too restrictive, we should review its impact on a few existing public reconciliation endpoints.

### Alternative solutions

Should we use another mechanism than iframes? It seems difficult to let services expose arbitrary previews without relying on that.

### Relevant code

https://github.com/OpenRefine/OpenRefine/blob/6095c44cb714f7b1ea6a1eac961b0394ac138a8b/main/webapp/modules/core/scripts/views/data-table/cell-ui.js#L468-L477

**Comment by thadguidry** [comment]
Is there a particular requirement for iframe?  If not, then I'd suggest Web Components instead (with Polyfills for Firefox/Edge).
https://webagility.com/posts/web-components-vs-iframes

**Comment by Abbe98** [comment]
> Is there a particular requirement for iframe? If not, then I'd suggest Web Components (or Shadow DOM) instead (with Polyfills for Firefox/Edge).

I don't think Web Components or Shadow DOM can be sandboxed at all, as mentioned by the first article:

> Encapsulation. Stylesheets and scripts inside the embedded page are isolated inside the Shadow DOM of your host page. However, you can still access the main document from inside JavaScript of the included page.

**Comment by thadguidry** [comment]
I've given this more thought and some cursory research.

- We don't want sites to load and render other sites.
  - So we can add `Content-Security-Policy: frame-src` configurations that allow only what we want, upon adding a reconcile service.  https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
- On the sites that are added to reconcile service, we also do not want them to use any scripts, instead only HTML and images and only from their site (since the user added and trusted the reconcile service into OpenRefine -  I think we can also improve that area by noting to users on the dialog somehow that "only add service urls that you trust to prevent browser attacks".
  - So we can again add CSP configurations.
- We don't want sites to trick users through possible clickjacking.
  - So we can add `sandbox` attribute with configurations to remove `allow-top-navigation`, `allow-top-navigation-by-user-activation`, `allow-popups`, or `allow-popups-to-escape-sandbox`.

Perhaps instead of HTTP header, we could add CSP directives directly into the `<meta>` element of our page and dynamically reload as part of the reconcile service setup?

Is any of the above do-able or should be?

**Comment by Abbe98** [comment]
I have been using sandbox="" since early January without any noticeable issues(using our own endpoints as well as the Commons and Wikidata ones).

Is there actually any legitimate use cases for any rights beyond the default setting? I guess forms and JS could be useful to some, although I personally wouldn't want to support such use-cases.
