### ISSUE TITLE
XSS vulnerability in suggest flyouts

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3141]
**Is your feature request related to a problem or area of OpenRefine? Please describe.**

The flyout services in reconciliation endpoints can return arbitrary HTML which is directly included in the DOM without sanitization:

https://reconciliation-api.github.io/specs/latest/#flyout-services

This means that reconciliation services can execute arbitrary Javascript in the user's browser when they hover a suggested item in an autocompleted field.

**Describe the solution you'd like**

Drop flyout services.

**Describe alternatives you've considered**

Change the specs so that the flyout services only return data following a fixed schema (a description string, for instance, but that would be redundant with the description that can be returned in the suggest responses directly).

Or cook up some way to sanitize the HTML returned by the service, by removing `<script>` tags for instance, but that is bound to be brittle.

**Additional context**

Similar to #3140.

**Comment by tfmorris** [comment]
This seems like it's identical to #3140. Removing flyouts is going to deprive users of valuable context that they need to resolve reconciliation ambiguities. We should fix the vulnerability, not rip out the functionality.

**Comment by wetneb** [comment]
Those are different because one is about previews, and the other one is about flyouts. These are two different things:
* previews are what you get when you hover reconciliation candidates in the cell UI
* flyouts are what you get when you hover suggested items in auto-complete widgets.

**Comment by wetneb** [comment]
@ayushrai206 I could not find a working service which uses flyout (I guess that's a sign that removing this feature would indeed not harm too much).
There is https://data1.kew.org/reconciliation/reconcile/IpniName, which does declare flyouts in the manifest, but apparently it cannot be added to OpenRefine (as it is unreachable via CORS and JSONP).
You can get an overview of how this feature worked in this older version of the specs:
https://www.w3.org/community/reports/reconciliation/CG-FINAL-specs-0.1-20230321/#flyout-services

**Comment by tfmorris** [comment]
Given that these are still included in the [reconciliation spec](https://www.w3.org/community/reports/reconciliation/CG-FINAL-specs-0.2-20230410/#flyout-services), it seems premature to remove them from OpenRefine. 

I still believe that this provides useful context for users as I mentioned in 2020:

> Removing flyouts is going to deprive users of valuable context that they need to resolve reconciliation ambiguities. We should fix the vulnerability, not rip out the functionality.

Is there a proposal to provide the functionality in some other way?

**Comment by wetneb** [comment]
Yes, I think the functionality is already replaced by the ability to include descriptions in the suggest responses (which are rendered in OpenRefine). This allows for a better UX (no need to hover each suggested item individually to find out whether it is the right one or not). Before we introduced this (a few years ago already), when looking for an entity with many namesakes, it was quite tedious.

**Comment by tfmorris** [comment]
Descriptions are just a tiny subset of the information that was included in flyouts. The [Freebase Suggest widget](https://developers.google.com/freebase/v1/suggest) is an example of what such a flyout would look like. In addition to the name and description, it also includes:

- An image of the entity, if available
- Notable types (in grey at the bottom). Which types are considered notable was driven my special properties in the metaschema
- Property values for important properties associated with the primary type (birth date, birth place, nationality in the case of a Person). Again, these are schema driven, so for a building, it might include the location. For a geo entity, in might include the containing entity, etc.

![Screen Shot 2023-06-14 at 5 00 08 PM](https://github.com/OpenRefine/OpenRefine/assets/82178/8062bdd5-2924-468a-ad5a-16d109ec33f9).

It certainly would be possible to codify this information in a data structure rather than allowing arbitrary HTML, but that would increase the rendering burden for the clients.

**Comment by wetneb** [comment]
That's clearly much nicer than the lousy flyouts I had implemented for the Wikidata service (and removed since), but even with those, I am not convinced by the UX.

Having to hover each suggested item means that you cannot eyeball the list quickly, looking for a keyword in the descriptions. Instead, you need to make relatively careful mouse movements over the suggested items one by one, and at each step wait for the flyout to load (which will not be instant even if the service is fast, especially for such rich content).

For me, what's really telling is how little this functionality is currently used: as I wrote above, I cannot find any publicly accessible service which actually works and relies on those flyouts. Looking at the manifests listed in the testbench, the only candidates are:
* https://data1.kew.org/reconciliation/reconcile/IpniName: not usable in OpenRefine at all due to broken JSONP and CORS
* https://reconcile.ror.org/reconcile, which does work, but then the flyouts it shows seem to be entirely redundant with the information shown in the items of the suggest widget itself:
![image](https://github.com/OpenRefine/OpenRefine/assets/309908/12881e8f-092d-4d00-8852-f4b3616e5caa)
* https://numismatics.org/crro/apis/reconcile, where the flyout endpoint returns HTTP 500 errors (so the flyouts are not shown)
* https://nomisma.org/apis/reconcile, which does work, but renders pretty huge descriptions, which in my opinion could as well be inserted in the suggested items:
![image](https://github.com/OpenRefine/OpenRefine/assets/309908/9d7a9be1-85dd-4b38-aaa9-99b7a9b49c59)

If we really want to keep this UX of having to hover the elements of an auto-completion widget despite the usability issues above, then why not just show the previews (rendered via `<iframe>`) that the API also supports?

**Comment by wetneb** [comment]
@magdmartin rightly suggested me to ping @OpenRefine/designers for more input about this UX

**Comment by tfmorris** [comment]
The proposed Sanitizer API sounds like it could be valuable for mitigating this risk:
https://github.com/WICG/sanitizer-api

**Comment by tfmorris** [comment]
> That's clearly much nicer than the lousy flyouts I had implemented for the Wikidata service (and removed since), but even with those, I am not convinced by the UX.

Well then, let's get a better UI designed rather than just ripping out the functionality. What did the @OpenRefine/designers  suggest?

There's a tension between having a compact list representation and being able to access more detailed information. The flyout is an attempt at addressing that, but there may be other ways to represent the detailed information. Just adding more detailed text to the list entries is not a good solution in my opinion.

Note also that #6103 proposed a different solution for the duplicate #3140

**Comment by wetneb** [comment]
#3140 is not a duplicate of this issue, because the flyouts and previews are two separate features (see the separate section in [the specs](https://www.w3.org/community/reports/reconciliation/CG-FINAL-specs-0.1-20230321/#preview-service)). I don't think you can render a snippet of HTML that has been designed to be included in OpenRefine directly (as is the case of flyouts) in an iframe and expect it to look as intended.
