### ISSUE TITLE
Extend forEach() to support JSON objects as well as arrays

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3149]
Currently `forEach()` support native arrays, JSON arrays, and collections, but not JSON objects. Adding JSON objects would would allow parsing payloads like:

* Wikimedia Commons -> https://commons.wikimedia.org/w/api.php?action=query&titles=File:Google%202015%20logo.svg&prop=imageinfo&iiprop=url&format=json
* MySociety MapIt -> https://mapit.mysociety.org/point/4326/0.1293497,51.5464828

### Proposed solution

Extend `forEach()` to allow JSON objects as well as arrays for the first argument.

### Alternatives considered

This is the simplest version of #3147.

**Comment by thadguidry** [comment]
@tfmorris Thanks Tom, but can you give an example expression of how it's used given that first Wikimedia Commons example?
```json
{"continue":{"iistart":"2015-09-02T16:59:57Z","continue":"||"},"query":{"pages":{"42827827":{"pageid":42827827,"ns":6,"title":"File:Google 2015 logo.svg","imagerepository":"local","imageinfo":[{"url":"https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg","descriptionurl":"https://commons.wikimedia.org/wiki/File:Google_2015_logo.svg","descriptionshorturl":"https://commons.wikimedia.org/w/index.php?curid=42827827"}]}}}}
```

**Comment by thadguidry** [comment]
@tfmorris OK,  I think I have figured it out and the 2nd MySociety link makes it easier to understand the usage after I looked at your test cases as well. And seems to work well.  Good Job!

With that MySociety link I was hoping that sort() would still work with the `null` values in the output array
![image](https://user-images.githubusercontent.com/986438/91660992-deaf8a80-ea9e-11ea-8ddc-03dec5ffa258.png)
![image](https://user-images.githubusercontent.com/986438/91661000-eff89700-ea9e-11ea-859a-a13d48edb9f2.png)

I think instead of defaulting to the NullPointerException, instead we could still allow sorting of arrays that contain null values and place nulls first or last with a new `sort()` Boolean parameter for nullsLast.
https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/expr/functions/arrays/Sort.java#L55
To do that we could use `java.util.Comparator`  https://www.tutorialspoint.com/How-to-sort-an-array-of-objects-containing-null-elements-in-java

Shall I open a new enhancement issue for that new `sort()` Boolean parameter enhancement?

**Comment by tfmorris** [comment]
@thadguidry Please don't use images for things which can be explained using text. It just makes people have to retype a lot of text which could be cut & paste with last effort and fewer errors.

> Shall I open a new enhancement issue for that new sort() Boolean parameter nullsLast?

Have you ever known me to say to **not** open an issue? :) Except that I consider this a bug, not an enhancement request.

As a workaround, you can use `forEach(value.parseJson(), v, toString(v.codes.gss)).sort()`

**Comment by thadguidry** [comment]
@tfmorris sorry.  My text usually confuses more. :-)  I'll open a new bug issue now.

**Comment by tfmorris** [comment]
Thanks for creating the bug report.

For text vs image, you can do both if you think it's helpful. The key thing, from my perspective, is that the developers have easy access to the information that they need, so, if you use images, please also back them up with textual versions of key elements that they need for reproduction and debug, ie URLs, GREL expressions, error messages, stack traces, etc.

**Comment by thadguidry** [comment]
@tfmorris yes understood your point well. sorry. I'll make sure to include textual versions so you can easily copy/paste to reproduce.
