### ISSUE TITLE
Create fully automated kit build

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3241]
Currently the kit build process is a mix of automated (`./refine dist 3.4`) and manual steps (tag, edit, upload, etc).

### Proposed solution

Integrate as many steps as possible into the automated procedure, including:
- checking prerequisites: Apple & Google credentials, other?
- setting release version string
- tagging release in git
- injecting Google credentials
- downloading/caching Windows & Mac JREs to be bundled
- building all 4 kits - Windows (x2), Mac, Linux
- compressing .dmg
- signing release artifacts
- creating Github release & uploading artefacts (marked as draft until manually reviewed/published)

### Alternatives considered

We could keep our current mix of manual and automated steps, but the higher the number of manual steps, the more error-prone it will be.

**Comment by wetneb** [comment]
I have made quite some progress in this direction, by scripting the release process in a Github action and in the Maven configuration. What is currently left is:
* setting release version string
* tagging release in git
* creating Github release
* uploading artifacts from Maven Central to the Github release

It is already much better than before in my opinion, but still not perfect!

**Comment by wetneb** [comment]
I am satisfied with the current process for now, so unassigning myself.

**Comment by wetneb** [comment]
I would even argue that the rest ought to stay manual - I don't think we should really expect to have a script that creates and pushes a git tag and the corresponding GitHub release - those are administrative steps that we can expect of maintainers, I would say.

More automation can go into updating the download page (so that it always displays the latest release without us needing to update the Markdown source every time), but that's not for this repository. We also have another issue (#2359) to automate the writing of the changelog.
