### ISSUE TITLE
404 on /en/en.json during Project Open

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/OpenRefine#3250]
Similar to #2835 we have a 404 for `/en/en.json` when we open a project. 

Tested with OpenRefine 3.3 and 3.4.1 
OS Linux with Chrome

GET http://127.0.0.1:3333/en/en.json 404 (Not Found)

![Screenshot from 2020-10-05 17-40-19](https://user-images.githubusercontent.com/2589584/95135188-0cd55980-0732-11eb-9750-d0418a6fa710.png)

**Comment by tfmorris** [comment]
This looks like it's coming from /extension/database/scripts/project/database-exporters.js.

https://github.com/OpenRefine/OpenRefine/blob/1157cb047ca7192d7a3e5f5afe4a230482335606/extensions/database/module/scripts/project/database-exporters.js#L31-L44

With my language set to `fr`, I get two 404s, one for /fr/fr.json and one for /fr/enjson, presumably due to fallback processing.

**Comment by wetneb** [comment]
I tried reproducing this and no longer get a 404 error, the translations for the database exporter just load fine here.
