### ISSUE TITLE
Can't see projects or open Workspace Directory with non-ASCII characters in workspace path

### ISSUE THREAD

**Issue by fhc1958** [OpenRefine/OpenRefine#3277]
Hi,
I have installed OpenRefine 3.3. in Windows10 and open with Chrome
Everything works ok, but I can't see Created Projects nor open the Browse directory
Also, I can't import projects.
![image](https://user-images.githubusercontent.com/73102849/96425213-14016a80-11fc-11eb-9dcd-d5cb55f734ad.png)
![image](https://user-images.githubusercontent.com/73102849/96425451-53c85200-11fc-11eb-8681-7a400882741c.png)

Many thanks

**Comment by tfmorris** [comment]
Sorry to hear that you're having trouble. Were you able to figure out what this issue was?

I'd recommend using the latest release 3.4.1 since it has all the latest features and bug fixes, but we have many users successfully using OpenRefine 3.3 and 3.4.1 on Windows 10, so I suspect this is something specific to your local setup.

**Comment by thadguidry** [comment]
@fhc1958 This might be because your workspace directory contains non-ASCII characters, but I'm not certain.  One thing you could do is make a new folder using ASCII characters only... such as just `openrefine_workspace` and then point OpenRefine to use that folder.

You can change this 2 ways:
* by adding this line to the file `openrefine.l4j.ini` and specifying your desired drive and folder path:

  `-Drefine.data_dir=D:\MyDesiredFolder`

If your folder path has spaces, use neutral quotation marks around it:

  `-Drefine.data_dir="D:\My Desired Folder"`

* when you run OpenRefine from the terminal, by pointing to the workspace directory through the -d parameter:

`./refine -p 3333 -i 0.0.0.0 -m 6000M -d /My/Desired/Folder`

If the folder does not exist, OpenRefine will create it.

**Comment by fhc1958** [comment]
Hi Thad
Many thanks.
You're right the problem was in the path of my workspace. I have followed
your instructions and now is working

Muchísimas gracias

**Comment by thadguidry** [comment]
@fhc1958 You are welcome!  We'll close this issue now.

**Comment by devyzr** [comment]
Had a similar issue on Linux, using Open Refine 3.5.2 on Ubuntu 20.04.03. There were no non-ascii in my workspace directory, it is  /home/coconut/.local/share/openrefine. I didn't have any non-ascii characters in my title either, only alpha-numeric and lower case characters. I had to delete my entire project folder and then restart open refine and my browser to get this to stop happening.
