### ISSUE TITLE
Weird scrolling behavior with Docusaurus Tab syncing

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3309]
### To Reproduce
1. Go here: https://docs.openrefine.org/manual/installing/#set-where-data-is-stored
2. Then click on Windows, Mac or Linux tab

### Current Results
On Firefox or Chrome, you are scrolled into a completely different section than the `#set-where-data-is-stored` !!!

### Expected Behavior
When clicking on a Tab, it should keep me at the start of the same tab with the same `groupId`
Just as it does on the documentation for Docusaurus Tab https://v2.docusaurus.io/docs/markdown-features/#tabs
Maybe it's because there is some confusion on syncing tabs or the groupId's.  It might also be some corner case bug we are hitting with the way we are styling or using the `Tabs` or `TabItem` so we might ask folks on Docusaurus Slack channel.

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox, Chrome
 - JRE or JDK Version: N/A
 - OpenRefine: N/A

**Comment by wetneb** [comment]
I can reproduce this too. I think this should be reported to Docusaurus.

**Comment by allanaaa** [comment]
As far as I know it's just the page resizing all of the multi-tab sections whenever you switch to another. The Mac and Linux versions of the page are close to being the same size, and the Windows version is much longer (because of screenshots in this case). It's not great, but unless we manually insert extra dead space into the shorter pages I don't see how it can be resolved. 
I thought we talked about this before, and decided that since most people won't be switching around between operating systems it isn't a serious problem. But lodging it with Docusaurus is a good idea.

**Comment by thadguidry** [comment]
Thanks @allanaaa yes, can you pretty please bring this up with Docusaurus (they might even have a quick fix or suggestion for us)
