### ISSUE TITLE
Make Wikibase tag configurable in the manifest

### ISSUE THREAD

**Issue by Nikerabbit** [OpenRefine/OpenRefine#3359]
### To Reproduce
Same as in #3354 when actually trying to save edits.

### Current Results
No edits are being made.

This appears in the logs:
```
openrefine_1        | 16:26:03.794 [..ting.EditBatchProcessor] MediaWiki error while editing [badtags]: The tag "openrefine-3.5" is not allowed to be manually applied. (2044ms)
openrefine_1        | 16:26:03.867 [..ting.EditBatchProcessor] MediaWiki error while editing [badtags]: The tag "openrefine-3.5" is not allowed to be manually applied. (73ms)
openrefine_1        | 16:26:03.934 [..ting.EditBatchProcessor] MediaWiki error while editing [badtags]: The tag "openrefine-3.5" is not allowed to be manually applied. (67ms)
openrefine_1        | 16:26:04.008 [..ting.EditBatchProcessor] MediaWiki error while editing [badtags]: The tag "openrefine-3.5" is not allowed to be manually applied. (74ms)
openrefine_1        | 16:26:04.091 [..ting.EditBatchProcessor] MediaWiki error while editing [badtags]: The tag "openrefine-3.5" is not allowed to be manually applied. (83ms)
openrefine_1        | 16:26:04.177 [..ting.EditBatchProcessor] MediaWiki error while editing [badtags]: The tag "openrefine-3.5" is not allowed to be manually applied. (86ms)
openrefine_1        | 16:26:04.267 [..ting.EditBatchProcessor] MediaWiki error while editing [badtags]: The tag "openrefine-3.5" is not allowed to be manually applied. (90ms)
openrefine_1        | 16:26:04.351 [..ting.EditBatchProcessor] MediaWiki error while editing [badtags]: The tag "openrefine-3.5" is not allowed to be manually applied. (84ms)
openrefine_1        | 16:26:04.433 [..ting.EditBatchProcessor] MediaWiki error while editing [badtags]: The tag "openrefine-3.5" is not allowed to be manually applied. (82ms)
openrefine_1        | 16:26:04.434 [..baseapi.WbEditingAction] We are editing too fast. Pausing for 8203 milliseconds. (1ms)
```

### Expected Behavior
Edits succeed or there is a clear error message in the user interface.

### Versions
 - Operating System: Debian 10
 - Browser Version: Google Chrome 87.0.4280.66
 - JRE or JDK Version: openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
 - OpenRefine: Version 3.5-beta [96789f9]
- MediaWiki: 1.35.0

### Additional context
I believe I can manually create the openrefine-3.5 change tag, and then it may work (did not test yet), but it would be nice if this was clearly documented or even better automated. If this is documented somewhere, I'll note that I did not see such a thing and I've been reading and googling stuff for a bit while debugging various issues.

 Since the version number is included, it's likely to break again in the future once openrefine is updated.

**Comment by tfmorris** [comment]
That's a strange error message since there's no OpenRefine 3.5 release https://github.com/OpenRefine/OpenRefine/releases

**Comment by Nikerabbit** [comment]
Sorry, I forgot to fill in the version information, but I'm using the master branch due to #3354.

**Comment by Nikerabbit** [comment]
The edit tag is defined in https://github.com/OpenRefine/OpenRefine/blob/7d4e182c7551ba828febe6b26d4aa0c0fd4fb578/extensions/wikidata/src/org/openrefine/wikidata/operations/PerformWikibaseEditsOperation.java#L171-L177 and it's just `openrefine-major.minor`.

**Comment by wetneb** [comment]
We should decide whether:
1. we require Wikibase instances to have a tag of the desired format (`openrefine-$VERSION`)
2. or whether we make this tag configurable in the manifest
3. or whether we can somehow apply the tag only if it exists in the target Wikibase instance

I am thinking 2. or 3. could work. For 3., I would try to make the first edit with the tag, and if that fails because the tag does not exist, try again without the tag (and do all further edits without the tag).

**Comment by wetneb** [comment]
This will be released in 3.6. The syntax to use in the Wikibase manifest is documented here:
https://docs.openrefine.org/next/manual/wikibase/configuration#tag

**Comment by anchardo** [comment]
Hi,

I was not able to edit/add data to my Wikibase instance with OpenRefine 3.5.2 & Manifest 1.0 and got this error message:
09:54:05.293 [..ting.EditBatchProcessor] MediaWiki error while editing [badtags]: The tag "openrefine-3.5" is not allowed to be manually applied. (324ms)

So, reading this issue, I've installed OR 3.6.2 and adapted my manifest to use the 2.0 template, but I still face the same issue:
12:00:07.260 [..ting.EditBatchProcessor] MediaWiki error while editing [badtags]: The tag "openrefine-3.6" is not allowed to be manually applied. (161ms)

What can I do to solve this problem? I was logged in with a "normal" account and not a bot, could this have an impact?

(For your information I will be on vacation from tonight so I will not be able to answer/make new tests before the end of July)

**Comment by ostephens** [comment]
As far as I know on Wikidata you would have to use a bot account (see https://docs.openrefine.org/manual/wikibase/overview#manage-wikidata-account) but I don't know if that would apply to all Wikibases or if it's just a Wikidata requirement

**Comment by wetneb** [comment]
I would say:
* either you have not created an `openrefine-3.6` tag on your Wikibase instance
* or when creating it you did not specify that it could be applied manually when making edits

**Comment by regisrob** [comment]
I tried to add new items from OpenRefine and faced exactly the same issue as @Nikerabbit (`MediaWiki error while editing [badtags]: The tag "openrefine-3.6" is not allowed to be manually applied`). 
I am using OpenRefine 3.6-rc1. 
I was not able to populate the Wikibase schema using OpenRefine 3.5 due to several errors (@wetneb I could file a separate issue for that).

I agree with the remark about the lack of documentation. It took me a little while to figure out what the term "tag" refers to and how to add a new one in Mediawiki. Further explanation in the doc would be very helpful (especially in the [Requirements](https://docs.openrefine.org/manual/wikibase/configuration#requirements) section). It seems a bit weird to have to create a tag in Mediawiki for every version of OpenRefine (as Wikidata did: https://www.wikidata.org/wiki/Special:Tags)).

The documentation does not say whether the [tag property](https://docs.openrefine.org/next/manual/wikibase/configuration#tag) in the Manifest is required or not. But it seems to be the case since my problem was solved after adding the "tag" in my Manifest (and create it in Mediawiki of course).

One last thing: I do not get the point of the Gif screenshot in [Check the format of the manifest](https://docs.openrefine.org/manual/wikibase/configuration#check-the-format-of-the-manifest
) section in the docs.

**Comment by wetneb** [comment]
Hi @regisrob, thanks a lot for this precious feedback!
Because this issue is already closed, your comment is unlikely to be acted on: it would be great if you could create an issue explaining why the current documentation is problematic (basically your last three paragraphs).

Of course if you feel like it you could even propose a pull request which edits the docs: at the bottom of each documentation page there is a link which should help you do that in very little effort. No need to open an issue beforehand.

**Comment by regisrob** [comment]
Thx @wetneb, I could create an issue to report the problem I faced with OpenRefine 3.5 (if still relevant) and will do my best to propose a PR to edit the docs, at least a first draft 😉

**Comment by D063520** [comment]
Hi,

I'm running the latest version of wikibase-release-pipeline [wmde10.env](https://github.com/wmde/wikibase-release-pipeline/blob/main/versions/wmde10.env), the latest version of the [openrefine-reconciliation service]( https://gitlab.com/nfdi4culture/ta1-data-enrichment/openrefine-wikibase) and the latest version of Open Refine and I got this issue. I had to create the tag and then it worked. Is this expected?

**Comment by anchardo** [comment]
Almost exactly 2 years later, I've switched to a new version of OpenRefine and I'm back to the same problem [the tag is not allowed to be manually applied...] and the same difficulty in finding documentation for that. 

So, I'm writing it clearly here, if you encounter the same difficulty: you need to modify this page: https://[your.wikibase]/wiki/Special:Tags
Like this: 

![image](https://github.com/OpenRefine/OpenRefine/assets/16308046/4fefee34-6bfc-4adf-b20e-9748b3b0feb9)

**Comment by wetneb** [comment]
This should be the last time you have to do this as from 3.9 on it will make untagged edits if the tag does not exist.
