### ISSUE TITLE
Normalize casing in UI text in English

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3363]
We do not use a consistent casing throughout the UI.
For instance, in the "Export" menu:
* "Custom **t**abular **e**xporter" versus "SQL **E**xporter"

In the "SQL Exporter" dialog:
* "Output **e**mpty **row** (i.e. all cells null)" vs "Trim **C**olumn **N**ames"

### Expected Behavior

We should consistently use lowercase since that is what is used in most places so far.

### To solve this issue

Simply go through the existing translation files (in English) and normalize the phrases with incorrect casing.

**Comment by allanaaa** [comment]
![sql](https://user-images.githubusercontent.com/28012148/100376553-b839b680-2fdd-11eb-8ca5-8e8d0afe92e8.PNG)

Thanks for this. Just want to mention an example: "Drop Statement" should become "DROP statement"

**Comment by swkasica** [comment]
This seems like a good issue to tackle as I get familiar with the UI code. I could probably resolve it sometime this week.

**Comment by thadguidry** [comment]
Great Steve! Go for it! Appreciate all the help we can get on our issues and roadmap!

**Comment by leoshrey** [comment]
I would like to tackle it, if @swkasica not proceeding...

**Comment by swkasica** [comment]
@leoshrey I am proceeding.

**Comment by leoshrey** [comment]
Sure thing, please go ahead.

**Comment by swkasica** [comment]
**Quick update**: I'm about halfway through. End of term stuff took longer than I anticipated. Grammar is kind of tricky in UI because in addition to the normal rules of grammar and usage, there's UX specific conventions. I'm adapting [these guidelines from Firefox UX](https://design.firefox.com/photon/copy/capitalization.html) on when to use different capitalization styles: title case, sentence, case, all caps, lowercase, camel case, etc...

**Comment by SmritiSharmaBG** [comment]
Hello, I am new to Open Source. I want to know if this bug is fixed? If it is fixed and merged then why is it still showing up in Issues section? If not, then can I start to work on it? Any help/feedback will be appreciated. Thankyou :)

**Comment by wetneb** [comment]
We should ask @swkasica first, to see if he is still working on this.

**Comment by swkasica** [comment]
Hi all, 

Sorry I haven't had time to work on this issue this month. Academic stuff has consumed all my time. To boot, my computer died a week ago and I don't have a way of running OpenRefine 😢. But I will have more free time by February 4th (and hopefully a real computer too 🤞).

@SmritiSharmaBG, please feel free to work on this issue but keep me in the loop because I have done a bit of work addressing this issue. I think it requires a bit more thought than just changing the specific examples pointed out in this thread. OpenRefine currently doesn't have a set of guidelines on capitalization. So I was creating some based on the guidelines from the Firefox UX, and implementing these rules throughout the entire interface in English. These fixed the issues mentioned above, but also other areas of the interface where casing isn't consistent.

**Comment by pvcodes** [comment]
Hi @wetneb, Is anyone working on this issue right now?

**Comment by wetneb** [comment]
@pvcodes what is your guess, based on the discussion above and the assignee of this issue?

**Comment by pvcodes** [comment]
Yeah! I think @SmritiSharmaBG on it.

**Comment by wetneb** [comment]
I am clearing assignees to signal that this issue could be worked on.

**Comment by pvcodes** [comment]
@weblate Now it think it is open?

**Comment by wetneb** [comment]
@pvcodes it's all yours!

**Comment by pvcodes** [comment]
@wetneb So basically, I have to change the all casing to lower case for example: in SQL Exported there is  a checkbox of `Include 'IF EXISTS' in DROP statement` I have to change it to `Include 'if exists' in drop statement`
Also could you please tell me where these statements are present, i.e., in which file or folder

**Comment by ostephens** [comment]
@pvcodes I think you've picked an example there that should not be changed. "IF EXISTS" and  "DROP" are deliberately capitalised in that case because this is the usual way of writing these statements in SQL.

This is a case of checking each individual situation and making a decision - there is no single rule that can be applied across the board. The initial examples given by @wetneb are good and changes like this should be made:

```
SQL Exporter -> SQL exporter
Trim Column Names -> Trim column names
```
@swkasica also mentioned the Firefox guidelines https://design.firefox.com/photon/copy/capitalization.html which may help guide the work.

I think the general rule you can work to is "lowercase should be used except where there is a good reason for capitalisation"  which is what the Firefox guidelines describe as "Sentence case". Good reasons to capitalise could include: 

- Start of sentence
- Real names
- Code conventions

**Comment by pvcodes** [comment]
Have a look [file](https://github.com/pvcodes/OpenRefine/blob/pvcodes/main/webapp/modules/core/langs/translation-en.json)

**Comment by wetneb** [comment]
it's much easier to discuss your changes if you open a pull request for them, actually :)

**Comment by pvcodes** [comment]
Fair enough

**Comment by ostephens** [comment]
No problem

**Comment by pvcodes** [comment]
Sorry for the delay! I was an unwanted and unexpected one, I was tested positive and yesterday I'm fully recovered. Now things are coming back on track.

**Comment by pvcodes** [comment]
Hi, @wetneb

**Comment by wetneb** [comment]
Hello @pvcodes, how are you doing today? Nice weather, isn't it?

**Comment by pvcodes** [comment]
NVM, 😁 I was asking about the commit should I do PR

**Comment by wetneb** [comment]
Please do!

**Comment by riteshsoni123** [comment]
@wetneb I would like to work on this issue. Can you assign it to me??

**Comment by riteshsoni123** [comment]
@wetneb I have a doubt. The changes made by pvcodes-zz is not merged . Is it better to make all the changes as he did and add some more changes of mine or do you want me to start from the beginning??

**Comment by wetneb** [comment]
@riteshsoni123 as you prefer! It could make sense to start from https://github.com/OpenRefine/OpenRefine/pull/3976 since I have already reviewed that: you should only have to address the review comments there.
