### ISSUE TITLE
Clarify options on the SQL exporter dialog

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3364]
The options "Include Schema" and "Include Contents" in the SQL exporter dialog can be a bit mysterious for users.

### Proposed solution

Just like concrete SQL commands are included in the UI text elsewhere in the dialog ("DROP"), we could expand these phrases to mention the corresponding SQL commands ("CREATE TABLE", "INSERT").

### Alternatives considered

We could also drop the mentions of the commands elsewhere, but I think they are useful (and clear for users who know SQL).

**Comment by Armaxxx** [comment]
Do you have an example on where can I add the UI text, and how UI text is added in the other commands? 
Thanks in advance.

**Comment by wetneb** [comment]
@Armaxxx To locate where to do your code changes, you could try this method: https://github.com/OpenRefine/OpenRefine/issues/3137#issuecomment-691649962

**Comment by Armaxxx** [comment]
#3385

**Comment by Armaxxx** [comment]
Can someone help me, why was my PR rejected when all I did was change some text

**Comment by thadguidry** [comment]
@Armaxxx bear with us as we just migrated to GitHub Actions instead of Travis and so our CI (continuous integration) is not quite ideal yet.  There was an error when submitting to Coveralls.  But rest assured @wetneb will review your changes and then we'll merge this in.  Thanks for your patience and enjoy your weekend!
