### ISSUE TITLE
Having UX tests running on Firefox

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3367]
Tests are broken on Firefox
Basically the browser get stuck and the requests are not even hitting OpenRefine.

### Proposed solution

In case backend API calls are causing the bug : Move them to a Cypress plugin, so node will take care of the API calls, and not the browser itself

Try with Firefox developer edition

### Alternatives considered

Escalate to Cypress support

### Additional context

Problem has been detected on Travis and local (Macos)
Firefox support is relatively new for Cypress

**Comment by tfmorris** [comment]
Should we even bother testing Firefox? The last figures I saw its popularity at well under 5% -- and declining. That's for the general internet though. Do we have different numbers for OpenRefine users?

**Comment by thadguidry** [comment]
I use Firefox. Exclusively because of Servo and [Quantum](https://wiki.mozilla.org/Quantum) initiatives that continually get rolled into improving Firefox.  But a lot of that development has slowed down because of [those big layoffs last year from Mozilla](https://arstechnica.com/information-technology/2020/08/firefox-maker-mozilla-lays-off-250-workers-says-covid-19-lowered-revenue/)
