### ISSUE TITLE
Add UX tests for the create project preview

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3429]
![Screen Shot 2020-12-16 at 14 36 13](https://user-images.githubusercontent.com/6267288/102356130-1c341700-3fad-11eb-9cc7-3b2e3b576e78.png)

#### Start over behavior

Add a test to start over a project creation.
Just ensure the user is redirected to the previous page.

#### Rename the project add tags

Rename the project and add tags.   
Ensure those modifications are persisted (when visiting the project list page ? or is there a better way to do it ?)

#### Navigation

Ensure that once a project reaches the preview step, a user can navigate back&forth to other screens of OpenRefine (language for example)

#### Parsing Options

Does it make sense to test each and every parsing option? It looks like a backend matter.
Looking at the requests, they are similar, whatever the option is (importing-controller, get-models, get-rows)

To start, we could have an MVP test that would

* load a CSV
* change a few parsing options, and ensure the grid reflect those changes

This simple test could be duplicated with JSON data to have better coverage.

**Comment by thadguidry** [comment]
For Prevew, to start with, I'd like to see 2 tests minimally:
* CSV
* JSON
 
Then @kushthedude or community can add in the 4 others often used like:
* EXCEL
* LINE
* XML files
* Open Document Format spreadsheets (.ods)

**Comment by tfmorris** [comment]
Any particular reasoning behind the choice of those two formats? I'd have thought JSON would be waaay down the popularity list (but perhaps representative of tree formats).

**Comment by thadguidry** [comment]
@tfmorris Yes, so that we have testing previews in place to support Records testing with hierarchical data.  That way other community members can help and see how its done since @fgiroud would provide those minimal examples.  The idea was that @fgiroud would only do a few and the community could then look at how things are done and work on the others.  Well, that was the thought we had on our meeting the other day (the Florian, Kush, myself...Antonin couldn't make it).
