### ISSUE TITLE
XML and JSON importers and using "Store file source" doesn't make a column

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#3462]
### To Reproduce
1. Create new project from a file or URL  (either JSON or XML)
2. Choose JSON or XML as appropriate for file.
3. Then make any record row selection from an element in the JSON or XML with a mouse selection
4. Click on **Store file source** check box
5. Notice the preview refresh

### Current Results
Preview refreshes but doesn't add the extra column **File** as it does if you simply select another importer like Line based or CSV.

### Expected Behavior
**File** column should be created when clicking **Store file source** checkbox option on importers

### Versions
 - Operating System: Windows 10
 - Browser Version: Firefox latest
 - JRE or JDK Version: JDK8
 - OpenRefine: 3.5-beta [8eabec1] (master)

### Datasets
https://github.com/PerseusDL/treebank_data/raw/master/v2.1/Greek/texts/tlg0012.tlg001.perseus-grc1.tb.xml

**Comment by Warpeas** [comment]
@wetneb Our study group would like to solve this issue and would like to get some advice. Thank you!

SE_SUSTech

**Comment by wetneb** [comment]
Hi @Warpeas, great! Can you tell me more precisely what you need advice about?

**Comment by Warpeas** [comment]
We are investigating how this bug happens, but we have trouble understanding how the import task process. As the (documentation)[https://github.com/OpenRefine/OpenRefine/wiki/Importing-Architecture#server-side-components] for the server-side components are not available. It will be great if you have time to give us a brief introduction to this part.

**Comment by wetneb** [comment]
Sure! The importers in question here are:
* `com.google.refine.importers.JsonImporter`
* `com.google.refine.importers.XmlImporter`
Both of them extend `com.google.refine.importers.tree.TreeImportingParserBase` and that is probably the class where this feature needs to be implemented / fixed. This is a fairly complicated part of the backend because this is where the conversion from hierarchical data formats (JSON, XML) to a table using records is happening. That being said, you should not need to understand all the details of this algorithm to fix this issue: it should be enough to ensure that the file source is passed down to where rows are generated.

I hope that answers the question - if not feel free to point me to a more precise problem.

**Comment by Warpeas** [comment]
Great thanks! We will dive into them and try to fix the bug.
