### ISSUE TITLE
Common transforms for columns should contain `to boolean`

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#3518]
There are a variety of options to cast a column into text, number or date. But there is no common cast option to change a column to a boolean type.
### Proposed solution

Common transforms for columns should contain `to boolean`
### Alternatives considered

None
### Additional context

Why wasn't this implemented, or are there concerns on this option?

<img width="808" alt="Screenshot 2021-01-26 at 12 07 51 AM" src="https://user-images.githubusercontent.com/44091822/105750283-92dc1100-5f6a-11eb-8a23-1578b82208de.png">

**Comment by wetneb** [comment]
I think it could make sense to have this, for consistency. Of course it is likely to be language-specific, but so are the date parsing functions.

**Comment by singhakshita** [comment]
can i work on this ?

**Comment by kushthedude** [comment]
Sure, please go ahead

**Comment by singhakshita** [comment]
we  also get an option to change data type  to boolean through "edit" option in each cell  which shows false for every other data except for only "true"  ,according to me it should also consider 0,1,null as some deciding factor .just wanted to know your opinion on this . 
should 'to boolean " convert any string to false as it doing now ?

**Comment by wetneb** [comment]
I would probably keep things simple: keep the current behaviour of the "edit" dialog for a single cell, and use the same behaviour for the common transform you will introduce.

We can of course add support for other values but as soon as we start doing this, we run into the problem that the list is never going to be exhaustive. @thadguidry @ostephens do you have opinions about this?

That being said, it could be worth thinking about the handling of `null`. Arguably `null` should not be transformed to `false` but to `null` itself.

**Comment by thadguidry** [comment]
@wetneb are you talking about the String value `null` or [null terminator](https://en.wikipedia.org/wiki/Null_character) (C0 \u0000)?

No matter, String value `null` or null terminator should be allowed to be transformed by a user with GREL, I would say.  The problem we will have is sometimes around the null terminator codes or byte representations (but 2 pass data type transforms are usually how they are handled in other programming languages)

Literal String values of:
- `null`
- `NUL`
- `\u0000`
- `\0`

Byte values of:
- Char(0)

are the most common typically seen in raw data output that might be loaded into OpenRefine.  And I think users already can transform them all with GREL.  In fact, we should probably have tests to ensure they actually can.

**Comment by tfmorris** [comment]
I actually think we've got too many of this special transformations already -- at least for system without customizable menus.

If we add this, we'll need better specification of how it should work. I'm not sure if we need to take into account natural language (ie not English), but we probably DO want to handle various other language (Python, Javascript, SQL) versions of "truthiness" so decide whether we think "", []. "T", "True", etc are truthy or not.

**Comment by ostephens** [comment]
At the moment I'm unclear on the purpose of the transformation. Is it to make it easy to interpret string values as meaning "true" or "false" in a boolean sense (e.g. wherever there is a string "true" convert this to boolean `true` and wherever there is a string "false" convert to boolean `false`), or is it to treat values as true or false in a more programmatic sense. I think we have to be clear which we are doing before we actually implement something.

I can see that @singhakshita has done some work on this already, building it into the menu with the transformations defined using `doTextTransform`, and has included different interpretations based on Python, Javascript and SQL treatments of "truthiness" as mentioned by @tfmorris 

While I appreciate the time @singhakshita has already put in, I'm a little concerned that the approach we have at the moment is a little limited and will be confusing for the user (I definitely don't know how Javascript, Python and SQL differ in their treatment of truthiness, and I don't think it's reasonable to expect that OpenRefine users in general will know).

I think we need more work to define what behaviour we are looking for rather than just the absence of a function in our menus. At the moment I don't have a clear idea of what that behaviour should be.

**Comment by singhakshita** [comment]
Instead if giving options of language(javascript ,sql , python etc ) should we  give user an option of choosing amongst the list of( null , 0,1 " " , none ,[] etc)  what values do they want to be treated  as false and true ?

**Comment by thadguidry** [comment]
@ostephens @tfmorris I agree there would need to be decisions on the options presented to the user on if `null` would be handled as `true` or `false` as Apache BooleanUtils and others treat "truthiness".  `toBooleanDefaultIfNull` comes to mind for perhaps handling that and presenting to the user a choice to make on what to do if the `valueIfNull`.  Beyond that, we would need to take a stand on Integer to Boolean convention, and where we could make a smart default of `true` is 1 and `false` is 0.  Because, I don't think we really need to support a custom conversion option (they could always use Facets to mass edit some values) for what represents "truthiness" [like BooleanUtils has](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/BooleanUtils.html#toBoolean-int-int-int-).  As far as the smart defaults (and unboxing needed) we might just use what Apache BooleanUtils supports https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/BooleanUtils.html#toBoolean-java.lang.String-
- 'true', 'on', 'y', 't', 'yes' or '1' (case insensitive) will return true.
- 'false', 'off', 'n', 'f', 'no' or '0' (case insensitive) will return false.
- Otherwise, null is returned.

It seems there's some optimization for performance by interning 'true' as well, if we care one way or another.
https://commons.apache.org/proper/commons-lang/apidocs/src-html/org/apache/commons/lang3/BooleanUtils.html#line.569

**Comment by ostephens** [comment]
@thadguidry if we are going in this direction I'd be inclined to be a bit more flexible (as per the BooleanUtils). I'd suggest a GREL function which supports the following from the BooleanUtils:

toBoolean(int)
toBoolean(int, int trueValue, int falseValue)
toBoolean(string)
toBoolean(string, string trueValue, string falseValue)

This would mean that `value.toBoolean()` would behave pretty much as you describe above, but there would be flexibility where required.

I'm still not entirely sure that we need a 'toBoolean' function, but if we do then the cost of implementing this slightly more flexibly is low IMO. I'm happier with the approach of creating a new GREL function than I am in just wrapping a load of logic in a menu item for convenience. Once the GREL exists then it can be wrapped as a menu item if that is useful.

However, I'm still unclear of the exact use case for this. Can someone describe a situation where the user would need to use the "toBoolean" function? This would definitely help be more confident that whatever we implement here is meeting a real world need.

**Comment by thadguidry** [comment]
@ostephens Agree on all points.  No one has upvoted on this issue including me, as I don't think this is a priority need for our users.  They get by with Facets and `replace()` for getting consistency with boolean strings, and then go from there.  I was simply laying out some advice on where I thought usefulness could be had and indeed a function before a UX dialog.

I'd advise to mark this issue as low priority as a new GREL function proposition and then move on to other issues where the community [has upvoted](https://github.com/OpenRefine/OpenRefine/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) and voiced their needs ([survey results](https://openrefine.org/blog/2020/02/20/2020-survey-results.html))

**Comment by tfmorris** [comment]
I think it's low priority too and don't find implementing things for "completeness" to be particularly compelling if there's not an actual need/use for them. Having said that @wetneb _**was**_ persuaded by the completeness argument when he triaged the issue, although he seemed to envision support for multiple (human) languages.

@singhakshita We apologize for wasting your time on this. It may take us a little while to reach consensus on what the specification should look like (and if it's really needed), so you might want to work on something else.

@kushthedude In answer to @ostephens question about use, do you see a specific use for this or were you mainly concerned with equal coverage for all the data types?

If someone feels strongly that we need a `toBoolean()` function, please write up a draft spec for it. In addition to strings and numbers, behavior for dates, booleans, and arrays of all types should be specified.

@wetneb would you like to weigh in on what you envisioned for this functionality?

**Comment by wetneb** [comment]
My interest in this is lukewarm too, I agree with @ostephens and @tfmorris. The fact that these menus are already pretty cluttered is a good point. I propose we close this as "won't fix".

**Comment by kushthedude** [comment]
> do you see a specific use for this or were you mainly concerned with equal coverage for all the data types?

I was just concerned for equal coverage as while writing tests for boolean transform either I had to edit each cell or had to use a GREL function whereas for other types we had a common transform. However, seeing the above discussion I think it's better we close the issue.
