### ISSUE TITLE
Enforce ES-Lint rules for cypress-test-suite 

### ISSUE THREAD

**Issue by kushthedude** [OpenRefine/OpenRefine#3536]
Hi, I think as we are progressing with tests we need some kind of rules and standard notations to prevent us from writing bad code.
### Proposed solution

ES-Lint is pluggable and configurable linter tool for identifying and reporting on standard coding patterns in JavaScript. Cypress team has also created an ESLint extension for standard cypress rules https://github.com/cypress-io/eslint-plugin-cypress. I suggest incorporating ESLint for our cypress-test-suite
### Alternatives considered

Prettier but it only formats and beautifies code rather than actually complaining about coding patterns.

**Comment by kushthedude** [comment]
@wetneb @fgiroud How does this sound?

**Comment by tfmorris** [comment]
There's JSHint too, but I think ESLint is the best choice.

I know @wetneb said he was happy to use different setups for testing and application code, but I have a strong preference for a single set of tools and standards for all of the project's Javascript code, so I'd like to see adopt ESLint project wide.

**Comment by fgiroud** [comment]
I am good with ESLint
@tfmorris the thing is that OpenRefine code and Cypress tests does not use the same Javascript version.
OpenRefine is coded using plain old javascript, whereas tests are using ECMA script 2015, so it might create issues if we try to have  ESLint project wide.
Basically OpenRefine code will triggers millions of warning and errors, because it's pretty outdated syntax, we would need to disable so many rules, making the use of ESLint pointless
