### ISSUE TITLE
Add UX Test for column / Edit cells / Transform & Replace

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3554]
This issue is following the work implemented for issue #3423 in PR 3541

Two tests are still left to implement

- Transform
- Replace

![Screen Shot 2021-02-02 at 09 27 00](https://user-images.githubusercontent.com/6267288/106572718-154f6c80-6539-11eb-9e8b-84d7eda344b2.png)

**Comment by sardug10** [comment]
Hey, I am new to open source contributions. I want to work on this issue. Can you guide me?

**Comment by AhwiniMirajkar** [comment]
I want to work on this

**Comment by fgiroud** [comment]
Hi @sardug10 , thanks for your interest
To get started, you can start by reading those two articles in OpenRefine documentation
* [Contributing to OpenRefine](https://docs.openrefine.org/technical-reference/contributing/)
* [Tests technical reference](https://docs.openrefine.org/technical-reference/functional-tests)

Issue assigned to you !

**Comment by sardug10** [comment]
> Hi @sardug10 , thanks for your interest
> To get started, you can start by reading those two articles in OpenRefine documentation
> * [Contributing to OpenRefine](https://docs.openrefine.org/technical-reference/contributing/)
> * [Tests technical reference](https://docs.openrefine.org/technical-reference/functional-tests)
> 
> Issue assigned to you!

Hey, I have read these articles and have learnt about Cypress through their documentation and some of the videos.  What should be my next steps?

**Comment by fgiroud** [comment]
Hello, you can follow the [getting started guide](https://docs.openrefine.org/technical-reference/functional-tests/), that will guide you to write your first test
You next step would be to add test scenarios for what is described in this issue

**Comment by sardug10** [comment]
Hello, a quick question. The test scenarios that I have to add are of client-side and I have to write them in JavaScript and to do this I need to install OpenRefine on my local machine which requires JDK? I am asking this because I am just confused about where should I start?

**Comment by fgiroud** [comment]
Yes, on the step2 of the getting started guide, notice the step to start OpenRefine `./refine`, this will start the software
From there, you can run existing tests, and add new ones, in the src/tests/cypress directory

**Comment by sardug10** [comment]
Hey, I need some help solving this error.
![Screenshot 2021-02-21 134442](https://user-images.githubusercontent.com/52778617/108619451-f4e54480-744a-11eb-82e6-8cd40c4b89d5.jpeg)
`
error could not find or load main class com.google.refine.refine
Caused by: java.lang.ClassNotFoundException: com.google.refine.Refine
`

**Comment by wetneb** [comment]
I would try `refine.bat clean`

**Comment by haarsh01** [comment]
Hey, I am new and a beginner in open source contributions.I want to work on this issue. Can you guide me the steps ?

**Comment by fgiroud** [comment]
Hi @haarsh01, looks like this issue is already attributed, you can ping in another one maybe
@sardug10 are you actively working on it ?

To get started, you can start by reading those two articles in OpenRefine documentation
* [Contributing to OpenRefine](https://docs.openrefine.org/technical-reference/contributing/)
* [Tests technical reference](https://docs.openrefine.org/technical-reference/functional-tests)

**Comment by haarsh01** [comment]
okay no problem

**Comment by riteshsoni123** [comment]
can I work on this issue?

**Comment by fgiroud** [comment]
Sure @riteshsoni123 
Thx a lot

**Comment by riteshsoni123** [comment]
Hello @fgiroud, I am facing one problem in implementing test for "Transform". I used this method to write the command for transform   "  cy.get('.dialog-container textarea[bind="expressionPreviewTextarea"]').type('value.replace("change","a")');  "   ,but I am getting this "Internal error" on the right as shown in the image below.

![Screenshot (76)](https://user-images.githubusercontent.com/26280032/136018345-a44f8ee4-b746-4501-be9a-a007f0a33aad.png)


Can you please help me with this?

**Comment by thadguidry** [comment]
@riteshsoni123 It's because `replace()` requires 3 parameters.  You have tried to inline inject the first parameter `String value` but it's not available for some unknown reason,  You might first try `value.type()` to see if the type is reported correctly as `String` and gosh I hope so.  Maybe you compiled/built OpenRefine yourself and missed something somewhere?

Regardless, we should really improve that error description, but whenever you see a red error like that...you can check the OpenRefine log console for more details as a hint to what might have happened with GREL syntax.

The simple quick fix workaround would be to do something like this:
`"test this change".replace("change","a")`
which should result in output like:
`"test this a"`

(or figure out what's going on with your OpenRefine build)

`value` is a placeholder for the cell's value or more formally `cells["someColumnName"].value`
Our documentation on [GREL expressions ](https://docs.openrefine.org/manual/expressions) has really good details on all that.

**Comment by riteshsoni123** [comment]
One more thing I would like to add is that this "Internal error" is only shown when I am trying to test it through cypress. When I normally run Openrefine and perform transform task everything works fine. When it comes to cypress testing no matter whatever expression I type it shows this error. I still have no clue what to do.

**Comment by riteshsoni123** [comment]
Yes sure. I just did.

**Comment by fgiroud** [comment]
Hi, interesting issue
because your "type" is the latest statement of the test, cypress doesn't really record the very last state of the UI, instead the screenshot is when you typed `cy.get('.dialog-container textarea[bind="expressionPreviewTextarea"]').type('value.replace("change","a"` (missing last parenthesis)

I am sure that if add a few lines of codes or assertions after that, it will be fine

**Comment by riteshsoni123** [comment]
Thanks @fgiroud for clearing the doubt. It helped a lot. I have updated the PR.
