### ISSUE TITLE
OpenRefine does not send an "Origin" header in reconciliation

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3599]
Mentioned by @gitonthescene in https://github.com/reconciliation-api/specs/issues/64#issuecomment-774872779:

> Also my local service isn’t receiving the `Origin` header from OpenRefine.  That’s not a problem but it makes it tougher to calculate the `Access-Control-Allow-Origin` header.

I assume this must apply to requests made by the backend (such as reconciliation queries) rather than those made by the browser (such as accessing the service manifest) since I would expect web browsers to add all the necessary headers themselves.

@gitonthescene do you have more details to share about which requests are missing this header (and pointers to docs explaining why it is necessary)?

**Comment by gitonthescene** [comment]
Hi, I'm not 100% sure what you're asking so please let me know if I've over/under explained.  The technical part is that with this diff to [the demo server](https://github.com/mikejs/reconcile-demo)

``` python
--- a/reconcile.py
+++ b/reconcile.py
@@ -7,7 +7,7 @@ import re
 
 from flask import Flask, request, jsonify, json
 app = Flask(__name__)
-
+app.config['SERVER_NAME'] = "127.0.0.1:5050"
 # Basic service metadata. There are a number of other documented options
 # but this is all we need for a simple service.
 metadata = {
@@ -41,7 +41,7 @@ def search(query):
     pattern = re.compile(query, re.IGNORECASE)
     matches = []
 
-    for (id, name) in zip(xrange(0, len(presidents)), presidents):
+    for (id, name) in zip(range(0, len(presidents)), presidents):
         if pattern.search(name):
             # If the name matches the query exactly then it's a
             # (near-)certain match, otherwise it could be ambiguous.
@@ -79,6 +79,8 @@ def jsonpify(obj):
 @app.route("/reconcile", methods=['POST', 'GET'])
 def reconcile():
     # If a single 'query' is provided do a straightforward search.
+    from pprint import pprint as pp
+    pp( request.headers )
     query = request.form.get('query')
     if query:
         # If the 'query' param starts with a "{" then it is a JSON object

```
I get this output when I connect with OpenRefine and try to reconcile some colummn:

``` sh
$ python reconcile.py
 * Serving Flask app "reconcile" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:5050/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 331-654-570
EnvironHeaders([('Content-Length', '122'), ('Content-Type', 'application/x-www-form-urlencoded; charset=UTF-8'), ('Host', '127.0.0.1:5050'), ('Connection', 'Keep-Alive'), ('User-Agent', 'OpenRefine/3.4.1 [437dc4d]'), ('Accept-Encoding', 'gzip,deflate')])
127.0.0.1 - - [09/Feb/2021 14:55:26] "POST /reconcile HTTP/1.1" 200 -
$
```

You can see that there is no `Origin` header [1].  Usually for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) you receive an `Origin` header indicating where the client is sending the request from and the server sends back an `Access-Control-Allow-Origin` header indicating which hosts are safe to use the results.  This service need not use the received header to construct the return header but it may as well.  I believe this processing general takes place during a preflight `OPTIONS` request.  I think the client then rejects responses where the `Access-Control-Allow-Origin` doesn't match the client.  (I should probably think through more carefully exactly what security risk is avoiding...)

In any event, for my purposes I was just wondering which `Origin` I should send back.  Not knowing which would be accepted, I'm left to do the most permissive `"*"`.

I think CORS is meant to prevent certain "man-in-the-middle" attacks which aren't an issue when you're talking to the local host.  This is why browsers don't require CORS for requests to localhost.  In other words, this header isn't necessary when dealing with localhost.  I haven't experimented sniffing headers with a remote reconciliation service, so I'm not sure if the `Origin` header is sent in that case.

Please let me know if anything is unclear. 

Regards

[1]  There is a `Host` header, but CORS is more about securing the use of remote services.  Not navigating from the browser directly, but having calls triggered by an action where the user doesn't see which URL has been accessed.  I think this is why you forward an `Origin` header.

**Comment by gitonthescene** [comment]
I think this can probably be closed.  Using [flask-cors](https://flask-cors.readthedocs.io/en/latest/) just works(TM) so perhaps I was checking the headers from the wrong request.  This just surprised me from the last time I had to manually implement CORS support.  I’ll try to have a closer look to understand how it’s working and post back.

**Comment by tfmorris** [comment]
OK. Feel free to reopen or create a new issue if you find a problem with it.

**Comment by gitonthescene** [comment]
FWIW, I checked again and it looks like the Origin header is being sent, but only when requesting the service manifest.  I'm functional at the moment, but it does seem curious to me.  I'm clearly not an expert, but this might need a review.  See #3672 for some inconsistency in how CORS/JSONP is being used currently.

**Comment by wetneb** [comment]
Fetching the manifest is done in the frontend (so, by your web browser), sending reconciliation queries is done by the backend (so, in Java).

It is not clear to me what `Origin:` header requests made by the backend should have.

**Comment by gitonthescene** [comment]
As I said, I’m not an expert here, but after doing [some reading](https://mobilejazz.com/blog/which-security-risks-do-cors-imply/) my understanding is that CORS exists to prevent people from running scripts inadvertently loaded with a given page
and manipulating how other scripts on that page work, potentially to transfer sensitive information elsewhere.

That is to say, scripts run in a browser do unwanted things.  The “single origin policy” implemented in the browser prevents the browser from allowing scripts to interact with sites other than the site hosting the page because that interaction is likely not expected from the site unless explicitly relaxed through mechanisms such as CORS.

The critical point, I think is that this is a browser policy that’s needed because the browser is general purpose in that it can load source scripts from anywhere a page tells it to.

I don’t think server to server communication suffers from the same type of exploits.  Servers should be careful about what they do with their input but it’s not as free form as scripts loaded in a browser.

The upshot is that CORS is not needed for server to server communication.

This is as best as I can gather.  I’d be happy to learn more if you have a better understanding of this.

It’s highly unlikely that these reconciliation services have anything sensitive to exploit but the browser policy must be addressed anyway for browser communication.

Sorry if my post muddied the waters, but the OpenRefine setup has more moving parts than the typical CRUD app so I hadn’t needed to wrap my head around CORS in such detail before.

Regards
