### ISSUE TITLE
LGTM build is broken

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3652]
The LGTM service seems to be running tests when it attempts to check our pull requests, but the database extension tests fail because the corresponding databases are unavailable.
We should fix this: it is not clear to me why we would need to run any tests on LGTM.

Example build:
https://lgtm.com/projects/g/OpenRefine/OpenRefine/logs/rev/pr-bbec6ee044d3fb9c1abb9fd4b5b3d13d306cb2be/lang:java/stage:Build%20merge_e3c15fda718be8292d9a43235ee79ed780070d29

**Comment by wetneb** [comment]
I have suspended LGTM in our GitHub project settings while this is broken. This is just to make sure we don't get used to ignoring red marks in PR checks. If anyone wants to work on this I can re-enable it there.
https://github.com/organizations/OpenRefine/settings/installations/9833642

**Comment by tfmorris** [comment]
The wikidata extension fails to build on a clean checkout (e.g. the CI environment) with the command `mvn clean compile`. I was able to work around this by using `mvn clean test-compile`. This is arguably better because LGTM identifies source files to analyze by watching what gets touched during compilation, so our test classes will get analyzed too, but it indicates something weird with the dependency structure. The dependency `openrefine:main:tests` looks like it is required for the `compile` phase, even though being declared with `<scope>test</scope>`

**Comment by wetneb** [comment]
Yes, that is something I have fixed in the new architecture (by having one maven modules for test utilities reused across the project).

**Comment by tfmorris** [comment]
Obviously it goes without saying that it's a waste of resources to be debugging problems which are known and fixed already.
