### ISSUE TITLE
Cypress builds fail in forked repo

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#3677]
I'm getting the following errors from the "Test with Cypress on Chrome" step when Github Actions attempts to run in my fork of OpenRefine:

```
Run echo REFINE_MIN_MEMORY=1400M >> ./refine.ini
Using refine.ini for configuration
You have 6954M of free memory.
Your current configuration is set to use 4096M of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
https://github.com/OpenRefine/OpenRefine/wiki/FAQ-Allocate-More-Memory
fatal: No names found, cannot describe anything.
ERROR: Found a Cypress project id but no record key
Type './refine -h' for usage information.
Error: Process completed with exit code 1.
```

@fgiroud @kushthedude Do you know what's going on here and how I can fix it?

**Comment by kushthedude** [comment]
It won't work on forked repo as the secrets are not available from the original upstream repository

**Comment by fgiroud** [comment]
The issue is that you need a secret in order to run the tests and push the results into the Cypress dashboard.
You could
- add the secret of Cypress into your own fork (since you're admin, that should not be an issue), but your tests records would be pushed into the main Cypress account
- temporarily disable the cypress integration, replace line 142 in github/pull_request.yml by `./refine ui_test ${{ matrix.browser }}`

**Comment by tfmorris** [comment]
Thanks for the quick responses. The build needs to run in forked repos. We have many, MANY forks.

Please fix the build so that it doesn't fail if it doesn't have the secret key. You can do this by checking whether the build is running in the OpenRefine org or by checking for the presence of the secret key itself or any other mechanism that allows are many contributors to run the tests in their forked repo.

You can probably find examples to follow in some of the other CI jobs that have secrets associated with them.
