### ISSUE TITLE
Process of fetching URLs is considerable slower in macOS

### ISSUE THREAD

**Issue by EstebanMH-SiB** [OpenRefine/OpenRefine#3692]
I have been using my MacBookPro (Processor i9, 12 GB RAM alocated to OpenRefine, 150 MG of internet) to fetch URLs, but it is taking an extraordinary ammount of time compared to windows. For example, a dataset of 9.000 records takes almost 15 minutes in macOS but only 2 minutes in a similar computer running Windows.
We run another test with a different script that fetchs information from another API and macOS is still significantly slower.

We have tried with another macs and all have the same problem with the slow process, we should like to report it and know if this is a general problem or maybe is something we can solve in the interntal options.

### To Reproduce
1. Upload the data to OpenRefine 
[CerrejonPublicados.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/6079682/CerrejonPublicados.openrefine.tar.gz)

2. Use the following script, code goes from line 64 to 459: https://github.com/SIB-Colombia/data-quality-open-refine/blob/master/ValTaxonomicAPIGBIF_ValTaxonomicaAPIGBIF.txt 

### Current Results
The results are correct, but it takes almost 10 times more compared to Windows.

### Expected Behavior
We expect that to computers with similar specifications should run the fetching process in almost the same time.

### Versions
 - Operating System: macOS Big Sur 11.2.2 (20D80)
 - Browser Version: Chrome Versin 88.0.4324.150 (Build oficial) (x86_64)
 - JRE or JDK Version: Java version included in the Mac kit
 - OpenRefine: Version 3.4.1 (1)
 
### Datasets
[CerrejonPublicados.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/6079615/CerrejonPublicados.openrefine.tar.gz)

Thanks in advance for your answer,
Esteban SiB Colombia @RicardoOrtizG @camiplata @SiBColombia

**Comment by ostephens** [comment]
I've just tried recreating this.

Using OpenRefine 3.4.1 Linux distribution on my Mac (macOS High Sierra) the operation history completes in around 30 seconds
Using OpenRefine 3.4.1 Mac distribution on the same machine the operation history completes in around 180 seconds

Obviously the absolute speed is going to be affected by the speed of the internet connection available, but this makes the Mac distribution approx 6 times slower than the Linux distribution on the same machine - which is similar to the difference quoted above by @EstebanMH-SiB between his Windows and Mac. 

There's nothing in the console in either case (except an error caused by an attempt to move a non-existent column which reflects an issue with the history, nothing to do with the API fetch)

**Comment by wetneb** [comment]
That's really puzzling! Perhaps due to an old JRE being embedded in the Mac distribution. It's really worth fixing this before 3.5 I would say.

**Comment by tfmorris** [comment]
The bundled JRE is Oracle 1.8.0_181. That would be the only difference between Owen's two test cases, but 3 minutes (180 sec) is a far cry from the reported 15 minutes.

In my testing on a mid-2014 MacBook Pro Retina running Mac OS X Catalina, the script completed in under a minute (~55sec), if I set the delay to 0, so that's what I would recommend doing.

With the provided delay of 5 (msec), OpenRefine 3.4.1 Mac seems to send GETs approximately every 10 seconds. In looking at the packet traces, it appears that the TCP connection is getting torn down and reestablished, probably after some 10 second TCP connection  timeout. In 10 minutes, it had only processed 6% of the entries which extrapolates to 3h45m for a full run (although with caching the times aren't linear).

The current 3.5 development branch runs in 57 seconds with a delay of 5 and 51 seconds with a delay of 0.

Given that this seems to be a JRE specific issue/interaction and there's a workaround, I'm not sure it warrants too much effort.

**Comment by wetneb** [comment]
I will pay attention to upgrading the embedded JRE when doing the 3.5-beta release, hopefully in the coming weeks.

**Comment by wetneb** [comment]
@EstebanMH-SiB have you had a chance to try out the 3.5-beta1 version? I would be interested to know if using an up to date JRE has solved the issue for you.

**Comment by EstebanMH-SiB** [comment]
@wetneb I have just tried and it works! From the original 15 minutes using my mac now it just take 90 seconds using a delay of 5 and roughly the same time for a delay of 0. 
So I think the issues is solved, thanks everyone for helping us with this!

**Comment by wetneb** [comment]
awesome, thank you very much for confirming!

**Comment by TomM2020** [comment]
@ostephens

Sorry to be so late to this discussion but I am experiencing the same problem! I increased my imac to 6gb (of 8) for OpenRefine and am trying to process 1000 records at a time but it's incredibly slow. What I am attempting to do is parsing just the thumbnail urls from IIIF manifest json files - so, fetching the urls and then using value.parseJson()['thumbnail'] as in this link: 

https://programminghistorian.org/en/lessons/fetch-and-parse-data-with-openrefine#example-2-url-queries-and-parsing-json

...But I feel I'm using a sledgehammer to crack a walnut here - I just need to extract the thumbnail urls and that's it! It does work for, say, 100 records at a time, but I'm copying pasting a huge amount of json text into each cell (of which there are over 60,000). Is there a more elegant way of doing this?

Many thanks and best wishes
Tom

**Comment by TomM2020** [comment]
Hi Owen, thank you for your prompt reply! It is just very slow to process 1000 urls. I haven't tried the same action on a Windows machine - I can try next time I'm in the office.

**Comment by wetneb** [comment]
In the meantime, I have improved the packaging process so that the latest JRE gets download at release time automatically. So if what @TomM2020 is experiencing here is indeed due to an old JRE, I would be curious to know if the problem persists with a recent snapshot of the development version, that can be downloaded here: 
https://github.com/OpenRefine/OpenRefine-snapshot-releases

**Comment by TomM2020** [comment]
Dear Owen and Antonin

Many thanks for this - I will post more details and context on the google groups. My version of OpenRefine is 3.2 so I should definitely upgrade. Maybe this is at least part of the problem.

Best wishes
Tom
