### ISSUE TITLE
Can't see projects (but can open them)

### ISSUE THREAD

**Issue by jkjkjkjkjk** [OpenRefine/OpenRefine#3719]
No project is showing in open project dialog box, only overlapping All a and Browse workspace directory buttons (same like https://github.com/OpenRefine/OpenRefine/issues/3277).  I am able to open workspace directory and I am able to open the projects using direct link (http://127.0.0.1:3333/project?project=xxx).

### To Reproduce
I have deleted one project directory from workspace directory. 

### Screenshots
<a href="https://ibb.co/Df8SRJf"><img src="https://i.ibb.co/Df8SRJf/OpRef.jpg" alt="OpRef" border="0"></a>

### Versions
 - Operating System: Windows 7
 - Browser Version: Chrome 89
 - OpenRefine: OpenRefine 3.4.1

**Comment by gitonthescene** [comment]
Did you see [this comment](https://github.com/OpenRefine/OpenRefine/issues/3277#issuecomment-721305890) in the issue you referenced?

Can you try starting with the `-d` pointing to a directory with only ASCII characters to see if that helps?

**Comment by gitonthescene** [comment]
@thadguidry - Do you know where the requirement for ASCII directory names comes from?

**Comment by thadguidry** [comment]
@gitonthescene not sure in the code.  It's a core Java lib.  @tfmorris would know.

**Comment by ToVie** [comment]
@thadguidry You can reproduce the behavior described by @jkjkjkjkjk like this:

### Steps to reproduce the problem
1. Fresh install of openrefine
2. Create first project in standard workspace directory and change some data
3. Create second project in standard workspace directory and change some data
4. Quit OpenRefine
5. Check the  "projectIDs"-array of workspace.json => it contains two valid project ids
6. Restart OpenRefine 
7. Delete both projects  on the UI ("Open project")
8. Quit OpenRefine
9. Check the  "projectIDs"-array of workspace.json => it still contains the id of one of the deleted projects
10. Open OpenRefine => The screen shows only "create project" and "open project"
11. Create a new project and change some data
12. Quit OpenRefine
13. Reopen OpenRefine and the UI still only shows "create project" and "open project"
14. Quit OpenRefine and reopen it => the problem persists as the id of the deleted project remains in workspace.json

### Solution
To resolve the issue I had to remove the invalid project id from the "projectIDs"-array of workspace.json

### Tested with
- macos 10.14.6 with OpenRefine 3.5 beta1 as well as OpenRefine 3.4.1 on Safari 14.1 and Firefox 88
- windows 10 with OpenRefine 3.4.1 (incl Java8-JRE) on Edge.

The PATH to workspace directory contains only ascii characters.

### Expected behaviour
Remove all ids of deleted projects from the "projectIDs"-array of workspace.json

**Comment by jkjkjkjkjk** [comment]
Thanks, removing id of deleted project from workspace.json worked.

**Comment by antoine2711** [comment]
@WaltonG: I think you are right. So I will assign you on the basis you are working on I#1418.

Regards, Antoine
