### ISSUE TITLE
Tests failing on Firefox

### ISSUE THREAD

**Issue by fgiroud** [OpenRefine/OpenRefine#3837]
Following the merge of Firefox tests into master, 4 tests are failing

Please review the run on the Cypress dashboard : https://dashboard.cypress.io/projects/s5du3k/runs/999/overview

**Comment by thadguidry** [comment]
To my eyes, it looks like some selection problem with the DialogPanel for the fields? 
For example, in the `it('Ensures two columns are joined', function () {` ...

`Shrt_Desc` and `NDB_No` are switched around, because if you look at the assert, it's expecting the `NDB_No` to come before the `Shrt_Desc`, not afterwards, but the reverse of that seemed to be selected in the Join DialogPanel for some reason?
If you look at the yellow banner for the UNDO and see the operation itself, it performed this where `Shrt_Desc` was coalesced before `NDB_No`:

![image](https://user-images.githubusercontent.com/986438/115403905-72f76a80-a1b2-11eb-8306-d2744f246a9e.png)

**Comment by thadguidry** [comment]
OK, for some reason `value` is not the right value... I debugged the /support/commands.js and that's where it seems the problem begins... 
https://github.com/OpenRefine/OpenRefine/blob/master/main/tests/cypress/cypress/support/commands.js#L154

It's as if `value` didn't get overwritten from the previous test's assertion value.
The test `Ensures two columns are joined respecting the column ordering`
https://github.com/OpenRefine/OpenRefine/blob/master/main/tests/cypress/cypress/integration/project/grid/column/edit-column/join_columns.spec.js#L12

is still hanging on to the assert value
from test `Ensures two columns are joined'
https://github.com/OpenRefine/OpenRefine/blob/master/main/tests/cypress/cypress/integration/project/grid/column/edit-column/join_columns.spec.js#L26

**Comment by fgiroud** [comment]
@thadguidry @kushthedude do you think we should revert the FF PR ? It brings a lot of instability in the builds

**Comment by wetneb** [comment]
Perhaps that would make sense, yes.

**Comment by kushthedude** [comment]
I am working on their fixes, I will let you know by EOD if I find no fix
then we can revert the PR.

**Comment by fgiroud** [comment]
@kushthedude what's the status on FF ?
It's probably not a bad idea to revert the PR, as we are also preparing an update on CI that will let anyone runs the tests on their fork, and we can troubleshoot from there

**Comment by kushthedude** [comment]
I was able to solve the column joining test, but I have zero lead on the scatterplot tests. Its best we revert the PR then.

**Comment by wetneb** [comment]
This is no longer an issue since we do not run the CI with Firefox anymore.
