### ISSUE TITLE
Default "Use quote as separator" to False for TSV imports

### ISSUE THREAD

**Issue by EricBuck** [OpenRefine/OpenRefine#3853]
I got a TSV file and uploaded it to OpenRefine, but OpenRefine parsed it incorrectly, shifting values over several columns.

### To Reproduce
1. Upload the file to OpenRefine.

2. Facet the categories column and select one of the values with "mm" in it. Look at the information in the size columns of the selected row. 

### Current Results
You should see that the actual size values have been shifted two or three columns to the left so that the height value is now in the categories value.

### Expected Behavior
In the raw XSLX file, the values are in the columns they are supposed to be in, I believe that OpenRefine is parsing the information incorrectly.

### Screenshots
![OpenRefineScreenshot](https://user-images.githubusercontent.com/83297405/116272186-b754ae80-a74e-11eb-8e4f-27405cdbc8d4.png)
![ExcelScreenShot](https://user-images.githubusercontent.com/83297405/116272225-bde32600-a74e-11eb-8d13-9939cc323179.png)

### Versions
 - Operating System: Windows 10
 - Browser Version: Microsoft Edge 90.0.818.46
 - JRE or JDK Version:
 - OpenRefine: 3.4.1

### Datasets
Since Github won't let me upload the original TSV, here is an XSLX I created by exporting the TSV's information from OpenRefine.
[phm-collection.xlsx](https://github.com/OpenRefine/OpenRefine/files/6385815/phm-collection.xlsx)

**Comment by thadguidry** [comment]
Hi @EricBuck does the Importer Preview also show this shifting happening?  Your screenshot shows after the TSV/XLSX was imported and I'd like to know what the Importer Preview shows and what all the options you choose during the importer.  Can you give us a screenshot of that?

**Comment by wetneb** [comment]
You should be able to upload the original TSV if you compress it as a ZIP file first. I think it would be very interesting to have the original file to understand the issue better :)

**Comment by EricBuck** [comment]
Apologies for taking so long to respond.

Here is the zipped TSV file:
[phm-collection.zip](https://github.com/OpenRefine/OpenRefine/files/6503006/phm-collection.zip)

Here is a screenshot of the upload menu. In the previewed 100 rows, there were no instances of the bug I mentioned above, but I highlighted a new problem I found. It seems that sometimes huge amounts of information that should be separated into new rows get grouped into one column. I highlighted what I am fairly sure is the start of a new item record in the screen shot.
![OpenRefineImportScreenshot](https://user-images.githubusercontent.com/83297405/118692994-a260bd80-b7d8-11eb-8d2e-96fe89aa277e.png)

**Comment by thadguidry** [comment]
@EricBuck You are using TSV format (tab separated values) and it is also automatically keeping the checkbox for **Use character " to enclose cells containing column separators**.
But the tabs themselves will suffice here to separate the columns nicely.
So in your data's case, there is no need to use that extra default checkbox option, so just uncheck it, and then things should work fine for your records import after that.

**USER NOTE:** It's hard for OpenRefine itself to detect these cases because sometimes the data has additional quote characters to enclose additional fields (yours has this with additional HTTP attribute fields but they are part of the record row), and sometimes the data does not, or its not needed.  We probably want **finer control** here to help the user depending on the Column separator method.

**DEVELOPERS NOTE:**  We could instead be more deterministic where a few java libraries can indeed support a independent checkbox option for csv, tsv, custom where each has their own extra options.  But we decided long ago to just have a more simple UI with only the single checkbox option here.  This might be instead flipped to an Enhancement issue where we want to revisit that decision and maybe here with the CSV/TSV/separator-based file importer to allow the user to see that deterministic support for extra options ... per Column separator method.  This would require a moderate amount of effort on both frontend UI (I'd probably go with a horizontal tabbed sub-panel where the user could click on COMMA, TAB, CUSTOM and then see the sub options for each independently.)

**Comment by tfmorris** [comment]
It doesn't make sense to me to have this option checked by default for TSV files. I think a more likely escaping strategy for TSVs would be to use `\t` to escape TABs.

**Comment by thadguidry** [comment]
@tfmorris Agree on your points, it will be best by default for TSVs to uncheck the checkbox and as I noted at the end of the developers note" I said:

> It's bitten my hand many numerous times as well, but thankfully, I'm just very used to always unchecking the option, where new users don't realize the extra problem it might cause with tsv format oftentimes.

**Comment by jnchen1** [comment]
Hello @thadguidry, my team and I would like to contribute to the project. Can you assign this issue to me?

**Comment by ostephens** [comment]
Thanks @wetneb I'm happy with disabling this option by default for TSV files. Obviously important that it's still there as an option in case someone uses inverted commas as in a TSV (which does happen) but agree this is the less common case and so shouldn't be the default
