### ISSUE TITLE
UI errors

### ISSUE THREAD

**Issue by haklaekim** [OpenRefine/OpenRefine#3857]
### To Reproduce
1. Start OpenRefine
2. Then, UI does not display properly. I created 30~40 projects so far. There are some errors when facet is selected (the project has 300,000 rows).
3. Although I uninstall previous version and install different versions such as 3.3 and 3.4.1, same problem occurrs.

### Screenshots

![Screen Shot 2021-04-28 at 11 02 32 PM](https://user-images.githubusercontent.com/5422771/116417071-e9acfb80-a875-11eb-9c54-bf6098403809.png)

### Versions
 - Operating System: iOS 11.3
 - Browser Version:  Chrome 19
 - JRE or JDK Version: AdoptOpenJDK build 11.0.9
 - OpenRefine: 3.3

**Comment by thadguidry** [comment]
Thanks for this issue!
It seems we have had another Mac user who had a similar problem here: https://groups.google.com/g/openrefine/c/yVofDRgDKi0
You might look through that group conversation from our mailing list and then update this issue with anything you might have done differently or tried.
The more info that we can collect about the workspace, it's path location, etc.  the more useful this issue will become to us, since not all Mac users are seeing this issue.
Our suspicion is something about the workspace folder location.

**Comment by kushthedude** [comment]
Hi, the following issues is due to presence of corrupt projects or either issue in workspace directory. As @thadguidry mentioned there can be variety of cause to this issue. But a quick fix as mac user would be to delete your workspace directory and then restart openrefine(if you have any important projects already setup in the refine, then I would suggest you to copy that project from workspace directory before deleting it).

**Comment by wetneb** [comment]
With the given information, it does not look like we can reproduce this bug unfortunately.
