### ISSUE TITLE
Minified Javascript files in the repository

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#3958]
[Posted by Markus Koschany on the openrefine-dev mailing list](https://groups.google.com/g/openrefine-dev/c/eJbPPYnqJiw):
> The webapp includes several minified Javascript files without providing the
> original non-minified source files. This is acceptable and in accordance with
> the license of those files but it is a reason to reject a package for Debian's
> ftp team because Debian requires the original sources. I suggest to include the
> corresponding non-minified Javascript files as well. Actually I believe
> minified JS files don't improve the performance that much since OpenRefine is
> run on the user's local system. You could remove them completely and use the
> non-minified versions instead. There are some files like date.js which appear
> to be minified Javascript as well despite the missing min.js suffix.

We should therefore reevaluate whether we can use non-minified files instead.
The real problem here is our lack of a proper dependency management system for our frontend, #2423.

**Comment by thadguidry** [comment]
We should be able to use non-minified files since we support local use and don't run an OpenRefine service for the world.
Historical context:  They were minified long ago with the idea that Metaweb/Google "might" provide an online data cleaning service based on OpenRefine, but after 1 year of headbanging they gave up. Instead they began to partner with Trifacta.
