### ISSUE TITLE
Add Column from Freebase should support refresh

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#417]
_Original author: tfmorris (June 30, 2011 19:17:21)_

After using Add Column from Freebase, it would be useful to be able to refresh the contents of the column to cover two cases:
1. cells in the source column which have been reconciled since the original Add was done
2. data that's changed in Freebase since the column was added.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=417_
##

**Comment by wetneb** [comment]
This functionality was moved to standard services and the issue is still valid. However, this does not seem to be something that we should support. This just does not fit in OpenRefine's philosophy: operations modify the table by adding or changing rows and columns, but cannot will not take into account later changes to the data they are relying on. The way to obtain this sort of update is to replay the change (extracted from the history).
