### ISSUE TITLE
Operate on the last row/record of the project using GREL without knowing actual row/record count

### ISSUE THREAD

**Issue by iomicifikko** [OpenRefine/OpenRefine#4203]
I want modify one or more cells of the last row (or record) of a project via GREL without knowing the actual row count inside the project. 

### Proposed solution

Create a new "project" object (I already proposed that in another ticket for different purposes, see [here](https://github.com/OpenRefine/OpenRefine/issues/4202)) and a new field "rowCount" (similar to row.record.rowCount).

### Alternatives considered

Right now you can do the same thing with the following steps:
- add a new column (grel: row.index), 
- apply permanent sort (largest first)
- use if(row.index==0 (...) inside the rest of the code

**Comment by magdmartin** [comment]
If you are in a record mode the grel `row.record.cells[columnName].value` turn all the rows part of one records into an array. You can then do `row.record.cells[columnName].value.sort()[-1]`  
Does it answer your use case?

**Comment by thadguidry** [comment]
We have added pagination controls since this issue and you can now click on **last>** button to get the last page with last row very quickly and then apply operations by flagging or starring that last row if desired, then use the **All** column menu to Facet by star and perform your cell changes using each columns' menus.

Closing as will not fix.

For batch or programmatic operations across all columns of the last row, you might consider 1. sorting using your alternative, 2. using All > Transform
But certainly, a new GREL variable could be proposed to use such as `lastRow` which could work such as `lastRow.cells[Column3].value` and conversely, `firstRow`.

@iomicifikko let us know if the new GREL variables would be your desire and we can reopen.
