### ISSUE TITLE
Security mailling list does exist

### ISSUE THREAD

**Issue by chicocvenancio** [OpenRefine/OpenRefine#4322]
### To Reproduce
1. Try to send an issue to the email mentioned in [SECURITY.md](https://github.com/OpenRefine/OpenRefine/blob/cf8b1401fab085bef09a2ce8b885d6b5c55b61a6/SECURITY.md) openrefine-coredev@googlegroups.com
2. Get back `We're writing to let you know that the group you tried to contact (openrefine-coredev) may not exist, or you may not have permission to post messages to the group`

**Comment by wetneb** [comment]
@thadguidry any chances you own this google group? if so, could you share the ownership with me so I can fix those settings?

**Comment by thadguidry** [comment]
@wetneb The owner is @magdmartin who indeed should make you co-owner

**Comment by magdmartin** [comment]
@chicocvenancio  I confirm the issue. I tried to post to the group from another email address and got a `Delivery Status Notification (Failure)` . If you like to report a security issue privately, I sent you an email. 


@wetneb  you are now owner on the group. 
I think the issue is because the group is private and Non member cannot post to it.  See the posting policty: https://groups.google.com/g/openrefine-coredev/settings#posting

![image](https://user-images.githubusercontent.com/2589584/143587907-70a21f0b-557e-458a-9ea8-13b240e05470.png)

We should work with CSS  to get a dedicated security email address (something like security@-) that redirect to the right mailing list.

**Comment by thadguidry** [comment]
@magdmartin and @trnstlntk please continue the action of getting CSS to help with a security@-* email address as @magdmartin suggested.

Then we can update the SECURITY.md file and finally close this issue.

**Comment by wetneb** [comment]
We can set up email addresses on our own actually! But somehow I do not seem to have access to this openrefine-coredev list at all, curious.

**Comment by magdmartin** [comment]
#5966 closed this issue.
