### ISSUE TITLE
Optimization: change ReconStats into a facet

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4350]
We currently maintain global reconciliation statistics for each reconciled column, counting how many cells are matched to an existing entity, matched to a new entity or non-matched. In Java, this is stored in a `ReconStats` object.

For large projects, those recon statistics are expensive to keep up to date. For most actions which trigger a change of the reconciliation data, we need to recompute those statistics entirely, which involves doing a pass on the whole grid. As a user, this is frustrating because I do not actually need a precise count of those reconciliation statuses. For instance, when interactively reviewing reconciliation results for cells in a column, each matching action will trigger a re-count of the reconciliation statistics. Those updates can be optimized when we are matching a single cell, but not when matching all cells with a given value.

### Proposed solution

As a user, I do not actually care about the exact number of cells in each status: in fact, the UI only displays a percentage when I hover the histogram in the column header.
![image](https://user-images.githubusercontent.com/309908/145197179-c11df292-3dff-4c39-933a-1cf3df0cb56a.png)

Therefore, this information should be treated as a facet, for which we already have a sampling mechanism which prevents from scanning the entire table. I see multiple options to use the same mechanism for ReconStats:
* [x] when computing the recon stats, only do it for a fixed maximal number of rows (like for the facets, but not configurable). This is easy to introduce but we are relying on a non-configurable parameter, which is not ideal.
* [ ] remove the `ReconStats` object from the backend entirely, and let the frontend render it itself, by adding facets on its own and rendering them in place. This is more involved for the frontend, but would be much cleaner for the backend.

I propose to start with the first approach, leaving this issue open for the second.

**Comment by thadguidry** [comment]
@wetneb I recall that somewhere we talked about this long way back in the early days...(might have been before you joined @wetneb ) I'm surprised we don't have an issue already? Perhaps not, but the longstanding #821 is one of the symptoms that users face as you sorta mention in your initial summary above.  Our conversations were probably in some mailing list thread around the time that issue was made by Ruben.

Regardless, yes your proposal for completely removing the ReconStats object makes more sense to me and we even had a loose roadmap for Faceting by aspects of of various attributes like Type, but the old Freebase API had some issues if I recall and David had started on a custom Freebase App but dunno whatever happened to it.

**Comment by wetneb** [comment]
Yes I think this could actually be a good opportunity to introduce more column-level stats, for instance we could have one to display the proportions of datatypes in each column.

**Comment by wetneb** [comment]
I have started to work on this and opened a discussion on the forum about how to expose datatype statistics in the UI:
https://forum.openrefine.org/t/exposing-datatype-statistics-in-columns/265
