### ISSUE TITLE
Status feedback during processing

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#438]
_Original author: zach...@indolering.com (August 24, 2011 23:36:57)_

When processing large datasets, Refine will gives a spinning circle but no indication of it's progress.  This leaves the user without knowing if the operation/data set is to large for Refine to reasonably handle given machine performance or if Refine is frozen.

Some basic information such as &quot;current command&quot; applied to x/y rows and or basic time completion estimations would ease this problem.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=438_

**Comment by wetneb** [comment]
The "Working…" dialog is generically shown when most HTTP requests from the frontend take a long time to be processed by the backend. It is a sort of fallback for requests that should normally be quick but take unexpectedly longer than usual. It would of course be great if for all of them one could have a better progress report, but we cannot realistically do that uniformly for all API endpoints (it would require even more endpoints to poll for the state of those computations!)

Improving the user experience for large datasets is something I am actively working on at the moment and a lot of this work is about avoiding such "Waiting…" screens. For instance, if you create a new column based on an existing column in 3.x, with a Jython expression which takes a long time to compute (such as making an HTTP request via Jython, for instance because more control over the headers is wished), then you will get such a "Working…" screen until the expression is evaluated on the entire grid. In 4.x this is instead replaced by a progress indicator like the one you get for other long-running operations. Given the statement of the issue it is hard to tell if that's the use case the author was aiming at though.

In cases of outright failure, it is possible that this "Working…" screen is shown indefinitely. This is likely linked to the very poor handling of XHR requests both from the backend (not exposing proper HTTP response codes) and the frontend (not handling error responses). We have #165 for that.

Therefore closing this.
