### ISSUE TITLE
timeout loading IPNI reconciliation service

### ISSUE THREAD

**Issue by heimor** [OpenRefine/OpenRefine#4419]
### To Reproduce
1. open a project
2. start reconciliation
3. add service http://data1.kew.org/reconciliation/reconcile/IpniName 
4. produces a timeout

### Screenshots

![grafik](https://user-images.githubusercontent.com/839889/148831894-3b6938fa-5efb-4cfb-b06e-b6634b008f9a.png)

### Versions
service running on server 
 - Operating System: UBUNTU 18.04.6
 
service call on server from local machine
 - Browser Version: Firefox 95.0.2 (64-Bit)
 - JRE or JDK Version: JDK 11.013 
 - OpenRefine: installation openrefine 3.5.1

**Comment by wetneb** [comment]
Curious! Perhaps because the service returns the header `Content-Type: application/json;charset=UTF-8` which is not really correct since it is returning a JavaScript script, not a JSON object.

Do you know if adding this service works with another version of OpenRefine or another browser? I suspect this could be browser-dependent.

**Comment by wetneb** [comment]
I just tried this reconciliation service with the [testbench](https://reconciliation-api.github.io/testbench/) and it fails there too (also with Firefox and Chrome), indicating that this is indeed a problem with the reconciliation service itself and not OpenRefine.

Therefore, closing this issue since it is outside our reach.
