### ISSUE TITLE
Prevent users from uploading duplicate files to Wikimedia Commons

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#4472]
In some cases, people who use OpenRefine for uploading new files to Wikimedia Commons will not be aware that (some of) these files already exist on Wikimedia Commons. This may happen, for instance, in cases where a cultural institution (GLAM) wants to do a batch upload to Commons, where previously a volunteer may already have found and uploaded (some of) their files there, or vice versa.

### Proposed solution

_Exact_ duplicates can be tracked/identified during upload to Wikimedia Commons, and upload tools usually (but [not always](https://bitbucket.org/magnusmanske/flickr2commons/issues/80/not-tagging-duplicates-properly)) support discovery and rejection of upload of such duplicates. It would be really good if OpenRefine would indeed do this too.

[Commons:Guide to batch uploading](https://commons.wikimedia.org/wiki/Commons:Guide_to_batch_uploading#Check_for_duplicates) contains some pointers on how to check for duplicates: it is possible to [ask the Commons API](https://commons.wikimedia.org/w/api.php?action=query&titles=File:Example.jpg&prop=imageinfo&iiprop=sha1) to look for files with [a same SHA-1 hash](https://commons.wikimedia.org/w/api.php?action=query&list=allimages&prop=imageinfo&aisha1=d01b79a6781c72ac9bfff93e5e2cfbeef4efc840).

As an example, Wikimedia Commons' own UploadWizard provides the user with an immediate warning if they try to upload an exact duplicate of a file.
![image](https://user-images.githubusercontent.com/9881645/151369614-373e9b16-9a94-4631-9f75-b13e639678cf.png)

### What about nearly exact duplicates?

It would be great if it would be possible to also identify nearly exact duplicates (e.g. visually extremely similar files), but this seems not technically possible yet. 

As an example, [this file](https://commons.wikimedia.org/wiki/File:Naturalis_Biodiversity_Center_-_RMNH.AVES.110015_-_Chloridops_kona_Wilson,_1888_-_Kona_Grosbeak_-_specimen_-_lateral_view.jpeg) was uploaded in 2015 during a GLAM partnership (by a Wikipedian in Residence). The file [is also shared on the GBIF website](https://www.gbif.org/occurrence/2433871981) and was [uploaded again with another tool in 2022](https://commons.wikimedia.org/wiki/File:Chloridops_kona_S.B.Wilson,_1888_2433871981.jpg). While both files are visually identical, they do have different file sizes and EXIF data, so some processing has happened through time.

There are some [ideas and discussions](https://commons.wikimedia.org/wiki/User:F%C3%A6/Imagehash) around this issue on Wikimedia Commons, but to my knowledge no concrete/actionable steps yet (e.g. applying other types of image hashing). See also https://phabricator.wikimedia.org/T251026

**Comment by wetneb** [comment]
Since there is no viable technical solution on Commons' side for this, I propose we close this issue.
We can revisit this when/if some API is developed to detect duplicates.

**Comment by multichill** [comment]
> Since there is no viable technical solution on Commons' side for this, I propose we close this issue. We can revisit this when/if some API is developed to detect duplicates.

You can't make an upload tool to Commons without preventing exact duplicates. It's pretty easy for a tool:
1. Tool downloads the file
2. Tool calculates the hash
3. Ask the API for any files with the hash, for example https://commons.wikimedia.org/w/api.php?action=query&list=allimages&aisha1=b12eb7f6b43a3cc1eefc54db90ec5ae1504c3f17
4. If it returns anything, you have a duplicate and you don't upload it

Working code at https://github.com/multichill/toollabs/blob/master/bot/commons/wikidata_uploader.py#L288

**Comment by trnstlntk** [comment]
@wetneb can we consider re-opening this issue? And perhaps it should be moved to the CommonsExtension repo?

Folks will be mad at us if OpenRefine will be responsible for many duplicate uploads.

If we can't develop this as part of the current grant due to time constraint / too much current complexity, let's at least keep it on the wishlist for a next iteration.

**Comment by wetneb** [comment]
@multichill do you know if it is possible to ask MediaWiki to do this check server-side, at upload time? By this I mean refuse the upload if its hash duplicates another file. It seems to me that by setting `ignorewarnings=0` (which we currently do) we should be safe, no? See https://www.mediawiki.org/wiki/API:Upload#Upload_warnings where duplicate files are mentioned as a possible warning.

Otherwise, to implement this in OpenRefine following the workflow you mentioned, it seems a bit heavy: when the user uploads files by URLs, that means we need to download the file first to compute its hash, which sorts of defeats a bit the benefits of uploading by URL (although I guess we can still assume that the bandwidth between MediaWiki and the third-party server is still higher than that between the OpenRefine user and MediaWiki).

**Comment by trnstlntk** [comment]
Also reported in #5041

**Comment by Ambrosiani** [comment]
just to clarify: in the batch upload I did, OpenRefine 3.7 did upload a few duplicate files where the exact hash already existed on Commons. I.e. the `ignorewarnings=0` flag seems to not be enough to avoid duplicate uploads.

example file:

https://commons.wikimedia.org/wiki/File:Aspudden_Flygfoto._ArkDes_ARKM.1962-101-2192.jpg (batch uploaded)
https://commons.wikimedia.org/wiki/File:Aspuddens_skola_flygfoto_(1950).jpg (existing duplicate)

I think checking the hash at upload time seems reasonable, but maybe as a user-selected action (since it consumes a lot of bandwidth by downloading each file).

**Comment by wetneb** [comment]
Ah, it's my fault, because `ignorewarnings=0` is actually interpreted as `ignorewarnings=1` by the MediaWiki API.

> Boolean parameters work like HTML checkboxes: if the parameter is specified, regardless of value, it is considered true. For a false value, omit the parameter entirely.

So we should remove this parameter entirely and see if it does prevent the upload of exact duplicates.
