### ISSUE TITLE
Menu items that open popups and new windows should have ellipsis

### ISSUE THREAD

**Issue by elebitzero** [OpenRefine/OpenRefine#4585]
Some of the menu items don't have an ellipsis but should because they open a popup, file explorer, or new window.

The following options need ellipsis:

All->Edit all columns->Transform 
All->Edit all columns->Trim leading and trailing whitespace
All->Edit all columns->Collapse consecutive whitespace
All->Edit all columns->Unescape HTML entities
All->Edit all columns->Replace smart quotes with ASCII
All->Edit all columns->To titlecase
All->Edit all columns->To uppercase
All->Edit all columns->To lowercase
All->Edit all columns->To number
All->Edit all columns->To date
All->Edit all columns->To text
All->Edit all columns->To null
All->Edit all columns->To empty string
Column->Facet->Custom text facet on column 
Column->Facet->Custom numeric facet on column 
Column->Facet->Scatterplot facet
Column->Edit cells->Replace 
Column->Edit Column->Add column by fetching URLs based on column X 
Column->Edit Column->Add column based on column X 
Column->Edit Column->Split column X into several columns 
Column->Edit Column->Join columns  
Column->Edit Column->Rename this column
Column->Transpose->Transpose cells across columns into rows... 
Column->Transpose->Transpose cells in rows into columns... 
Column->Transpose->Columnize by key/value columns... 
Column->Reconcile->Start reconciling
Column->Reconcile->Use values as identifiers
Column->Reconcile->Add entity identifiers column
Export->Google Sheets
Export->Wikibase schema
Wikibase->Select Wikibase instance
Wikibase->Manage Wikibase account
Wikibase->Import schema
Wikibase->Upload edits to Wikibase

### Proposed solution
Add ellipsis to the necessary menu items.

**Comment by thadguidry** [comment]
@elebitzero Yeap, agree, I was just thinking about this today as I was testing our 3.6 Snapshot build with your earlier merged changes for the alignment of dialog buttons.  I'm wondering on this particular issue if we might use the Unicode ellipsis char and bake this into the menu's that need them via a JS variable?  

<html><body>


Name: | Horizontal Ellipsis
-- | --
PostScript Name: | `ellipsis`
HTML Entity: | `&#8230; &#x2026; &mldr;`
UTF-8 Encoding: | `0xE2 0x80 0xA6`
UTF-16 Encoding: | `0x2026`


</body>
</html>

This way would make translations easier also, since translators would not have to worry about the ellipsis being part of the text string at all.  Example: https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/langs/translation-en.json#L521

Maybe we could avoid much backend coding on this if we could, since it should be simply that any frontend framework knows that its particular component item in our UI (jQuery for us on most of this) has a action to present a dialog.

Another side issue, I noticed that our **Rename column*** could use some touchup and be converted to a regular dialog.

**Comment by thadguidry** [comment]
@elebitzero Further thoughts,  I have seen in some applications that the context of "more" which is what the ellipsis represents in many human languages, but sometimes not all of the human languages prefer the ellipsis style for that context of "more".  We might further allow the Unicode char choice to switch the Unicode char that is appropriate for that language whenever the user switches to a different language.  For example, in many Asian applications, I have seen "more" often represented with the double right chevron (a double `>>`) and sometimes just the circled `+` or circle plus icon.

We might first consult with https://www.w3.org/WAI/standards-guidelines/wcag/ and ask them about that first on what they think?

**Comment by thadguidry** [comment]
Still further, we might avoid iconography completely on this issue and instead consider embold the text for those particular ones, or indent or emboss or glow or highlight or shade the items differently?  Still if we do choose iconography, we might place it **before** the text, rather than afterwards?  Notice how the main menu has our `Sort...` with an ellipsis against in that same menu the look and feel of the right arrows shown that have the context of "more menu structure".

**Comment by elebitzero** [comment]
Thanks for the comments.  

For menu items which already have ellipsis, the ellipsis is added after translation (localizedText+"...").

I believe this is correct since the ellipsis is a symbol and does not need localization.

I'm not familiar with different representations of the ellipsis in other locales in the context of an app menu.  

For this issue, I am calling out which menu actions are missing a required ellipsis. I was going to issue a PR tomorrow to correct these.  I can implement a JS var or function so that the ellipsis is added in one spot. This way, changes can be easily made in the future.

**Comment by thadguidry** [comment]
@elebitzero then go ahead with your plan and I'll be happy to review and test your PR on Windows. Thanks so much for working on these issues!
