### ISSUE TITLE
Add a pop-up window after uploading edits to wikibase

### ISSUE THREAD

**Issue by SIXIN-LI** [OpenRefine/OpenRefine#4751]
It is frustrated to not know if the upload is successful after uploading edits to wikibase, and to manually open "user contribution" page on wikidata.

### Proposed solution

Have a pop-up window appearing after finishing uploading. The window gives two options with links to "user contribution" page or "edit groups" page.

### Alternatives considered

Arbitrarily open up the "user contribution" result page with username entered and searched already.

**Comment by wetneb** [comment]
We could also display some statistics about the number of failed edits, and potential error messages.
In terms of user experience I am not completely sure how this would look like, since uploading edits to Wikibase is a long-running operation which can run in the background (the user can keep using OR to browse the dataset while edits are done).
Maybe @lozanaross has ideas?

**Comment by wetneb** [comment]
Let's close this as something that will be included in #5032 already. If one manages to get the edit group information there, adding error logs should not be very hard.
