### ISSUE TITLE
Possibility to adjust column width manually

### ISSUE THREAD

**Issue by lozanaross** [OpenRefine/OpenRefine#4806]
Right now column width is generated arbitrarily based on content of the column headers and/or data values - this can be very problematic particularly with XML files where the column headers and sometimes the data values  can be quite lengthy if the XML is not particularly well structured, then very wide columns fill up a user's screen - preventing efficient work.

### Proposed solution
Ideally, column width should be controlled by the users with a familiar user interaction pattern, such as a dragging motion by the user's cursor, as is the case in other tabular management tools such as Excel / Google sheets, etc.

### Alternatives considered
None yet.

### Additional context
N/A

**Comment by Lydiaofficial** [comment]
Iterating on this issue of letting users control and resize column width, I arrived at 2 (two) alternative solutions that can both work together or separately.

They are:
1. The dragging motion 
As stated in the issue, the dragging motion is most likley the preferred and most user centric approach to letting users resize columns by simply dragging their cursor from one end to the other to change the widths of columns. However, resizing column width wll definitely affect the data that is contained in each column as well as its height.

in my iteration, when a user extends the width of a column, it causes the data contained to spread in order to adjust to the column width. Likewise, when column width is shortened, the data contained therefore, breaks into more lines to fit into the shortened column , which in turn elongates the height of each column and row.

The above are shown in these screenshots:
![image](https://user-images.githubusercontent.com/17748526/226102182-4f33ca8a-64c6-4a9b-bd01-63539c383ee2.png)

![image](https://user-images.githubusercontent.com/17748526/226102197-81096fd5-26cc-4a18-817e-400c34468962.png)

2. Alternative proposition.
Adding the "Resize this column" action/option to edit column dropdown.

This alternative proposition, which can also work alongside the dragging option ,adds the option to resize columns to the edit column options available to OpenRefine users and just below the option to remove a column.

On click, the user is shown a modal to add their desired column width and save and on save, the width added is automatically applied on the column the user chose to resize.

This alternative is further explained in the below screenshots;
![image](https://user-images.githubusercontent.com/17748526/226102524-e44d5e0d-a440-47cf-b1e9-f2c7fd2d59cc.png)

![image](https://user-images.githubusercontent.com/17748526/226102773-0fd3c0ac-7940-46b7-89be-5813cce0a187.png)

![image](https://user-images.githubusercontent.com/17748526/226102925-68721dd0-54d9-4768-a092-8fa3482b6d29.png)

**Comment by thadguidry** [comment]
@Lydiaofficial is it a click, hold button, drag?  holding mouse buttons is sometimes cumbersome for folks.  It's a small accessibility issue in some regards.  Would be nice to avoid having to hold down the mouse button.  A click, drag around until you like it, then click again to release... would be my preferred choice if that's possible. Or some other alternative.

**Comment by Lydiaofficial** [comment]
@thadguidry I understand the accessibility issue that holding mouse buttons can cause , so definitely, should be a "click and drag until you like it and click to release " and definitely is possible.

**Comment by lozanaross** [comment]
@Lydiaofficial @wetneb I'm not sure this issue is so appropriate for the Outreachy group. My advice here is not to reinvent the wheel. 

Resizing columns in both Excel and Google Sheets (as indicated in my original formulation of the issue) works in exactly the same way (with same mouse cursor design even) and it's thus a very familiar behaviour. The dragging design mockups above miss the point that dragging should only be activated in the title region of each column - enabling dragging anywhere else in a data field (as shown in mockups) will potentially interfere with other possible data operations in that region (clicking hyperlinks, clicking the edit button, hover states after reconciliation, etc).

**Comment by thadguidry** [comment]
@lozanaross Oh I didn't catch that, they have mocked up dragging behavior on the vertical column lines as well? (I now see the white barbell arrow)  Agree, dragging should only be accomplished against a column header and not anything below them.

**Comment by Lydiaofficial** [comment]
@lozanaross Oh thank you for the feedback.
I'll make the necessary corrections.

**Comment by Lydiaofficial** [comment]
Oh. Alright.
Thank you.

**Comment by tfmorris** [comment]
Retargetting for 3.9 with pending PR

**Comment by thadguidry** [comment]
This does not work well on Edge and exhibits a snapping back problem upon the Event: mouseup

![SnappingBackProblem](https://github.com/user-attachments/assets/d57ef2fe-6d7d-4356-953d-8307c0a8274f)

Perhaps instead we just simplify the development cognitive load and use [Jquery UI Resizable](https://jqueryui.com/resizable/#default) ? - easy to use and works across all the browsers since 9 years ago.  Up to @wetneb if he really wants to continue hand coding the JS for this feature.

**Comment by thadguidry** [comment]
The other thing I noticed was that the cursor style changes back to an arrow on any of the empty `<th>` elements ?
![CursorChangesOnHeaderRows](https://github.com/user-attachments/assets/b623467b-db7b-44b4-9542-a7b7e7b14f21)

**Comment by wetneb** [comment]
I'm definitely open to improvements but perhaps it would be easier if you opened a new issue, no?

**Comment by thadguidry** [comment]
So you're considering the feature complete?  And I should treat this as a bug - but we haven't shipped this yet?  I don't think it's beneficial.  I don't understand "easier" here.

**Comment by wetneb** [comment]
Yes I would treat this as a bug of an already implemented feature, but no strong feelings about it. It feels "easier" in the sense that we can start a fresh discussion, milestone management is perhaps also a bit cleaner…
