### ISSUE TITLE
Selection of Wikibase instance directly in the schema editor

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4819]
Our Wikibase schema editor currently looks like this:
![image](https://user-images.githubusercontent.com/309908/165939943-90415650-4561-471c-8b87-1ac4e1dc0544.png)

This has a few problems:
* the currently selected Wikibase instance is not very well identifiable, because it is just mentioned in passing in a big blob of text
* the big blob of text may be read the first time, but then it is really just taking up space on the screen
* the way to change the Wikibase instance is not obvious

### Proposed solution

@lozanaross proposed the following design (from [this series of wireframes developed for the Wikimedia Commons integration project](https://upload.wikimedia.org/wikipedia/commons/2/2e/Structured_Data_on_Commons_file_upload_in_OpenRefine_-_wireframes_draft_v2.pdf)):
![image](https://user-images.githubusercontent.com/309908/165941106-f637252b-ae7a-419f-9dbb-b994f002063d.png)

(disregard the schema template part: that is for a separate issue).
Note also the change of layout for the buttons on the right-hand side, which also makes sense to me.

I am not sure if the explanations removed in the process should be displayed elsewhere or if we can remove them entirely.

### Alternatives considered

None

### Additional context

Design proposed for the Wikimedia Commons integration project.

**Comment by lozanaross** [comment]
Slight update here: https://xd.adobe.com/view/d8b086f2-199a-4fcf-a1e8-8d939842b790-8de3/
![Image](https://user-images.githubusercontent.com/25489750/166142767-02fe9f03-a5f4-4c1b-bbc6-4e49a53da5e6.png)

@wetneb @trnstlntk Should I make a separate version just for the Wikibase extension in general, because this is specific to SDC extension, but it can be cleaned up more just for the WB extension as well.

**Comment by wetneb** [comment]
Yes I would hope we can have one version that can be integrated in the Wikibase extension and which can be used for Commons as well as any other Wikibase instance.

**Comment by lozanaross** [comment]
> Yes I would hope we can have one version that can be integrated in the Wikibase extension and which can be used for Commons as well as any other Wikibase instance.

@wetneb Thanks. Given your answer to https://github.com/OpenRefine/CommonsExtension/issues/24 I assume there is actually no need to simplify the design for Wikibase extension then, because it will also include a template dropdown? And the schema template option will also be there?

The text "The schema below specifies how your data will be transformed into Wikimedia Commons edits." should also be contextually sensitive then & the word "Wikimedia Commons" should be replaced with the title of whatever WB instance is selected in the first dropdown. 

Regarding your question:
> I am not sure if the explanations removed in the process should be displayed elsewhere or if we can remove them entirely.

Yes, I think the text should be removed entirely and we can show it in an onboarding tour and/or other forms of documentation we develop. I don't think it has massive added value to users to be there visible at all times.

**Comment by wetneb** [comment]
Great!

My main motivation to introduce this text was the drag and drop feature which is not really easy to discover without explanation.

**Comment by lozanaross** [comment]
> My main motivation to introduce this text was the drag and drop feature which is not really easy to discover without explanation.

Yeah. Agreed. That info is a good candidate for onboarding text, or alternatively "tooltip text" over a blue "i" icon that we're introducing elsewhere in the SDC extension design as well, which reminds me - I may set up a separate issue just for the "i" icon design in any case.

**Comment by lozanaross** [comment]
Picking up this thread with an updated version of the design that disregards the schema templates (for now - we can address this in a dedicated issue) and focuses just on Wikibase selection + introducing a tooltip text. The mockups are below:
![Changing WB instance](https://user-images.githubusercontent.com/25489750/178364547-a484d32e-2d50-4b5f-9265-664464e7d6ca.png)
![Changing WB instance w- tooltip](https://user-images.githubusercontent.com/25489750/178364550-80924be2-4446-4f92-b433-485566e2db2e.png)
Interactive version (wide dev tools for inspecting sizes, etc): https://xd.adobe.com/view/aca8ebf1-4e95-4339-8363-0a7e37f081bd-f9fb/

Tooltip icon is here: 
![info_icon](https://user-images.githubusercontent.com/25489750/178364658-7acef3d1-52ea-4556-81aa-4c6585ec7cbd.svg)

The styling of the tooptip box doesn't have to follow the mockup - it can be just the browser default. The actual tooltip text is also only a placeholder draft for now, it can be improved if needed. 

One final note here: The Wikibase extension currently actually read as "Wikidata" in the top Extensions menu. Can that be switched to Wikibase (I've done so in the mockups), not sure if we need a separate issue for that.

**Comment by thadguidry** [comment]
@lozanaross Just a quick side comment ... throughout that viz I notice something:
* interactive elements have border shading (3D) applied to them

Should the Tooltip icon also have slight shading since it is interactive? or not really "interactive" in that sense but merely "hover-able"?

**Comment by wetneb** [comment]
> One final note here: The Wikibase extension currently actually read as "Wikidata" in the top Extensions menu. Can that be switched to Wikibase (I've done so in the mockups), not sure if we need a separate issue for that.

This is #4525

**Comment by lozanaross** [comment]
> Should the Tooltip icon also have slight shading since it is interactive? or not really "interactive" in that sense but merely "hover-able"? I worry about the consistency of style with "interactive" elements. Long ago it was consistent since Haley @ Google did the original original designs.

Good question - since it's only "hover-able" it's a bit in between a fully interactive element and a static graphic. I think it's a bit too small also to make it visibly shaded. My preference is to keep it flat for visual simplicity & since we are slowly moving towards different styles in line with more modern frameworks (e.g. #4957).
