### ISSUE TITLE
Character encoding not being set in new projects

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#486]
_Original author: tfmorris (November 18, 2011 19:42:20)_

The problems that Thad reported with reintepret here:

http://code.google.com/p/google-refine/issues/detail?id=237#c6

I think are due to the character encoding being set to &quot;&quot; in newly created projects.

It looks to me like if the user doesn't explicitly select a character encoding we are using &quot;&quot;.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=486_

**Comment by drangons** [comment]
Hi,
I am the issue with importing text written in German language. When csv file is imported to refine, the column values are displayed as ? for ö ü characters. I am using 2.5-r2407 . 
for example für is displayed as fÃ¼r.

Can you suggested me what can be done to get it to work.
Thanks.

Update: I understand that I have to change the character encoding. Can it be configured in file ? .

**Comment by jackyq2015** [comment]
Is this still a problem for current code base? seems Tom already fixed it by putting a default encoding when it's empty.

I tried the testing file under win 7. it works fine. If someone can provide the testing file and procedures to reproduce it, that will be helpful.

**Comment by jackyq2015** [comment]
@tfmorris I tried the attached testing file with GREL reinterpret(value,"utf-8") and reinterpret(value,"big5"). Neither of them has the error as mentioned in original post. 

Could you please elaborate if you still think it's problem?

**Comment by magdmartin** [comment]
I still have the error in 2.5 and 2.6rc-1 with both chrome and firefox on a linux machine. Here the project with the error: https://drive.google.com/file/d/0B7tW6wTrzLf7X3dkQUg2QUVzbG8/view?usp=sharing

**Comment by jackyq2015** [comment]
I downloaded the project and confirmed that the encode was wrongly set to us-ascii. In windows the same file when importing it is set to utf-8. Will come up a solution for this issue under Linux.

**Comment by jackyq2015** [comment]
@magdmartin can you please run command locale at command line and paste the result?

**Comment by magdmartin** [comment]
martin@martin-Lenovo-G585:~$ locale
LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"
LC_ALL=

**Comment by jackyq2015** [comment]
For this particular file, adding JVM option -Dfile.encoding=Cp1252 when starting the OR can fix the encoding issue under Linux. Linux use the UTF-8 by default but windows use Cp1252 by default. That's why this problem only happens on Linux. The file is read in a wrong encoding and thus writing incorrectly in the project data file. So there's no way if you try to use the "reinterpret" to override the encoding because the byte streams already got mess up and there's no way you can restore it.  Seems for the JDK6, you will get UnsupportedEncodingException when doing String.getBytes(). But for the JDK7, you won't. That's why the same can't be reproduced but reflected in another way.

Adding this option is just a temp patch for this situation(BTW, it applies to other issues in the group related to Germany language encoding which are not off the top of my head. Adding the option to the configuration also possible if you are sure what kind of files you are dealing with). IMO, The permanent fix would be always detect the encoding of the file and read it in that encoding. Otherwise, it's likely mess up. For the file writing, the UTF-8 should be a good choice.

**Comment by jackyq2015** [comment]
Move to 2.7

**Comment by tfmorris** [comment]
Moving back to 2.6.  We shouldn't be doing a new release with critical bugs pending.  The reason this was given a critical priority is that, if the user doesn't notice that the encoding is messed up at import time, there's no way to recover later.

**Comment by thadguidry** [comment]
@OpenRefine/core I'd like to see us finish off what David started on this old issue and connect the encoding guessing code and ensure it populates the Character encoding field in the UI during import preview.  We might want to increase our max rows read to 1000, instead of the default 100 for the guessing. ( I recall David and I talking about that because of a few real-world files I ran across, but don't remember specifics other than the guessing was sub-optimal with fewer rows read on those files. I no longer have the files.)

**Comment by tfmorris** [comment]
Wow, 8 1/2 years later and still no fix, plus not it's even consider critical any more, despite being at the root of a number of different encoding issues.

I'll see if I can ressurect @stundzig's PR that he generously contributed 5 years ago.

**Comment by thadguidry** [comment]
@tfmorris About change in criticality.  My hand was controlled at that particular time by Jacky (maybe Antonin also? dunno) on a Sunday morning when we used to have project conf. calls to cover things like reviews of important issues (and no longer do).  In this case I recall that because the default was in place now, that it was deemed lesser importance.  But Thanks for any help you can offer!

**Comment by wetneb** [comment]
I have added this to 3.4 but I think this has the potential to break things, so I think we need an intermediate release (rc1?) before a final stable 3.4.
