### ISSUE TITLE
XML import fails if the file contains invalid XML characters

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#4928]
When trying to parse a file which contains invalid characters in XML, we get an error. Instead it would be nice if those characters could be ignored, perhaps via an importer option.

### To Reproduce

Import the following file: 
[expert_groups.zip](https://github.com/OpenRefine/OpenRefine/files/8839692/expert_groups.zip)

### Current Results

Error message: `javax.xml.stream.XMLStreamException: ParseError at [row,col]:[296,30402]
Message: Un caractère XML non valide (Unicode : 0xb) a été détecté dans la section CDATA`

### Expected Behavior

The dataset could be imported anyway

### Versions
 - Operating System: Debian
 - Browser Version: irrelevant
 - JRE or JDK Version: 11
 - OpenRefine: 3.6-SNAPSHOT

### Datasets

[expert_groups.zip](https://github.com/OpenRefine/OpenRefine/files/8839692/expert_groups.zip)

### Additional context
Similar issue to make the XML importer more accepting: #3638

**Comment by tfmorris** [comment]
Does this really need to be changed? There is no question that the file is not valid XML. It contains a single invalid character which has both its location (line 296) and value (0xB or Vertical Tab ctrl/K) given precisely in the error message. Removing the offending character allows the, now legal, file to be imported by OpenRefine.

The problem lies squarely in the domain of the XML parser. If the behavior is going to be changed, that is where the change should go (but good luck getting any XML parser devs accepting the parsing of invalid XML as a requirement).

In some cases you may also be able to use the hack of setting the XML version to 1.1 as [suggested on StackOverflow](https://stackoverflow.com/a/42359317/167425), but that doesn't work in this case, because the document isn't valid XML 1.1 either.

Consider also the risk of unintentionally breaking one or more of the *many* existing use cases by mucking with such an important input path.

**Comment by wetneb** [comment]
OpenRefine being a data cleaning tool, I expect it to be able to work with dirty files as input. Being less strict about the input format is a part of that, just like browsers do not just refuse to load a page at the first violation of the HTML standard.

> Consider also the risk of unintentionally breaking one or more of the many existing use cases by mucking with such an important input path.

I do not get it: what use cases can we break by removing characters which currently completely block the import of any XML file that contain it? Of course we would only do this replacement for the XML importer.

**Comment by wetneb** [comment]
> In some cases you may also be able to use the hack of setting the XML version to 1.1 as [suggested on StackOverflow](https://stackoverflow.com/a/42359317/167425), but that doesn't work in this case, because the document isn't valid XML 1.1 either.

I do feel like this is worth investigating more: we should make sure that parsing valid XML 1.1 documents works, even when they are not XML 1.0 valid.

**Comment by wetneb** [comment]
Duplicate of #3638, sorry about that!
