### ISSUE TITLE
Add operation for compact project

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#498]
_Original author: dfhu...@gmail.com (November 29, 2011 19:58:11)_

For performance, some existing operations tend to create more cells that are null than reorganize cells to save space (e.g., discussed in issue #493). It's probably a good idea to add an explicit operation to compact the project.

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=498_

**Comment by wetneb** [comment]
I'd argue against implementing this as an explicit operation since users are unlikely to understand when to trigger it and what it really does, since this would just be performing internal optimizations under the hood. From a user perspective, this ought to be handled silently by the tool.

In the 4.0 architecture I have removed the system of column indices which created the need for this, so I am closing this: users who run into performance issues on large datasets will be served by the 4.x release series.
