### ISSUE TITLE
Check that created Wikibase items have distinct (name,description) pairs

### ISSUE THREAD

**Issue by CollectieDIVA** [OpenRefine/OpenRefine#4980]
Hi all,

I am creating new Wikidata entries for a museum via OR (version 3.5) using the Wikidata extension. However, I have had several instances where the edits do not perform from a certain point onwards. Strange but perhaps important detail: OR shows the edits as 78% complete, while in Wikidata I can see in my contributions that only about 30 of the 293 items of _Part 4 of the public domain upload for the DIVA museum_ have been uploaded. Many titles are the same (Lepel, Vork, Modelprent met verschillende voorwerpen, ...), but it seems to me that this cannot be the problem, right? They are in fact different objects, as you can see in the object number column, and thus I created new items for each cell.

### To Reproduce
1. Reconciliation of column Title (= item) 
2. If the item doesn't exist > Actions > Create new item for each cell
3. Edit Wikibase schema
4. Upload edits to Wikibase

### Screenshots

![Screenshot 2022-06-22 at 12-13-21 78% complete - Publiek domein upload DIVA - OpenRefine](https://user-images.githubusercontent.com/73224676/175005080-5ff5fe35-6962-4608-bb03-feb72ae2eb48.png)
![afbeelding](https://user-images.githubusercontent.com/73224676/175005190-a1bd8f5c-3f80-4c2c-8d98-7bb17a7999be.png)

### Versions
 - Operating System: Windows 10,
 - Browser Version: Chrome 19, Firefox 61
 - OpenRefine: OpenRefine 3.5

**Comment by trnstlntk** [comment]
@CollectieDIVA On Wikidata, the combination of label and description needs to be unique. I think that's why your upload stalls: you are trying to create many items with the exact same label and description.

You can address this by making sure each label is unique; I would advise you to add `(DIVA Pxxxx/x/xx)`at the end of each label for that, e.g. for your item on line 77 I would make sure it has the Title `Modelprent met verschillende ontwerpen (DIVA P2013/1/36)`.

To make sure that it will work correctly, I would first remove the reconciliation judgments from the items that are indicated as 'create new items', then change their Title in OpenRefine according to my recommendations above, then reconcile them with Wikidata again and then again mark as new.

In your current situation, in the Issues tab, I think you should also see a message that warns you about trying to create items with identical labels. Are you seeing this indeed?

**Comment by wetneb** [comment]
I do not think we have such a check implemented yet - I think it would be a good idea to add one indeed!

**Comment by trnstlntk** [comment]
> I do not think we have such a check implemented yet - I think it would be a good idea to add one indeed!

It would be very useful. Even I, as a very experienced OpenRefine user, creating new items in Wikidata regularly, still come across this issue all the time!

**Comment by trnstlntk** [comment]
Ideally, one should be able to create Wikidata items (and Wikibase items) with identical labels, as long as the description is then unique.

**Comment by CollectieDIVA** [comment]
> @CollectieDIVA On Wikidata, the combination of label and description needs to be unique. I think that's why your upload stalls: you are trying to create many items with the exact same label and description.
> 
> You can address this by making sure each label is unique; I would advise you to add `(DIVA Pxxxx/x/xx)`at the end of each label for that, e.g. for your item on line 77 I would make sure it has the Title `Modelprent met verschillende ontwerpen (DIVA P2013/1/36)`.
> 
> To make sure that it will work correctly, I would first remove the reconciliation judgments from the items that are indicated as 'create new items', then change their Title in OpenRefine according to my recommendations above, then reconcile them with Wikidata again and then again mark as new.
> 
> In your current situation, in the Issues tab, I think you should also see a message that warns you about trying to create items with identical labels. Are you seeing this indeed?

Hi, thanks for your reply! As confirmed above, I did not get that warning message. I'll try again using your advice, but ideally, as you've mentioned, we would be able to upload identical labels, as long as the description or inventory number would be unique. But for now, I'll give your suggestion a try and give you a quick  heads up if it helps.

**Comment by wetneb** [comment]
So let us say that the solution to this issue is to implement a QA check in the Wikibase extension, which detects when the user wants to create items which share a common (name,description) pair in a given language. The severity of the warning raised in that case should be "critical", because that prevents the batch from being uploaded.
