### ISSUE TITLE
Feature request: "shortcut" menu item for new item creation against a chosen reconciliation service

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#4985]
Idea from @lozanaross, endorsed by me, which we discussed in the context of Wikimedia Commons user testing sessions.

Creating new items via reconciliation services is a confusing process, as we regularly see in demos or user tests. People first have to reconcile non-existent entities (eg not yet existing Wikidata items or Wikimedia Commons filenames) against a reconciliation service, and then mark them as new. We propose a shortcut to make this process easier and probably more logical.

### Proposed solution
Add a menu item which may be something like `Create new items via reconciliation service...`
When selecting this menu item, the user then gets a small dialog, very similar to the one produced by the `Use values as identifiers` menu command, saying: `Create a new item for each of the selected cells, against reconciliation service:` with a drop-down menu that allows the user to choose between all the reconciliation services they have installed.
![image](https://user-images.githubusercontent.com/9881645/175359665-824d74c1-68a4-4b26-9eb8-341178b78f3b.png)

(The idea is that prior reconciliation before this process then would not be necessary.)

### Alternatives considered
Keep the current situation with very confused users.

**Comment by lozanaross** [comment]
Two wireframe mockups are relevant to add here: 
1) How to select the action to directly create new items (or media uploads) (without going through reconciliation process first, which is a pain point even when using Wikidata/Wikibase). To do this a slight reorganization in the order of action menu items is proposed, see below (the items are re-ordered because items below the line require reconciliation first - perhaps a contradiction that needs resolving as well):
![Screenshot 2022-07-23 at 23 00 31](https://user-images.githubusercontent.com/25489750/180622814-aa990610-3b70-4ef7-bbb9-8d19a39d09cd.png)

2) What happens when that action from the menu is selected, a customized dialog window is opened:
![Screenshot 2022-07-23 at 23 00 19](https://user-images.githubusercontent.com/25489750/180622838-0627e00b-b491-464b-8112-38020080e9b7.png)

**Comment by ostephens** [comment]
My only concern here is it basically allows the user to skip the reconciliation process - which seems likely to increase the possibility of duplicating data in the targeted service. While I understand that having to:
>reconcile non-existent entities (eg not yet existing Wikidata items or Wikimedia Commons filenames) 

Seems confusing - this isn't quite what's happening. The reconciliation step is to check if the entity already exists in the service. Obviously sometimes the user will know that it doesn't, but the current situation makes the user double check this.

I wonder if we need to introduce a warning for the user if they skip the reconciliation step to go straight to New item creation?

**Comment by wetneb** [comment]
I would add a warning just like we added one in the "use values as identifiers" dialog.
