### ISSUE TITLE
More UI improvements for Wikibase selection dialog

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#5009]
In the (resolved) issue #3824, the Wikibase selection dialog window has been improved.

![image](https://user-images.githubusercontent.com/9881645/177038685-bbddaed1-35ec-4777-88cc-a7810bee2678.png)

@lozanaross and I have tested the "new style" window in v3.7 while observing people during Wikimedia Commons upload user tests, and we notice that its behavior is still confusing to folks, especially the way in which Wikibase instances change place in the window as a new one is selected (the active one will jump to the top). A UX where instances are e.g. in alphabetical order, and the active one is highlighted otherwise, would feel more natural/intuitively understandable.

### Proposed solution
This design by @lozanaross is probably still a better way to go (or do we already have a newer version?). Radio button to select the desired active instance, cross to delete an instance, `Add another instance` button to add a new one. Instances stay in the same place/order and don't switch around after selection/addition.
![image](https://user-images.githubusercontent.com/9881645/177038432-1e52d002-4662-4ce9-8234-af00fe6d6a36.png)

### Additional context
Also see #5007 - may be good to integrate a link to the Wikibase manifest repository as well?

I may miss elements that are relevant for better UX of this dialog, so feel free to chime in with more factors to take into account.

**Comment by thadguidry** [comment]
@trnstlntk do you envision users wanting to have a favorites listing?  Would folks even use a feature like that?, i.e. do some often have a need to switch back and forth between instances?

**Comment by antoine2711** [comment]
> Would folks even use a feature like that?, i.e. do some often have a need to switch back and forth between instances?

@thadguidry: I think it will be mandatory to use 2 services if someone wants to create Mxx items and Qxx items, as one require Wikidata and the other WikiCommons.

Regards, Antoine

**Comment by trnstlntk** [comment]
> @trnstlntk do you envision users wanting to have a favorites listing? Would folks even use a feature like that?, i.e. do some often have a need to switch back and forth between instances?

Wikimedia Commons editors and uploaders will switch back and forth between the Wikidata and Wikimedia Commons instances a lot. We also have some users who maintain multiple Wikibases and also interact with Wikidata, who switch back and forth a lot.

There will not be a need for favorites, I think - in most cases people will have 2-3 active Wikibases, and to me favorites make most sense if there would be a longer list (e.g. favorite projects, favorite past GREL commands).

**Comment by lozanaross** [comment]
Thanks for highlighting this @trnstlntk. Two key elements lack in the current version - 1) a clear indication that you have selected something (instead of merely highlighting it via color) - hence the need for something like a radio button; and 2) a clear way to confirm your selection (currently "close" is confusing to users as they expect an "ok" type button). The new design proposal addresses these two issues. And indeed an updated version is needed to include the new proposal from #5007. 

In terms of the "pinned" or "favorite" services, I also think the use cases for more than 2 instances will be edge cases rather than the majority. And in the new wireframes for the Commons extension (which also can be implemented in the general Wikidata/base extension) - there is also the option to switch instances directly in the schema building tab: 
![Screenshot 2022-07-03 at 23 32 40](https://user-images.githubusercontent.com/25489750/177057893-60e7052e-8ff7-424e-86c7-ea668ea0a05e.png)

**Comment by elebitzero** [comment]
I agree with the major points in the mockup: adding the radio button, not changing the order when changing selection, and not making the change until the user confirms.  

@loazanaross, I can work on this if you are not picking it up now.

**Comment by lozanaross** [comment]
@elebitzero - that would be great, if you have capacity to implement these changes please go ahead!
