### ISSUE TITLE
Apply Operation History from JSON file

### ISSUE THREAD

**Issue by villanueval** [OpenRefine/OpenRefine#5022]
Related to #4498, I would like to see a button to Apply Operation History by opening a JSON file instead of having to open the file separately. This would remove any need to copy-paste the contents of these files, and make it easier for users.

**Comment by ostephens** [comment]
What about this as an approach?

- "Import" button added to the Apply Operation History dialogue
- On clicking import, user prompted to upload file
- Once file is uploaded the content (assuming can be read correctly) is populated into the operation history window
- User can then click "Perform operations" as usual

**Comment by villanueval** [comment]
Yeah, I like this approach.

**Comment by IjayAbby** [comment]
Hello, can I be assigned this issue?

**Comment by IjayAbby** [comment]
How do I best approach this issue?

**Comment by ostephens** [comment]
And if you haven't already please read through the contributing guidelines etc https://openrefine.org/docs/technical-reference/contributing

**Comment by IjayAbby** [comment]
Thank you so much for clarity and resources you have shared.I will reach
out.

**Comment by ostephens** [comment]
Thanks @ljayAbby

I think you've got an extra step in there that would be a separate enhancement:
> - The operations in the JSON file will be applied to your current OpenRefine project. You can see the changes in the preview pane on the right side of the screen.

This isn't something that currently happens when applying an operation history and while I think adding it is a great idea I think that should be a separate enhancement (as it should work whether you do via a file upload or cut and paste of JSON). So I think you should aim for:

1. Click on the "Undo/Redo" button in the top right corner of the screen.
2. In the "Undo/Redo" panel, click on the "Apply" button.
3. In the "Apply Operations" dialog box, click on the "Import..." button.
4. In the "Import Operations" dialog box, select the JSON file that contains the operation history you want to apply.
5. Open the file and the file content will be populated into the window
6. Click on the "Perform operations" button to apply the operations to your current OpenRefine Project

**Comment by IjayAbby** [comment]
Yes I have, do you happen to be free we do a quick call maybe I will understand it better.

**Comment by ostephens** [comment]
I'm afraid I can't do a call today

**Comment by IjayAbby** [comment]
Okay let me try this and I will reach out.

**Comment by IjayAbby** [comment]
https://github.com/OpenRefine/OpenRefine/pull/5748
@ostephens, I managed to create the button but my function is not working well due to the URL on line 355. Advice me on how to best approach this.
Link to [pull request](https://github.com/OpenRefine/OpenRefine/pull/5748)
Thanks.
