### ISSUE TITLE
Migrate calls to String::trim() to Guava's whitespace trimming

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5105]
<s>Java 11 introduced the `String::strip()` method, which strips whitespace around a string, including newer Unicode whitespace characters.
We currently use the `String::trim()` method in a number of places. In many of those places, the string being trimmed can legitimately contain any Unicode character, so `String::strip()` should be used instead.

Since OpenRefine now requires Java 11+, we can migrate to `String::strip()` in most places. Note that `String::trim()` apparently removes the `\u0000` character and `String::strip()` does not, but I am not sure if that is relevant anywhere for us.</s>

We should rather migrate to Guava's whitespace trimming, see [@ostephens's post below](https://github.com/OpenRefine/OpenRefine/issues/5105#issuecomment-1275219596).

**Comment by tfmorris** [comment]
It's probably worth replacing the Guava com.google.common.base.CharMatcher calls used for whitespace stripping as well to minimize external dependencies.

**Comment by sritejap** [comment]
@elroykanye Are you working on this?

**Comment by elroykanye** [comment]
Hi @sritejap , I have not had enough time to look into this. If you are interested in the issue, I can assign this to you.

**Comment by vijal-patel** [comment]
I could look into this if no one is working on it right now

**Comment by vijal-patel** [comment]
Hi all, I see we already have a class called TrimTests. 

> It's probably worth replacing the Guava com.google.common.base.CharMatcher calls used for whitespace stripping as well to minimize external dependencies.

wrt this, I've found 1 usage of that class for white space stripping ([link](https://github.com/OpenRefine/OpenRefine/blob/master/main/src/com/google/refine/expr/functions/strings/Trim.java#L52))
but chaning this to use .strip() results in unit test failures for non-breaking space, figure space etc.

Shall I leave this one as is?

**Comment by ostephens** [comment]
So we have different options for stripping whitespace/space characters from a string:

- String::trim() -> strips `any character whose codepoint is less than or equal to 'U+0020' (the space character).`
- String::strip() -> strips any characters for which [Character::IsWhitspace()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Character.html#isWhitespace(int)) == TRUE
- com.google.common.base.CharMatcher.whitespace().trimFrom() -> strips any characters [defined by Unicode as whitespace](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5Cp%7Bwhitespace%7D)

Character::IsWhitespace() specifically excludes non-breaking spaces ('\u00A0', '\u2007', '\u202F') which is why the tests are failing when you change the method there.

Since the use of the Guava method was introduced explicitly so that non-breaking spaces were included in the GREL trim command (see https://github.com/OpenRefine/OpenRefine/commit/f29f77e8f8a0024deb50b3a13dec2874c859a7fb) it seems like we should preserve this behaviour.

I would flag that trimming of non-breaking spaces is also being asked for explicitly by #5246 - but in a place we currently use String::strip() ... so I wonder if we should rather move to the use of the Guava method at least in that scenario for consistency and to meet this user need?

**Comment by wetneb** [comment]
Thanks @ostephens for investigating this - I have not looked much in the details but I trust your judgment and update the issue to reflect that.

**Comment by tfmorris** [comment]
I agree with @ostephens analysis. I had forgotten that Java's definition of whitespace doesn't match the Unicode Consortium's definition, making `strip()` unsuitable for OpenRefine's use.

https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#trim()
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#strip()
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Character.html#isWhitespace(int)

**Comment by vijal-patel** [comment]
thanks, if that's the case then I've definitely messed up somewhere when setting up this repo in IntelliJ
`[ERROR]   ToStringTests.testToString:50 expected [100.0] but found [100,0]
`

**Comment by wetneb** [comment]
This should have been fixed a few days ago by https://github.com/OpenRefine/OpenRefine/pull/5326, so make sure you have an up to date version of the master branch.
Can we move this discussion to a support forum (such as the [openrefine-dev mailing list](https://groups.google.com/g/openrefine-dev) or the [Gitter channel](https://gitter.im/OpenRefine/OpenRefine))? We try to keep GitHub issues focused on one particular topic.
