### ISSUE TITLE
[doc] docusaurus installation instructions missing

### ISSUE THREAD

**Issue by VladimirAlexiev** [OpenRefine/OpenRefine#5120]
https://docs.openrefine.org/technical-reference/contributing says
> you can install Docusaurus with

and then the commands are missing.

Maybe cite something from https://docusaurus.io/docs/installation and make a link to that page?

**Comment by wetneb** [comment]
I think the instructions are all there, it is just that they start after "You will need to install [Yarn](https://yarnpkg.com/getting-started/install) before you can build the site." Worth reformulating indeed!

**Comment by VladimirAlexiev** [comment]
@wetneb I made a mistake in making a PR in my repo instead of this one. Can you take the PR from there, or should I "move" it here? (I'm not sure how to do that)

**Comment by wetneb** [comment]
I think you could just create a new one. This should be a good place to start:
https://github.com/OpenRefine/OpenRefine/compare/master...VladimirAlexiev:OpenRefine:VladimirAlexiev-issue-5120
although it shows more changes than this PR, perhaps because of the structure of your branches in your fork. If you create one branch per PR, branching off from master, this should avoid such issues.

**Comment by VladimirAlexiev** [comment]
I know, that's the mistake I made: branched off from patch-4. will redo
