### ISSUE TITLE
Allow specifying project_id (but not replacing input files in project)

### ISSUE THREAD

**Issue by VladimirAlexiev** [OpenRefine/OpenRefine#5123]
https://docs.openrefine.org/technical-reference/openrefine-api has limited operations on projects: create (and upload inputs), apply operations, export data, delete.

We use OntoRefine to automate knowledge graph building pipelines (through https://github.com/Ontotext-AD/ontorefine-cli).
OntoRefine is based on OpenRefine, but adds an RDF mapping UI and a virtual SPARQL endpoint over OR data.
We generate SPARQL update queries based on a semantic model of the data that look like this https://github.com/VladimirAlexiev/rdf2rml/blob/master/doc/rdf2ontorefine.txt#L131:

```sparql
      delete where {graph $GRAPH {?s ?p ?o}};
      insert {graph $GRAPH {
        <Insert Patterns>
      }}
      where {
        service <rdf-mapper:ontorefine:PROJECT_ID> {
          <Generated Binds>
        }
      };
```

Because of the above API limitation, we have to use this workflow for each data file:
1. Create a project and upload input data, get the project ID
2. Edit the query to replace the `PROJECT_ID` placeholder with the actual ID
3. Run the query against a GraphDB repository, which inserts data into it
4. Delete the project

Instead, we'd like to use this workflow:
1. Create a project with predefined ID and no data;
    THEN for each data file
2. Upload the data into the project
3. Run the query against a GraphDB repository
4. Clear the project data (to free up memory)

If it's hard/impossible to replace data files in an existing project,
then can only the "specifying project_id" feature be implemented?

**Comment by antoine2711** [comment]
> If it's hard/impossible to replace data files in an existing project,
> then can only the "specifying project_id" feature be implemented?

@VladimirAlexiev : have you tried the or-cli functionalities?
https://github.com/opencultureconsulting/openrefine-client

I think you could do you workflow with that. Create a project from an import, extract the Project_ID, adjust your query and executing it (this last part maybe not from OR, but still scripted).

Regards, Antoine

**Comment by wetneb** [comment]
Here, the usual caveat (mentioned at https://docs.openrefine.org/technical-reference/openrefine-api) applies: that this web API is considered internal, and may change independently of our semantic versioning. Because of that, I would be reluctant to introduce a feature in the API that is not used by our frontend.

Adding a command to upload more data in a project can be done (either in OpenRefine, in an extension, or in a fork like OntoRefine), but to respect the current guarantees offered by the tool, I would do this by implementing a new operation (which would therefore add a new entry in the history of the project, to make sure the change is versioned and can be undone). I would discourage implementing a command which simply modifies project data without changing the project history.

Pre-allocating a project id seems to be against the spirit of the current architecture, where project ids are internal to our backend and are therefore primary keys that users should have no control over.
Why not change your RDF mapper so that projects can be referenced by name instead of project id? This would likely be more user-friendly.

Of course, the immediate problem you would have is that project names are not currently guaranteed to be unique. But this is something that has been requested before (although I cannot find an issue for it right now) and would probably be worth introducing, for instance because we currently let users reference projects by name in the `cross` GREL function.

This would enable the following workflow on your side:
1. Create a project with a predefined name by uploading data to OpenRefine
2. Run the query against a GraphDB repository
3. Clear the project data (to free up memory)

**Comment by VladimirAlexiev** [comment]
@antoine2711 Thanks! We already do that with https://github.com/Ontotext-AD/ontorefine-cli (written in Java), see `we have to use this workflow for each data file` above.

@wetneb 
> implementing a new operation (to upload more, or to replace data)

Makes sense. Should I post a separate issue for it? 
And what would be the savings compared to recreating a project from scratch?

> change your RDF mapper so that projects can be referenced by name instead of project id?

Two concerns:
- permanence: Projects cannot be renamed, right? So the name is just as permanent as the ID?
- suitability as URL fragment: if the name is "400+_Tools_and_innovations_in_scholarly_communication - data collection forms",
  I wouldn't want to have to use a URL like 
  `<rdf-mapper:ontorefine:400%2B_Tools_and_innovations_in_scholarly_communication%20-%20data%20collection%20 forms>

**Comment by wetneb** [comment]
> Makes sense. Should I post a separate issue for it?

It depends if you can frame it in a way that makes sense from the point of view of an OpenRefine user (in which case it makes sense to have a feature request here), or if it something really taylored to OntoRefine's use cases (in which case you could implement your own operation in OntoRefine).

> Projects cannot be renamed, right? So the name is just as permanent as the ID?

Projects can be renamed (in the project page, click on the project name and it will prompt you for a new name).

> suitability as URL fragment

That makes sense.

**Comment by VladimirAlexiev** [comment]
> frame it in a way that makes sense from the point of view of an OpenRefine user

I think the main purpose of having all these CLIs is that people use OR as part of automated ETL pipelines,
using two similar scenarios:
- develop the ETL script on one file, then run on 100
- develop the ETL script on 10% of a large file, then run it on all 100%

Either scenario needs the ability to replace the data within a project.
But before I post such feature request: what would be the savings compared to recreating a project from scratch?

--

> Projects can be renamed 

- Which API does that?
- Then using the project name as "handle" to the project is not a good idea.

>Pre-allocating a project id seems to be against the spirit of the current architecture, where project ids are internal to our backend and are therefore primary keys that users should have no control over.

This doesn't seem to be an architectural principle but a UX consideration.
As soon as the ID is unique, immutable and URL-friendly, why can't it be controlled by the user?
That UX consideration may be valid for novice users, but I don't think it's valid for advanced users.

Eg our @nikolatulechki posted this issue on May 13, 2022 :
> As a user I want the projectId in openRefine somewhere immediately visible and copyable
![image](https://user-images.githubusercontent.com/536250/181170329-ac328d43-64cd-4d8a-8fee-ed014ca793e6.png)

@thadguidry what do you think?

**Comment by wetneb** [comment]
> I think the main purpose of having all these CLIs is that people use OR as part of automated ETL pipelines, using two similar scenarios:
> 
>     * develop the ETL script on one file, then run on 100
> 
>     * develop the ETL script on 10% of a large file, then run it on all 100%
> 
> 
> Either scenario needs the ability to replace the data within a project.

I am also interested by those scenarios but I do not think they require replacing the data within a project.

> But before I post such feature request: what would be the savings compared to recreating a project from scratch?

I cannot think of any performance benefits honestly! What would worry me the most with such an approach would be the loss of the architectural guarantees which come with the existing immutability of versions of a given project. But of course I might be misjudging what you are proposing.

> 
> > Projects can be renamed
> 
>     * Which API does that?

On top of my mind, `set-project-metadata` or something like this, but I might be wrong. Because this API is internal, the way to find out is to open the "Network" tab of your web inspector in your browser, and observe the network calls that are made when you make the corresponding action in the UI.

> This doesn't seem to be an architectural principle but a UX consideration. As soon as the ID is unique, immutable and URL-friendly, why can't it be controlled by the user? That UX consideration may be valid for novice users, but I don't think it's valid for advanced users.

This is basically the same reason why, say, Wikidata will not let you pick the Qid of an item you create, or Google Sheets will not let you choose the hash that identifies your spreadsheet. You have the possibility to generate fresh ones and that should be enough.

**Comment by thadguidry** [comment]
Allowing an id to be chosen to create and identify a project by might be useful by a small group of users.  In OpenRefine we would have to add support for detecting an already used id and fail with warning. In the UI the workflow would have an intermediate step where Create Project also shows the id and allow change before Project is initiated.

Other APIs and services have to be rigid in unique ids minted because they control the service, the user uses the service.  I think in the case of OpenRefine, we certainly could give control to them on how they wish to identify a project, and should give them more control on this.  It's a bit of work, but probably something worthwhile to do.  

@VladimirAlexiev Are you thinking that OntoRefine could contribute this or sponsor the effort?

**Comment by VladimirAlexiev** [comment]
@wetneb 
>> savings compared to recreating a project from scratch?
> I cannot think of any performance benefits honestly! 

Producing the column model and other project metadata? 
If that is done on 1k rows, and then a file of 10M rows is put in its stead, will that save any time?

It seems that "replace project data" is not a profitable idea: one more negative answer and I'll drop it.

--

> `set-project-metadata`

Not documented at https://docs.openrefine.org/technical-reference/openrefine-api. 
I traced what happens in "Open Project>About" and I'll document `set-project-metadata` and `set-project-tags`

> Wikidata will not let you pick the Qid ... Google Sheets will not let you choose the hash 

Maybe because there's no case to replace the content of these entities while keeping the ID.

In contrast, the IDs in DBpedia come from page names in Wikipedia, and are selected by people 
(through a social process that eg allocated `Sofia` to my city, but `Sofia (Filipino singer)` to that lady).

@thadguidry 
>OntoRefine could contribute?

Possibly.

**Comment by tfmorris** [comment]
100% agree with @wetneb. Pretty much every API I've ever used returns a system created ID as the result of a Create operation rather than allowing the caller to specify it.

A better approach, I think, would be to make the Create operation more lightweight and not include any of the current implicit data import. A separate "Import Data" command could be split out to operate on the newly created empty project. This would also give better coverage with the project history.

Of course, since the current protocol wasn't designed for, and isn't documented or supported for, external use, there would be a bunch of prerequisite work to enable third party users first.

**Comment by nikolatulechki** [comment]
Given that the main use case for this request is have a means for consistently referring to a project, we will probably develop a mechanism to set a project alias (or even simpler, just sanitize and use the name) and have the possibility to use that in the URI of the virtual SPARQL endpoint. 

This seems simpler and keeps the work on the Ontotext Refine side and will not need extensive modification  of the OpenRefine codebase.

**Comment by thadguidry** [comment]
Sounds good @nikolatulechki , then well close this issue.
