### ISSUE TITLE
Add ability to rename, delete and export schema templates

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5280]
We recently introduced the notion of "schema template", which helps the user start from a skeleton of Wikibase schema instead of creating one from scratch.
Users can currently create their own schema templates, but they are not able to:
* rename them
* delete them
* export them to JSON

### Proposed solution
We should have an additional dialog which lists the templates stored for the current Wikibase instance, letting the user perform the actions above.

### Alternatives considered
It was also suggested by @lozanaross to store those schema templates in a directory of the file system, and let the user perform those operations using their file manager. While this is attractive (no need to re-implement our own file manager), templates are currently stored in the preference store (so in `workspace.json`), so it would be involved to change that.

### Additional context
Part of the Wikimedia Commons integration project.

**Comment by lozanaross** [comment]
Proposing a sample management dialog: 
![SDC_Wireframes_SchemaTemplate_managementDialog](https://user-images.githubusercontent.com/25489750/192158840-1befc04f-3faf-4464-ba5a-4cc50847a3fb.png)

(I am proposing the option to select multiple templates, so that they can be downloaded via same button, but if it's easier to just have separate rename / delete / download options next to each template name, that's also OK.)

Users can get to this management dialog via the "Save new..." dialog:
![SDC_Wireframes_SchemaTemplate_saveDialog](https://user-images.githubusercontent.com/25489750/192158937-c58cfff4-5869-477c-b86c-ae3e3c4cb2b6.png)
