### ISSUE TITLE
Dysfunctional reconciliation dialog window in OpenRefine 3.7 snapshots (since around Sep 20, 2022)

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#5285]
I tried reconciling against Wikidata in a large-ish dataset using our 3.7 snapshot release, and the reconciliation dialog appears wonky at the bottom. The `Start reconciling` and `Cancel` buttons are dysfunctional (nothing happens when clicking them).

<img width="906" alt="image" src="https://user-images.githubusercontent.com/9881645/192108615-8fce38f3-1257-41a6-b822-b3b68aa27658.png">

### To Reproduce

The bad things happened with this dataset: [homosaurus-v3-jsonld.openrefine.tar.gz](https://github.com/OpenRefine/OpenRefine/files/9639142/homosaurus-v3-jsonld.openrefine.tar.gz)
I tried reconciling the `http://www.w3.org/2004/02/skos/core#prefLabel` column
In Version 3.7-SNAPSHOT [549f83b] and the September 21 snapshot release.

I loaded this same dataset in OpenRefine 3.6.1 on Wikimedia PAWS, where the window does behave as expected, so it seems like the issue was recently introduced.

### Versions
 - Operating System: MacOS 12.6
 - Browser Version: Chrome Version 105.0.5195.125 (Official Build) (arm64)
 - JRE or JDK Version: n/a?
 - OpenRefine: Version 3.7-SNAPSHOT [549f83b] and the September 21 snapshot release

**Comment by elebitzero** [comment]
@trnstlntk , this is also reproducible in 3.5.2 and 3.6.1. It happens when the list of types doesn't have any long entries which makes the width of the column is narrower, and the controls at the bottom are in that same column so they wrap. You can see what happens in screenshots below (from 3.5.2):
![image](https://user-images.githubusercontent.com/42903164/192170905-cec63842-a158-4afb-8a6d-d2827781bc2f.png)
![image](https://user-images.githubusercontent.com/42903164/192170910-5a94872a-c137-4475-a39f-3e11f16ffdff.png)
