### ISSUE TITLE
Media file upload: provide clear error report when user has mistakes in local file paths

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#5298]
I've encountered a case where an OpenRefine user tried to upload media files to Wikimedia Commons. The upload failed because the (MacOS) file paths in the user's dataset didn't start with a `/` (very subtle!)

The user didn't get any error messages and it took a bit of searching to discover this issue. Maybe this will occur more frequently if users start from datasets with pre-entered local file paths.

### Proposed solution
Perform a general/rough check if the file path is formatted correctly and provide the user with a clear error message if there are obvious mistakes in there (e.g. missing drive letter in Windows paths, missing starting `/` for MacOS paths, wrong directions of (back)slashes, missing file extensions...?)

Related / similar: https://github.com/OpenRefine/OpenRefine/issues/5192

**Comment by wetneb** [comment]
There are various checks we can do here:
* whether the path is indeed an absolute path: we probably want to enforce this, because it is unlikely that local paths would make much sense (although in some hosted contexts you might want to rely on them? it feels rather unlikely to me). Checking this is very cheap.
* whether there actually is a file at the given path. That probably going to catch a lot more mistakes, but I wonder if we can really afford to run those checks in real time: it would mean making a lot of disk accesses at every change in the project. So I think this is really a good case for #5037.
