### ISSUE TITLE
Provide error message when user tries to upload duplicate files

### ISSUE THREAD

**Issue by trnstlntk** [OpenRefine/OpenRefine#5337]
I am trying to upload duplicate files to Wikimedia Commons, and I am indeed not succeeding in doing so, which is great. I am trying to upload files that already exist on Commons, with the exact same file name, from this project: (only the two first, flagged rows, using the filename2 column) 
[Jan-Geerling-photographs-Rotterdam-1503.openrefine (2).tar.gz](https://github.com/OpenRefine/OpenRefine/files/9778264/Jan-Geerling-photographs-Rotterdam-1503.openrefine.2.tar.gz)

The upload process is stuck at 0% but the user doesn't get any feedback or error messages, and I think it would be good to have these; otherwise the user is left in the dark about what they may be doing wrong.

**Comment by wetneb** [comment]
For upload-time error messages, we still need #4236 / #5032. We have sadly not got the infrastructure for this yet.

My hope is that we can do those checks earlier, as part of the Issues tab, so that this is reported even before the upload. Arguably that is even a better UX than ending up with a partially failed batch of uploads that you are not too sure how to fix afterwards (asking for deletion and uploading again is quite cumbersome).
