### ISSUE TITLE
junit flaky test in main

### ISSUE THREAD

**Issue by anantdahiya8** [OpenRefine/OpenRefine#5425]
We detected the existence of flaky junit test in main using [NonDex](https://github.com/TestingResearchIllinois/NonDex)

test:
https://github.com/OpenRefine/OpenRefine/blob/ed5e90e59cfd5edb4cac620b5966eae06d5787c7/main/tests/server/src/com/google/refine/clustering/binning/BinningClustererTests.java#L77

### To Reproduce
`mvn -pl main edu.illinois:nondex-maven-plugin:2.1:nondex`

### Current Results
The junit test can fail since the order of elements in clusterer can randomize

### Expected Behavior
The junit should pass always
PR : https://github.com/OpenRefine/OpenRefine/pull/5426

### Screenshots
Debug Screenshot
![image](https://user-images.githubusercontent.com/20678029/201248422-9b6699fc-dbdd-4876-8a39-a0fdab2eca6f.png)

**Comment by wetneb** [comment]
Thanks for this!

I am a bit puzzled - the screenshot you included shows differences in the order of keys in JSON nodes, but that is something that our `TestUtils.isSerializedTo` method accepts because it does compare the serializations as JSON objects and not as strings.
So it should rather be a difference in the order in which clusters or cluster components are listed.

**Comment by anantdahiya8** [comment]
Yaa it does, but if the order of the objects changes in the array, the equals method return false
![image](https://user-images.githubusercontent.com/20678029/201302475-78729f98-15fe-41f7-9f09-8864bc4b6ad7.png)
![image](https://user-images.githubusercontent.com/20678029/201302522-e4907a4a-8a4b-49dd-834f-a482d7565ae8.png)

**Comment by tfmorris** [comment]
Closing per comments here and the associated PR
