### ISSUE TITLE
"Clear reconciliation data" not clearing all reconciliation data

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#545]
_Original author: danpaulsmith (March 05, 2012 10:28:35)_

Hi,

I've noticed that after clicking the menu item &quot;Clear all reconciliation data&quot; for a column - the column object in the columnModel still has the properties &quot;reconConfig&quot; and &quot;reconStats&quot; - which are both populated.

The extension we're working on attempts to detect whether the user has reconciled columns previously by looking for columns that have the &quot;reconConfig&quot; and &quot;reconStats&quot; properties.

If the user decides to clear their reconciliation data - these properties do not disappear - which as a result, looks like they are not clearing their reconciliation data.

Dan

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=545_

**Comment by thadguidry** [comment]
@wetneb Do we have tests for this and they pass?  If so, then we can close this issue.

**Comment by wetneb** [comment]
If you found tests for this, can you paste a link to them?

**Comment by thadguidry** [comment]
https://github.com/OpenRefine/OpenRefine/blob/150ee12058e1503771e946090d041cca7ba80523/main/tests/server/src/com/google/refine/tests/operations/recon/ReconClearSimilarCellsOperationTests.java

https://github.com/OpenRefine/OpenRefine/blob/150ee12058e1503771e946090d041cca7ba80523/main/tests/server/src/com/google/refine/tests/operations/recon/ReconDiscardJudgmentsOperationTests.java

**Comment by wetneb** [comment]
@thadguidry these tests do not check the behaviour of the operations, they only check JSON serialization.

**Comment by ostephens** [comment]
I don't understand what the requirement is here. @thadguidry do you have a clear idea of what the behaviour should be when a user selects to "Clear reconciliation data"?

**Comment by thadguidry** [comment]
It used to clear (reset) the matched id's.  Effectively (and destructively) removing all matched id's as well as proposed candidate matches.  This would also show up visually as the green bar for "left to reconcile" was completely clear.

**Comment by ostephens** [comment]
That's what it does currently. My reading of this issue is that the requester wanted it to not only clear the matches/proposed matches, but also remove the "reconConfig" and "reconStats" properties - but I don't understand the reasons beyond "we are writing an extension that will look at these properties for some reason"

Given this was first requested in 2012 I think we could assume the extension has either been written or abandoned (or both!) in the meantime.

My vote would be to just close this now as changing the behaviour without understanding the requirement seems like a bad idea

**Comment by thadguidry** [comment]
Agreed. Thanks Owen.
