### ISSUE TITLE
XLS tests are locale-dependent

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5464]
The tests for XLS importer can fail depending on the locale they are run with.

### To Reproduce
Steps to reproduce the behavior: run `mvn test` in the `fr.FR` locale (unfortunately there does not seem to be a CLI argument to set that).

### Current Results

```
[ERROR] readXlsxAsText(com.google.refine.importers.ExcelImporterTests)  Time elapsed: 0.1 s  <<< FAILURE!
java.lang.AssertionError: expected [1.1] but found [1,1]
	at com.google.refine.importers.ExcelImporterTests.readXlsxAsText(ExcelImporterTests.java:224)
```

### Expected Behavior
The tests should pass.

### Versions
 - OpenRefine: master branch

### Additional context
Intuitively the locale dependency of OpenRefine's behaviour is expected here, since we are just preserving the string representation of values in the XLS file, which are locale dependent, so I would say we should just ensure the tests accept that.

It could be even better to give the user the option to select the locale in which the values should be represented, but I am not even sure POI lets us configure that.

**Comment by tfmorris** [comment]
Not all Excel formats are locale dependent, but many, including the most popular ones, are explicitly documented to vary with the locale setting. Apache POI mirrors this behavior, as it should.

I'll pin the locale in the tests so that they pass. If you want locale settings for importers, please open a separate enhancement request.
