### ISSUE TITLE
Enhance `forRange` to accept negative increments

### ISSUE THREAD

**Issue by ostephens** [OpenRefine/OpenRefine#5520]
`forRange` allows iteration based on a defined range of numbers and an increment, but currently only works if the increment is positive. Current examples:
```
forRange(0,10,1,i,i) -> [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
forRange(10,0,-1,i,i) -> [  ]
```

This is different to the `range()` function where a negative increment is accepted:
```
range(0,10,1) -> [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ]
range(10,0,-1) -> [ 10, 9, 8, 7, 6, 5, 4, 3, 2, 1 ]
```

### Proposed solution
forRange could be enhanced to work with a negative increment
It might also be a good idea to reject invalid arguments - for example currently:
```
forRange(10,0,1,i,i)
```
As there is no way of incrementing by 1 to get from 10 to zero, this should be rejected as invalid parameters, whereas instead it currently returns an empty array

### Alternatives considered
It is possible to use `range` combined with `forEach`:
```
forEach(range(10,0,-1),v,v) -> [ 10, 9, 8, 7, 6, 5, 4, 3, 2, 1 ]
```
This isn't hugely more complicated but it seems that `range` and `forRange` should be consistent with each other

**Comment by Huishin-pie** [comment]
Hello, I have read the document and tried to use grel to deal with data. Could you please assign this task to me? Thank you!

**Comment by wetneb** [comment]
Thanks for volunteering! Do not forget to unassign yourself if you stop working on this.

**Comment by Huishin-pie** [comment]
Ok, I will. Thanks for the reminder.

**Comment by Huishin-pie** [comment]
Hello, I have some questions.
1. What kind of data types of arguments are accepted for forRange? I saw the else block on line 98, which has made me a little confused. Should it be the same as Range?
2. If there are some invalid arguments, such as step == 0, Range currently returns an empty array. Could I modify its return value together?
![螢幕擷取畫面_20230213_030230](https://user-images.githubusercontent.com/58845513/218331433-2850364e-7ea7-44c8-902f-60edaf6bb167.png)
![螢幕擷取畫面_20230213_030257](https://user-images.githubusercontent.com/58845513/218331441-3d0be2dd-5fc9-42a5-b5d6-87302dbf6a90.png)

**Comment by tfmorris** [comment]
I'm not surprised you're confused! I am too after looking at the code. 

BTW Github has a nice permalink feature that you can use to make it easy for people to find your code references. If you click on the line numbers of the source listing on the Github website to select a line (or shift click to select multiple lines), then click on the "...", you'll see a drop down menu that includes "Copy Permalink"

![Screen Shot 2023-02-12 at 2 47 03 PM](https://user-images.githubusercontent.com/82178/218333519-517d3c41-58e8-4faf-93aa-55a664460601.png)

Pasting it into your comment gives you this:
https://github.com/OpenRefine/OpenRefine/blob/b2553c916c18d0ae26971b19ea07b03c41f91159/main/src/com/google/refine/grel/controls/ForRange.java#L98-L101

That section of code looks like it has a copy/paste bug in it where the `.longValue()` calls weren't updated to `.doubleValue()` when the code was copy/pasted from the section above.

> What kind of data types of arguments are accepted for forRange? I saw the else block on line 98, which has made me a little confused. Should it be the same as Range?

`forRange()` was written first and appears to be intended, to my eye, to include support for both integer and floating point values (although it doesn't work because of the above bug). The `range()` implementation goes a different direction but I would ignore it for the purposes of this ticket. It also seems quite complex, which is another good reason to ignore it.

> If there are some invalid arguments, such as step == 0, Range currently returns an empty array. Could I modify its return value together?
https://github.com/OpenRefine/OpenRefine/blob/b2553c916c18d0ae26971b19ea07b03c41f91159/main/src/com/google/refine/expr/functions/strings/Range.java#L306-L309

I think it would be useful for both functions to take the same arguments and have the same return behavior, but I'd leave that as a separate task and just focus on `forRange()` here. We can create a separate ticket to resolve the differences in behavior between the two functions (both parameters and returns).

**Comment by Huishin-pie** [comment]
I didn't know about the permalink feature. Thank you for telling me about it.
I am preparing to create a pull request, and then I will keep working to resolve the differences between the two functions. May I try to create a new issue for this?

**Comment by tfmorris** [comment]
Great! I'll have a look at the PR.

> May I try to create a new issue for this?

Thank you for offering! There's some background historical information that I'd like to include, which you probably aren't aware of, so I'll take care of creating the issue, but I appreciate the offer.
