### ISSUE TITLE
Suggest property query includes a type when none is selected

### ISSUE THREAD

**Issue by nhervieu** [OpenRefine/OpenRefine#5523]
When reconciling a column, using a service that supports a `/suggest/property` endpoint, if I select `Reconcile against no particular type`, OpenRefine includes the most recently selected type in the query.

For example, in this screenshot, I selected `Reconcile against no particular type` and then started typing `test` in the `As property` box.

<img width="926" alt="Screen Shot 2022-12-14 at 4 40 06 PM" src="https://user-images.githubusercontent.com/16618618/207953210-0b2413b5-d5c7-436a-9ae6-e381bbc3ca2f.png">

### Current Behavior
In that example, OpenRefine sent the following request to the reconciliation service:

`https://wikidata.reconci.link/en/suggest/property?prefix=test&spell=always&exact=false&scoring=schema&prefixed=true&type=Q223393`

### Expected Behavior
I would expect the type to be sent in the suggest/property query if one is selected so that a reconciliation service has the option to filter the suggested properties by the included type.

If `Reconcile against no particular type` is selected, then I expect no type to be included in the query so that the reconciliation service does no filtering on the suggested properties.

### Versions
 - Operating System: MacOS Monterey
 - Browser Version: Chrome
 - JRE or JDK Version: JDK 13.0.2
 - OpenRefine: Version 3.6.2

### Additional context
I'm creating a reconciliation service and this affects how we need to implement the internal logic of the suggest property endpoint.

**Comment by wetneb** [comment]
Adding the "reconciliation API design" tag because this parameter isn't mentioned by the specs yet. It would be good to align the theory and practice here. I would recommend adding the `type` parameter to the specs and removing the unspecified parameters from the calls OpenRefine is making.

**Comment by ostephens** [comment]
@wetneb I don't understand the link to the reconciliation API design - isn't this just a bug that the type is included here when it shouldn't be?

**Comment by wetneb** [comment]
Well it looks like @nhervieu is trying to use this information in her service, so instead of removing it, I am proposing (in https://github.com/reconciliation-api/specs/issues/104) to include it in the specs.

Given that the specs were originally written to match OpenRefine's behaviour, and this has been around for years, the fact that this parameter is not in the specs is actually an oversight on my part.

**Comment by ostephens** [comment]
>Well it looks like @nhervieu is trying to use this information in her service, so instead of removing it, I am proposing (in https://github.com/reconciliation-api/specs/issues/104) to include it in the specs.
I'd understood the issue being reported here to be that it's being included even when `Reconcile against no particular type` has been selected, and that limits the response to the type that was previously selected - which is not desired.

**Comment by wetneb** [comment]
Yes absolutely, but according to the current specs, this `type` parameter just does not exist - it should never be passed at all.

So either we decide to indeed drop it from OpenRefine entirely, or we update the specs to allow it. Or we decide to diverge from those specs, I guess?

**Comment by ostephens** [comment]
> So either we decide to indeed drop it from OpenRefine entirely, or we update the specs to allow it. Or we decide to diverge from those specs, I guess?

OK - just want to keep this issue focussed on fixing the current bug - which doesn't seem to be either of the options you mention

**Comment by wetneb** [comment]
> OK - just want to keep this issue focussed on fixing the current bug - which doesn't seem to be either of the options you mention.

Perhaps it's nitpicking but the current bug is not a bug if this parameter does not mean anything according to the specs - as services are not supposed to rely on it.

> this parameter works exactly as expected on the Wikidata reconciliation api end

I do not think this parameter is used on the Wikidata endpoint (there is a type parameter in the "propose properties" endpoint, not in the "suggest properties" one - perhaps we should find better names to distinguish them)

**Comment by ostephens** [comment]
> I do not think this parameter is used on the Wikidata endpoint (there is a type parameter in the "propose properties" endpoint, not in the "suggest properties" one - perhaps we should find better names to distinguish them)

OK - in that case I've misunderstood the report and sincere apologies. I had read the statement "This affects our service’s ability to only return property suggestions given the selected type, because it won’t display all relevant properties when no type is selected." in [the forum post](https://forum.openrefine.org/t/suggest-property-request-always-includes-a-type/264) to mean they were already seeing this behaviour with an existing service.

I now understand this isn't the case - thank you for clarifying

**Comment by tfmorris** [comment]
We need to keep the discussion of OpenRefine bugs and spec bugs separate.

> I'd understood the issue being reported here to be that it's being included even when Reconcile against no particular type has been selected, and that limits the response to the type that was previously selected - which is not desired.

I agree with this interpretation.

> Perhaps it's nitpicking but the current bug is not a bug if this parameter does not mean anything according to the specs - as services are not supposed to rely on it.

If you're talking about the draft W3C spec, I don't think it's relevant. What's relevant is that OpenRefine is sending a parameter value which doesn't represent what the user selected in the UI. That seems like a clear bug to me. I don't think fixing it would have a negative affect on compatibility with existing services.

> So either we decide to indeed drop it from OpenRefine entirely, or we update the specs to allow it. Or we decide to diverge from those specs, I guess?

It's strongly desirable that the W3C spec preserve backward compatibility with OpenRefine, but it's a separate issue from whether or not OpenRefine breaks compatibility with existing reconciliation services. I don't see why we'd remove functionality in a backward-incompatible fashion without very strong motivation and lots of advance notice to the reconciliation service developers.

**Comment by epaulson** [comment]
As a reminder in another place where OpenRefine departs from the Reconciliation API spec, or at least does something unanticipated by the recon API spec - in #4224 it looks like OpenRefine "preflights" a couple of rows to a recon API server when the user is getting set up with the service - so before the user has pressed 'Start Reconciling...'  OR has sent a couple of rows over to the service to see what the responses look like (and in particular, it uses the types on candidate matches that come back from that "preflight query" as the possible types it presents to the user, rather than looking at the manifest of the recon service)

It might not be a terrible idea for OpenRefine to be able to say "use old OR behavior against this recon API server" to preserve backwards compatibility if the recon API server isn't advertising the right things the service's manifest.

**Comment by wetneb** [comment]
From my perspective this "preflight" query has not got the same sort of status in terms of specs compliance: this conforms to the specs because those preflight requests are valid reconciliation requests on their own. Clients are free to make successive recon requests with slightly varying data. As an end user I often find myself reconciling some rows multiple times anyway (by faceting and using different settings). But that's probably a discussion for another issue.

**Comment by epaulson** [comment]
The preflight is something the spec should consider - maybe there's a better way to support what the OR preflight is doing - but that can be a discussion on the other repo. 

I don't think the preflight from OR is documented anywhere right now and it was a heck of a surprise when implementing a service, especially since OR makes decisions about what types to use before the user in theory has any opportunity to steer it in the right direction.

**Comment by tfmorris** [comment]
It's a garden variety bug with a simple fix that I've put up for review in #5543.

**Comment by tfmorris** [comment]
@epaulson I'm pretty sure this isn't true

> [OpenRefine] makes decisions about what types to use before the user in theory has any opportunity to steer it in the right direction.

but if you have evidence to support it, please create a separate bug report for it.

**Comment by thadguidry** [comment]
@tfmorris well this will be true later, sorta.  It will depend on the reconciliation service manifest.  And relatedly https://github.com/reconciliation-api/specs/issues/104
