### ISSUE TITLE
The database extension overrides CSS styles from core

### ISSUE THREAD

**Issue by Abbe98** [OpenRefine/OpenRefine#5548]
The database extensions loads Yahoo's prue.css library which styles elements regardless of classes and as a result one must always ensure that core got styles which take priority to avoid side effects. 

### To Reproduce

Inspect any element on either the index or project page and check for styles coming from prue.css.

**Comment by wetneb** [comment]
It would be great to unify this, in particular the database import tab whose style is visually very different from the rest of the UI.

**Comment by Abbe98** [comment]
Here is a real world case of "defensive" CSS: https://github.com/OpenRefine/OpenRefine/pull/5549/files#diff-9e4f4a212289cd6dae9f95ec0125b852018db93e3f85544208f532e3a4d1748dR290

**Comment by thadguidry** [comment]
> It would be great to unify this, in particular the database import tab whose style is visually very different from the rest of the UI.

I think it's OK for extensions to be differently styled since they are not core.

**Comment by wetneb** [comment]
There are actually two different issues:
* The different styling: yes, it is in general okay, but for extensions which we ship by default, I think it makes sense to keep a consistent style.
* The fact that the included CSS leaks to the rest of the application: if the database extension wants a different styling, the CSS rules it includes should be qualified so that they only apply to the UI elements defined by the database extension, which is not the case

**Comment by thadguidry** [comment]
Hmm, and we should move the DB importer into core and not an extension...but that can happen later.
