### ISSUE TITLE
Execution of arbitrary Python code via the Jython extension: vulnerability?

### ISSUE THREAD

**Issue by Enoki-web** [OpenRefine/OpenRefine#5602]
step 1：Locate one or more files on your computer to upload
![image](https://user-images.githubusercontent.com/45222311/216535441-d5b48a81-e68b-4197-93af-5d52399007e7.png)

step 2:
![image](https://user-images.githubusercontent.com/45222311/216535039-ad95609a-45f5-408d-89fa-476aeae972a0.png)

Because of the way python and others can invoke system commands. Attackers can access unauthorized project files to execute code on the server, thereby paralyzing user services

step 3:
![image](https://user-images.githubusercontent.com/45222311/216534864-5e2bc89a-5d35-42bd-9d7b-43a1dadf167b.png)

I am a security engineer, and I hope that products will become more and more secure.

**Comment by Enoki-web** [comment]
all version

**Comment by wetneb** [comment]
Hi @Enoki-web, thanks for reporting this!

You are correct that we let users execute arbitrary Python code via the Jython extension. Because OpenRefine is designed to be run locally and for a single user, this is not a Remote Code Execution (RCE) vulnerability.

It could still generally make sense to have a bit more sandboxing around this feature, perhaps in a configurable way. [Jython](https://www.jython.org/), the Java implementation of Python we use, [has no support for that](https://github.com/jython/jython/issues/61).
We are considering migrating to other libraries to support Python 3, and we could potentially have more control with those: #2249.
In any case, it is not clear to me what we would want to allow or forbid exactly. People use it to spawn other processes, to call web services, to access files, all in intuitively legitimate ways.

**Comment by Abbe98** [comment]
I wonder if there are actual use cases for OS-level operations among OR users? Maybe we could otherwise find a way to block import of such modules? There is, however, a lot of them.

**Comment by Enoki-web** [comment]
> 



> 你好@Enoki-web，感谢您报告此事！
> 
> 您是对的，我们让用户通过 Jython 扩展执行任意 Python 代码。由于 OpenRefine 旨在为单个用户在本地运行，因此这不是远程代码执行 (RCE) 漏洞。
> 
> 围绕此功能进行更多的沙盒处理通常仍然有意义，也许是以一种可配置的方式。[Jython](https://www.jython.org/)，我们使用的 Python 的 Java 实现，[不支持它](https://github.com/jython/jython/issues/61)。 我们正在考虑迁移到其他库以支持 Python 3，我们可能会对这些库进行更多控制：#2249。 无论如何，我不清楚我们究竟希望允许或禁止什么。人们用它来生成其他进程、调用 Web 服务、访问文件，所有这些都以直观合法的方式进行。

Service doesn't look like it's running in a sandbox
![image](https://user-images.githubusercontent.com/45222311/216570633-5ce893ec-1af3-4c4b-9bd1-82d1f6053c64.png)

**Comment by Enoki-web** [comment]
So it is harmful, whether it is a hacker as a springboard or an intrusion into the user, it provides convenience. It is equivalent to a loophole in executing commands.

**Comment by Enoki-web** [comment]
> 我想知道在 OR 用户中是否存在操作系统级操作的实际用例？也许我们可以找到一种方法来阻止导入此类模块？但是，其中有很多。
Business and loopholes are mutually accomplished and closely related. Therefore, more consideration needs to be given to the risk at the user level. This can be said to be a vulnerability, because it can indeed be attacked, even if it is the function of the product itself. We all know that bugs are born from product features

**Comment by Enoki-web** [comment]
> 我想知道在 OR 用户中是否存在操作系统级操作的实际用例？也许我们可以找到一种方法来阻止导入此类模块？但是，其中有很多。

Can't stop a programming language, or a virus that works.

**Comment by Enoki-web** [comment]
> > 
> 
> > 你好@Enoki-web，感谢您报告此事！
> > 您是对的，我们让用户通过Jython扩展执行任意Python代码。由于OpenRefine先为单个用户在本地运行，因此这不是远程代码整理(RCE执行)。
> > 围绕功能多的处理通常有有意义，也许也许有以以以一一种种[种种](https://www.jython.org/)可可可可配置配置配置配置配置配置配置的的的的方式方式方式方式方式方式[方式](https://github.com/jython/jython/issues/61)。。。。。。。，[＃2249](https://github.com/OpenRefine/OpenRefine/issues/2249)。无论多：的方式进行。
> 
> 服务看起来不像是在沙箱中运行 ![图像](https://user-images.githubusercontent.com/45222311/216570633-5ce893ec-1af3-4c4b-9bd1-82d1f6053c64.png)

Hope to get a CVE number
![image](https://user-images.githubusercontent.com/45222311/216578377-829725d1-427a-4ae1-9827-2a7ff31dfa35.png)

**Comment by thadguidry** [comment]
Piped command access through Python is a very useful thing to have in multiple scenarios with OpenRefine especially when used as a local ETL tool in many aspects.  I have Jython in various ways with system access for instance to iterate through JSON files based on OpenRefine cell values and pluck out ID's and concat them with other dataset values in columns.  A lazy join.

As @wetneb stated, there are many uses.  Certainly, we cannot prevent a user that grabs some Python code off the internet and just runs it in our expression editor, but that is no different from them doing the same thing with their own Python interpreter.

OpenRefine is a power tool and we allow users full control of what access they might already have at their system level.  For instance, if an institution doesn't want a user to be able to access some local system resources, then they should do due diligence in creating a sandboxed environment for that user.  We, as an application, do not want nor do we need to be the ones responsible for creating sandboxed environments.  We, as an application are certainly responsible for addressing any remote code execution pathways, however.

And Remote Code Execution is an entirely different matter, and for that we rely on the Browser vendors, Java, and our dependencies(which we keep up to date) to perform their due diligence regarding security towards remote exploits.

@Enoki-web There are **other areas** of OpenRefine that certainly could use very good security eyes when it comes to **data privacy**:
1. Fetching URLs - and ensuring no unnecessary data is egressed unintentionally.
2. and several of our other operations and commands that access the internet through OpenRefine.

I would encourage you to spend your efforts in those areas, rather than within local system access from OpenRefine.  I.E. *the other way around*
