### ISSUE TITLE
Facet sidebar shifts when it refreshes

### ISSUE THREAD

**Issue by elebitzero** [OpenRefine/OpenRefine#5610]
The issue is as @thadguidry says:
> Unneccesary jumping up/down of Facet panels while users click on selections. The div browsing-panel-indicator will quickly show a hidden spinner “Refreshing facets…” which is above the browsing-panel-controls and hence causes all child elements underneath to suddenly move down and then back up. The effect to a user is disconcerting with jerky motion.

![image](https://user-images.githubusercontent.com/42903164/217458353-30653b79-3b10-4d42-a2c3-466a36c0496e.png)

**Comment by thadguidry** [comment]
@elebitzero Thanks for tackling this issue.  The question will be where to move this small notice so that users still see it if there is a long running refresh on many facets?  I don't even know how to produce such a state.  Maybe have many (25-50?) facets with some custom expressions that take a long time to calculate?  We also could change the longish test "Refreshing facets..." to just a spinner icon (does Clusterer have one useful to borrow or shrink?) with some alt hover text and place this small icon in the top right or left corner of `leftPanelDiv` or in lower elements?
