### ISSUE TITLE
Specify multiple types in the reconciliation dialog

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5615]
The reconciliation API supports supplying not just one but multiple types for a reconciliation query. Whether the types are meant to be understood as an intersection (candidates should belong to all those categories) or a union (any of those categories) can be controlled by a `type_strict` parameter.

Our current reconciliation dialog only lets the user select a single type (or none).

### Proposed solution

A new UI could let the user select more types, as well as determine whether they should be understood as an intersection or union.

### Alternatives considered

I was kind of surprised that I could not find an existing issue for this - so perhaps there isn't actually a need for this, and the status quo is fine as is.
My prompt to open this issue was a discussion in the reconciliation CG, as @fsteeg wondered about this feature.
It would be good to have some concrete use cases in some reconciliation endpoints to validate the need.
In Wikidata, whenever I want to reconcile to multiple types, I would generally take the least common ancestor of those types (given the type hierarchy structure).

### Additional context

Discussed in today's reconciliation CG meeting.

**Comment by fsteeg** [comment]
> It would be good to have some concrete use cases in some reconciliation endpoints to validate the need.

In the use case where this came up for us, we're passing this type to our [reconciliation service](http://test.lobid.org/resources/reconcile): `(Series OR Journal OR EditedVolume OR MultiVolumeBook OR Periodical OR Proceeding OR Newspaper OR Bibliography OR OfficialPublication OR Legislation OR Report) AND NOT (Article OR PublicationIssue)` (we're reconciling with collection-like bibliographic resources, see [details](https://github.com/hbz/rpb/tree/rpb-50#rpb-36-sm-data-wo-hbz-ids)).

**Comment by tfmorris** [comment]
> In the use case where this came up for us, we're passing this type to our [reconciliation service](http://test.lobid.org/resources/reconcile): `(Series OR Journal OR EditedVolume OR MultiVolumeBook OR Periodical OR Proceeding OR Newspaper OR Bibliography OR OfficialPublication OR Legislation OR Report) AND NOT (Article OR PublicationIssue)` 

This sounds like a UI nightmare unless there's a super-type (e.g. Collection-like Bibliographic Resource) that the user can choose. @fsteeg How does the user express this big boolean expression in your reconciliation client?

There's a significant tradeoff between power and complexity and it's not clear to me that adding support for multiple types to the OpenRefine reconciliation UI is a clear net win, independent of what the W3C decides to do. Even though the Freebase Search API, upon which the original reconciliation service was built, supported a domain ID as well as type ID, a large set of [metaschema](https://developers.google.com/freebase/v1/search-cookbook#metaschema-constraints) semantic predicates and a `filter` [constraint language](https://developers.google.com/freebase/v1/search) similar to what's described above, none of this was exposed to Refine users.

p.s. For semantic clarity, the OpenRefine reconciliation API, as implemented by more than a decade of services in the wild, only supports a single type ID. The preface "The reconciliation API supports" is presumably referring to the draft proposed future W3C API. It's important not to conflate the two so that arbitrary breaking changes for existing OpenRefine reconciliation services aren't introduced unintentionally.

**Comment by wetneb** [comment]
> p.s. For semantic clarity, the OpenRefine reconciliation API, as implemented by more than a decade of services in the wild, only supports a single type ID. The preface "The reconciliation API supports" is presumably referring to the draft proposed future W3C API. It's important not to conflate the two so that arbitrary breaking changes for existing OpenRefine reconciliation services aren't introduced unintentionally.

Well at least the documentation in December 2017 mentioned the possibility of using multiple types, so that clearly predates the W3C group: https://github.com/OpenRefine/OpenRefine/wiki/Reconciliation-Service-API/2e1ab5547b90b215a7a42415c351cfdd92bfec9f
So that's probably that the Freebase service did support this. That possibility was not exposed by OpenRefine's UI.

**Comment by Abbe98** [comment]
UI-wise could it be enough if we replace the radio-button-list with a checkbox based approach? And the make the "Reconcile against type" add options to the list rather than being an individual option?

**Comment by wetneb** [comment]
That feels like an intuitive start indeed, but then that is assuming lists of types are always interpreted as a union or intersection?
It is not clear to me how useful that really is.

I sympathize with @tfmorris' concerns regarding how to generalize the UI sufficiently to let users pick union or intersection, especially since @fsteeg's example suggests that we would need support for arbitrary boolean combinations.
I am not saying it cannot be done though.

**Comment by Abbe98** [comment]
> but then that is assuming lists of types are always interpreted as a union or intersection?

I imagine this would just be an additional checkbox among the current settings with the non default state as a label.

**Comment by wumionwheels** [comment]
after reading this conversation and checking out the reconciliation dialogue, I want to be sure I understand this issue. So this is about allowing choosing multiple types in the reconciliation api and allowing defining the search query whether as an intersect or union ("and" "OR"), what I want to know is will it return the result just like the current ui result in multiple matches found?

**Comment by wumionwheels** [comment]
Also, I will love to be assigned to this and make a UI for it

**Comment by wumionwheels** [comment]
Also, I will love to be assigned to this and make a UI for it

**Comment by wumionwheels** [comment]
Oh okay, no problem

**Comment by wetneb** [comment]
Given that we merged #115, I would not attempt to add support for multiple types here, therefore closing.

**Comment by dlindem** [comment]
There are use cases that would need to reconcile against items of several types (classes). For example, we had to link music terms to Wikidata; some where instance of "music form", others instance of "music genre", others of "music instrument", etc.; in the actual Open Refine, one can select a single class for the candidate items, so that in a use case like the described, we had to select "match against no particular type", which lead to many undesired matching candidates.

@dpriskorn, that would be sth like your subtitle linker, but for any TXT in a certain language one submits to the tool.

**Comment by tfmorris** [comment]
@dlindem In your example, what is the column called which contains all these disparate terms?

I notice that at least one of them is a subclass of "concept of musicology" in Wikidata. If the Wikidata ontology were more fully formed and consistent, would there be some superclass of them all which would work?
