### ISSUE TITLE
Build an extension that can anonymize data

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#5642]
After 4.0 is released the size of datasets that users can work with will increase.
Personally identifiable information (PII) becomes harder to discover as data volumes increase sometimes.

### Proposed solution
Build an extension that can expose and show users risk metrics of a dataset with PII and allow them options to remove (void) data as well as anonymize data. 

### Alternatives considered
Hand rolling various facets and algorithms to first find and surface PII and then perform manual transformations to try to anonymize well.

### Additional context
There are some libraries that offer utility and algorithms to assess risk and allow anonymization as well as pseudonymization, the later of which is still useful sometimes depending on needs, although not true anonymization and sometimes is not compliant enough with GDPR standards as well as others.

https://github.com/arx-deidentifier/arx
https://github.com/realrolfje/anonimatron

**Comment by wetneb** [comment]
@thadguidry I have started a list of extension ideas on the wiki:
https://github.com/OpenRefine/OpenRefine/wiki/Extension-ideas
Do you think it would make sense to list this there? Can I leave it to you to expand on the use case?
That would let us close this issue - since it's not meant to be implemented in this repository.

**Comment by thadguidry** [comment]
Sure, please close this and list the general idea on the wiki and I can expand with additional details there.
