### ISSUE TITLE
Display SOMETHING in the browser once context is initialized through Jetty

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#5824]
In 4.0 the startup of OpenRefine has increased about 6-7 seconds.  It's not bad, but...
```
10:42:17.789 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
10:42:17.886 [            refine_server] Initializing context: '/' from 'F:\Downloads\openrefine-4.0-SNAPSHOT\webapp' (97ms)
10:42:22.232 [                   refine] Starting OpenRefine 4.0-SNAPSHOT [5ede832]... (4346ms)
10:42:33.805 [                   refine] initializing FileProjectManager with dir (11573ms)
10:42:33.805 [                   refine] C:\Users\thadg\AppData\Roaming\OpenRefine4 (0ms)
10:42:33.805 [                   refine] Starting runner 'org.openrefine.runners.local.LocalRunner' (0ms)
```

### To Reproduce
1. Start OpenRefine.exe using it's default .ini setting on Windows 11 (even with fast NVME SSD and 8 CPU cores)

### Current Results
Displaying something in the opened browser for the user during startup is slower in v4.0 and nothing displayed in browser for over 13 seconds.

### Expected Behavior
We should be able to display a simple static HTML page of "Loading OpenRefine..." or similar after we have initialized context (10:42:17)  even before we begin starting (10:42:22) up 5 seconds later or initializing FileProjectManager (10:42:33) 11 seconds later.

### Versions
 - Operating System: Windows 11
 - Browser Version: Edge latest
 - JRE or JDK Version: builtin JRE (openrefine-win-with-java-4.0-SNAPSHOT)
 - OpenRefine: 4.0-SNAPSHOT

**Comment by wetneb** [comment]
Interesting that you observe a slowdown there, I would not expect that. Could it be a difference between the development version (running from a git clone) versus a packaged one? I'll have a look on my side too.

**Comment by elebitzero** [comment]
I tried the 4.0 branch on Windows 11 desktop and http://127.0.0.1:3333/#create-project loads in 6.5 seconds.

@wetneb, the 4.0 branch doesn't have some of the enhancements that were made to refine.bat. In particular, the optimization of using wmic to get free memory instead of calling systeminfo which gets all system info. (Ref: https://github.com/OpenRefine/OpenRefine/pull/5719) That fix saved 3-4 seconds on startup. If @thadguidry has been using latest SNAPSHOT version, that might be why 4.0 startup seems slow to him on Windows.

How are we syncing up master to 4.0? I'm concerned that not all the changes on the master branch are getting carried forward to the 4.0 branch. It seems to be out of sync.

Also, what is the timeline to merge 4.0 back to master?

**Comment by wetneb** [comment]
@elebitzero thanks for trying it out! I merge master into 4.0 every few months, so it is normal that your latest changes have not made it there - they definitely will!

Concerning the timeline, my expectation is that 4.0 becomes the main line when the team considers it stable enough to be the default. I think more testing is needed before that, and I am hoping to publish a 4.0-alpha2 this month to ease that. Based on the feedback we get out of that, it should become clearer what timeline we can hope for.

**Comment by elebitzero** [comment]
@wetneb, if you would like me to merge my changes from master to 4.0, I can help out if you tell me the procedure you are following.

I can also try out 4.0 and see if I notice any regressions. When I tried it out a few months ago, I noticed the data table pagination was broken.

**Comment by elebitzero** [comment]
Coming back to @thadguidry's issue,  on the 3.8-SNAPSHOT, OpenRefine starts in 4 seconds on my Windows machine, and 4.0 starts in 6.5 seconds. The discrepancy can be explained by 4.0 not have the wmic fix for looking up freeMem.

**Comment by wetneb** [comment]
Ah, brilliant, thanks @elebitzero, that's very good news!

> @wetneb, if you would like me to merge my changes from master to 4.0, I can help out if you tell me the procedure you are following.

So far I literally just do a git merge (of master into 4.0). Resolving conflicts can be a lot of work depending on the changes that have happened on both sides. If you are motivated to do it I would definitely not hold you back, but I suspect it's a task that is much easier for me given that I am familiar with the changes on both sides.
I'd be happy to also merge more often myself - the time it takes to do the merge is roughly proportional to the time since the last merge anyway.

**Comment by thadguidry** [comment]
OK, let me compile and test from source.

**Comment by thadguidry** [comment]
MUCH better!
For me, it was about 4.5 seconds to from `refine` to seeing browser fill with Project manager.  And no longer 13+ seconds.

Note the seconds between ... or ms on log tails.

```
14:01:38.553 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
14:01:38.555 [            refine_server] refine.memory size: 1400M JVM Max heap: 1468006400 bytes (2ms)
14:01:38.579 [            refine_server] Initializing context: '/' from 'E:\GitHubRepos\OpenRefine\main\webapp' (24ms) 
14:01:40.892 [                   refine] Starting OpenRefine 4.0-SNAPSHOT [f28a0be]... (2313ms)
14:01:45.290 [                   refine] initializing FileProjectManager with dir (4398ms)
14:01:45.290 [                   refine] C:\Users\thadg\AppData\Roaming\OpenRefine4 (0ms)
```
