### ISSUE TITLE
CI failing to download some Maven artifacts

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#5834]
Our CI often fails to deploy packaged artifacts with the following error:
```
Failed to execute goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:2.3.2:launch4j (l4j-clui-without-jre) on project packaging: Execution l4j-clui-without-jre of goal com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:2.3.2:launch4j failed: Plugin com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:2.3.2 or one of its dependencies could not be resolved: Failed to collect dependencies at com.akathist.maven.plugins.launch4j:launch4j-maven-plugin:jar:2.3.2 -> net.sf.launch4j:launch4j:jar:core:3.50: Failed to read artifact descriptor for net.sf.launch4j:launch4j:jar:core:3.50: The following artifacts could not be resolved: net.sf.launch4j:launch4j:pom:3.50 (absent): Could not transfer artifact net.sf.launch4j:launch4j:pom:3.50 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]
```

See for instance this log: https://github.com/OpenRefine/OpenRefine/actions/runs/4923978151/jobs/8796452145
(Full log archive: [logs_8314.zip](https://github.com/OpenRefine/OpenRefine/files/11440680/logs_8314.zip))

**Comment by wetneb** [comment]
I would actually expect Maven dependencies to be cached and not re-downloaded every time but this caching mechanism does not seem to work.
We could try and set up some caching for the downloaded JREs as well.
To reduce the length of this job we could also skip tests (which we run in the Linux job anyways, and we never had a MacOS-specific Java test failure so it's probably wasteful to run them on that platform too)

**Comment by thadguidry** [comment]
Caching is done when the hashed `cache key`.  It's done behind the scenes automatically if you configure in the job using :
```
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'
```

But your job has a step output of:
```
Run actions/setup-java@v3
Installed distributions
Creating settings.xml with server-id: ossrh
Writing to /Users/runner/.m2/settings.xml
Importing private gpg key
maven cache is not found
```

That tells me there's a cache miss and it didn't have an exact `key` match.
https://github.com/actions/setup-java/blob/ddb82ce8a6ecf5ac3e80c3184839e6661546e4aa/src/cache.ts#L82

I'm wondering also if we simply can setup the workflows to directly use @actions/cache and configure some of it's advanced arguments to help troubleshoot. https://github.com/actions/cache  Instead of relying on the @actions/setup-java to simply and hide something that we might be missing?

**Comment by thadguidry** [comment]
Hmm... there's some very interesting notes in the Actions documentation itself: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

**Comment by wetneb** [comment]
This does not seem to happen anymore.
