### ISSUE TITLE
'SELEZIONA UN FILE' instead of 'Choose a file'

### ISSUE THREAD

**Issue by fabiolinus** [OpenRefine/OpenRefine#5913]
Hi. All menu are localized in English but not "Nessun file selezionato" (Choose a file). See attachment. Thanks a lot, Fabio

![image](https://github.com/OpenRefine/OpenRefine/assets/33990409/57b0e0c6-e6aa-4b3e-a34a-8543261ed006)

**Comment by Abbe98** [comment]
Inputs of type "file" is labeled by the browser and thus picks up whatever language your browser is set to.

**Comment by fabiolinus** [comment]
Thanks a lot, I didn't know that.

**Comment by wetneb** [comment]
I think we could technically fix this by re-implementing this logic ourselves, away from the browser's defaults. Maybe it could make this part of the UI less accessible though?

Also it's not clear to me to what extent the current situation is a problem: the text is displayed in Italian because your browser's locale is set to that, so you can likely understand it. On the other hand it's inconsistent with the rest of the UI so it would feel cleaner to have it in the same language as the rest.

Overall I'd be edging towards closing this issue but I don't have strong feelings on this.

**Comment by Abbe98** [comment]
> I think we could technically fix this by re-implementing this logic ourselves, away from the browser's defaults. Maybe it could make this part of the UI less accessible though?

It's possible but non trivial: positioning the input off-screen, creating new custom input-button hiding this from the accessibility tree/keyboard, and finally setup a outline of the custom element when the real off-screen one has focus. Slightly simplified, in reality it's quite hard to get completely right.

I too, does not necessarily think that this is something we should fix given limited scope of the issue and the potential implication implementation wise.
