### ISSUE TITLE
Add method to retrieve sorting criteria in BaseSorter class of java project

### ISSUE THREAD

**Issue by Pritu2022** [OpenRefine/OpenRefine#5923]
By adding this method, other parts of the codebase can retrieve the sorting criteria used by an instance of "BaseSorter" and access their configurations as needed.

If you agree to add then please respond.

**Comment by wetneb** [comment]
Hi @Pritu2022,

Welcome to the project! People rarely come here to suggest a code change formulated from this abstract perspective. That's of course welcome too, but I am curious what prompts you to suggest this. Would this change help us implement new features or fix some bugs? Would it fix an architectural issue in the code base?

Also, it's not very clear to me what the change you are proposing really look like. Perhaps it's easiest if you open a pull request for it so that we can see the changes concretely.

**Comment by Pritu2022** [comment]
Hello @wetneb,

Yes, I have sent a pull request, kindly look into that.

Thank you.

**Comment by wetneb** [comment]
The need for this is not clear to me, as it is not justified by some sort of good practice or user requirement.
