### ISSUE TITLE
Edit button misplaced for empty cells

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#5989]
When a cell has no value, the Edit button is rendered centered on the bottom edge of the cell making it ambiguous as to which cell will be edited.

### Current Results
Empty cell:
<img width="219" alt="Screen Shot 2023-07-27 at 1 43 37 PM" src="https://github.com/OpenRefine/OpenRefine/assets/82178/ce0f9198-0894-4970-9692-490110223c92">
### Expected Behavior
Edit button should be rendered in the middle of the cell like it is when there's a value in the cell.
<img width="213" alt="Screen Shot 2023-07-27 at 1 44 01 PM" src="https://github.com/OpenRefine/OpenRefine/assets/82178/864d3806-28ca-4898-8f0c-d23bbf9484ca">

### Versions
 - Operating System: Mac OS X
 - Browser Version: Chrome Version 114.0.5735.198 (Official Build) (x86_64)
 - OpenRefine: current head / 3.8-snapshot

**Comment by aqsaaqeel** [comment]
Can I work on this?

**Comment by aqsaaqeel** [comment]
So I was trying to set up OpenRefine. I followed the steps on https://openrefine.org/docs/technical-reference/build-test-run
But after I ran ./refine build command, it kept on downloading a bunch of files and never finished.
I am using Linux- Ubuntu. Can anyone help out?

**Comment by wetneb** [comment]
Hi @aqsaaqeel, sure! You could reach out [on the forum](https://forum.openrefine.org/c/dev/8) or [on Gitter](https://app.gitter.im/#/room/#OpenRefine_OpenRefine:gitter.im) with detailed logs of your `./refine build` command.

**Comment by GittyHarsha** [comment]
@tfmorris can you provide the steps to reproduce the bug?
Is there a problem with the table component globally?

**Comment by thadguidry** [comment]
@GittyHarsha If you run OpenRefine and just use the clipboard importer, then enter some simple rows manually like
```
a,b,c
1,2,3
1,,
2,,
3,,
```

Then Create Project and then hover over the rows in any of those columns and notice that when the cell is empty value, then the little Edit button exhibits what Tom was mentioning, where the Edit button is not aligned to the right side of the cell  (it used to be top-right somewhat, if I recall, like 5% padding off the top right corner)

**Comment by GittyHarsha** [comment]
Thanks! will look into it

**Comment by GittyHarsha** [comment]
@thadguidry I found out the root cause of the issue.

The html structure of a table cell is as follows
```
<td>
    <div class="data-table-cell-content">
        <div>
            <span class="data-table-null" style="display: none;">null</span>
        </div>
        <button class="data-table-cell-edit" title="Edit this cell" style="opacity: 0;">
            edit
        </button>
    </div>
</td>

```
![WhatsApp Image 2024-08-20 at 23 25 32_125ceca7](https://github.com/user-attachments/assets/aa9ad74d-38f2-494b-94ed-a750a4a658ff)
I put small border around `div.data-table-cell-content`.

I investigated the css styles for the classes `data-table-cell-content` and `data-table-cell-edit`.
`data-table-cell-content` has `position: relative` css property.
`data-table-cell-edit` has `position: absolute`;
Thus, the button is positioned relative to the `data-table-cell-content`.

When `data-table-cell-content` is empty, you can see a dark line and the button positioned relative to this div.

Thus, here are the changes I am proposing:

make the `td` html element have `position: relative` and remove position property of `data-table-cell-content`.
Then the button positions with respect to the `td` element irrespective of whether the cell is empty or not.


Here is the result after the changes:
![image](https://github.com/user-attachments/assets/0df09eba-ae3a-477f-b729-e5a5d95ecddd)

![image](https://github.com/user-attachments/assets/996eb704-03e7-4308-8aa9-6584c9051f36)

**Comment by tfmorris** [comment]
Thanks for investigating! I've reassigned the issue to you since the previous assignee doesn't appear to have made progress.

Please have a look at our contributing guide and open a pull request (PR) with your proposed change so that the team can review it. Thanks!
