### ISSUE TITLE
Improve display of reconciliation results

### ISSUE THREAD

**Issue by Lydiaofficial** [OpenRefine/OpenRefine#6154]
### Problem Description
During user interviews conducted in September on the redesign of the reconciliation dialog feature, a common pain point identified by reconciliation was the challenge of dealing with a large number of results displayed after selecting a reconciliation service. The feedback highlighted issues with both the accuracy and the overwhelming nature of the displayed results. Users expressed the need for improved visibility and control as they often had to sort through numerous irrelevant results and this also causes a distatsteful UI by expanding cells thereby creating too much whitespace.

### Proposed solution
To address the identified problem, I propose an enhancement to the reconciliation feature in OpenRefine. The suggested solution involves introducing a more user-friendly way for managing the display of reconciliation candidates. 
- We start of displaying limited number of resuts, say limited to 2 by defaut.
- A "See More" button: Users can reveal additional candidates beyond the initially specified limit.
- A "See less" buton (link) to reverse the previous action and return back to the default display of 2 results.

This solution aims to provide users with greater control over the display of results, making the reconciliation process more efficient and user-friendly.

### Alternatives considered
An alternative is a straightforward "truncate results" option added to the dropdwon options of each reconciled cell. On click, a pop-up containing an input field appears where users can input the number of results they want displayed.

### Additional context
The proposed solution is a response to direct user feedback about the challenges faced when reconciling data, particularly in scenarios where a large number of candidates are presented. By allowing users to control the visibility of results, the proposed feature seeks to enhance the overall user experience, improving accuracy, and reducing the time and effort required for reconciliation tasks.

**Proposed defaukt display of results**
![image](https://github.com/OpenRefine/OpenRefine/assets/17748526/f009b43d-ab84-4385-a610-4c26798101b9)

When user clicks on "See more"
![image](https://github.com/OpenRefine/OpenRefine/assets/17748526/82d48e09-2751-4990-b8a3-87e2898bc95d)

**Alternative proposed**

![image](https://github.com/OpenRefine/OpenRefine/assets/17748526/a36af268-ec7c-4b24-98d8-5751009bffb8)

![image](https://github.com/OpenRefine/OpenRefine/assets/17748526/747367e3-3ca4-4cbd-a736-97c15774cdb7)

**Comment by lozanaross** [comment]
Thanks @Lydiaofficial - I think this is a good & elegant solution to add "See more" after 2 suggested matches. I just wonder if we should make the Search for match link available already in the first view, so something like "See more | Search for match" & then "See less | Search for match", but will let others comment on this as well. 

Another point is that maybe we need a better way to indicate scores / ranks to users because this (100) is really unclear to me (I had at some point thought it's indicating a QID 🤦🏻‍♀️), but I can make a separate issue about that.

**Comment by tfmorris** [comment]
Thanks for working on this! The current situation is definitely seriously sub-optimal. Something it might be worth considering doing is rather than fetching lots of results and then hiding a portion of them, instead returning the default number of results requested to its previous value of 3. We could also consider making the control for the number of choices more obvious, but I think an appropriately chosen default should fix the bulk of the problem.

You can see what the original UI looked like here: https://youtu.be/5tsyz3ibYzk?si=eDtVXpWcKZfRJjiG&t=219

Reconciliation really needs to be looked at from a systems point of view because the behavior of the reconciliation services greatly influences the user's perceptions. I suspect part of the reason that so many results are being returned is because poor ranking means there's a good chance that the desired result isn't in the top 3. I think a better fix than showing more results would be to improve the ranking.

I got the screen below when doing some work reconciling authors today. It's clearly not acceptable from several different points of view.

1. No user is going to look at 25 results, so there's no point in returning them all
2. Results with very low scores are likely to be irrelevant and shouldn't be returned to the user
3. A half dozen results with precisely the same score gives the user no information

Another historical note is that Wikidata is structured differently than Freebase was so that useful Freebase types like Author, Politician, Professional Athlete, etc don't exist in Wikidata. Instead they're all just Humans (Q5), so it may be worth putting some thinking into how we help users with this structural difference. There's been some discussion of supporting reconciling against a constant e.g. Occupation == Writer so that they don't have to add an Occupation column to their data if it doesn't naturally exist there, but perhaps there are more clever solutions, particularly for the common case of reconciling people.

![Screen Shot 2023-11-19 at 7 24 56 PM](https://github.com/OpenRefine/OpenRefine/assets/82178/114f41d6-56e3-4237-9731-49d540adac79)

[The difference between the two sets of results is that Author2 on the right was reconciled using the added Occupation column, while Author on the left was reconciled just against type Q5 with the book title as Notable Work (which I doubt helped much since this isn't well populated in Wikidata]

**Comment by thadguidry** [comment]
I definitely agree with @tfmorris in regards making it super easy to reconcile against higher types. A mini facet might be one way to show the distribution of higher types than what the user might have initially picked to reconcile against.  If a user picked a subtype initially it would be fantastic to show them the distribution (count/percentage) of candidates returned so that a user could 1-click to reconcile against a suggested higher type.  Another example, this might even help show that 80% of returned candidates are not even in the same type hierarchy as initially requested by the user.  I still stand by my idea of making the reconciliation suggestion dialog by default a much larger or expandable thing, especially for showing type distribution counts (mini facet in the expanded dialog). I also see the need for an extension that can support browser tabs for users with 2 monitors or split browser on 1 monitor which allows a reactive user interaction with a recon dialog in 1 tab and grid in the other tab.

**Comment by tfmorris** [comment]
Sorry, I guess I should have kept my comment more focused. My main suggestion is to reduce the default number of returned results to 3.

**Comment by Lydiaofficial** [comment]
Here are the mockups.

1: 3 displayed results and the "see more" and "serach for match" options as defaults
![image](https://github.com/OpenRefine/OpenRefine/assets/17748526/eb00b0b5-4edb-43a1-b1b1-d5faa5bcf998)

2: More results on expand and the "see less" action after "see more" is clicked.
![image](https://github.com/OpenRefine/OpenRefine/assets/17748526/c8cc6b8d-76ed-44c7-a49a-d8dcb1398f77)
