### ISSUE TITLE
Cypress tests: remove calls to waitForImportUpdate() and waitForOrOperation()

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#6164]
Our Cypress test suite relies in various places on two helpers, `waitForImportUpdate()` and `waitForOrOperation()`.

Quoting @elebitzero from #6162:

> `waitForImportUpdate()` has the same problem as `waitForOrOperation()` which I have been trying to remove.  Both of those methods are waiting for a temporary loading/in-progress element to be visible and then not visible.
> 
> The problem is that the element may have been shown and hidden again before this code executes, causing it to wait forever until it times out.
> 
> The solution is to not focus on the transient loading indicators, but to just do `cy.get()` and assertions on the expected state after the operation completes. For long running operations,  the timeout on the `cy.get()` command may need to be increased if the operation could exceed the default timeout of 4 seconds.

### Proposed solution

Remove all uses of those helpers and remove the helpers themselves. This means that the Cypress tests need to be adapted to wait on the actual update, for instance by looking for a particular cell content. See #6162 for an example of how this can be done.

### Alternatives considered

None

### Additional context

Follow-up to #6162.
Marking this as a good first issue because it may not require much familiarity with OpenRefine itself. See https://openrefine.org/docs/technical-reference/functional-tests for documentation about this test suite.

**Comment by thadguidry** [comment]
Cypress has automatic waiting and it might be that the DOM elements are not actionable yet.  Their docs describe ways to handle that. https://docs.cypress.io/guides/core-concepts/interacting-with-elements#Actionability

It might first be good to try the .debug() command before the action to understand why Cypress thought an element wasn't visible.

**Comment by tfmorris** [comment]
Both @elebitzero and I independently came to the same conclusion about the race condition, so I don't think additional analysis is needed. Since @wetneb has tagged this as a good first issue, let's keep the ticket clean and focused. I'll hide both the comments as off-topic in a day or two.

**Comment by akashinde** [comment]
Hello, I wanted to check in on the status of this issue. Is this issue currently assigned to anyone, or is it in progress? I would like to work on it if not assigned!

**Comment by tfmorris** [comment]
@akashinde I see that @wetneb has assigned you. To provide an update on the status, all instances of `waitForImportUpdate()` have already been removed and there are only two instances of `waitForOrOperation()`, which can be found here:

https://github.com/OpenRefine/OpenRefine/blob/620b77a27478b22586c3538a2fcace55d505c141/main/tests/cypress/cypress/e2e/project/grid/column/facet/facets.numeric.cy.js#L46-L49

when they have been replaced, the helper function itself should be removed also.

**Comment by akashinde** [comment]
Thanks for the overview. I found the usage and the helper function as well. I am debugging the issue and so far found that for this case only, the drag and drop is not working as expected and moving the x-axis of the component more than 130px (146px in this case) which results in different row counts and hence failing the test. I will look more into the issue.

**Comment by tfmorris** [comment]
Thanks for the status update. From playing with this interactively, it appears to me that the row counts being tested for might be wrong (ie they're transient values, not the final values). I think one way to combat this false matching would be to first wait on the facet label to be updated as I did at the start of the test:
https://github.com/OpenRefine/OpenRefine/blob/620b77a27478b22586c3538a2fcace55d505c141/main/tests/cypress/cypress/e2e/project/grid/column/facet/facets.numeric.cy.js#L35

I think that, as the test is set up now, your target values would be:

Initial: 0 — 94
After move right handle: 0 — 45
After move middle: 23 — 68
After move left handle: 66 — 68

With this setup, the row counts for the last two tests are incorrect, as you noticed, and will need to be adjusted to 74 instead of 70 and 3 instead of 4.

Lastly, because the facets are refreshed after the grid is updated, the matching row count test will be satisfied before the facet is ready to be manipulated again, so you will need to wait until the `browsing-panel-indicator` `div` is hidden before attempting to move the facet handles again. 

Let us know if you have any questions.

**Comment by akashinde** [comment]
Thank you very much @tfmorris for such a detailed explanation. Initially, I thought the issue might be because of mouse events not getting updated properly. However, after your comment I saw that the Refreshing Facets was not getting resolved and then next mouse event was asserting previous counts.

Thanks for the tip, I have created the PR to fix this issue. Let me know if any change is required!
