### ISSUE TITLE
Pre-project expression histories no longer saved

### ISSUE THREAD

**Issue by jquartel** [OpenRefine/OpenRefine#6362]
As described here https://forum.openrefine.org/t/is-the-facet-creation-history-tab-meant-to-be-able-to-show-the-source-projects/1242 ,  the "From" column in the History tab of the custom expression modal always shows as "This project" even when the corresponding expression was created in another project (than the current one).

![3aeb3ab38578af70c38318b12b305d943474e32c](https://github.com/OpenRefine/OpenRefine/assets/36742596/fa3b2931-92c0-4d74-83ab-c9ca0c912198)

**Comment by tfmorris** [comment]
There are two related bugs here, both introduced by the conflict resolution of a single commit revert in 2018:
1. Expression history is no longer saved in the local project
2. Global expression history entries are always displayed as "This project" rather than "Other project"

I've identified the missing pieces and "just" need to pull them together into a PR.
