### ISSUE TITLE
Add an icon in line with the new visual guidelines of MacOS

### ISSUE THREAD

**Issue by teolemon** [OpenRefine/OpenRefine#6399]
- The icon of OpenRefine is out of place with the new graphic charter for m

### Proposed solution
- Add an icon in line with the new visual guidelines of MacOS

<img width="1023" alt="image" src="https://github.com/OpenRefine/OpenRefine/assets/1689815/18c46888-6a66-4006-9e82-72afd9da7fe1">

### Available solution
- https://macosicons.com/#/open%20refine

**Comment by wetneb** [comment]
Thanks for bringing this up!

It's unclear to me if we can simply reuse the icon you pointed at on macosicons.com. [This repository that's associated to the website](https://github.com/elrumo/macOS_Big_Sur_icons_replacements ) is in GPL v3, which would not work, but that's not necessarily the license that applies to the icons themselves.
We could also redo the adaptation on our side, following the same idea.

Once we have a suitable ICNS file at hand, it can simply replace this one:
https://github.com/OpenRefine/OpenRefine/blob/master/graphics/icon/openrefine.icns

**Comment by tfmorris** [comment]
The licensing discussion is here: https://github.com/elrumo/macOS_Big_Sur_icons_replacements/discussions/1382
It sounds like enough of a mess that we should just modify our own.

Perhaps a good task for the @OpenRefine/designers ?

**Comment by teolemon** [comment]
![512x512@2x](https://github.com/OpenRefine/OpenRefine/assets/1689815/f982ec72-1e88-45b5-85dc-681295086ec1)
https://www.figma.com/file/dJSxFNE0AmXnDgwb1nIzXM/Official-macOS-App-Icon-Template-(Community)?type=design&node-id=0-58&mode=design&t=jau7wfipCZUcRUNF-0

@tfmorris @wetneb I redid something in Figma from a template: https://openrefine.org/img/openrefine_logo.svg

**Comment by thadguidry** [comment]
The [App icons guidelines](https://developer.apple.com/design/human-interface-guidelines/app-icons) state that we CAN go a bit larger with the OpenRefine gem coming a bit closer towards the edge of the app Icon grid bounding box.  It looks like we might have constrained the gem a bit too much in your design image above, where it's well within the "Icon grid" square (which is inside the "Icon grid bounding box".  You can probably increase the gem size so that it just touches the edge of the "Icon grid bounding box"?

![image](https://github.com/OpenRefine/OpenRefine/assets/986438/72d21017-8cb5-4933-80f0-13bac7af7e08)


>Keep primary content within the icon grid bounding box; keep all content within the outer bounding box. If an icon’s primary content extends beyond the icon grid bounding box, it tends to look out of place. If you overlay a tool on your icon, it works well to align the tool’s top edge with the outer bounding box and its bottom edge with the inner bounding box, as shown below. You can use the grid to help you position items within an icon and to ensure that centered inner elements like circles use a size that’s consistent with other icons in the system.

Also, we SHOULD add a faint drop shadow under the gem and follow the style of the app-icon template for that.  For example, look at the Safari icon compass and notice the faint drop shadow of the red/white compass needle that is lower-right of the needle.  Apple is encouraging the use of faint drop shadows now when it can keep the icon clear and distinct and there's no text within its image.  We could also do a recessed look, which is an option now as well since Sonoma changed the visual style somewhat.  Read the guidelines and notice the red Music app icon for the macOS where the notes look recessed.  They mention this in the paragraph.

>Create a design that works well on multiple platforms so it feels at home on each. If your app or game runs on more than one platform, use similar images and color palettes in all icons while rendering them in the style that’s appropriate for each platform. For example, in iOS, tvOS, and watchOS, the Music app icon depicts the white musical notes on a red background using a streamlined, graphical style; macOS displays the same elements, while adding shadow that makes the notes look recessed. Similarly, the Music app icon in visionOS uses the same color scheme and content, but offers a true 3D appearance when viewed while wearing the device.

> Use the drop shadow in the icon-design template. The app-icon [template](https://developer.apple.com/design/resources/#macos-apps) includes the system-defined drop shadow that helps your app icon coordinate with other macOS icons.

> Consider using interior shadows and highlights to add definition and realism. For example, the Mail app icon uses both shadows and highlights to give the envelope authenticity and to suggest that the flap is slightly open. In icons that include a tool that floats above a background — such as TextEdit or Xcode — interior shadows can strengthen the perception of depth and make the tool look real. Use shadows and highlights that suggest a light source facing the icon, positioned just above center and tilted slightly downward.
