### ISSUE TITLE
Excel importer doesn't work from URL

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#6418]
When the Excel importer is invoked after downloading from a URL, the sheet selection logic doesn't work because it's comparing against the original URL rather than the local filename.

The relevant piece of code is:
https://github.com/OpenRefine/OpenRefine/blob/f4878804960162ba6145941bfbe0d14e60133d9b/main/src/com/google/refine/importers/ExcelImporter.java#L200-L201

which causes every sheet to be skipped. Unfortunately, we need original URL for provenance if the user has requested it to be saved AND we need the local filename for the sheet matching, but we don't have it available.

### To Reproduce
1. Create Project
2. Web Addresses (URL) - https://usace.contentdm.oclc.org/digital/api/collection/p16021coll2/id/2106/download

### Current Results
Both the preview and the actual project import are empty

### Expected Behavior
File contents are correctly previewed and imported.

### Versions

 - OpenRefine: 3.8-SNAPSHOT

### Additional context

This may also be a problem with Excel files which are contained in archives or are compressed, but I haven't checked.

**Comment by Kurocifer** [comment]
Hey @tfmorris could I work on this issue ?

**Comment by Kurocifer** [comment]
Hey @tfmorris can I work on this issue ?

**Comment by tfmorris** [comment]
I only took a quick look at this, but I think it may be a little complicated due to not having the necessary information available when needed, as outlined above, but if you want to give it a go, go ahead! Let us know if you have any questions.

**Comment by Kurocifer** [comment]
It actually works well with Excel files contained in archives or compressed without any modifications to the program.

**Comment by Kurocifer** [comment]
Thanks. It actually works well with Excel files which are contained in archives or are compressed without making any modification to the program.

**Comment by Kurocifer** [comment]
Also modifying that line @tfmorris highlighted (still checking against the URL, but to see if it just contains the file name) works with the different files I've used to test with (not only the compressed ones) but as you say the problem seems deeper than that and I doubt that being the solution.

I have this question why was the file name checked against the URL, was there some particular reason for this ?

**Comment by Kurocifer** [comment]
This method might be what's causing this problem with Excel importing from URL

![Screenshot from 2024-04-03 22-35-05](https://github.com/OpenRefine/OpenRefine/assets/121205895/cda248a4-8d64-45cd-8615-eae109084cbd)

when the fileRecord contains the URL (which for some reason I don't know, that of the zipped file I was using to test did not have which is why it worked for it), this method will ultimately return the URL rather than the fileName which is why at the if statement highlighted above it was comparing to the file's download URL. I don't yet really understand why this was done so, but modifying that method actually solves the problem.

Please @tfmorris or @wetneb  tell me if there was any reason for that method written like that so I could dig deeper or I submit the pull request.

**Comment by Kurocifer** [comment]
This method might be what's causing this problem with Excel file importing from URL

![excelimp](https://github.com/OpenRefine/OpenRefine/assets/121205895/422cca7a-491d-4e1e-8f42-d5375a995a50)getFileSource

when the fileRecord contains the URL (which for some reason I don't know, that of the zipped file I was using to test did not have which is why it worked for it), this method will ultimately return the URL rather than the fileName which is why at the if statement highlighted above it was comparing to the file's download URL. I don't yet really understand why this was done so, but modifying that method actually solves the problem.

Please @tfmorris or @wetneb tell me if there was any reason for that method written like that so I could dig deeper or I submit the pull request.

**Comment by tfmorris** [comment]
pro tip you can use Github's permalink feature to create clickable code previews that will take people directly to the code in question

https://github.com/OpenRefine/OpenRefine/blob/f4878804960162ba6145941bfbe0d14e60133d9b/main/src/com/google/refine/importing/ImportingUtilities.java#L601-L606

> his method will ultimately return the URL rather than the fileName which is why at the if statement highlighted above it was comparing to the file's download URL. I don't yet really understand why this was done so, but modifying that method actually solves the problem.

The original data source is stored as part of the provenance for the file creation (you can see it in the project metadata on the Open Project screen with all the projects listed). There are (potentially) multiple layers to the onion: 
1. The URL that was downloaded
2. An archive/zip file containing one or more files
3. An Excel/ODS file containing one or more sheets

My memory (without having had the chance to refresh it, which I'll try to do tomorrow) is that we have one fewer variables than we need to hold all the necessary data in this particular case.

They key thing to double check as you look for a solution is that you've preserved the provenance information in the project metadata.

**Comment by Kurocifer** [comment]
Did not know about the tip thanks. For the preservation of the provenance information in the project metadata, I just checked it and after the modifications to that method, the provenance information in the project metadata is as preserved as it was before the modifications, and the Excel importing works right.

> pro tip you can use Github's permalink feature to create clickable code previews that will take people directly to the code in question
> 
> https://github.com/OpenRefine/OpenRefine/blob/f4878804960162ba6145941bfbe0d14e60133d9b/main/src/com/google/refine/importing/ImportingUtilities.java#L601-L606
> 
> > his method will ultimately return the URL rather than the fileName which is why at the if statement highlighted above it was comparing to the file's download URL. I don't yet really understand why this was done so, but modifying that method actually solves the problem.
> 
> The original data source is stored as part of the provenance for the file creation (you can see it in the project metadata on the Open Project screen with all the projects listed). There are (potentially) multiple layers to the onion:
> 
>     1. The URL that was downloaded
> 
>     2. An archive/zip file containing one or more files
> 
>     3. An Excel/ODS file containing one or more sheets
> 
> 
> My memory (without having had the chance to refresh it, which I'll try to do tomorrow) is that we have one fewer variables than we need to hold all the necessary data in this particular case.
> 
> They key thing to double check as you look for a solution is that you've preserved the provenance information in the project metadata.
