### ISSUE TITLE
Column menu button icon has acquired a hard grey box

### ISSUE THREAD

**Issue by jquartel** [OpenRefine/OpenRefine#6440]
This is pretty trivial and may have been a deliberate aesthetic choice so apologies if it doesn't constitute a bug, but while assessing OR 3.8-beta1 I noticed that the menu buttons next to the column names now have a hard grey box around them which, in my opinion, looks a little inelegant (at least compared to what it used to be).

3.8-beta1:
<img width="53" alt="Screenshot 2024-03-13 at 11 25 50" src="https://github.com/OpenRefine/OpenRefine/assets/36742596/965d07ae-2b99-48ad-90cc-eb6009f2468a">

3.7.9:
<img width="45" alt="Screenshot 2024-03-13 at 11 26 08" src="https://github.com/OpenRefine/OpenRefine/assets/36742596/315c2a00-f9aa-4672-8d48-e4f98f3eebbd">

**Comment by wetneb** [comment]
I agree that the previous version is nicer and I don't remember this being a deliberate change, so I would support cleaning this up.

**Comment by abhishekkujur1307** [comment]
I was checking difference of 3.7.9 vs 3.8-beta1.

Found out this bug was due to change in tag from <a> tag in case of 3.7.9 to <button> tag in case of 3.8-beta1.

Attaching screenshots for your reference.

3.7.9
![openrefine-3 7 9](https://github.com/OpenRefine/OpenRefine/assets/59303347/403d79ff-fd83-4a8d-8247-36062b19cac2)

3.8-beta1
![openrefine-3 8-beta1](https://github.com/OpenRefine/OpenRefine/assets/59303347/fe131afe-a467-4371-b469-3e5a846f5c9b)

3.8-beta1 : Replaced <a> tag with <button> tag solved the issue.
![openrefine-3 8-beta1-solved](https://github.com/OpenRefine/OpenRefine/assets/59303347/bb81053d-7b16-4cc2-aae2-f57bd638ef05)

Searching - Why this bug is happening in first place ?

**Comment by wetneb** [comment]
@abhishekkujur1307 thank you! I believe the `<a>` was changed into a `<button>` to ease keyboard navigation. Do you see a way to change the style of the button so that it does not have this grey background anymore?

**Comment by abhishekkujur1307** [comment]
@wetneb I was exploring the difference between `<a>`  and `<button>`, was tinkering around and ultimately found the solution.
Solution : `<button>` can be styled to get desired no grey background.

Can you please assign me this issue ?

**Comment by abhishekkujur1307** [comment]
@wetneb Please review #6473 , if any modification is required, please let me know.
