### ISSUE TITLE
cell.cross returns Error: “java.lang.NullPointerException”

### ISSUE THREAD

**Issue by magdmartin** [OpenRefine/OpenRefine#6453]
I am creating this issue to track in Github the error reported in conversation on the forum https://forum.openrefine.org/t/cell-cross-not-working-getting-the-following-error-message-error-java-lang-nullpointerexception/688 -  I am not personally experiencing the issue and cannot help to reproduce it. 

Summarizing the environment from the four users that reported issues we have no clear pattern: 
* OpenRefine 3.7.1 and 3.7.2  - macOS Ventura Opera 97.0.4 - archilecteur
* OpenRefie version unknown Mac Os version 13.6.2 Java(TM) SE Runtime Environment (build 17.0.9+11-LTS-201) Bart_Magnus
* OpenRefine 3.7.9 ubuntu Java version "21.0.2" 2024-01-16 LTS Michel_Guenard
* OpenRefine 3.7.5 and 3.7.9 Windows 11 openjdk version "17.0.10" 2024-01-16 Michael_Beckett

### Current Results
The cell.cross function returns a NullPointerException

**Comment by tfmorris** [comment]
This is caused by corrupt workspaces which have projects listed in `workspace.json` which don't have project directories. Although we have code to attempt to recover a `metadata.json` file if it's missing and there's data there, if there's nothing at all, it will cause problems for the project lookup by name that `cross()` uses.

One way to identify workspaces that might be corrupted in this way is empty project directories in the workspace directory. If they are deleted, they will get recreated the next time OpenRefine is started. Editing the `workspace.json` file to remove the offending project ID(s) (there may be more than one) is a temporary workaround until a fixed version of OpenRefine is available.

**Comment by tfmorris** [comment]
@wetneb Although this is tagged with the 3.8 milestone, it doesn't appear on the 3.8 branch.

```
git branch --contains 3e42f5da5e3f85533b55c135cbe5bb68bbd53706
```

**Comment by wetneb** [comment]
That looks like an oversight on my part, let's include it in 3.8.1

**Comment by judaicadhpenn** [comment]
Do you know when @wetneb when will 3.8.1 be released?

**Comment by wetneb** [comment]
I proposed to release on 22nd May: https://forum.openrefine.org/t/releasing-3-8-1/1521
