### ISSUE TITLE
Bundled extensions should declare slf4j and Jackson as "provided"

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#6475]
As described in https://github.com/OpenRefine/simile-butterfly/issues/15#issuecomment-2008558262 core facilities that are used by extensions should be declared as "provided" in the extensions POMs, so that they don't get re-imported with a different classloader hierarchy causing LinkageErrors. In particular, this applies to slf4j and jackson-databind.

### Current Results
Butterfly fails to start with OpenRefine extension modules unless its classloading isolation mechanism is disabled.

### Expected Behavior
All bundled extensions load without issue even with Butterfly's isolation enabled.

**Comment by thadguidry** [comment]
Wonderful find!  Glad we finally figured this out.

**Comment by wetneb** [comment]
That would be a pretty natural solution indeed! I'm curious to see if Jackson serialization still works as it should after that.

**Comment by tfmorris** [comment]
> I'm curious to see if Jackson serialization still works as it should after that.

Do you have a particular test (manual or automated) that was failing before? Was the broken serialization on the wire or on disk?

FWIW all unit and end to end tests pass with this fix (and the Butterfly patch reverted).

**Comment by wetneb** [comment]
This is a problem that sadly isn't covered by the test suite because the class loaders used when running unit tests are configured differently to the normal operation of the application.
It might be possible to write a unit test for the problem by explicitly invoking the class loaders in the way they are in the normal application.

One way to test this manually would be to use the Wikibase integration (saving a Wikibase schema in a project should be enough, no need to upload), restarting OpenRefine and checking that the schema is indeed restored as expected. This would test Jackson serialization and deserialization under normal circumstances.

**Comment by tfmorris** [comment]
Took me a while to figure out how to make a schema that the Wikibase extension would let me save, but save/restore appears to work correctly.
