### ISSUE TITLE
Data parsing bug when the first column has nulls

### ISSUE THREAD

**Issue by clombion** [OpenRefine/OpenRefine#6516]
When opening a file where the first column ends with several rows of null values, OpenRefine 3.8-beta1 [7fd4077] doesn't properly parse the data and ends up grouping the rows starting with null values as if it was a single row. The behavior stops facets from working properly and also hallucinates quotes around some values. 

### To Reproduce
1. First, import the dataset from URL (I did not try downloading before importing): the problem https://raw.githubusercontent.com/civicliteracies/EITI_SDT_data_verification_and_validation/main/data/outputs/agencies_4_actual_complete.csv
3. Then create a facet by country then one by Government entity. You can either click exactly as the picture above (AFGHANIISTAN, AGENCE DE L'EAU) or try with any other government entity facet option that is found at the end of the dataset (they generally have only one ocurrence)
4. Finally, compare the outcome by loading from URL the comparison file for which an index was added: https://raw.githubusercontent.com/civicliteracies/EITI_SDT_data_verification_and_validation/main/data/outputs/agencies_4_actual_complete_indexed.csv

### Current Results

The following picture shows a combination of facets which should show only one row, but end up showing a lot of rows bunched together.

<img width="1426" alt="Capture d’écran 2024-04-08 à 13 38 39" src="https://github.com/OpenRefine/OpenRefine/assets/8268300/1774aa03-4ae0-42bb-9ead-36fd1251165a">

We worked around the bug by adding an index to the dataset, so that the first column wouldn't have any nulls. We discovered in that process that not only rows are bunched together, but OpenRefine hallucinates double quotes around some values, as illustrated in the below picture. 

![comparison open refine bug](https://github.com/OpenRefine/OpenRefine/assets/8268300/95589611-7a26-4f52-8195-c5f0cc34f792)

### Expected Behavior

OpenRefine should properly facet the file even if the first column has nulls.

### Screenshots

See above

### Versions
 - Operating System: MacOS Ventura 13.2
 - Browser Version: Firefox 124.0.2
 - JRE or JDK Version: openjdk version "17.0.9" 2023-10-17
 - OpenRefine: 3.8-beta1 [7fd4077] 

### Datasets
* problem dataset: https://raw.githubusercontent.com/civicliteracies/EITI_SDT_data_verification_and_validation/main/data/outputs/agencies_4_actual_complete.csv
* comparison dataset that solves the issue by adding an index https://raw.githubusercontent.com/civicliteracies/EITI_SDT_data_verification_and_validation/main/data/outputs/agencies_4_actual_complete_indexed.csv

### Additional context
Bug found today.

**Comment by wetneb** [comment]
Yes, you're not the first one to be surprised by that! We are aware that the records mode is pretty unintuitive for newcomers, especially because it gets activated by default in a case like yours.
You can read more about it here:
https://openrefine.org/docs/manual/exploring#rows-vs-records

We have some ideas of how to make that more transparent #5174, #5175. Do you think they would have helped?

**Comment by clombion** [comment]
Wow I did not consider the record mode because I've never used it, despite years of using OpenRefine! Is it for dealing with json and other hierarchical data?

My bad then! I really like the suggestion in https://github.com/OpenRefine/OpenRefine/issues/5175 as it would have made clear to me that OR is warning me about something, even if I don't know yet what it is. It would then be easy to have a Q&A page with "why is my first column red?" for people looking for answers.

A tutorial would have been useless because probably forgotten by the time you end up activating record mode by chance. As I mentionned, I've been using OpenRefine for years, and I mentioned the issue to 2 other colleagues who use it regularly, and everybody thought that was a bug.

What about the double quotes though?

**Comment by wetneb** [comment]
> What about the double quotes though?

Ah yes I had missed that part, well, that's something that we should definitely investigate, I don't see any reason why this would be by design.

**Comment by tfmorris** [comment]
I think perhaps just changing the defaults to never start in record mode might be the best solution.

There's no "hallucination" here because a) we don't use LLMs and b) the quotes are in the original data. Selecting the option `Use character "  to enclose cells containing column separators` will make them go away.

I see three things that could be improved with this dataset:
1. Guess CSV instead of TSV, as it currently does, for the initial format
2. Enable quote stripping by default when it's indicated
3. Start in row mode instead of record mode

The CSV package that we use has a format "sniffer" which may be able to help with 1 & 2.

**Comment by tfmorris** [comment]
@wetneb I recommend that the fix for this be included in 3.8 since the regression was first introduced in that release and it is, in my opinion, a low risk fix which restores the prior behavior.

**Comment by wetneb** [comment]
Ok, let's do that
