### ISSUE TITLE
Text files are saving wrong on macOS Sonoma

### ISSUE THREAD

**Issue by leo-buitrago** [OpenRefine/OpenRefine#6549]
### To Reproduce
1. First, I am downloading data from OpenRefine on my Mac (macOS Sonoma Version 14.4.1) in any text file format (CSV, TXT or TSV); selecting the option in the drop-down list or using the custom tabular option.
![Screenshot 2024-04-19 at 1 26 09 PM](https://github.com/OpenRefine/OpenRefine/assets/61566113/a62e3241-59f3-46ec-aa69-aeb95e593c15)

2. Then, I get the files as plain text but always with an apparently encoding error ("%2E") and always with the extension ".txt"
![Screenshot 2024-04-19 at 1 21 09 PM](https://github.com/OpenRefine/OpenRefine/assets/61566113/7ff716df-be86-407f-a689-65aa05e16041)

### Expected Behavior

Despite you can change the name and the format extension afterwards (to CSV for example) I would like to get my file with the original name and the correct extension (TSV, CSV...)

I have changed the language region settings of my MAC, the app to open text files by default and other possibilities but nothing works. 

### Versions
 - Operating System:  macOS Sonoma Version 14.4.1) 
 - Browser Version: Safari
 - OpenRefine:  I have tried with the three last versions and I am getting the same result

### Additional notes
I have now this problem with this software version but with previous macOS versions it worked well.

**Comment by tfmorris** [comment]
Apologies for the delay in triaging this! I can reproduce this using Safari, but it appears to be a browser specific bug which doesn't occur in Chrome. The %2E is a percent escaped period (.) which should have been excluded from the percent encoding added in  #3736 to fix #3724. 

While investigating I also discovered that because Safari doesn't support rfc5987, non-ISO Latin 1 characters aren't correctly handled by Safari. That's a separate issue, but we can fix it at the same time.

**Comment by leo-buitrago** [comment]
Thanks to work on this Tom!

**Comment by tfmorris** [comment]
This was first reported in #3988
