### ISSUE TITLE
join() of array with nulls throws NullPointerException

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#6683]
As mentioned in https://github.com/OpenRefine/OpenRefine/issues/6521#issuecomment-2104513492

### To Reproduce
1. `parseJson("['a',null,'b']".join(',')`

### Current Results
NullPointerException

### Expected Behavior
`"a,,b"` (but because of a different bug it should currently return `"a,b"`

**Comment by thadguidry** [comment]
I know how difficult I have made it for the team when pushing for separating concerns for NULL versus Empty String.  But, in fact, it is worth our pain and has really helped a lot of folks especially debugging their own internal data workflows and fixing issues where NULL creeps in where they didn't expect it!  (I've heard from 3 folks already in the last 4 years...not a lot, I know, but who knows how many smiled and didn't reach out to me to acknowledge our efforts on that).

Much appreciated @tfmorris !

**Comment by tfmorris** [comment]
@thadguidry I wasn't aware that you had an issue open for handling arrays with nulls. Can you please link it here so that we can track it and close it when the fix for this gets merged?

This was just splitting out the issue raised by @iomicifikko.

**Comment by thadguidry** [comment]
I don't have a direct issue open.  I was referring to @ostephens previous work on Blank and Null handling that had been already merged.  But our importers still don't treat them separately!

We have the remaining tangential array/null issues:
#4823
#2157  <-- Actually, this can be closed now, I think?  Because `null` cell values can be checked with a Text Facet and mass edit replaced.  Agree?

To me, what remains is I think a left over "bug", but really original handling of not differentiating between `null` like `,,` and `blank`/`empty string` like `""` cells.

You can see this remains an issue if you use the clipboard importer or CSV/TSV importer on something like this:
```
"A","B","C"
"1","","3"
"1",,"3"
```

The B column row.index(0) should be an empty string `blank` and row.index(1) should be `null`.
But what happens is that both row indexes are imported as empty string (blank).
This is a bug to me that remains since we said we would treat `null` and `blank` separately throughout OpenRefine's importers and expressions and it's something that still pesters those in the scientific community who view row 2/column B value `null` as an outlier, but currently OpenRefine makes the value look the same as row 1/column B `""` empty string during import.

Shall I open a new issue for that?

**Comment by tfmorris** [comment]
> Shall I open a new issue for that?

If you think that the behavior of the CSV importer should be changed, yes, please create an issue. Ditto for any other importers.
