### ISSUE TITLE
Java version 8 not detected by start script in Linux

### ISSUE THREAD

**Issue by jmcastagnetto** [OpenRefine/OpenRefine#671]
I am using java 8 64-bit under Ubuntu Linux 12.04 (64-bit), and the start script for version 2.5 r2407 does not recognize this version. 

The fix is trivial and shown below:

```
$ diff -u refine-old  refine
--- refine-old  2011-12-11 17:08:39.000000000 -0500
+++ refine  2013-02-01 10:45:21.789571935 -0500
@@ -827,6 +827,7 @@

 # ----- Make sure there is an appropriate java environment is available -------------

+
 if [ "$OS" = "macosx" ] ; then
     if [ -z "$JAVA_HOME" ] ; then
         # Mac OS X defaults to Java 5. So update JAVA_HOME unless the user manually set it.
@@ -844,7 +845,7 @@
     error "Could not find the 'java' executable at '$JAVA', are you sure your JAVA_HOME environment variable is pointing to a proper java installation?"
 fi

-JAVA_VERSION=`$JAVA -version 2>&1 | grep version | cut -d ' ' -f 3 | egrep '^\"1\.(6|7)'`
+JAVA_VERSION=`$JAVA -version 2>&1 | grep version | cut -d ' ' -f 3 | egrep '^\"1\.(6|7|8)'`
 if [ -z "$JAVA_VERSION" ] ; then
     error "Google Refine requires Java version 6 or later. If you have multiple versions of Java installed, please set the environment variable JAVA_HOME to the correct version."
 fi

```

**Comment by manugarri** [comment]
somehow this issue is happening in Ubuntu 14.10

![](https://s3.amazonaws.com/uploads.hipchat.com/30021/535410/0LZiWo9EMmE4AKY/upload.png)

**Comment by jackyq2015** [comment]
@manugarri This is different issue. Please create separate ticket.

**Comment by pbhj** [comment]
I've got 2.5 r2407 for linux just now as a download from GitHub and the bug is still present, altering the "(6|7)" to "(6|7|8)" in the script works for me, I'm using  'java version "1.8.0_45" ' (according to "java -version").

The error I got was "Google Refine requires Java version 6 or later. If you have multiple versions of Java installed, please set the environment variable JAVA_HOME to the correct version."

Once the script was altered in ran without any apparent problem.

FWIW I'm running Kubuntu 14.10.
