### ISSUE TITLE
Clustering dialog resultSummary div has wrapping problems in control-row div

### ISSUE THREAD

**Issue by thadguidry** [OpenRefine/OpenRefine#6840]
`resultSummary` div in Clustering dialog has unnecessary "squishyness" when adjusting **Length variance of choices** slider.

### To Reproduce
1. First, import test dataset below using the Clipboard importer, Create Project, and on Column 1, Edit cells -> Cluster and edit...
2. Then use **Method:** Nearest neighbor with **Distance function:** Levenshtein and **Radius**=2 and **Block chars**=3
3. Finally, move **Length variance of choices** left lower slider to somewhere above .03 in order to change number of clusters included and show problem with the resultSummary div

### Current Results

![image](https://github.com/user-attachments/assets/01d062b7-10d3-46bf-8137-28e6a8bb2597)

### Expected Behavior

Easier to read, and doesn't cause wrapping issues with Block chars input box and extra "squishyness" of resultSummary div.

We can perhaps make some small adjustments while helping the resultSummary view to also account for translations/languages - we give the resultSummary a long space to wrap into automatically by changing the grid-template-columns to repeat at 4 instead of 5, which pushes 5th column for resultSummary automatically  down.  We then make small padding adjustments to help recover the small loss of vertical space.

In `.clustering-dialog-control-row` make the following changes:
- `grid-template-columns: repeat(4, auto);`
- `padding: 0.25em;`
- `gap: 0.25em;`

![image](https://github.com/user-attachments/assets/1eb89b2d-723e-4bb4-8d93-51ef886f68d9)

### Versions
 - Operating System: Windows 11 Pro
 - Browser Version: Edge latest
 - JRE or JDK Version: embedded
 - OpenRefine: 3.8.2

### Datasets

```
China surname of Fang
DaFong
fang
Fanged
fong
New York
New york
NEW York
new york fanged
```

**Comment by tfmorris** [comment]
Thanks for reporting the problem and suggesting a possible solution. The current development version is even more squished because there's a large "Manage clustering functions" button in the middle of the row. The general problem is that the header has had elements added to it organically without a principled rethink of the layout and ordering.

If we move to a 2 row layout, I think there might be a better ordering of the elements than just wrapping the current 1-row layout.

I also noticed that the "Manage clustering fuctions" (sic) button appears between Distance Function dropdown and the associated parameters, which doesn't really make sense to me.
![Screenshot 2024-09-18 at 1 40 52 PM](https://github.com/user-attachments/assets/0082cc29-a9c6-4824-9750-10263b3c06eb)

I think this whole set of controls could use a little UX designer love.
