### ISSUE TITLE
mobile view support

### ISSUE THREAD

**Issue by nnWhisperer** [OpenRefine/OpenRefine#6900]
Hello, I saw in previous comments that the original design was for larger screens and smallers weren't of consideration. My question is, how could we adapt it to not run but to view from smaller screens? Probably this has been thought of, but I couldn't find references, thanks

**Comment by thadguidry** [comment]
Note: OpenRefine has a very small contributor base, and thus it would be hard to support working on a completely different view aspect ratio and workflow to accommodate smaller views.

It works great on small Linux or Windows pads even down to 8 inch screens??, if you can bear with the tiny text size.  For mobile/cellphones, that would be a completely different workflow aspect, and we don't have the resources to work on something like that, unfortunately, and it would have to come from other organizations to fork OpenRefine and create those different view aspect workflows - not an easy task (basically, each panel of OpenRefine would end up likely being a single view itself, that you have to navigate between, rather than having them all available in the current single page view.

Still, I am curious, what specific size/resolution/device types where you thinking of?

**Comment by tfmorris** [comment]
I agree with @thadguidry that this isn't something within our feasible planning horizon. Switching to "not planned."
