### ISSUE TITLE
Can’t login to Google (extension gdata) with OR v3.8.2 on Mac

### ISSUE THREAD

**Issue by antoine2711** [OpenRefine/OpenRefine#6931]
Can’t login to Google (extension gdata) with OR v3.8.2 on Mac.
Also, the signing of the application doesn’t seem to work.

### To Reproduce
1. Goto Google Data in the « create project » tab
2. Click on the button « Sign in »

Also, just opening a public document doesn’t work more.

### Current Results
The OAuth client was deleted.
Si vous êtes un développeur de cette application, consultez les [détails de l'erreur](https://accounts.google.com/).
Erreur 401 : deleted_client

### Expected Behavior
OR should log me in my Google account.

### Screenshots
| Screenshots of Google login  |
| -----------  |
|![image](https://github.com/user-attachments/assets/90b8b988-e94f-43c2-8fa8-9207e1c67886)|

| Screenshots of loading public document  |
| -----------  |
|![image](https://github.com/user-attachments/assets/40031588-bda4-42b8-af42-6b2f3e65e2e5)|

### Versions
 - Operating System: MacOS sonama (v14.6.1)
 - Browser Version: Chrome v130.0.6723.59
 - JRE or JDK Version: openjdk version "23" 2024-09-17
 - OpenRefine: v3.8.2

**Comment by wetneb** [comment]
This is indeed because I have revoked the OAuth credentials we have been bundling into the application. I did this because the credentials could be extracted from the released artifacts, meaning that other applications could use them and impersonate OpenRefine.

If you want to continue using this integration, you unfortunately need to [obtain Google API credentials yourself](https://github.com/OpenRefine/OpenRefine/wiki/Google-Extension).

Given that the steps required are really involved, I think only a small minority of our users will be following that, so I would propose to stop bundling the gdata extension. We could migrate it to a separate repository and users would be able to install it manually. What do you think?

**Comment by tfmorris** [comment]
It looks like our error handling needs to be changed/improved. The error path followed when there are no credentials includes a direct link to that page of directions on how to get your own credentials. We should change the error path for revoked/invalid credentials to do the same. I guess this will be a good way to find out who's using it...

**Comment by antoine2711** [comment]
> I think only a small minority of our users will be following that, so I would propose to stop bundling the gdata extension.

@wetneb: I guess that would be smart.

I just wonder: since this will break the functionaly in all versions of OR that have gdata, why didn't we warned the user and plan a migration process? Like a 3 months period of grace?

> It looks like our error handling needs to be changed/improved.
@tfmorris: Yes, and we should also think about the olders versions, for which we can't change the error reporting.

I guess a page for this extension in the documentation could be a very good step.

Regards, Antoine

**Comment by wetneb** [comment]
I agree it's a bit of an abrupt end for a feature, but it's not clear to me how to avoid that.
If you warn users about the problem without revoking the credentials, you are attracting everyone's attention on the fact there those credentials are free to use and abuse, which is putting people even more at risk, I would say.
What sort of migration process are you thinking about?

**Comment by tfmorris** [comment]
@antoine2711 Good point about older versions. We can release a 3.8.x with improvements which might help. Anyone on an older version isn't getting security updates, so we can probably consider unsupported.

**Comment by antoine2711** [comment]
We can close this issue, as the main problem is that the Google API credentials have been revoked..

@wetneb: I would restore the old credential, and wait until we release v3.9 to revoke it for good.
The security threat is not that important, as anybody using the keys would do it with the name OpenRefine visible.
For this to be a real attack, one would need to also do other deceptions, like providing a reworked version of OpenRefine and insert his malicious code there and distribute that particular version.

Even with a user creating its own Google credential, such an attack would still be possible.
Also, any other open-source (and even closed source) software can't really hide that unless they use complex mecanism, as machine debugger with a breakpoint at the good place can't really hide that information, unless the HTTP request is done on an external server.

We need to improve the documentation on how to create the Google API credentials and add it to our [openrefine.org/docs](https://openrefine.org/docs) manual, maybe remove the extension from OR and make it standalone, and give an early warning, so that our user base can adapt itself, IMO.

Regards, Antoine

**Comment by wetneb** [comment]
> For this to be a real attack, one would need to also do other deceptions, like providing a reworked version of OpenRefine and insert his malicious code there and distribute that particular version.

No, it doesn't need to be a reworked version of OpenRefine. You could use the credentials in any web application, which has nothing to do with OpenRefine.

> Even with a user creating its own Google credential, such an attack would still be possible.

If you create your own Google API keys and don't publish them, you are a lot safer because even if your user tokens acquired in the OAuth process leak (for instance via one of the other 8 vulnerabilities patched in 3.8.4), they are useless.

> I would restore the old credential, and wait until we release v3.9 to revoke it for good.

I wouldn't do that especially now that we have attracted people's attention on the existence of such credentials. Anyway, anyone publishing those in clear text online would get them revoked after some time, because after a while Google notices them and invalidates them. That's what happened with the previous credentials which had been put in clear text in the source code.
