### ISSUE TITLE
Move Cypress Cloud secret to Github Secrets

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#6959]
We are currently publishing the secret for Cypress cloud in our workflow file, so anyone who clones the repo can push to our dashboard, making for confusing debugging and wasted time.  We should invalidate that secret, mint a new one, move it to Github secrets, and adjust the workflow to reference it from the secrets store

https://github.com/OpenRefine/OpenRefine/issues/6942#issuecomment-2442785321_

**Comment by wetneb** [comment]
If I remember correctly this was intentional when @fgiroud set it up, but I don't remember exactly why, so let's indeed move it to a secret. I've sent you an invite for the Cypress Cloud org.

**Comment by antoine2711** [comment]
@tfmorris: I have a question, maybe because I don’t understand, but if I run the tests on my computer, are the stats going to be added to a common Cypress projects?

Maybe the solution would be to have 2 sets of credentials, one just for our CI/CD runs, and one that is publicly shared by all developpers. It would help keep clean stats for our CI/CD and core developper, while still have public testings which could get sometimes corrupted by inexperienced developpers that use it for other projects or whatever problem could arrise…

Regards, Antoine
