### ISSUE TITLE
wikibase: Upload to Wikidata and Commons in one go

### ISSUE THREAD

**Issue by wetneb** [OpenRefine/OpenRefine#7045]
_Citing Beat Estermann from [Commons_talk:OpenRefine](https://commons.wikimedia.org/wiki/Commons_talk:OpenRefine#Commons_extension_is_missing_on_PAWS)_

> 1) It is not obvious from the instructions that uploaders may have to ingest data on Wikidata first. In the case of museum artefacts, the approach with the "Art photo" template looks very simple at first. However, the data ingest on Wikidata can be quite tricky and represents a major challenge. I think this should be mentioned in the instructions. Ideally, easier alternatives would be pointed to. - Maybe add a pros and cons for using OpenRefine vs. Pattypan.

For a lot of upload projects to Commons, getting good structured data statements on Commons will indeed require a two step upload process:
* add information to (or create items about) the artworks, entities depicted, authors, in Wikidata.
* then, upload the files from Commons, referencing the Wikidata items created/enriched in the previous step

This is indeed rather complicated.

### Proposed solution

Allow uploading metadata to Wikidata and files to Commons in one step. Concretely, this is done by making it possible to add items in schemas built for Commons. The edits on the corresponding items are directly made in Wikidata.

### Alternatives considered

status quo

### Additional context

none

**Comment by Jadhavsakshi7887** [comment]
hey,i understand the issue can you pls assign this to me

**Comment by wetneb** [comment]
It's a rather complicated one that I would not recommend to new contributors. It's not even clear if there is consensus on the proposal, given that I only opened this issue yesterday. Can you have a look at our [good first issues](https://github.com/OpenRefine/OpenRefine/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22) instead?

**Comment by IIITM-Jay** [comment]
Hi @wetneb! 
Great to meet you here. 

While I was reading the issue and the proposed solution, I just wanted to put my thoughts and correct me if my thought process is going side the track. The way how how I think as a developer, I am putting here:

> Allow uploading metadata to Wikidata and files to Commons in one step. Concretely, this is done by making it possible to add items in schemas built for Commons. The edits on the corresponding items are directly made in Wikidata.

For sure, the above will simplify the two-step process for an experienced user who already understand both Wikidata and Commons workflows and it will make the process feel seamless by creating it as a one-stop solution for both structured data and file uploads.

#### Challenges
But, I think the challenge still retains that users must still define schemas correctly to handle both Wikidata and Commons metadata simultaneously. This adds complexity, particularly for new or non-technical users.  Handling errors could become more complicated. For instance:

1.  If metadata edits to Wikidata fail but the Commons upload succeeds (or vice versa), users may struggle to debug the issue.
2. A mismatch in schemas or missing data could disrupt both operations.

The complexity will also arise with the implementation side where Error-handling mechanisms would need to be significantly improved to account for edge cases like partial success/failure in one of the platforms (e.g., metadata edits succeed, but file uploads fail) and also while maintaining consistency between Wikidata items and Commons metadata. The API interaction would need to be asynchronous and highly optimized, given the volume of data OpenRefine handles.

**I think, decoupling a unified process into Pre-Configured Pipelines for Two-Step Uploads (Step 1: Metadata Preparation and Upload to Wikidata and Step 2: File Upload to Commons with Metadata Links) will make the flow much easier.** 
By this we can also introduce an enhanced **_Error Handling mechanism with Rollback Options_** by introducing a transaction log to track each operation (Metadata edits on Wikidata & File uploads to Commons). If an error occurs in either step, users can roll back the changes or retry failed operations without starting over.

Pardon me if I am not allowed to put my points here. I wrote what I felt. I hope to hear soon on this what others have to say.

Thanks & Regards
-Jay

**Comment by thadguidry** [comment]
@IIITM-Jay Agree.  Most of OpenRefine workflows having the concept of Operations (steps in a workflow/pipeline).  What I don't think OpenRefine has IS A workflow or pipeline concept yet.  The History came about from the ideas of CDC Change Data Capture, and DB Transaction logs.  During early design of OpenRefine, though inspired by other ETL tool designs in some areas, it wasn't deemed a priority to have the need to rerun Workflows/Pipelines, hence the lack of that structure, and the very loose fitting Undo/Redo that lacks many details of Operations.

I'm not sure how much @wetneb has done or envisioned in 4.0 branch to give OpenRefine a more true Workflow/Pipeline aspect, but it was something that in hind sight the team didn't envision would be useful to users (OpenRefine being primarily designed for one-off adhoc data cleaning and export for individual datasets).  I on the other hand, came from an ETL background and although I wanted Workflows/Pipelines at the time the JSON of Operations from Undo/Redo sufficed for me, but I think we missed a huge opportunity early on to make OpenRefine more flexible.

I'll let @wetneb speak about his ideas and work towards improving that as part of the Reproducibility project. https://github.com/orgs/OpenRefine/projects/6

**Comment by wetneb** [comment]
@IIITM-Jay isn't the two-step workflow you are describing exactly what we currently have? I am not sure which concrete change you are suggesting.

@thadguidry I think you understood the term "workflow" in a different way than @IIITM-Jay was using it, as a series of steps a user can take to achieve something in OpenRefine, without necessarily thinking about its reproducibility. So it seems to me that your points and questions about that are going in a different direction. To answer your question though, yes I am still working on the reproducibility improvements, expect my monthly report in the coming days on the forum (with a request to help with design and testing).

**Comment by IIITM-Jay** [comment]
Hi @wetneb few things from side to put into clarity.

> @IIITM-Jay isn't the two-step workflow you are describing exactly what we currently have? I am not sure which concrete change you are suggesting.

Actually, my suggestion was not to retain the current two-step process in its existing form but to enhance it with pre-configured pipelines and introduce mechanisms to make the process easier, more transparent, and error-resilient for users. My suggestion also included on the portion that you mentioned on combining the two steps in a single one - as they will introduce challenges _(what I mentioned in my earlier comment)_. I also emphasized on the introduction of transaction log, which OpenRefine currently lacks that in its design. While it has a history mechanism (undo/redo stack), this feature is not a fully-fledged transaction log. If an operation partially succeeds (e.g., some rows are processed while others fail), OpenRefine has no built-in way to: Log partial successes and Revert only the failed parts of the operation. While JSON scripts enable reproducibility to some extent, a transaction log would provide more robust state-based reproducibility, enabling users to rollback, retry, or audit changes seamlessly. 
Also, to add on, As highlighted in the issue raised in Common talks, there is insufficient clarity about what fields are picked up from Wikidata/Commons and best practices for licenses and other metadata, for sure, they are mentioning about documentation gaps, but IMO, the problem lies in the below items:
1. Complexity for Users: Users unfamiliar with schemas or reconciliation may struggle with the process, particularly when errors occur in either step.
2. Manual Linking: Users need to manually ensure that metadata on Wikidata is properly referenced in Commons uploads.

> @thadguidry I think you understood the term "workflow" in a different way than @IIITM-Jay was using it, as a series of steps a user can take to achieve something in OpenRefine, without necessarily thinking about its reproducibility. 

 I don’t believe @thadguidry was focusing exclusively on reproducibility _(but I am not sure if he was)_ ; instead, he also touched on the broader need for structured workflows/pipelines in OpenRefine that could streamline user processes and support reproducibility.  IMO, the enhanced pre-configured two-step uploads is also a form of reproducibility because it helps users retry, debug, and understand workflows better.
 
 To put it in a nutshell, my thinking goes into addressing the following challenges:

1. **Complexity for Users:** Users unfamiliar with schemas or reconciliation may struggle with the process, particularly when errors occur in either step.
2. **Manual Linking:** Users need to manually ensure that metadata on Wikidata is properly referenced in Commons uploads.
3. **Error Handling:** Debugging partial failures (e.g., metadata edits succeed, but file uploads fail) is cumbersome.
4. **Documentation Gaps:** As highlighted in the issue raised, there is insufficient clarity about what fields are picked up from Wikidata/Commons and best practices for licenses and other metadata.

**Comment by IIITM-Jay** [comment]
and to address those challenges, Here’s the vision for my proposed enhancement:

  1.  **Pre-Configured Pipelines:**

-  Rather than expecting users to define schemas for both Wikidata and Commons simultaneously, OpenRefine could guide users through two clear and pre-defined steps:
                 1. Pipeline Step 1: Metadata Preparation and Upload to Wikidata.
                 2.  Pipeline Step 2: File Upload to Commons with Metadata Links.

- These steps would be structured as a guided process in the UI, reducing the burden on users to manually configure workflows.

2. **Enhanced Error Handling and Rollback:**
- Introduce a transaction log to track operations in both steps. If an error occurs (e.g., metadata edit fails on Wikidata), users could either retry the operation or roll back changes without starting over.
- Partial success/failure scenarios could be handled more gracefully with clear feedback in the UI.

3. **Improved Documentation and Templates:**
- Address gaps in documentation by explicitly detailing which fields are pulled from Wikidata/Commons and best practices for metadata and license information.
- Provide additional examples, as suggested in the issue, for various licensing scenarios and metadata structures.

IMO, my thought process aligns with reproducibility as follows:
- The decoupled pipeline simplifies workflows, making it easier to reproduce each step independently, reducing errors and confusion.
-  The transaction log  inherently improves reproducibility by:
         1. Providing detailed logs of each operation.
         2. Supporting rollbacks and retries, which ensure a consistent state for rerunning workflows.
          3. Making debugging easier, which is crucial for replicating successful workflows.

- By focusing on error handling and modular steps, even complex workflows can be retried and reproduced with more reliability.

**Comment by thadguidry** [comment]
@IIITM-Jay indeed, I wasn't focusing on reproducibility itself but having real pipelines with transactional history of steps/operations/transformations as nearly all ETL programs do, which lends itself to pipelines that can be rerun when need such as failed or partially failed.

**Comment by Abbe98** [comment]
> It is not obvious from the instructions that uploaders may have to ingest data on Wikidata first. In the case of museum artefacts, the approach with the "Art photo" template looks very simple at first. However, the data ingest on Wikidata can be quite tricky and represents a major challenge. I think this should be mentioned in the instructions. Ideally, easier alternatives would be pointed to. - Maybe add a pros and cons for using OpenRefine vs. Pattypan.

To me this reads like an issue with documentation and best practices. I would argue that the best practice is that ones uploads to each project should be as independent from each other as possible. The communities have different standards. Aside from issues around different user rights on each project, different rate limits, and much more semi-technical things  it will increase the social issues, not only for uploaders when one project might take action, but more importantly for administrators who would be increasingly blocked by dependencies across projects.

If ones upload needs edits to both Wikidata and Commons, edit Wikidata, let your changes settle for a while, then make your Commons edits.  There is probably plenty of improvements both around documentation, best practices, and in terms of features around reusing projects, importing Wikibase data, etc to be done to make this simpler. Uploading to both projects at the same time, however, will do much more harm than good.

**Comment by wetneb** [comment]
@IIITM-Jay it looks like you have a lot of improvements in mind and many of those could be formulated independently from this issue. I would encourage you to write up individual issues about each improvement you would like to propose, with more concrete descriptions of what you would like to change exactly (perhaps with UI mock ups or example datasets). At the moment your text is formulated at a fairly abstract level, which means I cannot really judge how it would fit in the tool.

**Comment by wetneb** [comment]
Let's close this issue per @Abbe98's comment - I agree users will need to be aware of the differences between Commons and Wikidata anyway, so there isn't so much more we can smoothen on OpenRefine's side.
