### ISSUE TITLE
toDate() can't parse dates in non-default locale

### ISSUE THREAD

**Issue by whxiyi100829** [OpenRefine/OpenRefine#729]
Hi,
I just encounter this issue:
I'm trying to parse a string to date using Refine, for example:
"01-六月-2013".toDate('dd-MMM-yyyy') is OK!
"01-Jun-2013".toDate('dd-MMM-yyyy') will print: Error: Cannot parse to date
First, I'm in China.

**Comment by mabecabrera** [comment]
Sorry to bother you here. Just can not find what I need anywhere. 
I need to edit the date format so that all the dates in my database are the same. I have some dd/mm/yyyy and some are yyyy/mm/dd. And I need all of them to be yyyy-mm-dd. 
Where can I find the expression to filter just one kind (dd/mm/yyyy) so I do not have to include them in the text facet to be able to work only with them and so I can separate in columns and order them in the order I need?
Too many clicks needed. Must be another way.

**Comment by ostephens** [comment]
@mabecabrera the dedicated support forum https://forum.openrefine.org is probably a better place to ask this type of question (where the issue is "how do I do X" rather than a bug or feature request). But to answer briefly, there are a few ways of doing this, but I'd suggest using a text filter on the column, check the 'regular expression' check box and use `\d{2}/\d{2}/\d{4}` to filter to only dd/mm/yyyy style dates and `\d{4}/\d{2}/\d{2}` to filter to only yyyy/mm/dd style dates

**Comment by mabecabrera** [comment]
Thank you very much!!! it helps a lot! I will save that forum link for further questions.
I'm very grateful!!! Thank you very much!
