### ISSUE TITLE
Allow user to specify language for Freebase topic names

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#789]
When doing reconciliation against Freebase and "Add column from Freebase" it would be desirable to allow the user to specify the language to use when querying for labels (perhaps using the client front end language as the default if it's not specified).

**Comment by magdmartin** [comment]
OpenRefine is moving away from freebase. This issue is a no fix

**Comment by tfmorris** [comment]
We're going to have the same need for both Knowledge Graph and Wikidata APIs, but I guess we can just create new issues for those.

**Comment by magdmartin** [comment]
Overall, I agree to close all freebase related issue in github.

Reconciliation service support is tied to freebase integration due to the
project history. With freebase being shut down I think OpenRefine core
should support generic reconciliation protocols and have specific
integration with Knowledge Graph and Wikidata APIs done via extension.

This tied back to how are we removing freebase extension. What is specific
to freebase and what is generic for any reconciliation service.
