### ISSUE TITLE
Add support for a map facet

### ISSUE THREAD

**Issue by tfmorris** [OpenRefine/OpenRefine#94]
_Original author: iainsproat (June 23, 2010 16:48:55)_

Add a map facet to display geolocations.

The scatter facet already works similarly and so does most of the hard work already, but produces the output as an image.  An option next to the scatter facet 'show in map' might work, or we'd have to have a way to flag that a column is a coordinate.  (maybe could be could be inferred from the protograph?)

_Original issue: http://code.google.com/p/google-refine/issues/detail?id=94_

**Comment by thadguidry** [comment]
This should be handled by an extension.

**Comment by answerquest** [comment]
Hi, wow this was filed quite long ago!  
I just want to be able to see the facet/cluster I'm seeing on a map. I came across [this extension](https://github.com/ryanfb/georefine), but they don't seem to have that. What I presently have to do is export as CSV, then import it in a mapping app like geojson.io.

There's a complication that the latitude and longitude are usually stored in two separate columns.

How about Export > To Map? We could do some tweaks to the existing HTML table export option.

**Comment by thadguidry** [comment]
Hi @answerquest we'll be eventually changing our UI to a more modern framework, quite possibly based on React, and so extensions will have to be re-written.

Having said that, this need you have to make it easier to export to a map should be handled by an extension.  We won't add this to our core, mainly because there are many kinds of mapping applications and endpoints that could be utilized, so its best to have extensions handle that where the community that is interested in their particular Mapping need, can directly contribute to those extensions and enhance them, without disturbing our core.

If someone wants to work on this extension need, my suggestion would be to begin in 2019, since this fall/winter 2018 we plan to begin changing quite a few things.

**Comment by wetneb** [comment]
I'd be tempted to agree with Thad here too - this would be a good feature for an extension focused of geo data. Feel free to reopen if you disagree.
