### ISSUE TITLE
Autosave generate the corrupted file

### ISSUE THREAD

**Issue by jackyq2015** [OpenRefine/OpenRefine#943]
We found some corrupted project file in workspace.
Seems it is caused by the auto saving of the project. I guess It has been a incurring issue on the project saving. The "auto saving" was introduced which may cause the corrupted file issue. Then the "auto recover" feature was put as a patch to fix this when loading the workspace. sometime it works. But most of time it still fails to rescue.

static protected class AutoSaveTimerTask implements Runnable {
        @Override
        public void run() {
            try {
                ProjectManager.singleton.save(false); // quick, potentially incomplete save
            } catch (final Throwable e) {
                // Not the best, but we REALLY want this to keep trying
            }
        }
    }

Need a decent way to save the project file. Autosave may not a good idea.

**Comment by tfmorris** [comment]
What version did you see this with?  There were significant changes made in 2.6 specifically to improve robustness of the save code in the face of heap exhaustion.

The periodic automatic project save uses exactly the same code as the user initiated save, so any problems seen in one will be seen in the other.

What evidence do you have that autosave, specifically, is the root cause?

Note that the alternative, forcing the user to manually save, will cause them to lose all work since their last manually initiated save.  In my mind, fixing the save function (if it still needs fixing) is vastly preferable to disabling autosave altogether.

**Comment by jackyq2015** [comment]
The version I am using the 2.6 Beta. That might be reason. Will keep watching the new version if it still happens.

The evidence is that I can find *.corrupted file in my workspace. when I trace back from the code, the auto saver most likely the reason. My understanding is that even the auto saver and user initiated save use the same code, but the timing matters. The auto saver could happen at any time point even when some task is running. In that case may cause issue.

**Comment by tfmorris** [comment]
@wetneb You tagged this "to be reviewed". What type of review were you thinking? From my point of view, it's old enough and unreproducible enough to close.

**Comment by wetneb** [comment]
Fine with me!
