### ISSUE TITLE
OpenRefine in Spanish

### ISSUE THREAD

**Issue by nestorjal** [OpenRefine/OpenRefine#958]
I'd like to translate OpenRefine to Spanish. Any additional file besides [translation-default.json](https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/langs/translation-default.json)?

**Comment by magdmartin** [comment]
Thanks for reaching out! Always interesting to have Refine in a new language.

For support and question please use the developer mailing list: https://groups.google.com/forum/?fromgroups#!forum/openrefine-dev and keep the issue list for issue and feature requests.

As first pointer, did you check the documentation for Internationalization / Localization: https://github.com/OpenRefine/OpenRefine/wiki/Translate-OpenRefine

**Comment by asael2** [comment]
Great idea Nestor I'll be glad to help in that!

**Comment by nestorjal** [comment]
@magdmartin thanks, as soon as I check the documentation above I'll post in the mailing list my progress and probably asking for help, so @asael2 your offer is highly appreciated!

**Comment by tfmorris** [comment]
Thanks for offering to help.  I think a Spanish translation would be a great enhancement (and have tagged this issue as such).

I'd actually suggest using translation-en, rather than translation-default, as the starting point, even though they should be equivalent.  I think we're going to get rid of the latter eventually anyway.  From a political point of view, I'd like all languages be equal, but, in actual fact, the working language of the project is English, so that's the really default and it just makes extra work to maintain to identical files.

The email list would be a good place to solicit help with the translation, but also feel free to submit a pull request with just a partial translation and point others at your branch which is included in the pull request as a focus for them to help with the translation.  Please reference this issue with the pull request and that'll allow everyone to track what's going on and keep in sync.

Thanks again for volunteering!

**Comment by tfmorris** [comment]
p.s. we don't have an incredibly robust I18N structure, so if you find something in the core that doesn't work or needs improvement, feel free to open new issues to address them.  For right now you pretty much need to restrict yourself to simple string substitutions, so there's no fancy plurals, embedded parameters, reordering of phrases, etc.

**Comment by tfmorris** [comment]
@nestorjal Any progress on this?  v2.6 will be released shortly, so if this is close it would be great to have it in the release.

**Comment by nestorjal** [comment]
Yes! I'll submit tomorrow a pull request with a parcial translation, 85% or so done.

**Comment by tfmorris** [comment]
The partial translation as been merged

**Comment by magdmartin** [comment]
I've done a diff between the English and Spanish translation and I confirm that the Spanish translation is complete at 85%. I haven't check translation for extension.

I personally don't speak Spanish, so any help is appreciated to complete the translation. Please submit Pull Request or if you don't know how to do it just answer here wit the line number and the translation (or no need for translation). I will update the file directly. 

The following lines in https://github.com/OpenRefine/OpenRefine/blob/master/main/webapp/modules/core/langs/translation-es.json needs to be translated:
56
158
159
160
162
163
180
200
208
209
240
273
276
278
290
293
310
311
313
314
357
405
406
407
431
458
459
460
461
467
468
469
482
516
559
569
570
571
572
577
581
584
585
586
587
588
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
629
633
638
643
647
653
654
658
660
663
664
665

**Comment by magdmartin** [comment]
closed via #1064 please open new issue / submit new pull request if you want to make some change to the translation.
