### ISSUE TITLE
visual feedback of progress split multi-value-cells

### ISSUE THREAD

**Issue by baditaflorin** [OpenRefine/OpenRefine#977]
I have a 16 million rows database, and each cell is a multi-value-cell . There is only one column. The size of the import file was around 1 GB

After i click Edit Cells, split multi valued cells the server that i am testing just hangs and i am waiting for an hour,not knowing if it will ever finish or not. 

The 8 core CPU stays at around 790 % and it occupies all of the 44 GB RAM that i have given to the application , from htop stats

**Comment by tfmorris** [comment]
First, you are an order of magnitude (ie 10x) over the design center of OpenRefine, so you're going to find *lots* of things which don't work smoothly at this scale.

Second, there's little to no multi-threaded code in Refine (other than what is inherited from standard Java library implementations), so if you N*100% being used by Refine, especially for a very long period of time, the most likely consumer is the JVM garbage collector, which has the unfortunate characteristic that it will try really, REALLY hard to make things work, even if it should just give up, since it's going to fail eventually anyway.

Suggestions:
- check JVM garbage collector stats to see if you're at 99% of available heap, thrashing the GC
- allocate more memory
- process the data set in pieces
- split the database before importing it (or use the CSV importer which has a customizable delimiter)

How many cells are you trying to create?  You're starting with 16M rows x 1 column -- how many will you end up with?  There's overhead associated with each cell (and each row).

**Comment by baditaflorin** [comment]
@tfmorris i think i will end up with 100 to 200M rows

I have it in 240 pieces, but i wanted to do a single clustering on the whole database, and then apply to each of the pieces-es

I did the same with another column, that the final row count is only 16M rows, and after 55 steps, i was able to extract the JSON operations history , that occupies 164 MB , and now i plan to apply to each of the 240 pieces individually, so i don`t have to do 10-20 manual operations of clustering for each individual piece.

I know that OpenRefine is not designed for this, but i think in the future more and more people will try to use OpenRefine, for bigger and bigger data-sets, and also because is the only software to date that i have tested that works so good with clustering really bad data-sets, like the ones that i have. And i tested over 20 different software but none had what it take to be useful 

So even if what i post will not get fixed, because is not the primary purpose to work with really big datasets, i think this will be useful in the future, to know what kind of problems can arise when you want to increase the order of magnitude by 10.

**Comment by wetneb** [comment]
Hi @baditaflorin, it has been a while so I do not know if you are still interested in this but I expect the new architecture I am working on should fix the problem in your case. If you want to give it a try, I would be most grateful to know if it does. You can download snapshot releases for this architecture here:

- Linux:
https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=packaging&v=4.0-SNAPSHOT&c=linux&p=tar.gz

- Mac OS:
https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=packaging&v=4.0-SNAPSHOT&c=mac&p=dmg

- Windows (in you already have Java installed): https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=packaging&v=4.0-SNAPSHOT&c=win&p=zip

- Windows (with Java included): https://oss.sonatype.org/service/local/artifact/maven/content?r=snapshots&g=org.openrefine&a=packaging&v=4.0-SNAPSHOT&c=win-with-java&p=zip

**Comment by baditaflorin** [comment]
Hi, I'm glad to know that the development of OpenRefine is still going strong. To be honest I do not remember now what was the dataset that I was dealing with in 2015, but I will be happy to test the new version.

**Comment by wetneb** [comment]
Closing as this is solved by the new architecture.
